In [1]:
pip install nltk

Requirement already satisfied: nltk in ./.venv/lib/python3.13/site-packages (3.9.2)
Requirement already satisfied: click in ./.venv/lib/python3.13/site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in ./.venv/lib/python3.13/site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in ./.venv/lib/python3.13/site-packages (from nltk) (2026.1.15)
Requirement already satisfied: tqdm in ./.venv/lib/python3.13/site-packages (from nltk) (4.67.3)

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.

In [2]:
import os
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
from typing import List, Set, Dict, Any

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
def get_written_dates_and_any_text_file_locations_to_dataframe(root_folder):
    print(f"--- Starting Scan for metadata.json and any associated non-JSON text files ---")
    print(f"Scanning root folder: {os.path.abspath(root_folder)}\n")

    if not os.path.exists(root_folder):
        print(f"Error: The root folder '{root_folder}' does not exist at '{os.path.abspath(root_folder)}'.")
        return pd.DataFrame()

    data_for_df = []
    
    for dirpath, dirnames, filenames in os.walk(root_folder):
        metadata_filepath_in_dir = None
        text_file_path_in_dir = None
        
        non_json_files = []

        # First, identify the metadata.json and any non-JSON files in the current directory
        for filename in filenames:
            if filename.lower() == "metadata.json":
                metadata_filepath_in_dir = os.path.join(dirpath, filename)
            elif filename.lower().endswith(".txt"): # Consider anything that's not JSON as a potential text file
                non_json_files.append(os.path.join(dirpath, filename))

        # Check conditions for a valid pair
        if metadata_filepath_in_dir:
            if len(non_json_files) == 1:
                # Exactly one non-JSON file found, assume it's the text file
                text_file_path_in_dir = non_json_files[0]
                
                print(f"Processing directory: {os.path.abspath(dirpath)}")
                print(f"  Found metadata.json: {metadata_filepath_in_dir}")
                print(f"  Found associated text file: {text_file_path_in_dir}")

                extracted_written_date = None
                try:
                    with open(metadata_filepath_in_dir, 'r', encoding='utf-8') as f:
                        metadata = json.load(f)
                        if 'written_date' in metadata:
                            extracted_written_date = metadata['written_date']
                            print(f"  Extracted 'written_date': '{extracted_written_date}'")
                        else:
                            print(f"  Warning: 'written_date' key NOT found in {metadata_filepath_in_dir}. Setting to None for this entry.")
                except json.JSONDecodeError as e:
                    print(f"  Error: Could not parse JSON from {metadata_filepath_in_dir}: {e}. Setting 'written_date' to None.")
                except Exception as e:
                    print(f"  An unexpected error occurred reading {metadata_filepath_in_dir}: {e}. Setting 'written_date' to None.")
                
                # Add this pair to our DataFrame data
                data_for_df.append({
                    'written_date': extracted_written_date,
                    'text_file_location': os.path.abspath(text_file_path_in_dir)
                })
                
            elif len(non_json_files) == 0:
                print(f"  Note: Found metadata.json in {os.path.abspath(dirpath)} but NO non-JSON text file found. Skipping this directory.")
            else: # len(non_json_files) > 1
                print(f"  Warning: Found metadata.json in {os.path.abspath(dirpath)} but MULTIPLE non-JSON files ({non_json_files}). Cannot determine which is the text file. Skipping this directory.")
        # No else for when metadata.json is not found at all, to keep output cleaner

    print(f"\n--- Scan Complete ---")
    print(f"Total valid pairs (metadata.json + single non-JSON text file): {len(data_for_df)}")
    
    df = pd.DataFrame(data_for_df)

    if df.empty:
        print("No valid pairs of metadata.json and single non-JSON text file found to create a DataFrame.")
    else:
        print("\n--- Resulting DataFrame Head ---")
        print(df.head())
        print(f"\nDataFrame has {len(df)} rows and {len(df.columns)} columns.")
    
    return df

In [4]:
root_directory_to_scan = "data/OCR_Final"

list_of_file_locations = get_written_dates_and_any_text_file_locations_to_dataframe(root_directory_to_scan)

--- Starting Scan for metadata.json and any associated non-JSON text files ---
Scanning root folder: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final

Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/ධර්ම ප්‍රදීපිකාව හෙවත් මහාබෝධිවංශ පරිකථාව
  Found metadata.json: data/OCR_Final/ධර්ම ප්‍රදීපිකාව හෙවත් මහාබෝධිවංශ පරිකථාව/metadata.json
  Found associated text file: data/OCR_Final/ධර්ම ප්‍රදීපිකාව හෙවත් මහාබෝධිවංශ පරිකථාව/ධර්ම ප්‍රදීපිකාව හෙවත් මහාබෝධිවංශ පරිකථාව.txt
  Extracted 'written_date': '1187 - 1225'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/දුක්ඛ සත්‍ය වර්ණනා
  Found metadata.json: data/OCR_Final/දුක්ඛ සත්‍ය වර්ණනා/metadata.json
  Found associated text file: data/OCR_Final/දුක්ඛ සත්‍ය වර්ණනා/දුක්ඛ සත්‍ය වර්ණනා.txt
  Extracted 'written_date': ''
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/ටිබැට් රටේ බුදුදහම
  Found metadata.json: data/OCR_Final/ටිබැට් රටේ බුදුදහම/metadata.json
  Found associated text file: data/OCR_Final/ටිබැට් රටේ බුදුදහම/ටිබැට් රටේ බුදුදහම.txt
  Extracted 'written_date': '1832 - 1907'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/නිදහසේ මන්ත්‍රය
  Found metadata.json: data/OCR_Final/නිදහසේ මන්ත්‍රය/metadata.json
  Found associated text file: data/OCR_Final/නිදහසේ මන්ත්‍රය/නිදහසේ මන්ත්‍රය.txt
  Extracted 'written_date': '1901 - 1938'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/පැරණි ගම
  Found metadata.json: data/OCR_Final/පැරණි ගම/metadata.json
  Found associated text file: data/OCR_Final/පැරණි ගම/පැරණි ගම.txt
  Extracted 'written_date': '1944'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/පන්සිය පනස් ජාතක පොත
  Found metadata.json: data/OCR_Final/පන්සිය පනස් ජාතක පොත/metadata.json
  Found associated text file: data/OCR_Final/පන්සිය පනස් ජාතක පොත/පන්සිය පනස් ජාතක පොත.txt
  Extracted 'written_date': '1303 - 1333'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/හිතෝපදේශ සන්නය
  Found metadata.json: data/OCR_Final/හිතෝපදේශ සන්නය/metadata.json
  Found associated text file: data/OCR_Final/හිතෝපදේශ සන්නය/හිතෝපදේශ සන්නය.txt
  Extracted 'written_date': '1825 - 1905'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/කඩවර දීම සහ තුන්සමයන් පෙළපාලිය
  Found metadata.json: data/OCR_Final/කඩවර දීම සහ තුන්සමයන් පෙළපාලිය/metadata.json
  Found associated text file: data/OCR_Final/කඩවර දීම සහ තුන්සමයන් පෙළපාලිය/කඩවර දීම සහ තුන්සමයන් පෙළපාලිය.txt
  Extracted 'written_date': ''
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/අධිමාසභේදය
  Found metadata.json: data/OCR_Final/අධිමාසභේදය/metadata.json
  Found associated text file: data/OCR_Final/අධිමාසභේදය/අධිමාසභේදය.txt
  Extracted 'written_date': ''
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/අධිමාස සංග්‍රහව
  Found metadata.json: data/OCR_Final/අධිමාස සංග්‍රහව/metadata.json
  Found associated text file: data/OCR_Final/අධිමාස සංග්‍රහව/අධිමාස සංග්‍රහව.txt
  Extracted 'written_date': '1850 - 1903'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/සත්‍යාර්ථදීපනිය
  Found metadata.json: data/OCR_Final/සත්‍යාර්ථදීපනිය/metadata.json
  Found associated text file: data/OCR_Final/සත්‍යාර්ථදීපනිය/සත්‍යාර්ථදීපනිය.txt
  Extracted 'written_date': ''
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/දහම් සරණ.txt
  Found metadata.json: data/OCR_Final/දහම් සරණ.txt/metadata.json
  Found associated text file: data/OCR_Final/දහම් සරණ.txt/දහම් සරණ.txt
  Extracted 'written_date': '1220 - 1293'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/සඟබත් බෙදුම හෙවත් තුන්වන සඟබත බෙදුම පිළිබඳ විභාගය
  Found metadata.json: data/OCR_Final/සඟබත් බෙදුම හෙවත් තුන්වන සඟබත බෙදුම පිළිබඳ විභාගය/metadata.json
  Found associated text file: data/OCR_Final/සඟබත් බෙදුම හෙවත් තුන්වන සඟබත බෙදුම පිළිබඳ විභාගය/සඟබත් බෙදුම හෙවත් තුන්වන සඟබත බෙදුම පිළිබඳ විභාගය.txt
  Extracted 'written_date': ''
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/මධුර මනෝහර කථාවස්තූන් සඋදාහරණ කොට සන්න කරණ ලද පරාභව සූත්‍රය
  Found metadata.json: data/OCR_Final/මධුර මනෝහර කථාවස්තූන් සඋදාහරණ කොට සන්න කරණ ලද පරාභව සූත්‍රය/metadata.json
  Found associated text file: data/OCR_Final/මධුර මනෝහර කථාවස්තූන් සඋදාහරණ කොට සන්න කරණ ලද පරාභව සූත්‍රය/මධුර මනෝහර කථාවස්තූන් සඋදාහරණ කොට සන්න කරණ ලද පරාභව සූත්‍රය.txt
  Extracted 'written_date': ''
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/සූත්‍රසංග්‍රහව
  Found metadata.json: data/OCR_Final/සූත්‍රසංග්‍රහව/metadata.json
  Found associated text file: data/OCR_Final/සූත්‍රසංග්‍රහව/සූත්‍රසංග්‍රහව.txt
  Extracted 'written_date': ''
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/දුර්වාදී හෘදය විදාරණය
  Found metadata.json: data/OCR_Final/දුර්වාදී හෘදය විදාරණය/metadata.json
  Found associated text file: data/OCR_Final/දුර්වාදී හෘදය විදාරණය/දුර්වාදී හෘදය විදාරණය.txt
  Extracted 'written_date': '1854 - 1899'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/ශ්‍රද්‍රනීර්ණයදර්පණය
  Found metadata.json: data/OCR_Final/ශ්‍රද්‍රනීර්ණයදර්පණය/metadata.json
  Found associated text file: data/OCR_Final/ශ්‍රද්‍රනීර්ණයදර්පණය/ශ්‍රද්‍රනීර්ණයදර්පණය.txt
  Extracted 'written_date': ''
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/විමතිඡේදකය
  Found metadata.json: data/OCR_Final/විමතිඡේදකය/metadata.json
  Found associated text file: data/OCR_Final/විමතිඡේදකය/විමතිඡේදකය.txt
  Extracted 'written_date': ''
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/විස්තරාර්ථ ග්‍රන්ථිපද විවර්ණය සහිත සිංහල විමානවස්තූප්‍රකරණය
  Found metadata.json: data/OCR_Final/විස්තරාර්ථ ග්‍රන්ථිපද විවර්ණය සහිත සිංහල විමානවස්තූප්‍රකරණය/metadata.json
  Found associated text file: data/OCR_Final/විස්තරාර්ථ ග්‍රන්ථිපද විවර්ණය සහිත සිංහල විමානවස්තූප්‍රකරණය/විස්තරාර්ථ ග්‍රන්ථිපද විවර්ණය සහිත සිංහල විමානවස්තූප්‍රකරණය.txt
  Extracted 'written_date': '1469 - 1815'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/ද්‍රව්‍ය ගුණදර්පණ සන්නය
  Found metadata.json: data/OCR_Final/ද්‍රව්‍ය ගුණදර්පණ සන්නය/metadata.json
  Found associated text file: data/OCR_Final/ද්‍රව්‍ය ගුණදර්පණ සන්නය/ද්‍රව්‍ය ගුණදර්පණ සන්නය.txt
  Extracted 'written_date': ''
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/මහාකප්පිත නරේන්ද්‍ර චරිතය
  Found metadata.json: data/OCR_Final/මහාකප්පිත නරේන්ද්‍ර චරිතය/metadata.json
  Found associated text file: data/OCR_Final/මහාකප්පිත නරේන්ද්‍ර චරිතය/මහාකප්පිත නරේන්ද්‍ර චරිතය.txt
  Extracted 'written_date': ''
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/අවවාද පරිච්ජේදය
  Found metadata.json: data/OCR_Final/අවවාද පරිච්ජේදය/metadata.json
  Found associated text file: data/OCR_Final/අවවාද පරිච්ජේදය/අවවාද පරිච්ජේදය.txt
  Extracted 'written_date': ''
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/සිගාලෝවාද සූත්‍රය - සන්න සහිතයි
  Found metadata.json: data/OCR_Final/සිගාලෝවාද සූත්‍රය - සන්න සහිතයි/metadata.json
  Found associated text file: data/OCR_Final/සිගාලෝවාද සූත්‍රය - සන්න සහිතයි/සිගාලෝවාද සූත්‍රය - සන්න සහිතයි.txt
  Extracted 'written_date': ''
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/කැලණි හෑල්ල
  Found metadata.json: data/OCR_Final/කැලණි හෑල්ල/metadata.json
  Found associated text file: data/OCR_Final/කැලණි හෑල්ල/කැලණි හෑල්ල.txt
  Extracted 'written_date': ''
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/දශ පොරොන්දම සහ අංගවිනිස්චය
  Found metadata.json: data/OCR_Final/දශ පොරොන්දම සහ අංගවිනිස්චය/metadata.json
  Found associated text file: data/OCR_Final/දශ පොරොන්දම සහ අංගවිනිස්චය/දශ පොරොන්දම සහ අංගවිනිස්චය.txt
  Extracted 'written_date': ''
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/රුවන්මල් නිඝන්ටුව හෙවත් නාමරතන මාලාව
  Found metadata.json: data/OCR_Final/රුවන්මල් නිඝන්ටුව හෙවත් නාමරතන මාලාව/metadata.json
  Found associated text file: data/OCR_Final/රුවන්මල් නිඝන්ටුව හෙවත් නාමරතන මාලාව/රුවන්මල් නිඝන්ටුව හෙවත් නාමරතන මාලාව.txt
  Extracted 'written_date': '1412 - 1467'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/වෛද්‍ය චින්තාමනි භෛෂද්‍ය සංග්‍රහව
  Found metadata.json: data/OCR_Final/වෛද්‍ය චින්තාමනි භෛෂද්‍ය සංග්‍රහව/metadata.json
  Found associated text file: data/OCR_Final/වෛද්‍ය චින්තාමනි භෛෂද්‍ය සංග්‍රහව/වෛද්‍ය චින්තාමනි භෛෂද්‍ය සංග්‍රහව.txt
  Extracted 'written_date': '1706 - 1739'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/දනුමැති උපම්‍යොථි සංග්‍රහ හෙවත් උපමා කැඩපත
  Found metadata.json: data/OCR_Final/දනුමැති උපම්‍යොථි සංග්‍රහ හෙවත් උපමා කැඩපත/metadata.json
  Found associated text file: data/OCR_Final/දනුමැති උපම්‍යොථි සංග්‍රහ හෙවත් උපමා කැඩපත/දනුමැති උපම්‍යොථි සංග්‍රහ හෙවත් උපමා කැඩපත.txt
  Extracted 'written_date': ''
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/දුශ්ශිල දානාදී විනිශ්චය සන්නය
  Found metadata.json: data/OCR_Final/දුශ්ශිල දානාදී විනිශ්චය සන්නය/metadata.json
  Found associated text file: data/OCR_Final/දුශ්ශිල දානාදී විනිශ්චය සන්නය/දුශ්ශිල දානාදී විනිශ්චය සන්නය.txt
  Extracted 'written_date': ''
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/ශ්‍රාවක චරිතය - 2 වැනි කාණ්ඩය
  Found metadata.json: data/OCR_Final/ශ්‍රාවක චරිතය - 2 වැනි කාණ්ඩය/metadata.json
  Found associated text file: data/OCR_Final/ශ්‍රාවක චරිතය - 2 වැනි කාණ්ඩය/ශ්‍රාවක චරිතය - 2 වැනි කාණ්ඩය.txt
  Extracted 'written_date': ''
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/යසෝදරාවත
  Found metadata.json: data/OCR_Final/යසෝදරාවත/metadata.json
  Found associated text file: data/OCR_Final/යසෝදරාවත/යසෝදරාවත.txt
  Extracted 'written_date': ''
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/ඌර්ධ්‍රව ලිපිත් ඇතුව භාවසන්න සහිත සුභාෂිත රත්න මාලාව
  Found metadata.json: data/OCR_Final/ඌර්ධ්‍රව ලිපිත් ඇතුව භාවසන්න සහිත සුභාෂිත රත්න මාලාව/metadata.json
  Found associated text file: data/OCR_Final/ඌර්ධ්‍රව ලිපිත් ඇතුව භාවසන්න සහිත සුභාෂිත රත්න මාලාව/ඌර්ධ්‍රව ලිපිත් ඇතුව භාවසන්න සහිත සුභාෂිත රත්න මාලාව.txt
  Extracted 'written_date': ''
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/දුර්ලබ්ධි මර්ධනය
  Found metadata.json: data/OCR_Final/දුර්ලබ්ධි මර්ධනය/metadata.json
  Found associated text file: data/OCR_Final/දුර්ලබ්ධි මර්ධනය/දුර්ලබ්ධි මර්ධනය.txt
  Extracted 'written_date': ''
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/සන්න සහිත ආශිර්විෂොපම සූත්‍රය
  Found metadata.json: data/OCR_Final/සන්න සහිත ආශිර්විෂොපම සූත්‍රය/metadata.json
  Found associated text file: data/OCR_Final/සන්න සහිත ආශිර්විෂොපම සූත්‍රය/සන්න සහිත ආශිර්විෂොපම සූත්‍රය.txt
  Extracted 'written_date': ''
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/බුද්ධාගම නොහොත් පඤ්චස්කන්ධ විභාගය
  Found metadata.json: data/OCR_Final/බුද්ධාගම නොහොත් පඤ්චස්කන්ධ විභාගය/metadata.json
  Found associated text file: data/OCR_Final/බුද්ධාගම නොහොත් පඤ්චස්කන්ධ විභාගය/බුද්ධාගම නොහොත් පඤ්චස්කන්ධ විභාගය.txt
  Extracted 'written_date': ''
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/ජුබිලි වර්ණනාව
  Found metadata.json: data/OCR_Final/ජුබිලි වර්ණනාව/metadata.json
  Found associated text file: data/OCR_Final/ජුබිලි වර්ණනාව/ජුබිලි වර්ණනාව.txt
  Extracted 'written_date': '1857 - 1922'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/නමස්කාරවාද විදාරණය
  Found metadata.json: data/OCR_Final/නමස්කාරවාද විදාරණය/metadata.json
  Found associated text file: data/OCR_Final/නමස්කාරවාද විදාරණය/නමස්කාරවාද විදාරණය.txt
  Extracted 'written_date': ''
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/රුවන්වැලි විසිතුර සහ සොනුත්තර සාමනේරයින් නා ලොවින් ධාතු ගෙණ ඊම
  Found metadata.json: data/OCR_Final/රුවන්වැලි විසිතුර සහ සොනුත්තර සාමනේරයින් නා ලොවින් ධාතු ගෙණ ඊම/metadata.json
  Found associated text file: data/OCR_Final/රුවන්වැලි විසිතුර සහ සොනුත්තර සාමනේරයින් නා ලොවින් ධාතු ගෙණ ඊම/රුවන්වැලි විසිතුර සහ සොනුත්තර සාමනේරයින් නා ලොවින් ධාතු ගෙණ ඊම.txt
  Extracted 'written_date': ''
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/සිතියම් සහිත සද්ධර්මාලංකාරය
  Found metadata.json: data/OCR_Final/සිතියම් සහිත සද්ධර්මාලංකාරය/metadata.json
  Found associated text file: data/OCR_Final/සිතියම් සහිත සද්ධර්මාලංකාරය/සිතියම් සහිත සද්ධර්මාලංකාරය.txt
  Extracted 'written_date': '1398 - 1410'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/උභය ලෝකාර්ථ සිද්ධිය සදහා ගිහි ජනයන් විසින් පිළිපැදිය යුතු වූ ප්‍රාපතකර්ම සූත්‍රය
  Found metadata.json: data/OCR_Final/උභය ලෝකාර්ථ සිද්ධිය සදහා ගිහි ජනයන් විසින් පිළිපැදිය යුතු වූ ප්‍රාපතකර්ම සූත්‍රය/metadata.json
  Found associated text file: data/OCR_Final/උභය ලෝකාර්ථ සිද්ධිය සදහා ගිහි ජනයන් විසින් පිළිපැදිය යුතු වූ ප්‍රාපතකර්ම සූත්‍රය/උභය ලෝකාර්ථ සිද්ධිය සදහා ගිහි ජනයන් විසින් පිළිපැදිය යුතු වූ ප්‍රාපතකර්ම සූත්‍රය.txt
  Extracted 'written_date': ''
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/මහා සමනල හෑල්ල හෙවත් පුරාණ සමනල හෑල්ල
  Found metadata.json: data/OCR_Final/මහා සමනල හෑල්ල හෙවත් පුරාණ සමනල හෑල්ල/metadata.json
  Found associated text file: data/OCR_Final/මහා සමනල හෑල්ල හෙවත් පුරාණ සමනල හෑල්ල/මහා සමනල හෑල්ල හෙවත් පුරාණ සමනල හෑල්ල.txt
  Extracted 'written_date': ''
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/කඨිනවාදය
  Found metadata.json: data/OCR_Final/කඨිනවාදය/metadata.json
  Found associated text file: data/OCR_Final/කඨිනවාදය/කඨිනවාදය.txt
  Extracted 'written_date': ''
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/උම්මග්ග ජාතකය
  Found metadata.json: data/OCR_Final/උම්මග්ග ජාතකය/metadata.json
  Found associated text file: data/OCR_Final/උම්මග්ග ජාතකය/උම්මග්ග ජාතකය.txt
  Extracted 'written_date': ''
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/පුරාණ කතිකාවත්
  Found metadata.json: data/OCR_Final/පුරාණ කතිකාවත්/metadata.json
  Found associated text file: data/OCR_Final/පුරාණ කතිකාවත්/පුරාණ කතිකාවත්.txt
  Extracted 'written_date': ''
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/හංස සංදේශ සරලාර්ථ සංග්‍රහය
  Found metadata.json: data/OCR_Final/හංස සංදේශ සරලාර්ථ සංග්‍රහය/metadata.json
  Found associated text file: data/OCR_Final/හංස සංදේශ සරලාර්ථ සංග්‍රහය/හංස සංදේශ සරලාර්ථ සංග්‍රහය.txt
  Extracted 'written_date': ''
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/අසබැඳි සබැඳි
  Found metadata.json: data/OCR_Final/අසබැඳි සබැඳි/metadata.json
  Found associated text file: data/OCR_Final/අසබැඳි සබැඳි/අසබැඳි සබැඳි.txt
  Extracted 'written_date': ''
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/ශ්‍රී බාලාවබෝධනය
  Found metadata.json: data/OCR_Final/ශ්‍රී බාලාවබෝධනය/metadata.json
  Found associated text file: data/OCR_Final/ශ්‍රී බාලාවබෝධනය/ශ්‍රී බාලාවබෝධනය.txt
  Extracted 'written_date': ''
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/ශ්‍රී සද්ධම්මයෙහි ඵිතීය ධම්ම විනිශ්චය නොහොත් දුශ්ශිල මද්දිනයන්ට පිළිතුරුව
  Found metadata.json: data/OCR_Final/ශ්‍රී සද්ධම්මයෙහි ඵිතීය ධම්ම විනිශ්චය නොහොත් දුශ්ශිල මද්දිනයන්ට පිළිතුරුව/metadata.json
  Found associated text file: data/OCR_Final/ශ්‍රී සද්ධම්මයෙහි ඵිතීය ධම්ම විනිශ්චය නොහොත් දුශ්ශිල මද්දිනයන්ට පිළිතුරුව/ශ්‍රී සද්ධම්මයෙහි ඵිතීය ධම්ම විනිශ්චය නොහොත් දුශ්ශිල මද්දිනයන්ට පිළිතුරුව.txt
  Extracted 'written_date': ''
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/අහමඩ් - අරාබි කථන්දරය
  Found metadata.json: data/OCR_Final/අහමඩ් - අරාබි කථන්දරය/metadata.json
  Found associated text file: data/OCR_Final/අහමඩ් - අරාබි කථන්දරය/අහමඩ් - අරාබි කථන්දරය.txt
  Extracted 'written_date': ''
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/ශාංගධර සංහිතා
  Found metadata.json: data/OCR_Final/ශාංගධර සංහිතා/metadata.json
  Found associated text file: data/OCR_Final/ශාංගධර සංහිතා/ශාංගධර සංහිතා.txt
  Extracted 'written_date': ''
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/පුරාණ සන්න සහිත බාල පණ්ඩිත සූත්‍රය
  Found metadata.json: data/OCR_Final/පුරාණ සන්න සහිත බාල පණ්ඩිත සූත්‍රය/metadata.json
  Found associated text file: data/OCR_Final/පුරාණ සන්න සහිත බාල පණ්ඩිත සූත්‍රය/පුරාණ සන්න සහිත බාල පණ්ඩිත සූත්‍රය.txt
  Extracted 'written_date': ''
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/විශුද්ධිමාර්ගය බ්‍රහ්මවිහාර නිර්දේශාත්මක තෘතීය භාගය
  Found metadata.json: data/OCR_Final/විශුද්ධිමාර්ගය බ්‍රහ්මවිහාර නිර්දේශාත්මක තෘතීය භාගය/metadata.json
  Found associated text file: data/OCR_Final/විශුද්ධිමාර්ගය බ්‍රහ්මවිහාර නිර්දේශාත්මක තෘතීය භාගය/විශුද්ධිමාර්ගය බ්‍රහ්මවිහාර නිර්දේශාත්මක තෘතීය භාගය.txt
  Extracted 'written_date': '1412 - 1467'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/මාල කොබෝ සංදේශය නොහොත් ස්කන්ධ කුමාර දෙවියන්ට ආරාධනයක්
  Found metadata.json: data/OCR_Final/මාල කොබෝ සංදේශය නොහොත් ස්කන්ධ කුමාර දෙවියන්ට ආරාධනයක්/metadata.json
  Found associated text file: data/OCR_Final/මාල කොබෝ සංදේශය නොහොත් ස්කන්ධ කුමාර දෙවියන්ට ආරාධනයක්/මාල කොබෝ සංදේශය නොහොත් ස්කන්ධ කුමාර දෙවියන්ට ආරාධනයක්.txt
  Extracted 'written_date': ''
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/රුවන්වැලි විස්තරය
  Found metadata.json: data/OCR_Final/රුවන්වැලි විස්තරය/metadata.json
  Found associated text file: data/OCR_Final/රුවන්වැලි විස්තරය/රුවන්වැලි විස්තරය.txt
  Extracted 'written_date': ''
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/උත්තර සාමණේර කතා වස්තුව හෙවත් කිණිහිරි නම් දිව්‍යවිමාන විස්තරය

In [5]:
list_of_file_locations.head()

  written_date                                 text_file_location
0  1187 - 1225  /Users/nevidujayatilleke/Documents/MSC - Resea...
1               /Users/nevidujayatilleke/Documents/MSC - Resea...
2  1832 - 1907  /Users/nevidujayatilleke/Documents/MSC - Resea...
3  1901 - 1938  /Users/nevidujayatilleke/Documents/MSC - Resea...
4         1944  /Users/nevidujayatilleke/Documents/MSC - Resea...

In [6]:
def clean_words(data, path = True):
    try:
        if path:
            with open(data, 'r', encoding='utf-8') as file:
                text = file.read()
        else:
            text = data
        # Pattern: Split by whitespace OR find and keep the <psi> token
        tokens = re.split(r'(\s+|<psi>)', text)
        
        # Filter out empty strings and pure whitespace left by re.split()
        tokens = [t.strip() for t in tokens if t.strip()]  # FIX: keep '<psi>' so the merge loop below can see it

        # 2. Handle the <psi> token by concatenating adjacent words
        processed_tokens = []
        i = 0
        while i < len(tokens):
            if tokens[i] == '<psi>':
                # Check for preceding and succeeding words
                if i > 0 and i < len(tokens) - 1:
                    # Concatenate the left word, right word, and replace the <psi>
                    new_word = tokens[i-1] + tokens[i+1]
                    # Replace the previous token (which was added in the previous loop iteration)
                    processed_tokens[-1] = new_word
                    i += 2  # Skip <psi> and the concatenated right word
                elif i > 0:
                    # <psi> is at the end, just remove it.
                    i += 1
                elif i < len(tokens) - 1:
                    # <psi> is at the start, just remove it.
                    i += 1
                else:
                    # <psi> is the only token, just remove it.
                    i += 1
            else:
                processed_tokens.append(tokens[i])
                i += 1

        # Re-join the processed tokens into a single string for cleaning
        processed_text = ' '.join(processed_tokens)

        # 3. Remove non-Sinhala characters (keeping Sinhala Unicode range and whitespace)
        cleaned = re.sub(r'[^\u0D80-\u0DFF\s]', '', processed_text)

        # 4. Tokenize by whitespace and count
        words = cleaned.split()
        return words

    except Exception as e:
        print(f"Error reading {path}: {e}")
        return 0

In [7]:
all_text = ""
for path in list_of_file_locations['text_file_location']:
    try:
        with open(path, 'r', encoding='utf-8') as file:
            all_text += file.read()
    except Exception as e:
        print(f"Error reading {path}: {e}")

In [8]:
cleaned_text = clean_words(all_text, path = False)

In [9]:
import nltk
import string
from collections import defaultdict, Counter
from typing import List, Dict, Tuple

In [10]:
def find_context_cooccurrences(tokens: List[str], window: int) -> Dict[str, Counter]:
    """
    Finds all words co-occurring within a +/- window of a target word.

    Args:
        tokens: The list of pre-processed words.
        window: The +/- context window size.

    Returns:
        A dictionary where keys are target words and values are Counter 
        objects of their co-occurring neighbors.
    """
    # Use defaultdict to automatically create a Counter object for new target words
    cooccurrence_map = defaultdict(Counter)
    
    # Iterate through every token in the text, treating it as the target word
    for i, target_word in enumerate(tokens):
        # Define the start and end indices for the window
        start_index = max(0, i - window)
        end_index = min(len(tokens), i + window + 1) # +1 because slice end is exclusive
        
        # Extract the context window slice
        context_window = tokens[start_index:end_index]
        
        # Add all words in the window to the target word's Counter
        for neighbor in context_window:
            # We skip the target word itself to only count its neighbors
            if neighbor != target_word:
                cooccurrence_map[target_word][neighbor] += 1
                
    return cooccurrence_map

In [11]:
WINDOW_SIZE = 10 

cooccurrence_results = find_context_cooccurrences(cleaned_text, WINDOW_SIZE)

In [12]:
cooccurrence_results['මිතුර']

Counter({'තොප': 12,
         'කල': 9,
         'අප': 5,
         'වලා': 5,
         'සිටි': 4,
         'තැනටත්': 4,
         'කෙරෙති': 4,
         'වෙත': 4,
         'ඉන්': 4,
         'සිත': 4,
         'යන': 4,
         'සඳ': 4,
         'සැටි': 3,
         'දිනති': 3,
         'අහස': 3,
         'යස': 3,
         'පවසමි': 3,
         'කෙලෙස': 3,
         'මන': 3,
         'මියුරු': 3,
         'වන': 3,
         'සිරි': 3,
         'පෙර': 3,
         'රැගෙණ': 2,
         'වැඩෙයි': 2,
         'අන්වය': 2,
         'ද': 2,
         'හිරු': 2,
         'රුති': 2,
         'බැති': 2,
         'වැඩෙ': 2,
         'යි': 2,
         'අදහස': 2,
         'පසුකර': 2,
         'මරකත': 2,
         'මිණි': 2,
         'ගොදුරු': 2,
         'පිපි': 2,
         'හිස': 2,
         'ගමන්': 2,
         'ලක්': 2,
         'වත්': 2,
         'සසර': 2,
         'සොඳ': 2,
         'ඉත': 2,
         'දැක': 2,
         'යනු': 2,
         'පවර': 2,
         'සිතින': 2,
         'මැන': 2,
         'යුතු': 2,
         'දස': 2,
         'පත': 2,
         'මෙ': 2,
         'මා': 2,
         'කොට': 2,
         'දිනතී': 1,
         'රුතී': 1,
         'බැතී': 1,
         'හසරද': 1,
         'තෙපලකින්': 1,
         'ලොවට': 1,
         'හසර': 1,
         'ඔබගේ': 1,
         'ආකාරය': 1,
         'ගත්': 1,
         'පියවුරු': 1,
         'කාමුකයෝ': 1,
         'රුචි': 1,
         'ඔබ': 1,
         'බැතිය': 1,
         'ක්රී': 1,
         'ප': 1,
         'ලමිතුර': 1,
         'ලෙස': 1,
         'පියුම්': 1,
         'මනකල්': 1,
         'ආහාරයක්': 1,
         'පියුම්හිස': 1,
         'ඉඳ': 1,
         'පොකුරු': 1,
         'පියඹුන්': 1,
         'පිණවනා': 1,
         'සකී': 1,
         'බැවෙහි': 1,
         'දුටු': 1,
         'වාසනා': 1,
         'වකී': 1,
         'තොපගෙන්': 1,
         'උවමනාවකී': 1,
         'පැරකුම්': 1,
         'රජුගෙ': 1,
         'ආසිරි': 1,
         'ලත්': 1,
         'පැරනී': 1,
         'ජය': 1,
         'පින්': 1,
         'හා': 1,
         'සිතිනී': 1,
         'පෙන්': 1,
         'බර': 1,
         'යනකල': 1,
         'මග': 1,
         'තුටිනී': 1,
         'සින්': 1,
         'හල': 1,
         'දනන්': 1,
         'මෙහෙයා': 1,
         'දුක්': 1,
         'හැඳ': 1,
         'එමට': 1,
         'රිත්': 1,
         'ලිය': 1,
         'නාන': 1,
         'රඟ': 1,
         'කෙළි': 1,
         'කවට': 1,
         'සිව්මන්': 1,
         'වෙතට': 1,
         'දෑරා': 1,
         'මසුරු': 1,
         'සිත්': 1,
         'මනැසින්': 1,
         'නෑරා': 1,
         'අවට': 1,
         'පොල්': 1,
         'උයෙනෙන්': 1,
         'පතර': 1,
         'මාරා': 1,
         'විලට': 1,
         'මහමේ': 1,
         'පතා': 1,
         'අමු': 1,
         'නිවන': 1,
         'නිය': 1,
         'මඟ': 1,
         'දැන': 1,
         'යෙහෙනී': 1,
         'ඉතා': 1,
         'උස': 1,
         'බැතින්': 1,
         'ජිනසේන': 1,
         'දකු': 1,
         'පස': 1,
         'තිබෙන': 1,
         'බඳ': 1,
         'මෙනයින්': 1,
         'තුටුවම': 1,
         'නොමින': 1,
         'ගසෙද': 1,
         'වඩින': 1,
         'පියකරු': 1,
         'සැමතැස': 1,
         'නරඹා': 1,
         'අතුර': 1,
         'ලස්': 1,
         'නොව': 1,
         'ගඟිනු': 1,
         'නුඹ': 1,
         'පිය': 1,
         'ඹා': 1,
         'පෙලින්': 1,
         'සමුදුර': 1,
         'න්න': 1,
         'පුලා': 1,
         'සිතින්': 1,
         'රැගෙන': 1,
         'මරකතමිණි': 1,
         'රිවි': 1,
         'මෙතින්': 1,
         'නොගෙන': 1,
         'උන්ගෙන්': 1,
         'වනඅයා': 1,
         'තින්': 1,
         'මගෙහි': 1,
         'ලෙසට': 1,
         'කියා': 1,
         'ඇද්දෝ': 1,
         'තැබීමට': 1,
         'පෙම': 1,
         'කවියෙහිද': 1,
         'නැතිසර': 1,
         'කන්': 1,
         'යන්නට': 1,
         'මෙවර': 1,
         'වරද': 1,
         'නොකියා': 1,
         'කිතු': 1,
         'සමයෙහි': 1,
         'දුලද': 1,
         'සැම': 1,
         'ලොවැ': 1,
         'වගතුගක්': 1,
         'කී': 1,
         'දහමක්': 1,
         'ඇතිද': 1,
         'සැදී': 1,
         'ඈහී': 1,
         'ජේ': 1,
         'නැම්සි': 1,
         'ලඳ': 1,
         'බැඳී': 1,
         'ඇති': 1,
         'කතුට': 1,
         'ආයෙද': 1,
         'කිරිය': 1,
         'ඇද': 1,
         'පාසට': 1,
         'මට': 1,
         'සපන්': 1,
         'ලද': 1,
         'අඟනන්': 1,
         'දැකීමට': 1,
         'තොට': 1,
         'වලින්': 1,
         'නොරඳව': 1,
         'බෝ': 1,
         'කුසුමෙන්': 1,
         'කොක': 1,
         'වලනිරැස': 1,
         'ලොල්': 1,
         'දියර': 1,
         'ගැණුමට': 1,
         'ගවපල්': 1,
         'සසල': 1,
         'රැදිගුණ': 1,
         'සදිසිතර': 1,
         'ගඟින්': 1,
         'එතරට': 1,
         'යව': 1,
         'ව': 1,
         'ජේම්ස්': 1,
         'අල්විස්': 1,
         'උන්නාන්සේ': 1,
         'විසින්': 1,
         'මෙසේ': 1,
         'වර්ණනා': 1,
         'තිබේ': 1,
         'තර': 1,
         'ඉසුරු': 1,
         'ලැබ': 1,
         'සිරිලක': 1,
         'දවසරිණ': 1,
         'ගුණ': 1,
         'දරණ': 1,
         'සොයිසා': 1,
         'මැති': 1,
         'වරණ': 1,
         'ගොස්': 1,
         'දෙව': 1,
         'නමකර': 1,
         'සරණ': 1,
         'මේ': 1,
         'තුරේ': 1})

In [13]:
def print_top_cooccurrences(results: Dict[str, Counter], target_word: str, top_n: int = 5):
    """Prints the top co-occurring words for a specific target word."""
    if target_word in results:
        print(f"\n--- Top {top_n} Co-occurring words for '{target_word.upper()}' (within +/- {WINDOW_SIZE} window) ---")
        # Get the N most common neighbors
        top_neighbors = results[target_word].most_common(top_n)
        
        for neighbor, count in top_neighbors:
            print(f"- '{neighbor}': {count} times")
    else:
        print(f"'{target_word}' not found in the text or did not meet filtering criteria.")

In [14]:
print_top_cooccurrences(cooccurrence_results, 'සමග', top_n=5)

--- Top 5 Co-occurring words for 'සමග' (within +/- 10 window) ---
- 'හා': 77 times
- 'වූ': 60 times
- 'ඒ': 42 times
- 'නම්': 35 times
- 'විවාහ': 25 times

In [15]:
filename = 'z_score_analysis.json'

In [16]:
#5.2930

with open(filename, 'r', encoding='utf-8') as f:
        # Use json.load() to parse the JSON data into a Python object
        loaded_results: List[Dict[str, Any]] = json.load(f)

In [17]:
Z_SCORE_THRESHOLD = 5.2930

In [18]:
# Initialize an empty list to store the words that meet the criteria
highly_significant_words: List[Dict[str, Any]] = []

# Iterate through the loaded data and filter
for item in loaded_results:
    if item['z_score'] > Z_SCORE_THRESHOLD:
        highly_significant_words.append(item)

In [19]:
count_less_than_threshold = 0
for item in loaded_results:
    if item['z_score'] < Z_SCORE_THRESHOLD:
        count_less_than_threshold += 1

In [20]:
coverage_percentage = (count_less_than_threshold / len(loaded_results)) * 100
print(f"Total items: {len(loaded_results)}")
print(f"Items with -inf < Z < {Z_SCORE_THRESHOLD}: {count_less_than_threshold}")
print(f"Coverage for -inf < Z < {Z_SCORE_THRESHOLD}: {coverage_percentage:.2f}%")

Total items: 61368
Items with -inf < Z < 5.293: 61247
Coverage for -inf < Z < 5.293: 99.80%

In [21]:
highly_significant_words.sort(key=lambda x: x['z_score'], reverse=True)

In [22]:
highly_significant_words

[{'word': 'වූ', 'z_score': 140.6029636003449},
 {'word': 'ඒ', 'z_score': 70.6909537005933},
 {'word': 'ද', 'z_score': 63.19342617652523},
 {'word': 'මේ', 'z_score': 62.21972130326964},
 {'word': 'නම්', 'z_score': 60.79162082249477},
 {'word': 'යන', 'z_score': 42.291228230638495},
 {'word': 'කොට', 'z_score': 36.83848094040717},
 {'word': 'විසින්', 'z_score': 32.42435218164848},
 {'word': 'න', 'z_score': 31.807672428586606},
 {'word': 'ඇති', 'z_score': 28.919014637928345},
 {'word': 'ලද', 'z_score': 27.263716353393836},
 {'word': 'හා', 'z_score': 23.011871740177746},
 {'word': 'ය', 'z_score': 22.070623696030673},
 {'word': 'න්', 'z_score': 20.642523215255803},
 {'word': 'යයි', 'z_score': 19.60390468378317},
 {'word': 'බව', 'z_score': 19.57144785467465},
 {'word': 'ට', 'z_score': 18.889854443395734},
 {'word': 'ර', 'z_score': 18.630199810527575},
 {'word': 'වේ', 'z_score': 18.0135200574657},
 {'word': 'කියා', 'z_score': 17.299469817078265},
 {'word': 'කරණ', 'z_score': 16.68279006401639},
 {'word': 'ස', 'z_score': 16.098567140063032},
 {'word': 'ම', 'z_score': 15.806455678086355},
 {'word': 'මහා', 'z_score': 15.546801045218198},
 {'word': 'හෝ', 'z_score': 15.514344216109677},
 {'word': 'වහන්සේ', 'z_score': 15.287146412350038},
 {'word': 'කළ', 'z_score': 15.0599486085904},
 {'word': 'හෙයින්', 'z_score': 14.897664463047802},
 {'word': 'කර', 'z_score': 14.735380317505204},
 {'word': 'සේ', 'z_score': 14.280984709985926},
 {'word': 'මෙසේ', 'z_score': 14.248527880877406},
 {'word': 'එ', 'z_score': 13.89150276068369},
 {'word': 'තෙම', 'z_score': 13.89150276068369},
 {'word': 'යම්', 'z_score': 13.72921861514109},
 {'word': 'යි', 'z_score': 13.242366178513294},
 {'word': 'නා', 'z_score': 12.690600083668457},
 {'word': 'වන', 'z_score': 12.23620447614918},
 {'word': 'යනු', 'z_score': 12.13883398882362},
 {'word': 'එහි', 'z_score': 12.00900667238954},
 {'word': 'ව', 'z_score': 11.814265697738422},
 {'word': 'වී', 'z_score': 11.587067893978784},
 {'word': 'නේ', 'z_score': 11.294956432002106},
 {'word': 'මහ', 'z_score': 11.262499602893586},
 {'word': 'මෙන්', 'z_score': 11.230042773785067},
 {'word': 'යුතු', 'z_score': 11.230042773785067},
 {'word': 'මෙ', 'z_score': 11.165129115568027},
 {'word': 'වශයෙන්', 'z_score': 10.840560824482829},
 {'word': 'සහ', 'z_score': 10.74319033715727},
 {'word': 'ක', 'z_score': 10.74319033715727},
 {'word': 'පිණිස', 'z_score': 10.613363020723192},
 {'word': 'නැති', 'z_score': 10.580906191614671},
 {'word': 'කියන', 'z_score': 10.51599253339763},
 {'word': 'හට', 'z_score': 10.451078875180592},
 {'word': 'මෙහි', 'z_score': 10.321251558746512},
 {'word': 'ත', 'z_score': 10.288794729637994},
 {'word': 'එක', 'z_score': 10.158967413203914},
 {'word': 'ලෙස', 'z_score': 9.996683267661314},
 {'word': 'ධර්ම', 'z_score': 9.964226438552796},
 {'word': 'වෙයි', 'z_score': 9.834399122118716},
 {'word': 'රජ', 'z_score': 9.704571805684637},
 {'word': 'මා', 'z_score': 9.704571805684637},
 {'word': 'ල', 'z_score': 9.672114976576117},
 {'word': 'හෙවත්', 'z_score': 9.477374001924998},
 {'word': 'බැවින්', 'z_score': 9.1528057108398},
 {'word': 'කල', 'z_score': 9.087892052622761},
 {'word': 'විය', 'z_score': 9.022978394405722},
 {'word': 'සේක', 'z_score': 8.925607907080163},
 {'word': 'ත්', 'z_score': 8.828237419754602},
 {'word': 'නො', 'z_score': 8.730866932429043},
 {'word': 'දී', 'z_score': 8.665953274212004},
 {'word': 'එම', 'z_score': 8.633496445103484},
 {'word': 'අ', 'z_score': 8.568582786886445},
 {'word': 'අප', 'z_score': 8.536125957777925},
 {'word': 'සතර', 'z_score': 8.373841812235327},
 {'word': 'කල්හි', 'z_score': 8.373841812235327},
 {'word': 'සියලු', 'z_score': 8.373841812235327},
 {'word': 'ගුණ', 'z_score': 7.984359862933088},
 {'word': 'පටන්', 'z_score': 7.886989375607529},
 {'word': 'එසේ', 'z_score': 7.69224840095641},
 {'word': 'ලා', 'z_score': 7.59487791363085},
 {'word': 'ගෙණ', 'z_score': 7.562421084522331},
 {'word': 'වැඩ', 'z_score': 7.529964255413811},
 {'word': 'බුදුන්', 'z_score': 7.497507426305291},
 {'word': 'මම', 'z_score': 7.497507426305291},
 {'word': 'වනාහි', 'z_score': 7.302766451654173},
 {'word': 'එක්', 'z_score': 7.1080254770030535},
 {'word': 'දැක', 'z_score': 7.075568647894534},
 {'word': 'ගොස්', 'z_score': 6.913284502351935},
 {'word': 'කී', 'z_score': 6.848370844134895},
 {'word': 'සිටි', 'z_score': 6.751000356809336},
 {'word': 'දැන', 'z_score': 6.751000356809336},
 {'word': 'ති', 'z_score': 6.588716211266737},
 {'word': 'නිසා', 'z_score': 6.491345723941178},
 {'word': 'ණ', 'z_score': 6.491345723941178},
 {'word': 'ප්රකාශ', 'z_score': 6.393975236615619},
 {'word': 'වදාළ', 'z_score': 6.393975236615619},
 {'word': 'බොහෝ', 'z_score': 6.264147920181539},
 {'word': 'ලේ', 'z_score': 6.264147920181539},
 {'word': 'නැත', 'z_score': 6.1992342619645004},
 {'word': 'කරන', 'z_score': 6.16677743285598},
 {'word': 'ප', 'z_score': 6.16677743285598},
 {'word': 'සමග', 'z_score': 6.134320603747461},
 {'word': 'පමණ', 'z_score': 6.069406945530421},
 {'word': 'තිබෙන', 'z_score': 6.0369501164219015},
 {'word': 'ක්', 'z_score': 6.0369501164219015},
 {'word': 'නොහොත්', 'z_score': 6.004493287313381},
 {'word': 'යෙ', 'z_score': 5.939579629096342},
 {'word': 'ඔහු', 'z_score': 5.939579629096342},
 {'word': 'සිත', 'z_score': 5.907122799987822},
 {'word': 'මට', 'z_score': 5.809752312662263},
 {'word': 'ශ්රී', 'z_score': 5.777295483553743},
 {'word': 'බුදු', 'z_score': 5.712381825336704},
 {'word': 'මෙම', 'z_score': 5.712381825336704},
 {'word': 'එය', 'z_score': 5.712381825336704},
 {'word': 'කෙරෙහි', 'z_score': 5.679924996228184},
 {'word': 'මහත්', 'z_score': 5.647468167119664},
 {'word': 'ඊට', 'z_score': 5.582554508902624},
 {'word': 'ආදි', 'z_score': 5.582554508902624},
 {'word': 'හැර', 'z_score': 5.582554508902624},
 {'word': 'ඉතා', 'z_score': 5.355356705142986},
 {'word': 'රු', 'z_score': 5.355356705142986}]

In [23]:
highly_significant_word_set: Set[str] = {
    item['word'] for item in highly_significant_words 
    if item['z_score'] > Z_SCORE_THRESHOLD
}

In [24]:
highly_significant_word_set # 'ධර්ම', 'ප්රකාශ', 'පිණිස', 'බුද්ධ', 'බුදු', 'බුදුන්', 'බොහෝ', 'මහ', 'මහත්', 'රජ', 'යුක්ත', 'වදාළ', 'වහන්සේ', 'වැඩ', 'ශ්රී', 'සතර', 'සඳ', 'සමග', 'සිත', 'සිත්', 'සියලු'

{'අ',
 'අප',
 'ආදි',
 'ඇති',
 'ඉතා',
 'ඊට',
 'එ',
 'එක',
 'එක්',
 'එම',
 'එය',
 'එසේ',
 'එහි',
 'ඒ',
 'ඔහු',
 'ක',
 'කර',
 'කරණ',
 'කරන',
 'කල',
 'කල්හි',
 'කළ',
 'ක්',
 'කියන',
 'කියා',
 'කී',
 'කෙරෙහි',
 'කොට',
 'ගුණ',
 'ගෙණ',
 'ගොස්',
 'ට',
 'ණ',
 'ත',
 'ත්',
 'ති',
 'තිබෙන',
 'තෙම',
 'ද',
 'දැක',
 'දැන',
 'දී',
 'ධර්ම',
 'න',
 'නම්',
 'න්',
 'නා',
 'නැත',
 'නැති',
 'නිසා',
 'නේ',
 'නො',
 'නොහොත්',
 'ප',
 'පටන්',
 'පමණ',
 'ප්රකාශ',
 'පිණිස',
 'බව',
 'බැවින්',
 'බුදු',
 'බුදුන්',
 'බොහෝ',
 'ම',
 'මට',
 'මම',
 'මහ',
 'මහත්',
 'මහා',
 'මා',
 'මෙ',
 'මෙන්',
 'මෙම',
 'මෙසේ',
 'මෙහි',
 'මේ',
 'ය',
 'යන',
 'යනු',
 'යම්',
 'යයි',
 'යි',
 'යුතු',
 'යෙ',
 'ර',
 'රජ',
 'රු',
 'ල',
 'ලද',
 'ලා',
 'ලෙස',
 'ලේ',
 'ව',
 'වදාළ',
 'වන',
 'වනාහි',
 'වශයෙන්',
 'වහන්සේ',
 'වැඩ',
 'විය',
 'විසින්',
 'වී',
 'වූ',
 'වෙයි',
 'වේ',
 'ශ්රී',
 'ස',
 'සතර',
 'සමග',
 'සහ',
 'සිටි',
 'සිත',
 'සියලු',
 'සේ',
 'සේක',
 'හට',
 'හා',
 'හැර',
 'හෙයින්',
 'හෙවත්',
 'හෝ'}

In [25]:
identified_non_stopwords = ['ධර්ම', 'ප්රකාශ', 'පිණිස', 'බුද්ධ', 'බුදු', 'බුදුන්', 'බොහෝ', 'මහ', 'මහත්', 'රජ', 'යුක්ත', 'වදාළ', 'වහන්සේ', 'වැඩ', 'ශ්රී', 'සතර', 'සඳ', 'සමග', 'සිත', 'සිත්', 'සියලු']

In [26]:
highly_significant_word_set = [item for item in highly_significant_word_set if item not in identified_non_stopwords]

In [27]:
highly_significant_word_set

['වන',
 'යන',
 'වනාහි',
 'එම',
 'සහ',
 'මා',
 'නො',
 'ස',
 'නැති',
 'මහා',
 'පමණ',
 'මෙහි',
 'කියන',
 'විසින්',
 'එක්',
 'තෙම',
 'පටන්',
 'යෙ',
 'නැත',
 'ප',
 'කොට',
 'කරණ',
 'ඔහු',
 'හට',
 'ති',
 'වේ',
 'නේ',
 'කරන',
 'ය',
 'දැක',
 'ඇති',
 'ගුණ',
 'ලද',
 'කල',
 'කී',
 'සේක',
 'යනු',
 'ක්',
 'ර',
 'සේ',
 'හෝ',
 'රු',
 'එහි',
 'ට',
 'එ',
 'අප',
 'මේ',
 'වෙයි',
 'නම්',
 'ද',
 'ම',
 'හැර',
 'යුතු',
 'එය',
 'නිසා',
 'බැවින්',
 'තිබෙන',
 'මෙසේ',
 'න්',
 'වූ',
 'විය',
 'ගොස්',
 'මට',
 'ව',
 'වී',
 'මෙන්',
 'ගෙණ',
 'මෙ',
 'අ',
 'සිටි',
 'ඊට',
 'යි',
 'වශයෙන්',
 'ණ',
 'ත',
 'හා',
 'නොහොත්',
 'ත්',
 'නා',
 'කර',
 'කෙරෙහි',
 'ඉතා',
 'එක',
 'කියා',
 'බව',
 'මෙම',
 'කල්හි',
 'ක',
 'ඒ',
 'මම',
 'කළ',
 'හෙයින්',
 'එසේ',
 'ල',
 'හෙවත්',
 'ලේ',
 'යම්',
 'ලා',
 'දැන',
 'දී',
 'ආදි',
 'ලෙස',
 'යයි',
 'න']

In [28]:
filtered_cooccurrence_map: Dict[str, Counter] = {}

for target_word, neighbors_counter in cooccurrence_results.items():
    
    # A. Target word is NOT SKIPPED, regardless of its significance.
    #    The original line 'if target_word in highly_significant_word_set: continue' is removed.
    
    # B. Filter its NEIGHBORS (Values)
    filtered_neighbors_counter = Counter()
    
    for neighbor, count in neighbors_counter.items():
        # Check if the NEIGHBOR word is highly significant
        if neighbor not in highly_significant_word_set:
            # If the neighbor is NOT significant, keep it
            filtered_neighbors_counter[neighbor] = count
            
    # C. Only save the target word if it still has non-empty neighbors after filtering
    if filtered_neighbors_counter:
        filtered_cooccurrence_map[target_word] = filtered_neighbors_counter

In [29]:
filtered_cooccurrence_map['දරුවන්']

Counter({'රජ': 25,
         'වැදැහැ': 8,
         'ඔවුන්': 7,
         'පුත්ර': 7,
         'ස්වාමි': 5,
         'සමග': 5,
         'විවාහ': 5,
         'ගෑනු': 5,
         'මින්': 5,
         'විනාස': 5,
         'සෙසු': 4,
         'ඇගේ': 4,
         'දොන්': 4,
         'මහතා': 4,
         'පිරිමි': 4,
         'දෙදෙනකු': 4,
         'ලැබ': 4,
         'අදර්ශනයට': 4,
         'අත්': 3,
         'පා': 3,
         'ගත': 3,
         'අඹු': 3,
         'ලබා': 3,
         'තමන්': 3,
         'පිණිස': 3,
         'තොමෝ': 3,
         'කුරුප්පු': 3,
         'ජන්මාන්තර': 3,
         'වැඩිමහලු': 3,
         'ලැබුවාය': 3,
         'මේරි': 3,
         'ලත්': 3,
         'මූලොච්ඡින්න': 3,
         'කෙරෙමි': 3,
         'හැ': 3,
         'පමුනුවමි': 3,
         'මහාපරිනිර්වාණ': 3,
         'සූත්රය': 3,
         'අවැඩට': 3,
         'යුත්තේය': 3,
         'උගන්නා': 3,
         'ව්යාකරණ': 3,
         'පිය': 2,
         'යෙහි': 2,
         'බාල': 2,
         'හිස්': 2,
         'දෙදෙන': 2,
         'මහරජ': 2,
         'කියමින්': 2,
         'බොහෝ': 2,
         'ගම්': 2,
         'සුවඳ': 2,
         'අතීතයකි': 2,
         'කිරිකැටියන්': 2,
         'අත': 2,
         'ළදරුවන්': 2,
         'දඟකාර': 2,
         'තිදෙනා': 2,
         'නිවස': 2,
         'දන්නා': 2,
         'රටේ': 2,
         'සිටියේ': 2,
         'නමුත්': 2,
         'සිටියෝ': 2,
         'ලැබුනු': 2,
         'නිසාද': 2,
         'පැවත': 2,
         'එන': 2,
         'යහපත්': 2,
         'තරම්': 2,
         'සියලු': 2,
         'දඩ': 2,
         'නොදැක': 2,
         'ශොකයෙන්': 2,
         'වලට': 2,
         'ගියේය': 2,
         'තෙමේ': 2,
         'කාලයෙහි': 2,
         'සුදුසු': 2,
         'සිංහ': 2,
         'අවචිගේ': 2,
         'සිමන්': 2,
         'තිදෙනෙකු': 2,
         'විජේසේකර': 2,
         'කල්යාමෙන්': 2,
         'ඕ': 2,
         'තිදෙනකුද': 2,
         'මහතාගේ': 2,
         'ආවාහ': 2,
         'විසූ': 2,
         'තුන්': 2,
         'බෝසත්': 2,
         'මන්': 2,
         'වැද': 2,
         'බවත්': 2,
         'අභිභවනය': 2,
         'මහරජතෙම': 2,
         'කැමතිව': 2,
         'කීයේය': 2,
         'වජ්ජිරා': 2,
         'ජවංශොත': 2,
         'භූත': 2,
         'ලිච්ඡවි': 2,
         'අනය': 2,
         'ඡෙද්යය': 2,
         'වැදැ': 2,
         'පමුනුවම්': 2,
         'ඔවුන්ට': 2,
         'ක්ෂත්රිය': 2,
         'අනුයුත්තෙසු': 2,
         'රාජ්යයට': 2,
         'උන්': 2,
         'ගැන': 2,
         'සංඝරාජ': 2,
         'අවස්ථා': 2,
         'වේදී': 2,
         'පළමුවෙන්': 2,
         'ගෙන්': 2,
         'සිටිනාමළුවේ': 2,
         'තැන': 2,
         'දෙ': 1,
         'පක්ෂ': 1,
         'ඇත්තවුන්': 1,
         'වහන්සේ': 1,
         'ස්වර්ගස්ථ': 1,
         'කුලක්රමානුගත': 1,
         'වස්තු': 1,
         'සමවා': 1,
         'පිළිගත': 1,
         'මනා': 1,
         'ධර්ම': 1,
         'ද්වේෂී': 1,
         'අසත්': 1,
         'පුරුෂ': 1,
         'ජනයෝ': 1,
         'මෙලොව': 1,
         'පමුණුවන': 1,
         'කන්': 1,
         'නාසා': 1,
         'කැපීම්': 1,
         'ආදී': 1,
         'නානා': 1,
         'වචන': 1,
         'ඩබර': 1,
         'නඩුවට': 1,
         'සතරවරම්': 1,
         'කරා': 1,
         'සිටියාහුය': 1,
         'එවිට': 1,
         'සෙනාධිපති': 1,
         'යක්ෂ': 1,
         'සේනාධිපති': 1,
         'දිව්ය': 1,
         'රාජයෝ': 1,
         'නොයෙකුත්': 1,
         'බොරු': 1,
         'ප්රලාප': 1,
         'දැනට': 1,
         'ලංකාද්වීපයෙහි': 1,
         'සිංහළ': 1,
         'විළිබිය': 1,
         'නැතුවම': 1,
         'හීන': 1,
         'ජම්ම': 1,
         'යුතුය': 1,
         'වෙස්සන්තර': 1,
         'පූජක': 1,
         'බමුණා': 1,
         'පෘථිවිය': 1,
         'කම්පා': 1,
         'කෙළේයයි': 1,
         'ගිහි': 1,
         'බ්රාහ්මණ': 1,
         'ගෙන්වා': 1,
         'අද': 1,
         'තා': 1,
         'පස්දෙනා': 1,
         'නැවත්තාහ': 1,
         'තට': 1,
         'එයින්': 1,
         'භයෙක්': 1,
         'තාගේ': 1,
         'රක්ෂා': 1,
         'යෙහෙන්': 1,
         'ජීවත්': 1,
         'වෙවයි': 1,
         'අංග': 1,
         'අංගා': 1,
         'දිවන්නට': 1,
         'ගත්හ': 1,
         'සසර': 1,
         'වසන': 1,
         'ජන්මයෙක': 1,
         'ගම්දරුව': 1,
         'ඉපද': 1,
         'කෙළෙනාහු': 1,
         'දවසෙක': 1,
         'කොසඹෑසු': 1,
         'බලකින්': 1,
         'සියුම්': 1,
         'කූරක්': 1,
         'පිණිදිය': 1,
         'පුදා': 1,
         'සගමොක්': 1,
         'ලැබුබලේ': 1,
         'ගුනෝ': 1,
         'ගය': 1,
         'සාමි': 1,
         'කියති': 1,
         'බොරුවට': 1,
         'මෙමකලේ': 1,
         'මනෝ': 1,
         'දුස්': 1,
         'චරිතයෙන්': 1,
         'වැලකී': 1,
         'වඳිම්': 1,
         'සිරිපා': 1,
         'සමනලේ': 1,
         'වසර': 1,
         'දාහතරකට': 1,
         'පහළොවකට': 1,
         'එපිටින්': 1,
         'තුළ': 1,
         'ගතකළ': 1,
         'සොඳුරු': 1,
         'අතීතයයි': 1,
         'අරගන්නා': 1,
         'විට': 1,
         'වසරක්වත්': 1,
         'සම්පූර්ණ': 1,
         'වුණ': 1,
         'නිතර': 1,
         'හඬන': 1,
         'කිරි': 1,
         'ධාරාලාගේ': 1,
         'වැඩ': 1,
         'කටයුතු': 1,
         'හැමදෙයක්ම': 1,
         'කළේ': 1,
         'සීතා': 1,
         'කමනී': 1,
         'ගොඩනැගී': 1,
         'තිබුණේ': 1,
         'ධාරා': 1,
         'හැටියට': 1,
         'අම්මගේ': 1,
         'තාත්තගේ': 1,
         'නොවේ': 1,
         'කොයි': 1,
         'ඉසව්වලින්': 1,
         'සොයාගත්තාද': 1,
         'කියන්නට': 1,
         'පිළිතුරු': 1,
         'කීවත්': 1,
         'එවකට': 1,
         'වයස': 1,
         'හැටක්': 1,
         'ඇයගේ': 1,
         'පදිංචි': 1,
         'පිටරටයි': 1,
         'අයෝමා': 1,
         'ආන්ටිට': 1,
         'ධාරාලා': 1,
         'ප්රශ්නයක්': 1,
         'වෙලා': 1,
         'නැහැ': 1,
         'දේපළවල': 1,
         'අයිතිය': 1,
         'ගැනීමට': 1,
         'දෙදෙනා': 1,
         'මෙරට': 1,
         'ඔවුහු': 1,
         'ඇමරිකාවේ': 1,
         'ස්ථිර': 1,
         'පදිංචිය': 1,
         'හිඳුවන්නා': 1,
         'වූද': 1,
         'නොමරා': 1,
         'උලහිඳු': 1,
         'වන්නාවූද': 1,
         'කඩුවෙන්': 1,
         'හිසකපන්නා': 1,
         'වුද': 1,
         'පුද්ගල': 1,
         'නිරීක්ෂණය': 1,
         'කෙරේද': 1,
         'දකීද': 1,
         'මහණෙනි': 1,
         'එකල්හි': 1,
         'බාලපුද්ගලයා': 1,
         'යස': 1,
         'පොත්': 1,
         'වල': 1,
         'වෙසෙස': 1,
         'මදක්': 1,
         'දොස්': 1,
         'පළකරමි': 1,
         'ඇතිලෙස': 1,
         'වරද': 1,
         'අසා': 1,
         'මව්': 1,
         'සඳ': 1,
         'දඬුවම්': 1,
         'තද': 1,
         'ආදම්ට': 1,
         'ආදම්ගේ': 1,
         'ජීවන': 1,
         'හුස්ම': 1,
         'ඔහුට': 1,
         'දරුවන්ගෙන්': 1,
         'ප්රම්ප්රාවේ': 1,
         'කෙනෙකුගෙන්': 1,
         'තමුන්නාන්': 1,
         'සේද': 1,
         'ඇතිව': 1,
         'අනුන්ට': 1,
         'අනුශාසනා': 1,
         'කලත්': 1,
         'දෙමවුපියන්': 1,
         'තරමේ': 1,
         'හික්ම': 1,
         'වන්නා': 1,
         'අකුසලින්': 1,
         'දුරුව': 1,
         'කුසලෙහි': 1,
         'නෝ': 1,
         'කිඹුල්වත්': 1,
         'නුවර': 1,
         'යනාදීන්': 1,
         'ඔදන': 1,
         'නාමයෙන්': 1,
         'පංච': 1,
         'ප්රකාර': 1,
         'අතුරෙන්': 1,
         'සුදො': 1,
         'වුන්': 1,
         'මහරජහු': 1,
         'මහාමායා': 1,
         'දෙවීන්': 1,
         'කුස': 1,
         'පිළිසිඳ': 1,
         'සම්පුර්ණ': 1,
         'තැනැත්තිය': 1,
         'සමීපයට': 1,
         'ගියේ': 1,
         'ඕහට': 1,
         'මෙපමන': 1,
         'නියම': 1,
         'තබන': 1,
         'දණ්ඩ': 1,
         'නිග්රහ': 1,
         'සහිත': 1,
         'පෙළෙන': 1,
         'ලදුව': 1,
         'ආහාර': 1,
         'නොකැයේය': 1,
         'පැන්': 1,
         'නොබීයේය': 1,
         'සොයමින්': 1,
         'ප්රත්යන්ත': 1,
         'සිංහරාජ': 1,
         'කුමාරයානන්': 1,
         'පැමිණෙන': 1,
         'යක්ෂයෝ': 1,
         'නොවෙත්': 1,
         'යකින්නක්': 1,
         'විජය': 1,
         'රජු': 1,
         'ලද්දී': 1,
         'යන්න': 1,
         'ඇදහිය': 1,
         'නොවෙයි': 1,
         'යනුද': 1,
         'දෙන': 1,
         'දූ': 1,
         'පුත්රයකු': 1,
         'දුවක්ද': 1,
         'නිවුන්': 1,
         'වැදීය': 1,
         'පුත්රයාගේ': 1,
         'සිංහයාගේ': 1,
         'සමාන': 1,
         'මඩනා': 1,
         'තැනැත්තේ': 1,
         'ආහාරපාන': 1,
         'නොගත්තේය': 1,
         'සොයනුයේ': 1,
         'පිටිසර': 1,
         'ගමකට': 1,
         'ගමක්කරා': 1,
         'පැමිණේද': 1,
         'කුණ': 1,
         'රේඛාව': 1,
         'සමීපය': 1,
         'අංකුර': 1,
         'පැළය': 1,
         'මොටියා': 1,
         'මොටෙයියා': 1,
         'අංකපාලී': 1,
         'ඇකයෙන්': 1,
         'පාලනය': 1,
         'කරන්නී': 1,
         'උපමව': 1,
         'කිරිමව': 1,
         'අංකිත': 1,
         'සලකුණු': 1,
         'පාදාං': 1,
         'කිත': 1,
         'අවිච්ඡින්නව': 1,
         'ආ': 1,
         'ඊසාක්': 1,
         'කොට්ඨාසේ': 1,
         'රාළහාමි': 1,
         'සයිමන්': 1,
         'කළුතර': 1,
         'කච්චේරියේ': 1,
         'ඥාතිවරයකු': 1,
         'බස්තියන්': 1,
         'පීරිස්': 1,
         'රිජිස්ටර්': 1,
         'සොහොයුරිය': 1,
         'කරගත්': 1,
         'නොමැතිව': 1,
         'ඇවෑමෙන්': 1,
         'දෙවැනි': 1,
         'වරටත්': 1,
         'වැල්ලෙවත්තේ': 1,
         'විජේසිංහ': 1,
         'මුදලි': 1,
         'ඇලිස්': 1,
         'මාටින්': 1,
         'බ්රහම්': 1,
         'මිසි': 1,
         'කථා': 1,
         'ශෙෂ': 1,
         'භාවොපගත': 1,
         'වූවාය': 1,
         'සොපායා': 1,
         'සොහොයුරී': 1,
         'කොළඹ': 1,
         'ඇලෙක්': 1,
         'සැන්ඩර්එලිසබැත්ඇල්ප්රඩ්': 1,
         'ඇඩ්වින්': 1,
         'දියණියන්': 1,
         'බොල්ලෑගල': 1,
         'වළව්වේ': 1,
         'පාඨ': 1,
         'ශාලා': 1,
         'තෙන්නකෝන්': 1,
         'ඥාති': 1,
         'වරියකු': 1,
         'සිට': 1,
         'නොලැබ': 1,
         'ගතවිය': 1,
         'කණිෂ්ඨ': 1,
         'ආණ්ඩුවේ': 1,
         'සිවිල්': 1,
         'සර්විස්': 1,
         'චාර්ලට්': 1,
         'විල්හෙල්මිනා': 1,
         'මැතිණිය': 1,
         'ශුභ': 1,
         'සරණ': 1,
         'බන්ධනයට': 1,
         'ඇතුළත්': 1,
         'එකොළොස්': 1,
         'දෙනෙකු': 1,
         'ලැබුවේය': 1,
         'ජේ': 1,
         'ඩබ්ලිව්': 1,
         'ඇස්': 1,
         'ආටිගල': 1,
         'දොස්තර්': 1,
         'තවත්': 1,
         'සොහොයුරෙක්': 1,
         'ලෙව්වන්දූවේ': 1,
         'වලව්වේ': 1,
         'නැවතී': 1,
         'ජයනෙත්ති': 1,
         'පවුලෙන්': 1,
         'ආවාහයක්': 1,
         'කරගෙන': 1,
         'කීපදෙනකු': 1,
         'සිටියේය': 1,
         'මිනිරනින්': 1,
         'රබර්වලින්': 1,
         'උපයනලද': 1,
         'ධන': 1,
         'සම්භාරය': 1,
         'හේතුකොටගෙන': 1,
         'සියළුම්': 1,
         'යදිහට': 1,
         'දන්': 1,
         'දුන්නේ': 1,
         'තිලෝගුරු': 1,
         'බුදු': 1,
         'උදෙසා': 1,
         'බැඳ': 1,
         'දන්දුන්': 1,
         'කුරු': 1,
         'දම්': 1,
         'පුරණ': 1,
         'මහ': 1,
         'පඬිවර': 1,
         'මයියංගනේ': 1,
         'ලේන': 1,
         'කුලයේ': 1,
         'ඉපිද': 1,
         'සිල්': 1,
         'රකිනා': 1,
         'තැනේ': 1,
         'ජලේ': 1,
         'වැටිලා': 1,
         'ගොඩ': 1,
         'ගන්ට': 1,
         'සිතමින්': 1,
         'අනේ': 1,
         'සැනෙන්': 1,
         'දිය': 1,
         'කරම්': 1,
         'කිසිම': 1,
         'අපරාදයකටවත්': 1,
         'වරදකාරයෙක්': 1,
         'නොවන': 1,
         'නුමුත්': 1,
         'බුදුන්': 1,
         'මල්ලව': 1,
         'මරා': 1,
         'රාජ්යය': 1,
         'අත්පත්': 1,
         'ගැණිමට': 1,
         'අජාත': 1,
         'ශස්තෘ': 1,
         'රජහට': 1,
         'උපායක්': 1,
         'නොයෙක්': 1,
         'වලදී': 1,
         'අමු': 1,
         'සොහොනට': 1,
         'මිනීමස්': 1,
         'කෑ': 1,
         'ඔටුනුපලන්': 1,
         'ගණන්': 1,
         'ගසා': 1,
         'දැමූ': 1,
         'මග': 1,
         'සියළු': 1,
         'පිරිමින්': 1,
         'වචනය': 1,
         'හේතු': 1,
         'කොටගෙණ': 1,
         'වජ්ජි': 1,
         'රාජ': 1,
         'වැඩපවත්වණු': 1,
         'කැමති': 1,
         'වූයේය': 1,
         'විසාලා': 1,
         'මහනුවර': 1,
         'ධීශ්වර': 1,
         'විදෙහ': 1,
         'අජාසත්': 1,
         'භිභවනය': 1,
         'මැඩපවත්වනු': 1,
         'පිණිසයුද්ධයට': 1,
         'එව': 1,
         'රජදරුවන්': 1,
         'ඡද්යය': 1,
         'ව්යසනං': 1,
         'ආපාදෙස්සාමීති': 1,
         'පො': 1,
         'ව්යසනයට': 1,
         'මගධෙශ්වර': 1,
         'සො': 1,
         'අජාතසත්තු': 1,
         'රාජා': 1,
         'ඒඅජාසත්': 1,
         'වජ්ජී': 1,
         'මැඩ': 1,
         'වත්වනු': 1,
         'සමන්විත': 1,
         'මහත්': 1,
         'ආනුභාව': 1,
         'ඇත්තා': 1,
         'හිතට': 1,
         'නිරතුරුවම': 1,
         'යුද්ධයට': 1,
         'භුහර්තෘයෙක්': 1,
         'අභවත්': 1,
         'අඛණ්ඩ': 1,
         'කඩ': 1,
         'නොවූ': 1,
         'සම්බන්ධව': 1,
         'පිදිය': 1,
         'සිත්': 1,
         'මතු': 1,
         'ක්රමයෙන්': 1,
         'පවත්වව': 1,
         'අන්තො': 1,
         'ජනස්මිං': 1,
         'ඇතුලු': 1,
         'නුවරඅන්තඃපුරවාසී': 1,
         'ශීල': 1,
         'සංවරයෙහි': 1,
         'පිහිටීම්': 1,
         'මල්': 1,
         'වස්ත්රාභරණ': 1,
         'දීම්': 1,
         'පැ': 1,
         'වැත්විය': 1,
         'ඛත්තියෙසු': 1,
         'හස්ත්යශ්වාදිරන්න': 1,
         'ප්රදානය': 1,
         'කිරී': 1,
         'ධාර්මික': 1,
         'රක්ෂාවරණ': 1,
         'ගුප්තිය': 1,
         'පැවැත්විය': 1,
         'නොපැමිණි': 1,
         'යා': 1,
         'අනුයුක්ත': 1,
         'ඇත්': 1,
         'අස්': 1,
         'රථ': 1,
         'ගැල්': 1,
         'පුවක්': 1,
         'ඉථෝලි': 1,
         'වැඳලා': 1,
         'අහපන්නේ': 1,
         'අර්ථ': 1,
         'සමඟ': 1,
         'අකුරු': 1,
         'උගන්නේ': 1,
         'මෙලෙස': 1,
         'ගත්': 1,
         'සොඳට': 1,
         'නුවණ': 1,
         'වැඩේය': 1,
         'නිවට': 1,
         'නොවෙති': 1,
         'නොපැමිණේ': 1,
         'ලෙසිනා': 1,
         'සුගුණ': 1,
         'ගති': 1,
         'දෙගුරුවර': 1,
         'නැණ': 1,
         'යුති': 1,
         'තම': 1,
         'එගති': 1,
         'නිති': 1,
         'හික්මවා': 1,
         'ගණිති': 1,
         'මීමැසි': 1,
         'බැඳි': 1,
         'මියෙන': 1,
         'පලක්': 1,
         'නොම': 1,
         'කරන්නා': 1,
         'කාලේ': 1,
         'තමුන්නාන්සේ': 1,
         'වැනි': 1,
         'උතුමෙක්': 1,
         'ස්ව': 1,
         'කීය': 1,
         'පවා': 1,
         'සිය': 1,
         'භාෂාව': 1,
         'සමර්ථ': 1,
         'කරවා': 1,
         'තිබී': 1,
         'පෙරටු': 1,
         'ශාස්ත්ර': 1,
         'ඥානයෙන්': 1,
         'ලැබිය': 1,
         'ඵලය': 1,
         'ලබන': 1,
         'යොදවන්ට': 1,
         'භවත්': 1,
         'මැති': 1,
         'තුමා': 1,
         'කල්පනාව': 1,
         'ප්රශංසනීයයි': 1,
         'ගාල්ලේ': 1,
         'යතීන්ද්රයන්': 1,
         'සාධු': 1,
         'චරියාව': 1,
         'කියන්නේය': 1,
         'උගත්': 1,
         'සිල්වත්': 1,
         'පින්වත්': 1,
         'ගුණවත්': 1,
         'තව': 1,
         'උපාලි': 1,
         'එහෙව්': 1,
         'බියනද': 1,
         'එදි': 1,
         'ගිනිගත්': 1,
         'යක්කු': 1,
         'හඬා': 1,
         'දිවි': 1,
         'සෙද': 1,
         'බියගත්': 1,
         'මුනිසඳ': 1,
         'ඉදු': 1,
         'බෙලෙන්': 1,
         'සිදු': 1,
         'මැ': 1})

## Century-wise Analaysis

In [30]:
list_of_file_locations['written_date'].replace(['', None], np.nan, inplace=True)

/var/folders/p0/y_n4880x7cjbhx11tzvvqpzh0000gn/T/ipykernel_85333/1470307445.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  list_of_file_locations['written_date'].replace(['', None], np.nan, inplace=True)

In [31]:
list_of_file_locations.dropna(subset=['written_date'], inplace=True)

In [32]:
list_of_file_locations.head()

  written_date                                 text_file_location
0  1187 - 1225  /Users/nevidujayatilleke/Documents/MSC - Resea...
2  1832 - 1907  /Users/nevidujayatilleke/Documents/MSC - Resea...
3  1901 - 1938  /Users/nevidujayatilleke/Documents/MSC - Resea...
4         1944  /Users/nevidujayatilleke/Documents/MSC - Resea...
5  1303 - 1333  /Users/nevidujayatilleke/Documents/MSC - Resea...

In [33]:
len(list_of_file_locations)

59

In [34]:
list_of_file_locations.reset_index(drop=True, inplace=True)

In [35]:
list_of_file_locations.head()

  written_date                                 text_file_location
0  1187 - 1225  /Users/nevidujayatilleke/Documents/MSC - Resea...
1  1832 - 1907  /Users/nevidujayatilleke/Documents/MSC - Resea...
2  1901 - 1938  /Users/nevidujayatilleke/Documents/MSC - Resea...
3         1944  /Users/nevidujayatilleke/Documents/MSC - Resea...
4  1303 - 1333  /Users/nevidujayatilleke/Documents/MSC - Resea...

In [36]:
list_of_file_locations['start_date'] = np.nan
list_of_file_locations['end_date'] = np.nan

In [37]:
for index, row in list_of_file_locations.iterrows():
    date_str = str(row['written_date']) # Ensure it's treated as a string
    
    start_year = np.nan
    end_year = np.nan

    if ' - ' in date_str:
        # It's a range
        try:
            start_year_str, end_year_str = date_str.split(' - ')
            start_year = int(start_year_str.strip())
            end_year = int(end_year_str.strip())
        except ValueError:
            print(f"Warning: Could not parse range '{date_str}' at index {index}. Setting to NaN.")
    else:
        # It's a single year or potentially unparseable
        try:
            single_year = int(date_str.strip())
            start_year = single_year
            end_year = single_year # Duplicate for single date
        except ValueError:
            print(f"Warning: Could not parse single year/date '{date_str}' at index {index}. Setting to NaN.")
            
    # Assign the parsed (or NaN) values back to the DataFrame
    list_of_file_locations.at[index, 'start_date'] = start_year
    list_of_file_locations.at[index, 'end_date'] = end_year

In [38]:
list_of_file_locations.head()

,written_date,text_file_location,start_date,end_date
0,1187 - 1225,/Users/nevidujayatilleke/Documents/MSC - Resea...,1187.0,1225.0
1,1832 - 1907,/Users/nevidujayatilleke/Documents/MSC - Resea...,1832.0,1907.0
2,1901 - 1938,/Users/nevidujayatilleke/Documents/MSC - Resea...,1901.0,1938.0
3,1944,/Users/nevidujayatilleke/Documents/MSC - Resea...,1944.0,1944.0
4,1303 - 1333,/Users/nevidujayatilleke/Documents/MSC - Resea...,1303.0,1333.0

In [39]:
def get_century(year):
    """Calculates the century for a given year."""
    if pd.isna(year):
        return np.nan
    return (int(year) - 1) // 100 + 1

In [40]:
list_of_file_locations['end_century'] = list_of_file_locations['end_date'].apply(get_century)

In [41]:
list_of_file_locations.head()

,written_date,text_file_location,start_date,end_date,end_century
0,1187 - 1225,/Users/nevidujayatilleke/Documents/MSC - Resea...,1187.0,1225.0,13
1,1832 - 1907,/Users/nevidujayatilleke/Documents/MSC - Resea...,1832.0,1907.0,20
2,1901 - 1938,/Users/nevidujayatilleke/Documents/MSC - Resea...,1901.0,1938.0,20
3,1944,/Users/nevidujayatilleke/Documents/MSC - Resea...,1944.0,1944.0,20
4,1303 - 1333,/Users/nevidujayatilleke/Documents/MSC - Resea...,1303.0,1333.0,14

In [42]:
list_of_file_locations['tokens'] = list_of_file_locations['text_file_location'].apply(clean_words)

In [43]:
list_of_file_locations['tokens'][0][:10]

['අප',
 'බුදුන්',
 'සාරාසකි',
 'කප්සුවහස්',
 'මතුයෙහි',
 'කුලුණුනු',
 'වණින්',
 'යුත්',
 'මහත',
 'වු']

In [44]:
DOCUMENT_SEPARATOR = "__DOC_END__"

In [45]:
def combine_tokens_with_separator(series_of_lists):
    """
    Takes a pandas Series of token lists and combines them, 
    inserting a separator between each list.
    """
    combined_list = []
    
    # Iterate over each document's token list (item) in the Series
    for i, token_list in enumerate(series_of_lists):
        # 1. Add the tokens from the current document
        combined_list.extend(token_list)
        
        # 2. Add the separator, but only if it's not the last document in the group
        if i < len(series_of_lists) - 1:
            combined_list.append(DOCUMENT_SEPARATOR)
            
    return combined_list

In [46]:
century_tokens = list_of_file_locations.groupby('end_century')['tokens'].apply(combine_tokens_with_separator)
century_tokens = century_tokens.to_dict()

In [47]:
century_tokens

{5: ['කාම',
  'ලොක',
  'රූප',
  'ලොක',
  'අරූපලෝක',
  'යන්',
  'ලොකත්රයට',
  'ශ්රෙෂ්ඨ',
  'වූ',
  'මුනීන්ද්ර',
  'නම්',
  'වූ',
  'සම්යක්',
  'සම්බුද්ධයන්',
  'වහන්සේගේ',
  'ශ්රී',
  'පාද',
  'පද්මය',
  'භය',
  'ලොහ',
  'කුලාචාරයෙන්',
  'විනා',
  'සකසා',
  'වැඳ',
  'සකල',
  'ශාස්ත්රයෙහි',
  'පාරප්රාප්ත',
  'පණ්ඩිත',
  'වූ',
  'භෛෂජ්යාර්ථයෙහි',
  'දක්ෂ',
  'වූ',
  'වෙදුන්',
  'විසින්',
  'උතුම්',
  'වූ',
  'රස',
  'සංහිතාදි',
  'තන්ත්ර',
  'ශාස්ත්රයෙහි',
  'වුත',
  'කියන',
  'ලද',
  'විවිධං',
  'නානාප්රකාර',
  'වූ',
  'සාරාර්ථය',
  'උදුරා',
  'ගෙණ',
  'සකල',
  'සත්වයන්ගේ',
  'රොග',
  'ව්යපසමන',
  'සංඛ්යාත',
  'සංග්රහව',
  'පිණිස',
  'මේ',
  'සාරාර්ථ',
  'සංග්රහ',
  'නම්',
  'ප්රකරණය',
  'සර්ථාවබොධය',
  'සඳහා',
  'කියන්නෙමි',
  'යනාදී',
  'අනෙකවිධ',
  'මානයෙන්',
  'දැක්වූ',
  'මේ',
  'වෛද්ය',
  'ශාස්ත්රය',
  'ප්රථම',
  'කල්පයෙහි',
  'ලෝකාර්ථය',
  'කරන්නා',
  'වූ',
  'මහ',
  'බ්රහ්මයා',
  'දක්ෂ',
  'පුජාපති',
  'හට',
  'කීහ',
  'දක්ෂ',
  'ප්රජාපති',
  'අග',
  'විනීන්',
  'දෙදෙනා',
  'හට',
  'කීහ',
  'අගවිනි',
  'දෙදෙනා',
  'ශක්රයාහට',
  'කීහ',
  'ශක්රයා',
  'ධන්වන්තරී',
  'හට',
  'කීහ',
  'ධන්වන්ත',
  'සුශ්රුතාදී',
  'රුසිවරයන්ට',
  'කීහ',
  'රුසිවරු',
  'කසී',
  'රජහට',
  'කීහ',
  'ශිෂ්යානුශිෂ්ය',
  'පරම්පරානුගතව',
  'පැවැත්තා',
  'වූ',
  'මේ',
  'වෛද්ය',
  'ශාස්ත්රය',
  'අධි',
  'දීර්ඝ',
  'කාලයකින්',
  'ග්රන්ථි',
  'ස්ථාන',
  'ශුඪවීය',
  'තථාගතයන්',
  'වහන්සේ',
  'විසින්',
  'දක්වන',
  'ලද',
  'උතුම්',
  'වූ',
  'ධර්මය',
  'සත්ව',
  'කරුණාවෙන්',
  'බොහෝ',
  'කල්',
  'පට',
  'තිනා',
  'ලෙස',
  'වදාළ',
  'සේක්',
  'නම්',
  'එසේම',
  'ලොකාචාර්යය',
  'ඍෂින්',
  'විසින්',
  'කරුණාධ්යාසයෙන්',
  'කල්පායුෂ්ක',
  'කාලයක්',
  'පවතිනා',
  'පරිද්දෙන්',
  'හදා',
  'ගුඪාර්ථ',
  'සහිත',
  'වූ',
  'වෛද්ය',
  'ශාස්ත්රය',
  'ජීවකයන්හට',
  'කීවාහුය',
  'ඔහු',
  'විසින්',
  'නිර්වලව',
  'විපුලව',
  'ප්රසිද්ධ',
  'කළේයි',
  'ඔවුන්',
  'පරම්පරා',
  'ගෙනුදු',
  'පවත්තා',
  'ලද',
  'මේ',
  'මහා',
  'වෛද්යාණිවයට',
  'බැස',
  'බලනු',
  'හැම',
  'සත්වයන්ට',
  'උගහටසේ',
  'දැක',
  'සිතු',
  'සේ',
  'බැස',
  'ඇවිදිනා',
  'සකල',
  'සත්ව',
  'වර්ගයන්ට',
  'නානා',
  'ස්ථානගත',
  'සෘෂි',
  'ප්රොක්ත',
  'උදාහරණ',
  'ලොකාචරණයෙන්',
  'සමලංකෘත',
  'වූ',
  'නිර්ව්යාජ',
  'ස්වභාෂානු',
  'කථාවෙන්',
  'වණන්නෙමි',
  'හිෂක්',
  'ශාස්ත්රයක්',
  'ප්රකාශ',
  'කරන්',
  'නෙමැයි',
  'සේයි',
  'මෙසේ',
  'ශාස්ත්රොත්පත්ති',
  'කථනයෙන්',
  'ගරු',
  'භාවය',
  'ප්රකාශ',
  'කොට',
  'භිෂගුත්තමයා',
  'හට',
  'වෛද්යයාංගයන්',
  'දක්වත්',
  'දූත',
  'ලක්ෂණය',
  'නෛමි',
  'ලක්ෂණය',
  'අංග',
  'ලක්ෂණය',
  'ස්වප්න',
  'ලක්ෂණය',
  'අරිෂ්ට',
  'ලක්ෂණය',
  'ආරොග්ය',
  'ලක්ෂණය',
  'විපරිත',
  'ලක්ෂණය',
  'භිෂක්',
  'සම්පත්ය',
  'භෛෂජ්ය',
  'සම්පත්ය',
  'ආතුර',
  'සම්පත්ය',
  'පරිවාරක',
  'සම්පත්ය',
  'ව්යාධි',
  'ලක්ෂණය',
  'ප්රකෘති',
  'ලක්ෂණය',
  'ස්ථාන',
  'දෙශ',
  'ගුණය',
  'කාල',
  'ගුණය',
  'වයො',
  'ලක්ෂණය',
  'දෙහ',
  'ලක්ෂණය',
  'සතත්ව',
  'ලක්ෂණය',
  'සාත්මික',
  'ලක්ෂණය',
  'රස',
  'ලක්ෂණය',
  'දොෂ',
  'ස්වභාවය',
  'සියළු',
  'දොෂයන්ගේ',
  'උද්භවය',
  'එසේම',
  'දොෂ',
  'ශම්නය',
  'තුන්වැදෑ',
  'රුම්',
  'වූ',
  'ව්යාධි',
  'ලක්ෂණය',
  'ආම',
  'බලය',
  'අග්නි',
  'බලිය',
  'ආදාන',
  'ලක්ෂණය',
  'නිදාන',
  'ලක්ෂණය',
  'පූර්ව',
  'හේතු',
  'ලක්ෂණයයි',
  'යන',
  'මේ',
  'තිස්',
  'අංගයන්ගේ',
  'ලක්ෂණ',
  'වෙද',
  'තෙම',
  'බලා',
  'දැක',
  'භෛෂජ්යකර්මය',
  'මනාකොට',
  'කරන්නේය',
  'හීන',
  'ජාතිය',
  'අංග',
  'විකාරිය',
  'හෙවත්',
  'වෙදාර්ථ',
  'නසන්නාය',
  'මලපුඩුවක්',
  'හෝ',
  'දණ්ඩක්',
  'හෝ',
  'ආයුධයක්',
  'හෝ',
  'ගත්',
  'අත්',
  'ඇත්තේය',
  'රක්තා',
  'ශීත',
  'විජිණෛඃක',
  'වස්ත්ර',
  'රක්ත',
  'කෘෂ්ණ',
  'විජිණී',
  'වූ',
  'එක්',
  'වස්ත්රයක්',
  'හැන්දේය',
  'අනිෂ්ට',
  'වූවාක්',
  'ඇත්තේය',
  'යන',
  'මොහුද',
  'අතමඩනේ',
  'ද',
  'මිදූ',
  'කඳුලු',
  'ඇත්තේ',
  'ද',
  'තෙල්',
  'ඇඟ',
  'ගැල්',
  'වුයේ',
  'ද',
  'තණකොඳු',
  'කඩායන්නේ',
  'ද',
  'ස්ත්රී',
  'ලක්ෂණ',
  'නපුංසක',
  'වූ',
  'ද',
  'අංග',
  'විකල',
  'වූ',
  'අඩ',
  'පුගුලෝ',
  'ද',
  'පිට',
  'අත',
  'බැඳ',
  'යන්නාහුද',
  'ඛර',
  'කොටළුය',
  'ඔටුය',
  'මිය',
  'යන',
  'මොවුන්ට',
  'ආරූඪ',
  'නැංගාහුද',
  'මූග',
  'ගොළුය',
  'විලාපාදි',
  'බස්',
  'ඇත්තෝය',
  'යන',
  'මේ',
  'අරිෂ්ට',
  'දූතයෝ',
  'විරුද්ධ',
  'වෙත්',
  'නොහොත්',
  'වෛද්යාචාරීන්',
  'විසින්',
  'වළකනු',
  'ලැබෙත්',
  'මෙකී',
  'ලක්ෂණයන්ට',
  'විපර්යාස',
  'වූවාහු',
  'පසස්නා',
  'ලද්දාහුයි',
  'කන්යා',
  'ස්ත්රියක්',
  'හෝ',
  'වසුමා',
  'දෙනක්',
  'හෝ',
  'බෙර',
  'හෝ',
  'සක්',
  'හෝ',
  'දීමධුරඵල',
  'කුසුම',
  'යන',
  'මොවුන්',
  'හෝ',
  'බබලන්නා',
  'වූ',
  'ගින්න',
  'හෝ',
  'ගංගා',
  'තීර',
  'ප්රයුක්තාන්',
  'ගංතෙර',
  'යෙදුනා',
  'වූ',
  'භය',
  'අශ්වය',
  'ගජ',
  'හස්තිය',
  'වෘෂභය',
  'යන',
  'මොවුන්',
  'හෝ',
  'පුන්කලස්ය',
  'ධිජය',
  'යන',
  'මොවුන්',
  'හෝ',
  'සානා',
  'බිමක්',
  'හෝ',
  'මෙඝය',
  'හා',
  'මත්ස්ය',
  'යුගලයක්',
  'හෝ',
  'සුද්ධාහාර',
  'හෝ',
  'මන්ත්රාධ්යයන',
  'යක්',
  'හෝ',
  'හෝ',
  'මස්',
  'කැබල්ලක්',
  'හෝ',
  'ප්රිය',
  'හිත',
  'වචනයක්',
  'හෝ',
  'ගමනාරම්භ',
  'කළවුන්ට',
  'මංගලයක්',
  'වේ',
  'බෙරය',
  'මිහිඟු',
  'බෙරය',
  'මෘදුම',
  'දීල',
  'නම්',
  'වාද්ය',
  'භෙදය',
  'සක්ය',
  'වීණාය',
  'කුලල්',
  'බට',
  'ආදීන්',
  'පිඹීමය',
  'මත්ස්ය',
  'කුණ්ඩලය',
  'ගීති',
  'ඝොෂාය',
  'පුත්රයන්',
  'සහිත',
  'ස්ත්රීය',
  'වස්සා',
  'සහිත',
  'දෙනය',
  'සුදු',
  'වස්ත්ර',
  'ඇති',
  'වහමු',
  'වූ',
  'රජකයා',
  'යන',
  'මොහු',
  'පසස්නා',
  'ලද්දාහ',
  'ශකුණ',
  'තෙම',
  'වාම',
  'දිග්',
  'භාගයෙන්',
  'දකුණු',
  'දිගට',
  'යාති',
  'සේ',
  'ද',
  'දීර්ඝතෙම',
  'දකුණු',
  'දිග',
  'සිට',
  'වා',
  'මදිගට',
  'ප්රයා',
  'තිව',
  'යේද',
  'ගිරව්ය',
  'කවුඩුය',
  'කොබෙයිය',
  'යන',
  'මොවුහුද',
  'ඉදින්',
  'දකුණු',
  'දිගට',
  'යෙත්නම්',
  'යන',
  'ගමනට',
  'යහපත්',
  'වන්නේයි',
  'උතුම්',
  'වූ',
  'වෛද්ය',
  'තෙම',
  'ආතුරයාගේ',
  'ඉදිරියෙහි',
  'සිට',
  'යන',
  'මේ',
  'මන්ත්රය',
  'ජපකොට',
  'බලා',
  'සිටිකල',
  'පිටි',
  'පතුල',
  'ගත',
  'ඕහට',
  'අව්රුද්දක්ද',
  'වලලු',
  'කර',
  'ගත',
  'සමසක්',
  'ද',
  'කන්',
  'මුලගත',
  'තුන්මසක්',
  'ද',
  'නලළ',
  'ගත',
  'අඩ',
  'මසක්',
  'ද',
  'දෙබැම',
  'ගත',
  'නව',
  'දවසක්',
  'ද',
  'එසේම',
  'කඳගත',
  'සත්',
  'දවසක්',
  'ද',
  'ඇස',
  'ගත',
  'පස්',
  'දවසක්',
  'ද',
  'නාසයගත',
  'තුන්',
  'දවසක්',
  'ද',
  'ආයු',
  'ඇති',
  'වේ',
  'දිවගත',
  'එක',
  'දවසකුත්',
  'ජීවත්',
  'නොවන්නේයි'],
 12: ['තමා',
  'වරදස',
  'නොදිස්',
  'නේ',
  'මෙරමා',
  'දොස්',
  'දිස්නේ',
  'නුවන්',
  'බැහැර',
  'නහමත්',
  'තමා',
  'මුත්',
  'නොදක්නේ',
  'කිම්',
  'සරසවිය',
  'බැලුමසෙක්',
  'නි',
  'වෙත්වා',
  'කිවි',
  'දෙනෝ',
  'පෙදෙහි',
  'රසහව්',
  'විදුනා',
  'දෙනෙතා',
  'ඉතා',
  'දුලබෝ',
  'ම',
  'තෙපල',
  'පා',
  'ලදපිළි',
  'වේ',
  'වෙසෙස්',
  'මෙ',
  'සෙබේ',
  'කසුන්',
  'කෙවුන්නේ',
  'බඳ',
  'මිණීමැ',
  'ගුණෙනුතුරත්',
  'වේ',
  'තමා',
  'වරදස',
  'නොදිස්නේ',
  'තමාගේ',
  'වරදෙහි',
  'ස්වල්පයකුදු',
  'අදෘශ්යය',
  'මෙරමා',
  'දොස්',
  'දිස්නේ',
  'අනුන්ගේ',
  'දොෂ',
  'වනාහි',
  'පැණෙන්නේන්',
  'මැයි',
  'නුවන්',
  'නෙත්රය',
  'තමා',
  'මුත්',
  'තමා',
  'විනා',
  'බැහැර',
  'නහමත්',
  'බාහ්ය',
  'වස්තූන්',
  'විෂයෙහි',
  'විචාරත්',
  'හොත්',
  'නොදක්නේ',
  'කිම්',
  'සර්ෂප',
  'ආදී',
  'කොට',
  'අදෘශ්යමාන',
  'කිමෙක්ද',
  'සරසවිය',
  'සරස්වතියගේ',
  'බැලුමසෙක්නි',
  'අර්ධ',
  'නිරීක්ෂණ',
  'මාත්රයෙකින්',
  'දෙනෝ',
  'කිවි',
  'වෙත්වා',
  'ජනයෝ',
  'කිවිහු',
  'වෙත්වා',
  'පෙදෙහි',
  'රසහව්',
  'විදුනා',
  'දෙනෙතා',
  'පදයෙහි',
  'රසභාවය',
  'දන්නා',
  'ජනයෝ',
  'වනාහි',
  'ඉතා',
  'දුලබෝ',
  'අතිදුර්ලභයෝයි',
  'මෙ',
  'සෙබේ',
  'මේ',
  'ස්වභාවෙහි',
  'ම',
  'තෙපල',
  'පා',
  'ලද',
  'මාගේ',
  'තෙපුලට',
  'ප්රතිෂ්ඨා',
  'ලද',
  'නම්',
  'පිළි',
  'වෙසෙස්',
  'වේ',
  'නැවත',
  'විශෙෂ',
  'කිවි',
  'බැව්',
  'කිවිදුමේ',
  'කුසුම්සැපතෙහි',
  'විපුල්පෙලෙ',
  'බෝසත්',
  'සර',
  'වැණුම්',
  'වියතෙමුව',
  'පවත්',
  'වේවා',
  'රජ',
  'පැමිණි',
  'බෝ',
  'සත්',
  'සත්',
  'රජුනෙඩි',
  'මැඩ',
  'විසී',
  'විසී',
  'තමා',
  'කැරැ',
  'කලක්',
  'කලක්',
  'දස',
  'රජ',
  'දම්නෙන්',
  'ලද',
  'පියන්',
  'බිඳු',
  'පියවුරෙව්',
  'මෙ',
  'දා',
  'දක්වා',
  'පින්',
  'පියවුරු',
  'මණ්ඩලෙව්',
  'පිළි',
  'මෙහි',
  'විතර',
  'පානෙම්',
  'වී',
  'කුසාවත්',
  'නම්',
  'නුවරෙක්',
  'උපත්',
  'සත්සර',
  'පිරි',
  'බෝදාසිරි',
  'නදන්',
  'පියුමෙව්',
  'බඹ',
  'තෙලේ',
  'දුනු',
  'වෙයි',
  'කසුන්කෙවුන්නේ',
  'බඳ',
  'කාඤ්චනාධාරයෙහි',
  'බැන්දා',
  'වූ',
  'මිණීමැ',
  'මාණික්යයම',
  'ගුණෙනුතුරත්',
  'වේ',
  'ගුණයෙන්',
  'උත්තරී',
  'තර',
  'වේ',
  'කිවි',
  'බැව්',
  'කවි',
  'භාවය',
  'තෙමේ',
  'කිවිදුමේ',
  'කවිද්රැමයෙහි',
  'කුසුම්',
  'සැපත්',
  'කුසුම',
  'සම්පත්තියෙක',
  'එහි',
  'විපුල්පෙලෙ',
  'ඒ',
  'කුසුම',
  'සම්පත්ති',
  'යෙහි',
  'මහාඵල',
  'නම්',
  'බෝසත්',
  'සර',
  'වැණුම්',
  'බොධිසත්ව',
  'චරිත',
  'වර්ණනා',
  'විය',
  'එ',
  'වියත්',
  'මුව',
  'පවත්',
  'වේවා',
  'ඒ',
  'ඵලජාති',
  'ව්යක්ත',
  'යන්ගේ',
  'මුඛ',
  'ප්රවර්තිත',
  'වේවා',
  'බෝසත්සර',
  'බෝසත්',
  'බොධිසත්ව',
  'තෙමේ',
  'රජ',
  'පැමිණී',
  'රාජශ්රියට',
  'ප්රාප්තව',
  'සත්',
  'රජුනෙඩි',
  'මැඩ',
  'සප්ත',
  'රාජයන්ගේ',
  'දප්පමිරිකා',
  'තමා',
  'කලක්',
  'විසී',
  'කැරැ',
  'තමාගේ',
  'කාන්තාවක්',
  'වසඟ',
  'කොට',
  'දස',
  'රජ',
  'දම්නෙන්',
  'දශරාජ',
  'ධර්මයෙන්',
  'කලක්',
  'විසී',
  'එක්',
  'කාලයක්',
  'වාසය',
  'කෙළේයි',
  'ලද',
  'පියන්',
  'අභිනව',
  'ස්ත්රීන්ගේ',
  'බිඳු',
  'පියවුරු',
  'එව්',
  'බින්දු',
  'මාත්ර',
  'පයොධරයන්',
  'මෙන්',
  'මෙ',
  'දා',
  'දක්වා',
  'මේ',
  'ජාතකය',
  'සංක්ෂෙපයෙන්',
  'දක්වා',
  'පින්පියවුරු',
  'මඬලෙව්',
  'සන්නද්ධ',
  'යෞවනයෙහි',
  'ඔවුන්ගේ',
  'පීණපයොධර',
  'මණ්ඩලයන්',
  'මෙන්',
  'පිළි',
  'නැවත',
  'මෙහි',
  'විතර',
  'පානම්',
  'මේ',
  'ජාතකයෙහි',
  'විස්තර',
  'දක්වමි',
  'පිරිබෝදා',
  'සිරි',
  'නදන්',
  'පාරිභොගික',
  'ධාතුශ්රීයට',
  'නිධාන',
  'වූ',
  'බඹ',
  'තෙලේ',
  'දුනු',
  'පියුමෙව්',
  'බ්රහ්ම',
  'ලොකයෙහි',
  'ජාත',
  'පද්මයක්',
  'මෙන්',
  'දෙරණ',
  'වුලුඹෙපුරේනුබසරණ',
  'සර',
  'දුර',
  'ලූ',
  'නුබපා',
  'ගත්',
  'සෙමිණි',
  'වලා',
  'මහවුරු',
  'සේමිණි',
  'වලා',
  'පුරකත',
  'නුබඳ',
  'බඳ',
  'මහවුරු',
  'උකුළුවටහී',
  'සහගුම්',
  'බිඟුවැල',
  'පියුම්',
  'පිරි',
  'කියලී',
  'රසන්දම්',
  'කැරැළිමිණි',
  'රැස්යටගෙහි',
  'සේසතෙව්',
  'තෙවුනේ',
  'විමනුදුල',
  'එ',
  'පුරනුබේ',
  'සුපුන්',
  'සරා',
  'සරාසඳ',
  'සත්සර',
  'උපත්',
  'සත්වසාරයට',
  'උත්පත්ති',
  'ස්ථාන',
  'වූ',
  'කුසාවත්',
  'නම්',
  'නුවරෙක්',
  'වී',
  'කුසාවතී',
  'නම්',
  'නගරයෙක්',
  'වී',
  'දෙරණවුලුඹු',
  'ධරණීය',
  'පැහැර',
  'යන්නා',
  'වූ',
  'නුබසරණ',
  'සර',
  'දුර',
  'ලු',
  'නභශ්වරයන්ගේ',
  'ගමන්',
  'දුරලූවා',
  'වූ',
  'එ',
  'පුරේ',
  'ඒ',
  'පුරයෙහි',
  'සෙමිණි',
  'මහවුරු',
  'සස්ඵටික',
  'මාණික්ය',
  'මහත්',
  'ප්රා',
  'කර',
  'තෙමේ',
  'නුබ',
  'මිණි',
  'පා',
  'ගත්',
  'නහස්',
  'නැමැති',
  'මණි',
  'පාත්රය',
  'දැරූ',
  'සේමිණි',
  'වලා',
  'වලා',
  'සස්ඵටික',
  'මණී',
  'වලයාකාරයි',
  'සහගුම්',
  'ඝොෂා',
  'සහිත',
  'වූ',
  'බිඟු',
  'වැල',
  'භෘංගාවලීන්',
  'යුක්ත',
  'වූ',
  'පියුම්',
  'පිරි',
  'පද්ම',
  'පරිඛා',
  'තොමෝ',
  'පුරකත',
  'පුර',
  'නැමැති',
  'කාන්තාවගේ',
  'මහවුරු',
  'උකුළුවටහී',
  'මහාප්රාකාර',
  'නැමැති',
  'උකුළු',
  'වර්තයෙහි',
  'නුබඳ',
  'බඳ',
  'නිරන්තරයෙන්',
  'බද්ධ',
  'වූ',
  'රසන්දම්',
  'කියලී',
  'රසනාදාමය',
  'ප්රකාශ',
  'කළා',
  'විමනුදුල',
  'විමානයෙන්',
  'උද්දීප්ත',
  'වූ',
  'එ',
  'පුරනුබේ',
  'ඒ',
  'පුරාකාශයෙහි',
  'සුපුන්',
  'සරා',
  'සරා',
  'සඳ',
  'සම්පූර්ණ',
  'වූ',
  'ප්රභා',
  'සහිත',
  'වූ',
  'ශරච්චන්ද්ර',
  'තෙම',
  'කැරළිමිණි',
  'රැස්යටගෙහි',
  'ශෘංගමාණික්ය',
  'රශ්මි',
  'යෂ්ටි',
  'අග්රයෙහි',
  'සේසතෙව්',
  'තෙවුනේ',
  'ස්වෙතච්ඡත්රයක්',
  'මෙන්',
  'හොබනේයි',
  'සුනිල්මිණි',
  'වේබිමැ',
  'පිළිබිඹු',
  'බද',
  'දදසුමු',
  'පෙරළෙත',
  'කලිඳු',
  'ගඟැමින්',
  'කැල',
  'කෙළි',
  'පෑ',
  'එ',
  'පුරවර',
  'රතමිණි',
  'තොරණ',
  'රැස්රැසින්',
  'රතෙ',
  'පුර',
  'සුපුන්',
  'සඳ',
  'ලහිරු',
  'හො',
  'යී',
  'නොසරස්',
  'දැනවී',
  'සැක',
  'බිසරුවන්',
  'රත',
  'මිණි',
  'රැස්',
  'රැදින්',
  'නුබ',
  'විදුරතු',
  'සුරපුරෙන්',
  'ලහිරු',
  'හො',
  'යී',
  'නො',
  'සරස්',
  'දැන',
  'වී',
  'සැක',
  'බිසවරුවන්',
  'නේ',
  'මිණි',
  'රැස්',
  'රැදින්',
  'නුබ',
  'විදුරතු',
  'සුරපුරෙන්',
  'රුවන්',
  'යොත්',
  'නිදුල',
  'පවර',
  'සමහර',
  'බටෙව්',
  'එ',
  'නුවර',
  'සුනිල්මිණි',
  'වේබිමැ',
  'ඉන්ද්රනීල',
  'ඉන්ද්රනීල',
  'මණික්ය',
  'භුමි',
  'විථියෙහි',
  'පිළිබිඹු',
  'බද',
  'ප්රතිබිම්බිත',
  'වූ',
  'දදසුමු',
  'පෙරළෙත',
  'ධ්වජ',
  'සමූහයන්',
  'පෙරළෙන',
  'කල්හි',
  'එ',
  'පුරවර',
  'ඒ',
  'පුර',
  'ප්රවරය',
  'තෙම',
  'කලිඳු',
  'ගඟැ',
  'කාලින්දි',
  'ගංගායෙහි',
  'මින්',
  'කැල',
  'කෙළි',
  'පෑ',
  'මත්ස්ය',
  'සමූහයාගේ',
  'ක්රීඩා',
  'දැක්වී',
  'රථමිණි',
  'තොරණ',
  'රැස්',
  'රැසින්',
  'රක්තමාණික්ය',
  'තොරණ',
  'රශ්මි',
  'රාශියෙන්',
  'රත්',
  'රක්ත',
  'වූ',
  'එ',
  'පුරේ',
  'සුපුන්සඳ',
  'ඒ',
  'පුරයෙහි',
  'සම්පූර්ණ',
  'චන්ද්ර',
  'තෙම',
  'ලහිරු',
  'හෝයී',
  'බාලාර්ක',
  'දෝහෝයි',
  'කියා',
  'අබිසරුවන්',
  'අභිසාරිකාවන්ට',
  'නොසරස්',
  'සැක',
  'දැනවී',
  'වහ',
  'වහාශංකා',
  'නිපදවී',
  'නේමිණි',
  'රැස්',
  'රැදින්',
  'අනෙක',
  'ප්රකාර',
  'වූ',
  'මාණික්ය',
  'රශ්මි',
  'රාජින්',
  'නුබ',
  'නභසතලය',
  'විදුරතු',
  'අවුණන',
  'කල්හි',
  'උදුල',
  'උජජ්වලිත',
  'වූ',
  'රුවන්',
  'යොත්නි',
  'රත්න',
  'රජ්ජුයෙන්',
  'පවර',
  'උතුම්',
  'වූ',
  'එ',
  'නුවර',
  'ඒ',
  'පුරය',
  'සුරපුරෙන්',
  'දිව්ය',
  'පුරයෙන්',
  'සමහර',
  'බටෙව්',
  'අර්ථයක්',
  'අවතීර්ණ',
  'වූවාක්',
  'වැන්න',
  'තුගුතුල්',
  'යට',
  'හ',
  'ලෙල',
  'දද',
  'මෙ',
  'පුර',
  'සිරිමත',
  'ඉඳු',
  'නිල්',
  'මිණී',
  'දෙරණ',
  'පිළිබිඹුව',
  'බබළත',
  'මනකල්',
  'කලිඳු',
  'ගඟතුළ',
  'කෙළනා',
  'සතත',
  'පැහැදුල්',
  'නොයෙක්',
  'වග',
  'මික්සිරි',
  'පැයි',
  'දිමුත',
  'එහි',
  'විසිතු',
  'රෑ',
  'රතමිණී',
  'තොරණ',
  'රැස්',
  'වැද',
  'ගණදුරු',
  'දුරු',
  'කරණ',
  'රත',
  'වන්',
  'සුපුන්',
  'සඳ',
  'නෙක',
  'අබිසරු',
  'අඟනන්හට',
  'සරණ',
  'සෙද',
  'නව',
  'දිවයු',
  'රු',
  'යයිද්යානවීය',
  'සැක',
  'සඳ',
  'පිළිබිඹු',
  'ප්රතිත',
  'වූ',
  'බඳ',
  'බද්ධ',
  'වූ',
  'සමහර',
  'වුල්අස්න',
  'වීදු',
  'ර',
  'තු',
  'ආවූ',
  'න',
  'ත',
  'කල්හි',
  'යි',
  'ද',
  'ආවෘත',
  'කරණ',
  'කල්හි',
  'යි',
  'ද',
  'සියලු',
  'කව්සිළුමිණ',
  'සලෙලුවන්',
  'අලලත',
  'පුරයෝනන්',
  'නුවන්හී',
  'සිය',
  'කැමි',
  'නොබල',
  'මල්සරසැතපී',
  'ගි',
  'වී',
  'මස්සැර',
  'මහවෙහි',
  'බඳ',
  'රඟවියනෙව්',
  'ලෙව්නුවන්',
  'බඳ',
  'හැනී',
  'දෙපස්හී',
  'නන්',
  'රුවන්',
  'පහ',
  'මෙ',
  'රජරජ',
  'කෙළෙ',
  'තුටු',
  'රගොතමත',
  'ඟන්',
  'විදු',
  'වදගන',
  'ගැජුම්',
  'ගෙනෙ',
  'ඉඳුනිල්මිණි',
  'විමන්',
  'විමන්',
  'සිකිකැන්',
  'එ',
  'පුරේ',
  'මුහුළත්තඹුරු',
  'වින්',
  'දනනඟනන්',
  'උවන්',
  'සඳ',
  'සමහර',
  'දිසි',
  'පියුම්රා',
  'මිණීමැදුරෙ',
  'සීමැදුරේ',
  'පුරයෝනන්',
  'පුර',
  'යුවතීන්ගේ',
  'නුවන්හී',
  'නෙත්ර',
  'නැමැති',
  'බාණයෙන්',
  'සලෙලුවන්',
  'සල්ලාලජනයන්',
  'අලලත',
  'ආලොලනය',
  'කරණ',
  'කල්හි',
  'සියකැමින්',
  'ස්වකීය',
  'ක්රියාවෙන්',
  'ඔබල',
  'දුර්වල',
  'වූ',
  'මල්සර',
  'අනංගයාගේ',
  'මසැර',
  'පුෂ්පබාණ',
  'සැතපී',
  'ගී',
  'වී',
  'විශ්රාමය',
  'කළාක්',
  'වැනි',
  'වී',
  'දෙපස්හි',
  'උභය',
  'පාර්ශ්වයෙහි',
  'නන්රුවන්පහ',
  'මෙරජරජ',
  'හැනී',
  'අනෙක',
  'රතන',
  'ප්රාසාදයෙහි',
  'මරීචිරාජී',
  'එක්ව',
  'මහවෙහි',
  'බඳ',
  'මහා',
  'වීථියෙහි',
  'බද්ධ',
  'වූ',
  'රඟ',
  'විය',
  'නෙව්',
  'රංග',
  'විතානයක්',
  'මෙන්',
  'ලෙනුවන්',
  'බඳ',
  'ලොකයාගේ',
  'නෙත්ර',
  'බන්ධනය',
  'කළා',
  'රඥෙත',
  'මතඟන',
  'නෘත්ය',
  'ගත්තාවූ',
  'මත්තාගනා',
  'නැමැති',
  'විදු',
  'විද්යත්',
  'ඇති',
  'වද',
  'ගන',
  'ගැජුම්',
  'වාද්ය',
  'නැමැති',
  'මෙඝධ්වනි',
  'ඇති',
  'එ',
  'පුරේ',
  'ඒ',
  'පුරයෙහි',
  'ඉඳුනිල්මිණි',
  'විමන්',
  'ගෙනේ',
  'ඉන්ද්රනීල',
  'මාණික්ය',
  'විමාන',
  'නැමැති',
  'මේඝ',
  'තෙමේ',
  'විමන්',
  'සිකි',
  'කැන්',
  'තුටු',
  'කෙළේ',
  'ගෘහමයූර',
  'සමූහයා',
  'සන්තුෂ්ට',
  'කෙළේ',
  'පියුම්රාමිණී',
  'මැදුරේ',
  'පද්මරාග',
  'මාණික්යමය',
  'ප්රාසාදයෙහි',
  'සීමැදුරේ',
  'සිංහපඤ්ජරයෙහි',
  'අඟනන්',
  'කාන්තාවන්ගේ',
  'සමහර',
  'දිසි',
  'අර්ධයක්',
  'දෘශ්යමාන',
  'වූ',
  'උවන්',
  'සඳ',
  'වක්ත්ර',
  'චන්ද්ර',
  'තෙම',
  'දනන්',
  'ජනයන්ගේ',
  'මුහුළු',
  'මුකුලිත',
  'වූ',
  'අත්තඹුරු',
  'හසතාමරසයන්',
  'වින්',
  'වින්දේයි'],
 13: ['අප',
  'බුදුන්',
  'සාරාසකි',
  'කප්සුවහස්',
  'මතුයෙහි',
  'කුලුණුනු',
  'වණින්',
  'යුත්',
  'මහත',
  'වු',
  'සක්',
  'වැ',
  'දිවකුරු',
  'බුදුන්',
  'හමුවැ',
  'අතට',
  'පත්',
  'නිවන්',
  'සසර',
  'සේ',
  'පියා',
  'සතුන්',
  'සඳහා',
  'විඳුනා',
  'සසර',
  'දුක්',
  'නිවන්',
  'සේ',
  'ගෙන',
  'භව',
  'දුර්ගයට',
  'වැද',
  'පැරුම්',
  'පුරා',
  'තු',
  'පුර',
  'පැමිණ',
  'දසදහස්',
  'ලෝදාහි',
  'දෙව්බඹුන්ගේ',
  'අයජ',
  'මෙන්',
  'කිඹුල්වත්හි',
  'ඉපද',
  'වැඩිවිය',
  'පැමිණ',
  'මහභිනික්මන්',
  'කොට',
  'පැවිජි',
  'වැ',
  'මහා',
  'වීර්යය',
  'කොට',
  'බොධිපර්යංකාරූඪ',
  'වැ',
  'මාරවිජය',
  'කොට',
  'සර්වඥපදප්රාප්ත',
  'වැ',
  'හුනස්නෙන්',
  'නැඟී',
  'පූර්වොත්තර',
  'දිශා',
  'භාගයෙහි',
  'වැඩ',
  'සිට',
  'සප්තාහයක්',
  'අනිමිසලෝචන',
  'යුගලයෙන්',
  'පුදන',
  'ලද',
  'ජය',
  'මහා',
  'බොධිය',
  'තත',
  'ප්රභව',
  'වූ',
  'ඵල',
  'රුහ',
  'මහා',
  'බොධිය',
  'තදවයව',
  'වූ',
  'ශාඛා',
  'හා',
  'බොධිය',
  'යන',
  'තුන්',
  'මහා',
  'බොධීන්ගේ',
  'වංශයෙහි',
  'සහස්රරශ්මින්',
  'විභක්ත',
  'පදයන්',
  'අතුරෙහි',
  'පරිකථානුකූල',
  'පද',
  'ගෙන',
  'වර්ණනා',
  'කරනු',
  'ලැබේ',
  'යස්ස',
  'යනු',
  'චතුර්විධ',
  'පදයන්',
  'කෙරෙහි',
  'නාමපදයි',
  'එහි',
  'චතුර්විධ',
  'පද',
  'නම්',
  'කවරයත්',
  'නාම',
  'පදය',
  'ආඛ්යාත',
  'පදය',
  'උපසර්ග',
  'පදය',
  'නිපාතපදයි',
  'එහි',
  'නාම',
  'පද',
  'නම්',
  'සර්වාර්ථයන්',
  'නමන්නෙන්',
  'නාම',
  'පද',
  'නම්',
  'වේ',
  'එයින්',
  'කීහ',
  'ක්රියාවාචක',
  'පද',
  'ආඛ්යාත',
  'නම්',
  'වේ',
  'එයින්',
  'කීහ',
  'ක්රියා',
  'ද්යෝතක',
  'පද',
  'උපසර්ග',
  'නම්',
  'වේ',
  'එයින්',
  'කීහ',
  'දක්වන',
  'ලද',
  'පදයන්ගේ',
  'ආද්යන්ත',
  'මධ්යයෙහි',
  'නිපතිත',
  'වූ',
  'විචිත්රාර්ථ',
  'පදයෝ',
  'නිපාත',
  'නම්',
  'වෙත්',
  'එයින්',
  'කීහ',
  'මේ',
  'චතුර්විධ',
  'පදයන්ගේ',
  'ප්රයෝග',
  'දක්වන්නට',
  'කීහ',
  'යන',
  'තන්හි',
  'එව',
  'යන',
  'නිපාතය',
  'අයොග',
  'ව්යවඡදකය',
  'අන්ය',
  'යොග',
  'ව්යවච්ඡේදකය',
  'අත්යන්තා',
  'යොග',
  'ව්යව',
  'ච්ඡේදකය',
  'යි',
  'ත්රිවිධ',
  'වූයේ',
  'අන්ය',
  'යොග',
  'ව්යවච්ඡේදක',
  'වේ',
  'එහි',
  'විශෙෂණයා',
  'කෙරෙන්',
  'පර',
  'කොට',
  'ප්රයෝග',
  'කරන',
  'ලද',
  'එවකාරය',
  'අයොග',
  'ව්යවච්ඡේදක',
  'වෙයි',
  'යන',
  'තන්හි',
  'සෙයින්',
  'විශෙෂයා',
  'කෙරෙන්',
  'පර',
  'කොට',
  'ප්රයෝග',
  'කරන',
  'ලද',
  'එව',
  'කාරය',
  'වෙයි',
  'යන',
  'තන්හි',
  'සෙයින්ක්රියායෙන්',
  'පර',
  'කොට',
  'ප්රයොග',
  'කරන',
  'ලද',
  'එව',
  'කාරය',
  'අත්යන්තා',
  'යොග',
  'ව්යවච්ඡේදක',
  'වෙයි',
  'යන',
  'තන්හි',
  'සෙයින්වාක්යයන්',
  'ව්යවච්ඡේද',
  'ඵල',
  'වන',
  'බැවින්',
  'නිපාතයා',
  'ප්රයෝග',
  'නොකළද',
  'විවක්ෂා',
  'වශයෙන්',
  'ඔහුගේ',
  'අර්ථ',
  'ප්රතීත',
  'වේ',
  'මැයි',
  'එයින්',
  'කීහ',
  'ධර්ම',
  'කීර්තිපාදයෝ',
  'අහීස',
  'මාධි',
  'කථා',
  'යනුයෙන්',
  'දක්වන',
  'ලද',
  'බුදුහු',
  'අනන්තා',
  'පරිමාණ',
  'ගුණ',
  'ඇතියෝ',
  'කිසේය',
  'යත්',
  'බුදුහු',
  'රූප',
  'විලාසයෙනුදු',
  'වචන',
  'විලාසයෙනුදු',
  'ඥාන',
  'විලාසයෙනුදු',
  'අචින්ත්යයහ',
  'අවාච්යයහ',
  'අතුල්යහ',
  'අවෙද්යයෝයි',
  'එව්හු',
  'අචින්ත්ය',
  'වන',
  'බැවින්',
  'චින්තා',
  'විෂයාතික්රාන්තයහ',
  'අවාච්ය',
  'වන',
  'බැවින්',
  'වාග්',
  'විෂයාතික්රාන්ත',
  'සහ',
  'අතුල්ය',
  'වන',
  'බැවින්',
  'උපමා',
  'විෂයාතික්රාන්තයහ',
  'අද',
  'වන',
  'බැවින්',
  'ඥාන',
  'විෂයාතික්රාන්තයහ',
  'කපකුදු',
  'වූ',
  'දවස්',
  'තම',
  'සේම',
  'වූ',
  'බුදු',
  'කෙනෙකුනුදු',
  'කියත්',
  'නොගෙවෙන',
  'ගුණ',
  'ඇතියෝ',
  'මහ',
  'මුහුදැ',
  'හෙළූ',
  'සිදුහතුළුදු',
  'කළ',
  'සැළදු',
  'තම',
  'තමා',
  'පමණින්',
  'දියගන්නා',
  'සේ',
  'ඒ',
  'බුදු',
  'රජහුගේ',
  'ගුණ',
  'මුහුදට',
  'වන්',
  'පසේ',
  'බුදුහුදු',
  'බුදු',
  'සවෝද',
  'තම',
  'තමන්ගේ',
  'නුවණ',
  'පමණින්',
  'ගන්ති',
  'ගුණ',
  'පමණින්',
  'ගන්නට',
  'නොනිසෝ',
  'ඥානගර්ජනා',
  'කරන්නට',
  'සමර්ථ',
  'වූ',
  'ධර්ම',
  'සෙනෙවි',
  'සැරියුත්',
  'මහතෙ',
  'රුන්',
  'වැනි',
  'මහා',
  'පුරුෂයනටත්',
  'අවිෂය',
  'වූ',
  'බුදු',
  'ගුණ',
  'පුහුදුන්',
  'වැ',
  'කියම්',
  'හයි',
  'සිතනු',
  'මදුරු',
  'දළින්',
  'විදුරු',
  'ගිරි',
  'විදුනාක්',
  'පින',
  'හැඹිළි',
  'දළින්',
  'මහ',
  'පොළොව',
  'උකුල්',
  'දෙනුවක්',
  'වැනි',
  'බැවින්',
  'තම',
  'හට',
  'අවිෂය',
  'වතුදු',
  'ප්රසාද',
  'පරවශ',
  'වැ',
  'ප්රවචන',
  'වහල්',
  'කොට',
  'ශ්රද්ධා',

In [48]:
century_tokens[12]

['තමා',
 'වරදස',
 'නොදිස්',
 'නේ',
 'මෙරමා',
 'දොස්',
 'දිස්නේ',
 'නුවන්',
 'බැහැර',
 'නහමත්',
 'තමා',
 'මුත්',
 'නොදක්නේ',
 'කිම්',
 'සරසවිය',
 'බැලුමසෙක්',
 'නි',
 'වෙත්වා',
 'කිවි',
 'දෙනෝ',
 'පෙදෙහි',
 'රසහව්',
 'විදුනා',
 'දෙනෙතා',
 'ඉතා',
 'දුලබෝ',
 'ම',
 'තෙපල',
 'පා',
 'ලදපිළි',
 'වේ',
 'වෙසෙස්',
 'මෙ',
 'සෙබේ',
 'කසුන්',
 'කෙවුන්නේ',
 'බඳ',
 'මිණීමැ',
 'ගුණෙනුතුරත්',
 'වේ',
 'තමා',
 'වරදස',
 'නොදිස්නේ',
 'තමාගේ',
 'වරදෙහි',
 'ස්වල්පයකුදු',
 'අදෘශ්යය',
 'මෙරමා',
 'දොස්',
 'දිස්නේ',
 'අනුන්ගේ',
 'දොෂ',
 'වනාහි',
 'පැණෙන්නේන්',
 'මැයි',
 'නුවන්',
 'නෙත්රය',
 'තමා',
 'මුත්',
 'තමා',
 'විනා',
 'බැහැර',
 'නහමත්',
 'බාහ්ය',
 'වස්තූන්',
 'විෂයෙහි',
 'විචාරත්',
 'හොත්',
 'නොදක්නේ',
 'කිම්',
 'සර්ෂප',
 'ආදී',
 'කොට',
 'අදෘශ්යමාන',
 'කිමෙක්ද',
 'සරසවිය',
 'සරස්වතියගේ',
 'බැලුමසෙක්නි',
 'අර්ධ',
 'නිරීක්ෂණ',
 'මාත්රයෙකින්',
 'දෙනෝ',
 'කිවි',
 'වෙත්වා',
 'ජනයෝ',
 'කිවිහු',
 'වෙත්වා',
 'පෙදෙහි',
 'රසහව්',
 'විදුනා',
 'දෙනෙතා',
 'පදයෙහි',
 'රසභාවය',
 'දන්නා',
 'ජනයෝ',
 'වනාහි',
 'ඉතා',
 'දුලබෝ',
 'අතිදුර්ලභයෝයි',
 'මෙ',
 'සෙබේ',
 'මේ',
 'ස්වභාවෙහි',
 'ම',
 'තෙපල',
 'පා',
 'ලද',
 'මාගේ',
 'තෙපුලට',
 'ප්රතිෂ්ඨා',
 'ලද',
 'නම්',
 'පිළි',
 'වෙසෙස්',
 'වේ',
 'නැවත',
 'විශෙෂ',
 'කිවි',
 'බැව්',
 'කිවිදුමේ',
 'කුසුම්සැපතෙහි',
 'විපුල්පෙලෙ',
 'බෝසත්',
 'සර',
 'වැණුම්',
 'වියතෙමුව',
 'පවත්',
 'වේවා',
 'රජ',
 'පැමිණි',
 'බෝ',
 'සත්',
 'සත්',
 'රජුනෙඩි',
 'මැඩ',
 'විසී',
 'විසී',
 'තමා',
 'කැරැ',
 'කලක්',
 'කලක්',
 'දස',
 'රජ',
 'දම්නෙන්',
 'ලද',
 'පියන්',
 'බිඳු',
 'පියවුරෙව්',
 'මෙ',
 'දා',
 'දක්වා',
 'පින්',
 'පියවුරු',
 'මණ්ඩලෙව්',
 'පිළි',
 'මෙහි',
 'විතර',
 'පානෙම්',
 'වී',
 'කුසාවත්',
 'නම්',
 'නුවරෙක්',
 'උපත්',
 'සත්සර',
 'පිරි',
 'බෝදාසිරි',
 'නදන්',
 'පියුමෙව්',
 'බඹ',
 'තෙලේ',
 'දුනු',
 'වෙයි',
 'කසුන්කෙවුන්නේ',
 'බඳ',
 'කාඤ්චනාධාරයෙහි',
 'බැන්දා',
 'වූ',
 'මිණීමැ',
 'මාණික්යයම',
 'ගුණෙනුතුරත්',
 'වේ',
 'ගුණයෙන්',
 'උත්තරී',
 'තර',
 'වේ',
 'කිවි',
 'බැව්',
 'කවි',
 'භාවය',
 'තෙමේ',
 'කිවිදුමේ',
 'කවිද්රැමයෙහි',
 'කුසුම්',
 'සැපත්',
 'කුසුම',
 'සම්පත්තියෙක',
 'එහි',
 'විපුල්පෙලෙ',
 'ඒ',
 'කුසුම',
 'සම්පත්ති',
 'යෙහි',
 'මහාඵල',
 'නම්',
 'බෝසත්',
 'සර',
 'වැණුම්',
 'බොධිසත්ව',
 'චරිත',
 'වර්ණනා',
 'විය',
 'එ',
 'වියත්',
 'මුව',
 'පවත්',
 'වේවා',
 'ඒ',
 'ඵලජාති',
 'ව්යක්ත',
 'යන්ගේ',
 'මුඛ',
 'ප්රවර්තිත',
 'වේවා',
 'බෝසත්සර',
 'බෝසත්',
 'බොධිසත්ව',
 'තෙමේ',
 'රජ',
 'පැමිණී',
 'රාජශ්රියට',
 'ප්රාප්තව',
 'සත්',
 'රජුනෙඩි',
 'මැඩ',
 'සප්ත',
 'රාජයන්ගේ',
 'දප්පමිරිකා',
 'තමා',
 'කලක්',
 'විසී',
 'කැරැ',
 'තමාගේ',
 'කාන්තාවක්',
 'වසඟ',
 'කොට',
 'දස',
 'රජ',
 'දම්නෙන්',
 'දශරාජ',
 'ධර්මයෙන්',
 'කලක්',
 'විසී',
 'එක්',
 'කාලයක්',
 'වාසය',
 'කෙළේයි',
 'ලද',
 'පියන්',
 'අභිනව',
 'ස්ත්රීන්ගේ',
 'බිඳු',
 'පියවුරු',
 'එව්',
 'බින්දු',
 'මාත්ර',
 'පයොධරයන්',
 'මෙන්',
 'මෙ',
 'දා',
 'දක්වා',
 'මේ',
 'ජාතකය',
 'සංක්ෂෙපයෙන්',
 'දක්වා',
 'පින්පියවුරු',
 'මඬලෙව්',
 'සන්නද්ධ',
 'යෞවනයෙහි',
 'ඔවුන්ගේ',
 'පීණපයොධර',
 'මණ්ඩලයන්',
 'මෙන්',
 'පිළි',
 'නැවත',
 'මෙහි',
 'විතර',
 'පානම්',
 'මේ',
 'ජාතකයෙහි',
 'විස්තර',
 'දක්වමි',
 'පිරිබෝදා',
 'සිරි',
 'නදන්',
 'පාරිභොගික',
 'ධාතුශ්රීයට',
 'නිධාන',
 'වූ',
 'බඹ',
 'තෙලේ',
 'දුනු',
 'පියුමෙව්',
 'බ්රහ්ම',
 'ලොකයෙහි',
 'ජාත',
 'පද්මයක්',
 'මෙන්',
 'දෙරණ',
 'වුලුඹෙපුරේනුබසරණ',
 'සර',
 'දුර',
 'ලූ',
 'නුබපා',
 'ගත්',
 'සෙමිණි',
 'වලා',
 'මහවුරු',
 'සේමිණි',
 'වලා',
 'පුරකත',
 'නුබඳ',
 'බඳ',
 'මහවුරු',
 'උකුළුවටහී',
 'සහගුම්',
 'බිඟුවැල',
 'පියුම්',
 'පිරි',
 'කියලී',
 'රසන්දම්',
 'කැරැළිමිණි',
 'රැස්යටගෙහි',
 'සේසතෙව්',
 'තෙවුනේ',
 'විමනුදුල',
 'එ',
 'පුරනුබේ',
 'සුපුන්',
 'සරා',
 'සරාසඳ',
 'සත්සර',
 'උපත්',
 'සත්වසාරයට',
 'උත්පත්ති',
 'ස්ථාන',
 'වූ',
 'කුසාවත්',
 'නම්',
 'නුවරෙක්',
 'වී',
 'කුසාවතී',
 'නම්',
 'නගරයෙක්',
 'වී',
 'දෙරණවුලුඹු',
 'ධරණීය',
 'පැහැර',
 'යන්නා',
 'වූ',
 'නුබසරණ',
 'සර',
 'දුර',
 'ලු',
 'නභශ්වරයන්ගේ',
 'ගමන්',
 'දුරලූවා',
 'වූ',
 'එ',
 'පුරේ',
 'ඒ',
 'පුරයෙහි',
 'සෙමිණි',
 'මහවුරු',
 'සස්ඵටික',
 'මාණික්ය',
 'මහත්',
 'ප්රා',
 'කර',
 'තෙමේ',
 'නුබ',
 'මිණි',
 'පා',
 'ගත්',
 'නහස්',
 'නැමැති',
 'මණි',
 'පාත්රය',
 'දැරූ',
 'සේමිණි',
 'වලා',
 'වලා',
 'සස්ඵටික',
 'මණී',
 'වලයාකාරයි',
 'සහගුම්',
 'ඝොෂා',
 'සහිත',
 'වූ',
 'බිඟු',
 'වැල',
 'භෘංගාවලීන්',
 'යුක්ත',
 'වූ',
 'පියුම්',
 'පිරි',
 'පද්ම',
 'පරිඛා',
 'තොමෝ',
 'පුරකත',
 'පුර',
 'නැමැති',
 'කාන්තාවගේ',
 'මහවුරු',
 'උකුළුවටහී',
 'මහාප්රාකාර',
 'නැමැති',
 'උකුළු',
 'වර්තයෙහි',
 'නුබඳ',
 'බඳ',
 'නිරන්තරයෙන්',
 'බද්ධ',
 'වූ',
 'රසන්දම්',
 'කියලී',
 'රසනාදාමය',
 'ප්රකාශ',
 'කළා',
 'විමනුදුල',
 'විමානයෙන්',
 'උද්දීප්ත',
 'වූ',
 'එ',
 'පුරනුබේ',
 'ඒ',
 'පුරාකාශයෙහි',
 'සුපුන්',
 'සරා',
 'සරා',
 'සඳ',
 'සම්පූර්ණ',
 'වූ',
 'ප්රභා',
 'සහිත',
 'වූ',
 'ශරච්චන්ද්ර',
 'තෙම',
 'කැරළිමිණි',
 'රැස්යටගෙහි',
 'ශෘංගමාණික්ය',
 'රශ්මි',
 'යෂ්ටි',
 'අග්රයෙහි',
 'සේසතෙව්',
 'තෙවුනේ',
 'ස්වෙතච්ඡත්රයක්',
 'මෙන්',
 'හොබනේයි',
 'සුනිල්මිණි',
 'වේබිමැ',
 'පිළිබිඹු',
 'බද',
 'දදසුමු',
 'පෙරළෙත',
 'කලිඳු',
 'ගඟැමින්',
 'කැල',
 'කෙළි',
 'පෑ',
 'එ',
 'පුරවර',
 'රතමිණි',
 'තොරණ',
 'රැස්රැසින්',
 'රතෙ',
 'පුර',
 'සුපුන්',
 'සඳ',
 'ලහිරු',
 'හො',
 'යී',
 'නොසරස්',
 'දැනවී',
 'සැක',
 'බිසරුවන්',
 'රත',
 'මිණි',
 'රැස්',
 'රැදින්',
 'නුබ',
 'විදුරතු',
 'සුරපුරෙන්',
 'ලහිරු',
 'හො',
 'යී',
 'නො',
 'සරස්',
 'දැන',
 'වී',
 'සැක',
 'බිසවරුවන්',
 'නේ',
 'මිණි',
 'රැස්',
 'රැදින්',
 'නුබ',
 'විදුරතු',
 'සුරපුරෙන්',
 'රුවන්',
 'යොත්',
 'නිදුල',
 'පවර',
 'සමහර',
 'බටෙව්',
 'එ',
 'නුවර',
 'සුනිල්මිණි',
 'වේබිමැ',
 'ඉන්ද්රනීල',
 'ඉන්ද්රනීල',
 'මණික්ය',
 'භුමි',
 'විථියෙහි',
 'පිළිබිඹු',
 'බද',
 'ප්රතිබිම්බිත',
 'වූ',
 'දදසුමු',
 'පෙරළෙත',
 'ධ්වජ',
 'සමූහයන්',
 'පෙරළෙන',
 'කල්හි',
 'එ',
 'පුරවර',
 'ඒ',
 'පුර',
 'ප්රවරය',
 'තෙම',
 'කලිඳු',
 'ගඟැ',
 'කාලින්දි',
 'ගංගායෙහි',
 'මින්',
 'කැල',
 'කෙළි',
 'පෑ',
 'මත්ස්ය',
 'සමූහයාගේ',
 'ක්රීඩා',
 'දැක්වී',
 'රථමිණි',
 'තොරණ',
 'රැස්',
 'රැසින්',
 'රක්තමාණික්ය',
 'තොරණ',
 'රශ්මි',
 'රාශියෙන්',
 'රත්',
 'රක්ත',
 'වූ',
 'එ',
 'පුරේ',
 'සුපුන්සඳ',
 'ඒ',
 'පුරයෙහි',
 'සම්පූර්ණ',
 'චන්ද්ර',
 'තෙම',
 'ලහිරු',
 'හෝයී',
 'බාලාර්ක',
 'දෝහෝයි',
 'කියා',
 'අබිසරුවන්',
 'අභිසාරිකාවන්ට',
 'නොසරස්',
 'සැක',
 'දැනවී',
 'වහ',
 'වහාශංකා',
 'නිපදවී',
 'නේමිණි',
 'රැස්',
 'රැදින්',
 'අනෙක',
 'ප්රකාර',
 'වූ',
 'මාණික්ය',
 'රශ්මි',
 'රාජින්',
 'නුබ',
 'නභසතලය',
 'විදුරතු',
 'අවුණන',
 'කල්හි',
 'උදුල',
 'උජජ්වලිත',
 'වූ',
 'රුවන්',
 'යොත්නි',
 'රත්න',
 'රජ්ජුයෙන්',
 'පවර',
 'උතුම්',
 'වූ',
 'එ',
 'නුවර',
 'ඒ',
 'පුරය',
 'සුරපුරෙන්',
 'දිව්ය',
 'පුරයෙන්',
 'සමහර',
 'බටෙව්',
 'අර්ථයක්',
 'අවතීර්ණ',
 'වූවාක්',
 'වැන්න',
 'තුගුතුල්',
 'යට',
 'හ',
 'ලෙල',
 'දද',
 'මෙ',
 'පුර',
 'සිරිමත',
 'ඉඳු',
 'නිල්',
 'මිණී',
 'දෙරණ',
 'පිළිබිඹුව',
 'බබළත',
 'මනකල්',
 'කලිඳු',
 'ගඟතුළ',
 'කෙළනා',
 'සතත',
 'පැහැදුල්',
 'නොයෙක්',
 'වග',
 'මික්සිරි',
 'පැයි',
 'දිමුත',
 'එහි',
 'විසිතු',
 'රෑ',
 'රතමිණී',
 'තොරණ',
 'රැස්',
 'වැද',
 'ගණදුරු',
 'දුරු',
 'කරණ',
 'රත',
 'වන්',
 'සුපුන්',
 'සඳ',
 'නෙක',
 'අබිසරු',
 'අඟනන්හට',
 'සරණ',
 'සෙද',
 'නව',
 'දිවයු',
 'රු',
 'යයිද්යානවීය',
 'සැක',
 'සඳ',
 'පිළිබිඹු',
 'ප්රතිත',
 'වූ',
 'බඳ',
 'බද්ධ',
 'වූ',
 'සමහර',
 'වුල්අස්න',
 'වීදු',
 'ර',
 'තු',
 'ආවූ',
 'න',
 'ත',
 'කල්හි',
 'යි',
 'ද',
 'ආවෘත',
 'කරණ',
 'කල්හි',
 'යි',
 'ද',
 'සියලු',
 'කව්සිළුමිණ',
 'සලෙලුවන්',
 'අලලත',
 'පුරයෝනන්',
 'නුවන්හී',
 'සිය',
 'කැමි',
 'නොබල',
 'මල්සරසැතපී',
 'ගි',
 'වී',
 'මස්සැර',
 'මහවෙහි',
 'බඳ',
 'රඟවියනෙව්',
 'ලෙව්නුවන්',
 'බඳ',
 'හැනී',
 'දෙපස්හී',
 'නන්',
 'රුවන්',
 'පහ',
 'මෙ',
 'රජරජ',
 'කෙළෙ',
 'තුටු',
 'රගොතමත',
 'ඟන්',
 'විදු',
 'වදගන',
 'ගැජුම්',
 'ගෙනෙ',
 'ඉඳුනිල්මිණි',
 'විමන්',
 'විමන්',
 'සිකිකැන්',
 'එ',
 'පුරේ',
 'මුහුළත්තඹුරු',
 'වින්',
 'දනනඟනන්',
 'උවන්',
 'සඳ',
 'සමහර',
 'දිසි',
 'පියුම්රා',
 'මිණීමැදුරෙ',
 'සීමැදුරේ',
 'පුරයෝනන්',
 'පුර',
 'යුවතීන්ගේ',
 'නුවන්හී',
 'නෙත්ර',
 'නැමැති',
 'බාණයෙන්',
 'සලෙලුවන්',
 'සල්ලාලජනයන්',
 'අලලත',
 'ආලොලනය',
 'කරණ',
 'කල්හි',
 'සියකැමින්',
 'ස්වකීය',
 'ක්රියාවෙන්',
 'ඔබල',
 'දුර්වල',
 'වූ',
 'මල්සර',
 'අනංගයාගේ',
 'මසැර',
 'පුෂ්පබාණ',
 'සැතපී',
 'ගී',
 'වී',
 'විශ්රාමය',
 'කළාක්',
 'වැනි',
 'වී',
 'දෙපස්හි',
 'උභය',
 'පාර්ශ්වයෙහි',
 'නන්රුවන්පහ',
 'මෙරජරජ',
 'හැනී',
 'අනෙක',
 'රතන',
 'ප්රාසාදයෙහි',
 'මරීචිරාජී',
 'එක්ව',
 'මහවෙහි',
 'බඳ',
 'මහා',
 'වීථියෙහි',
 'බද්ධ',
 'වූ',
 'රඟ',
 'විය',
 'නෙව්',
 'රංග',
 'විතානයක්',
 'මෙන්',
 'ලෙනුවන්',
 'බඳ',
 'ලොකයාගේ',
 'නෙත්ර',
 'බන්ධනය',
 'කළා',
 'රඥෙත',
 'මතඟන',
 'නෘත්ය',
 'ගත්තාවූ',
 'මත්තාගනා',
 'නැමැති',
 'විදු',
 'විද්යත්',
 'ඇති',
 'වද',
 'ගන',
 'ගැජුම්',
 'වාද්ය',
 'නැමැති',
 'මෙඝධ්වනි',
 'ඇති',
 'එ',
 'පුරේ',
 'ඒ',
 'පුරයෙහි',
 'ඉඳුනිල්මිණි',
 'විමන්',
 'ගෙනේ',
 'ඉන්ද්රනීල',
 'මාණික්ය',
 'විමාන',
 'නැමැති',
 'මේඝ',
 'තෙමේ',
 'විමන්',
 'සිකි',
 'කැන්',
 'තුටු',
 'කෙළේ',
 'ගෘහමයූර',
 'සමූහයා',
 'සන්තුෂ්ට',
 'කෙළේ',
 'පියුම්රාමිණී',
 'මැදුරේ',
 'පද්මරාග',
 'මාණික්යමය',
 'ප්රාසාදයෙහි',
 'සීමැදුරේ',
 'සිංහපඤ්ජරයෙහි',
 'අඟනන්',
 'කාන්තාවන්ගේ',
 'සමහර',
 'දිසි',
 'අර්ධයක්',
 'දෘශ්යමාන',
 'වූ',
 'උවන්',
 'සඳ',
 'වක්ත්ර',
 'චන්ද්ර',
 'තෙම',
 'දනන්',
 'ජනයන්ගේ',
 'මුහුළු',
 'මුකුලිත',
 'වූ',
 'අත්තඹුරු',
 'හසතාමරසයන්',
 'වින්',
 'වින්දේයි']

In [49]:
from typing import List, Dict, Counter as T_Counter, Set, Any

In [50]:
def find_century_wise_context_cooccurrences(tokens: List[str], window: int, separator: str) -> Dict[str, T_Counter]:
    """
    Finds all words co-occurring within a +/- window of a target word, 
    respecting document boundaries defined by a separator token.
    """
    cooccurrence_map = {}
    
    # Iterate through every token in the century's text
    for i, target_word in enumerate(tokens):
        
        # 1. Skip the separator token itself (it should never be a target word)
        if target_word == separator:
            continue
            
        # Initialize a counter for this target word if it doesn't exist
        if target_word not in cooccurrence_map:
            cooccurrence_map[target_word] = Counter()
            
        # Define the search range
        start_index = max(0, i - window)
        end_index = min(len(tokens), i + window + 1)
        
        # Extract the context window slice
        context_window = tokens[start_index:end_index]
        
        # Add all valid neighbors in the window
        for neighbor in context_window:
            # 2. Skip the target word itself
            if neighbor == target_word:
                continue
            
            # 3. CRUCIAL: Skip the separator token when counting neighbors
            if neighbor == separator:
                continue

            if neighbor in highly_significant_word_set:
                continue
                
            cooccurrence_map[target_word][neighbor] += 1
                
    return cooccurrence_map

In [51]:
# Dictionary to store the co-occurrence results for every century
century_cooccurrence_results: Dict[str, Dict[str, T_Counter]] = {}

print(f"Starting co-occurrence analysis (Window: +/- {WINDOW_SIZE}) for each century...")

for century, tokens in century_tokens.items():
    print(f"Analyzing {century} century (Total tokens: {len(tokens)})...")
    
    # Run the analysis for the current century's tokens
    cooccurrence_map = find_century_wise_context_cooccurrences(
        tokens=tokens,
        window=WINDOW_SIZE,
        separator=DOCUMENT_SEPARATOR
    )
    
    # Save the result
    century_cooccurrence_results[century] = cooccurrence_map

Starting co-occurrence analysis (Window: +/- 10) for each century...
Analyzing 5 century (Total tokens: 565)...
Analyzing 12 century (Total tokens: 866)...
Analyzing 13 century (Total tokens: 13626)...
Analyzing 14 century (Total tokens: 5213)...
Analyzing 15 century (Total tokens: 8490)...

Analyzing 16 century (Total tokens: 1369)...
Analyzing 18 century (Total tokens: 4710)...
Analyzing 19 century (Total tokens: 12707)...
Analyzing 20 century (Total tokens: 17309)...

In [52]:
century_cooccurrence_results[13]['දෙමවුපියන්']

Counter({'තමන්': 2,
         'සිත්': 1,
         'ඇතිව': 1,
         'අනුන්ට': 1,
         'අනුශාසනා': 1,
         'කලත්': 1,
         'යහපත්': 1,
         'තරම්': 1,
         'දරුවන්': 1,
         'තරමේ': 1,
         'හික්ම': 1,
         'වන්නා': 1,
         'සියලු': 1,
         'අකුසලින්': 1,
         'දුරුව': 1})

In [53]:
len(century_cooccurrence_results[13])

5883

In [54]:
# all_centuries = list(century_cooccurrence_results.keys())

# for century in all_centuries[9:]:
#     current_century_keys = set(century_cooccurrence_results[century].keys())
#     # Find the intersection (words present in both the current common_keys set and the current century)
#     common_keys = common_keys.intersection(current_century_keys)

In [55]:
def get_consistent_keys(
    full_cooccurrence_results: Dict[str, Dict[str, T_Counter]], 
    selected_centuries: List[str]
) -> Set[str]:
    """Finds the intersection of target words across selected centuries."""

    if not selected_centuries:
        return set()

    all_key_sets = []
    
    for century in selected_centuries:
        if century not in full_cooccurrence_results:
            print(f"Error: Century '{century}' not found. Returning empty set.")
            return set()
        all_key_sets.append(set(full_cooccurrence_results[century].keys()))
    
    if not all_key_sets:
        return set()
        
    return set.intersection(*all_key_sets)

In [56]:
centuries_to_compare = [13, 14, 15 ,16, 18, 19, 20]
# Find the keys consistent ONLY within the selected subset
consistent_keys = get_consistent_keys(century_cooccurrence_results, centuries_to_compare)

In [57]:
consistent_keys

{'අප',
 'අසා',
 'ආ',
 'ආදි',
 'ඇති',
 'ඊට',
 'එ',
 'එක',
 'එක්',
 'එම',
 'එසේ',
 'ඒ',
 'ඔහු',
 'කර',
 'කල',
 'කළ',
 'කාල',
 'කියන',
 'කිසි',
 'කී',
 'කොට',
 'ගත',
 'ගිය',
 'ගුණ',
 'ද',
 'දක්වා',
 'දත්',
 'දවස',
 'දැක',
 'දී',
 'දුක්',
 'දෙන',
 'දෙවියන්',
 'නම්',
 'නැති',
 'නිසි',
 'නොයෙක්',
 'නොව',
 'පද',
 'පමණ',
 'පළමු',
 'පැමිණි',
 'පුර',
 'පෙර',
 'බල',
 'බලා',
 'මතු',
 'මල්',
 'මහ',
 'මහත්',
 'මා',
 'මෙන්',
 'මෙසේ',
 'මේ',
 'යන',
 'යනු',
 'යම්',
 'යුතු',
 'රජ',
 'රැස්',
 'ලද',
 'වන',
 'වසන',
 'විය',
 'විසිනුදු',
 'වී',
 'වූ',
 'වෙන',
 'සතර',
 'සත්',
 'සත්ව',
 'සමග',
 'සිට',
 'සිටි',
 'සිත',
 'සියලු',
 'හට',
 'හා',
 'හැර',
 'හෝ'}

In [58]:
len(consistent_keys)

80

In [59]:
filtered_century_cooccurrence_results: Dict[str, Dict[str, T_Counter]] = {}

In [60]:
filtered_cooccurrence_map_keys: Dict[str, T_Counter] = {
    target_word: neighbors_counter
    for target_word, neighbors_counter in cooccurrence_results.items()
    if target_word not in highly_significant_word_set
}

In [61]:
for century in centuries_to_compare:
    cooccurrence_map = century_cooccurrence_results.get(century)
    
    if cooccurrence_map is None:
        continue 

    # Filter the map to keep only the consistent keys
    filtered_map = {
        key: cooccurrence_map[key] 
        for key in consistent_keys
    }
    
    filtered_century_cooccurrence_results[century] = filtered_map

In [62]:
len(filtered_century_cooccurrence_results[14])

80

In [63]:
for century, filtered_map in filtered_century_cooccurrence_results.items():
        print(f"[{century}]:")
        for word, neighbors in filtered_map.items():
            print(f"  Target: '{word}' -> Neighbors (Top 3): {neighbors.most_common(3)}")

[13]:
  Target: 'වන' -> Neighbors (Top 3): [('විෂයාතික්රාන්තයහ', 8), ('බුදු', 5), ('වාග්', 4)]
  Target: 'යන' -> Neighbors (Top 3): [('ධාතුයැ', 38), ('අර්ථයි', 24), ('කෘදන්තයෙන්', 22)]
  Target: 'එම' -> Neighbors (Top 3): [('අධිගතයන්', 4), ('දශක', 3), ('සමුත්ථාන', 3)]
  Target: 'මා' -> Neighbors (Top 3): [('හිමියන්', 5), ('වැ', 4), ('නැමැති', 4)]
  Target: 'නැති' -> Neighbors (Top 3): [('කෙනෙකුන්', 4), ('තමා', 3), ('රූප', 3)]
  Target: 'පමණ' -> Neighbors (Top 3): [('ලක්ෂයක්', 7), ('කෙළ', 5), ('යනුයෙන්', 3)]
  Target: 'කියන' -> Neighbors (Top 3): [('සමාධි', 4), ('ලදී', 3), ('යනාදි', 3)]
  Target: 'එක්' -> Neighbors (Top 3): [('ගුරු', 4), ('යස', 4), ('දවසක්', 3)]
  Target: 'කොට' -> Neighbors (Top 3): [('වැ', 10), ('සියලු', 9), ('ඇත්තේයි', 9)]
  Target: 'ඔහු' -> Neighbors (Top 3): [('සකල', 2), ('දැනැ', 2), ('නිමිත්තෙන්', 2)]
  Target: 'හට' -> Neighbors (Top 3): [('සඳහා', 5), ('වැ', 4), ('දුක', 4)]
  Target: 'සිට' -> Neighbors (Top 3): [('මාරවිජය', 1), ('සර්වඥපදප්රාප්ත', 1), ('වැ', 1)]
  Target: 'මතු' -> Neighbors (Top 3): [('වැසී', 4), ('පැවැති', 4), ('ගේ', 3)]
  Target: 'දැක' -> Neighbors (Top 3): [('උපයා', 2), ('වස්තු', 2), ('කොටලා', 2)]
  Target: 'ගිය' -> Neighbors (Top 3): [('කප්', 2), ('අසංඛ්යයක්', 2), ('මුදුනෙහි', 1)]
  Target: 'ඇති' -> Neighbors (Top 3): [('නැමැති', 38), ('නුවණ', 13), ('සමාධි', 11)]
  Target: 'දුක්' -> Neighbors (Top 3): [('නිවන්', 4), ('සසර', 3), ('වැ', 2)]
  Target: 'ගුණ' -> Neighbors (Top 3): [('තම', 5), ('බුදු', 5), ('මහ', 5)]
  Target: 'ලද' -> Neighbors (Top 3): [('තුන්', 11), ('සමාධි', 8), ('පිණිස', 8)]
  Target: 'නිසි' -> Neighbors (Top 3): [('උපදෙස්', 2), ('පෙදෙන්', 1), ('යුත්', 1)]
  Target: 'පුර' -> Neighbors (Top 3): [('පැමිණ', 2), ('දුක්', 1), ('නිවන්', 1)]
  Target: 'පද' -> Neighbors (Top 3): [('නාම', 7), ('පදය', 7), ('එයින්', 7)]
  Target: 'කල' -> Neighbors (Top 3): [('මනා', 7), ('වැසි', 4), ('සුභික්ෂ', 4)]
  Target: 'සතර' -> Neighbors (Top 3): [('ගණ', 5), ('පර්වතය', 3), ('භාගයෙහි', 3)]
  Target: 'කී' -> Neighbors (Top 3): [('ග්රහණය', 4), ('එහෙයින්', 3), ('මොවුන්ගෙ', 3)]
  Target: 'පළමු' -> Neighbors (Top 3): [('ගාථාව', 5), ('පෘච්ඡා', 4), ('විසර්ජන', 3)]
  Target: 'ගත' -> Neighbors (Top 3): [('පාද', 2), ('මිහි', 2), ('අර්ථ', 2)]
  Target: 'යනු' -> Neighbors (Top 3): [('ධාතුයැ', 10), ('කෘදන්තයෙන්', 8), ('සුබ', 6)]
  Target: 'හෝ' -> Neighbors (Top 3): [('වැ', 6), ('වසන', 6), ('තමා', 6)]
  Target: 'එ' -> Neighbors (Top 3): [('සමාධි', 9), ('යොගි', 8), ('පතිරජ', 8)]
  Target: 'අප' -> Neighbors (Top 3): [('වහන්සේ', 4), ('සාරාසංඛ්ය', 3), ('වු', 2)]
  Target: 'මේ' -> Neighbors (Top 3): [('විශුද්ධි', 9), ('දත', 8), ('කීහ', 7)]
  Target: 'අසා' -> Neighbors (Top 3): [('බුදුන්', 9), ('නියාව', 4), ('මහ', 3)]
  Target: 'විසිනුදු' -> Neighbors (Top 3): [('යනාදි', 2), ('භයින්', 1), ('සොරුන්', 1)]
  Target: 'නොව' -> Neighbors (Top 3): [('යුතුයි', 3), ('මාත්රා', 2), ('ලකුණෙන්', 2)]
  Target: 'නොයෙක්' -> Neighbors (Top 3): [('රජු', 2), ('වසේළඹීම්', 1), ('අවෙහංගි', 1)]
  Target: 'නම්' -> Neighbors (Top 3): [('බිසොවුන්', 20), ('නුවර', 18), ('බුදුන්', 16)]
  Target: 'ද' -> Neighbors (Top 3): [('සමාධි', 43), ('කැප', 36), ('අකැප', 24)]
  Target: 'හැර' -> Neighbors (Top 3): [('සමවැද', 7), ('ධ්යානය', 6), ('ධ්යානයට', 4)]
  Target: 'යුතු' -> Neighbors (Top 3): [('දත', 11), ('විශුද්ධි', 6), ('මාර්ග', 5)]
  Target: 'මෙසේ' -> Neighbors (Top 3): [('තෙමේ', 4), ('බන්ධනය', 4), ('පද්ය', 3)]
  Target: 'පැමිණි' -> Neighbors (Top 3): [('උත්පත්ති', 1), ('දෙවියන්ට', 1), ('ඉදි', 1)]
  Target: 'වූ' -> Neighbors (Top 3): [('වැ', 40), ('නැමැති', 36), ('බඳු', 24)]
  Target: 'කාල' -> Neighbors (Top 3): [('යුතුයි', 2), ('අවහාර', 2), ('කාලය', 2)]
  Target: 'විය' -> Neighbors (Top 3): [('දහස්', 6), ('චක්රයෙහි', 5), ('දෙචක්රයෙක්', 3)]
  Target: 'පෙර' -> Neighbors (Top 3): [('කිසුණු', 1), ('ඉගුළු', 1), ('අහස', 1)]
  Target: 'මල්' -> Neighbors (Top 3): [('නැමැති', 4), ('අතුපතර', 1), ('ත්රිවිධ', 1)]
  Target: 'වෙන' -> Neighbors (Top 3): [('බඳු', 4), ('ශෘංගාර', 2), ('ශාලාවක්', 2)]
  Target: 'දවස' -> Neighbors (Top 3): [('නැමැති', 3), ('නුමුසු', 2), ('මූණලා', 1)]
  Target: 'වී' -> Neighbors (Top 3): [('තැන්', 3), ('සෙයින්', 3), ('ඇක්මෙමියි', 2)]
  Target: 'දත්' -> Neighbors (Top 3): [('දහම්', 2), ('සරණ', 2), ('මුළුල්ලෙහි', 1)]
  Target: 'මෙන්' -> Neighbors (Top 3): [('ශාස්ත්ර', 5), ('පැමිණ', 4), ('පමණක්', 4)]
  Target: 'දෙවියන්' -> Neighbors (Top 3): [('ඉදි', 1), ('කිරිබත', 1), ('විශුද්ධි', 1)]
  Target: 'සියලු' -> Neighbors (Top 3): [('මිහි', 4), ('තමන්', 4), ('සමාධි', 4)]
  Target: 'මහ' -> Neighbors (Top 3): [('නැමැති', 10), ('නිවන්', 8), ('මනා', 5)]
  Target: 'සත්ව' -> Neighbors (Top 3): [('සංඛ්යාත', 3), ('ජටාවෙන්', 2), ('ප්රජා', 2)]
  Target: 'වසන' -> Neighbors (Top 3): [('මගෙක්හි', 2), ('සුලඟ', 2), ('නොපහර', 2)]
  Target: 'සිටි' -> Neighbors (Top 3): [('පැනෙයි', 10), ('නාභි', 4), ('වටා', 4)]
  Target: 'සිත' -> Neighbors (Top 3): [('තණ', 2), ('පුරයට', 1), ('සුවයෙන්', 1)]
  Target: 'ඊට' -> Neighbors (Top 3): [('ව්යක්ත', 2), ('කසිණයෙහි', 2), ('ග්', 1)]
  Target: 'හා' -> Neighbors (Top 3): [('සමවැද', 6), ('ගුරු', 5), ('නැමැති', 4)]
  Target: 'කර' -> Neighbors (Top 3): [('වෙන', 2), ('නියම', 2), ('දරුවානන්', 1)]
  Target: 'කිසි' -> Neighbors (Top 3): [('සූත්රයෙක', 5), ('වසයෙන්', 5), ('දෙසන', 4)]
  Target: 'එක' -> Neighbors (Top 3): [('පැහැර', 4), ('වැ', 3), ('වෙ', 3)]
  Target: 'සමග' -> Neighbors (Top 3): [('කර්මාන්ත', 2), ('පුරුෂා', 1), ('ථ', 1)]
  Target: 'මහත්' -> Neighbors (Top 3): [('එයට', 2), ('ප්රතිපක්ෂ', 2), ('අතුරෙහි', 2)]
  Target: 'සත්' -> Neighbors (Top 3): [('දහම්', 2), ('සරණ', 2), ('සඳහා', 2)]
  Target: 'ඒ' -> Neighbors (Top 3): [('වුවහොත්', 14), ('ගුරක්', 10), ('හොත්', 9)]
  Target: 'කළ' -> Neighbors (Top 3): [('සඳහන්', 5), ('දෙව්', 4), ('පතිරජු', 4)]
  Target: 'ආ' -> Neighbors (Top 3): [('වහන්සේගේ', 4), ('පක්ෂයෙන්', 4), ('තිබී', 4)]
  Target: 'එසේ' -> Neighbors (Top 3): [('නොවෙයි', 2), ('වැ', 2), ('සියලු', 2)]
  Target: 'බලා' -> Neighbors (Top 3): [('බල', 3), ('සුදුසු', 2), ('මහ', 2)]
  Target: 'දක්වා' -> Neighbors (Top 3): [('කිසි', 3), ('කසිණයෙහි', 2), ('යන්නෙහි', 2)]
  Target: 'බල' -> Neighbors (Top 3): [('බැඳුම්', 4), ('බලා', 3), ('ගණ', 3)]
  Target: 'යම්' -> Neighbors (Top 3): [('පුරියෙක්හි', 13), ('ධ්යානය', 8), ('පිණිස', 7)]
  Target: 'දී' -> Neighbors (Top 3): [('කෙලෙස්', 2), ('මහදන්', 2), ('නුමුසු', 2)]
  Target: 'ආදි' -> Neighbors (Top 3): [('දු', 2), ('දත', 2), ('ඇත', 2)]
  Target: 'රැස්' -> Neighbors (Top 3): [('නැමැති', 3), ('අටුවා', 2), ('සංඝයා', 2)]
  Target: 'දෙන' -> Neighbors (Top 3): [('බ', 1), ('පිළිවෙළින්', 1), ('හැඳින', 1)]
  Target: 'රජ' -> Neighbors (Top 3): [('තෙමේ', 4), ('සැපත්', 3), ('සෙසු', 3)]
[14]:
  Target: 'වන' -> Neighbors (Top 3): [('ධර්මය', 3), ('දශ', 2), ('කරවා', 2)]
  Target: 'යන' -> Neighbors (Top 3): [('දෙසන', 5), ('ශ්රී', 4), ('කෙනෙකුන්', 3)]
  Target: 'එම' -> Neighbors (Top 3): [('දවස්', 3), ('රාත්රි', 3), ('භාගයෙහි', 3)]
  Target: 'මා' -> Neighbors (Top 3): [('සැරීරය', 3), ('ජාති', 2), ('නැත්තා', 2)]
  Target: 'නැති' -> Neighbors (Top 3): [('මරණ', 2), ('ජඹුද්වීපයෙහි', 1), ('දෙවියන්ගේ', 1)]
  Target: 'පමණ' -> Neighbors (Top 3): [('වහන්සේ', 11), ('ලක්ෂයක්', 4), ('ලක්ෂ', 3)]
  Target: 'කියන' -> Neighbors (Top 3): [('නිබ්බුත', 2), ('ලදි', 2), ('ශක්ර', 1)]
  Target: 'එක්' -> Neighbors (Top 3): [('සිසිල්', 1), ('අමෘත', 1), ('නිර්වානය', 1)]
  Target: 'කොට' -> Neighbors (Top 3): [('ස්වභාව', 14), ('ඇත්තෙමි', 14), ('වහන්සේ', 8)]
  Target: 'ඔහු' -> Neighbors (Top 3): [('කුල', 2), ('සදා', 2), ('පිටට', 2)]
  Target: 'හට' -> Neighbors (Top 3): [('වැඩ', 4), ('රජ', 3), ('අජාසත්', 3)]
  Target: 'සිට' -> Neighbors (Top 3): [('ආයු', 4), ('වැඩ', 2), ('කෙළවර', 2)]
  Target: 'මතු' -> Neighbors (Top 3): [('බොධිවජ්රාශන', 2), ('අග්ර', 2), ('ප්රකාශ', 2)]
  Target: 'දැක' -> Neighbors (Top 3): [('සසර', 5), ('තුන්දෙනා', 4), ('දවස්', 4)]
  Target: 'ගිය' -> Neighbors (Top 3): [('සම්පත්', 1), ('විඳිනා', 1), ('කුශල', 1)]
  Target: 'ඇති' -> Neighbors (Top 3): [('බුදුන්', 9), ('වහන්සේ', 6), ('නිර්වානය', 4)]
  Target: 'දුක්' -> Neighbors (Top 3): [('ස්වභාව', 3), ('උපන්', 2), ('ඇත්තෙමි', 2)]
  Target: 'ගුණ' -> Neighbors (Top 3): [('රාජ', 3), ('සකල', 3), ('සමන්නාගත', 2)]
  Target: 'ලද' -> Neighbors (Top 3): [('වහන්සේ', 8), ('සර්වඥයන්', 6), ('දෙසන', 6)]
  Target: 'නිසි' -> Neighbors (Top 3): [('වෛද්යාචාරියෙක්', 1), ('සමීපයෙහි', 1), ('ඇතුව', 1)]
  Target: 'පුර' -> Neighbors (Top 3): [('වඩනා', 1), ('එකාකාර', 1), ('වීර්යය', 1)]
  Target: 'පද' -> Neighbors (Top 3): [('ප්රාප්තව', 2), ('සේක්', 1), ('දීපංකර', 1)]
  Target: 'කල' -> Neighbors (Top 3): [('මහණ', 2), ('සත්මුතු', 1), ('පරම්පරාවක', 1)]
  Target: 'සතර' -> Neighbors (Top 3): [('සුභය', 1), ('තුන්පායෙහි', 1), ('වෙසෙමින්', 1)]
  Target: 'කී' -> Neighbors (Top 3): [('සුදුසු', 1), ('අර්ථ', 1), ('සිතින්', 1)]
  Target: 'පළමු' -> Neighbors (Top 3): [('පූර්ව', 1), ('කාලයෙහි', 1), ('සිංහළ', 1)]
  Target: 'ගත' -> Neighbors (Top 3): [('ප්රඥාගති', 1), ('සුමෙධ', 1), ('මහත', 1)]
  Target: 'යනු' -> Neighbors (Top 3): [('වහන්සේ', 4), ('සර්වඥයන්', 3), ('නුවරට', 2)]
  Target: 'හෝ' -> Neighbors (Top 3): [('ගෙන', 4), ('නින්දා', 2), ('ස්ත්රී', 2)]
  Target: 'එ' -> Neighbors (Top 3): [('සත්', 1), ('දවස', 1), ('ඇතුලෙහිම', 1)]
  Target: 'අප' -> Neighbors (Top 3): [('නුවර', 4), ('බුදුන්', 3), ('රජ', 3)]
  Target: 'මේ' -> Neighbors (Top 3): [('දෙසන', 11), ('ලද්දේද', 8), ('කවර', 6)]
  Target: 'අසා' -> Neighbors (Top 3): [('වහන්සේ', 3), ('කරා', 2), ('රාහුල', 2)]
  Target: 'විසිනුදු' -> Neighbors (Top 3): [('නැමති', 3), ('සැරීරය', 2), ('සැරිරයෙහි', 2)]
  Target: 'නොව' -> Neighbors (Top 3): [('වහන්සේ', 2), ('මහ', 1), ('තෙරුන්', 1)]
  Target: 'නොයෙක්' -> Neighbors (Top 3): [('රත්නයන්', 2), ('සොරුන්', 2), ('නියාව', 2)]
  Target: 'නම්' -> Neighbors (Top 3): [('වහන්සේ', 19), ('නුවර', 10), ('සුමෙධ', 7)]
  Target: 'ද' -> Neighbors (Top 3): [('තව', 4), ('නුවර', 3), ('ස්වභාව', 3)]
  Target: 'හැර' -> Neighbors (Top 3): [('බුදුන්', 5), ('සමන්නාගත', 4), ('බැව්', 3)]
  Target: 'යුතු' -> Neighbors (Top 3): [('ඇසිය', 2), ('නැසිය', 2), ('එපරිද්දෙන්ම', 2)]
  Target: 'මෙසේ' -> Neighbors (Top 3): [('ඇත්තෙමි', 3), ('තබා', 2), ('නැවත', 2)]
  Target: 'පැමිණි' -> Neighbors (Top 3): [('රජුන්', 2), ('රජ', 2), ('හිරු', 1)]
  Target: 'වූ' -> Neighbors (Top 3): [('වහන්සේ', 42), ('කරන්නා', 14), ('නුවර', 14)]
  Target: 'කාල' -> Neighbors (Top 3): [('ඔහුගේ', 2), ('බ්රාහ්මණෝත්තම', 1), ('කෙනෙක්', 1)]
  Target: 'විය' -> Neighbors (Top 3): [('සොයන්ට', 1), ('වටනේය', 1), ('භවයෙන්', 1)]
  Target: 'පෙර' -> Neighbors (Top 3): [('ආදර', 1), ('සහිතව', 1), ('සිත්හිලා', 1)]
  Target: 'මල්' -> Neighbors (Top 3): [('ගත්', 2), ('අත්', 2), ('ඇතිව', 2)]
  Target: 'වෙන' -> Neighbors (Top 3): [('නික්මුනු', 1), ('පස්සෙහි', 1), ('වඩනා', 1)]
  Target: 'දවස' -> Neighbors (Top 3): [('යටගිය', 2), ('ඵල', 1), ('භොජනය', 1)]
  Target: 'වී' -> Neighbors (Top 3): [('විජය', 2), ('රජ', 2), ('සෙනහ', 2)]
  Target: 'දත්' -> Neighbors (Top 3): [('යහන්', 1), ('මස්තකයෙහි', 1), ('හුන්නාහු', 1)]
  Target: 'මෙන්' -> Neighbors (Top 3): [('වඩනා', 2), ('චක්රවර්ති', 1), ('රජක්හුගේ', 1)]
  Target: 'දෙවියන්' -> Neighbors (Top 3): [('දෙනා', 2), ('දහසක්', 2), ('සිට', 2)]
  Target: 'සියලු' -> Neighbors (Top 3): [('වහන්සේ', 2), ('කල්පයෙක්', 1), ('වූයේය', 1)]
  Target: 'මහ' -> Neighbors (Top 3): [('වහන්සේ', 6), ('සුදර්ශන', 4), ('විහාරයෙහි', 4)]
  Target: 'සත්ව' -> Neighbors (Top 3): [('කෙලෙස්', 2), ('නැමති', 2), ('වෛද්යාචාරි', 1)]
  Target: 'වසන' -> Neighbors (Top 3): [('පිරිනිවී', 1), ('සියක්', 1), ('අවුරුදු', 1)]
  Target: 'සිටි' -> Neighbors (Top 3): [('වහන්සේ', 3), ('ලක්ෂයක්', 2), ('එකල', 2)]
  Target: 'සිත' -> Neighbors (Top 3): [('නොදැමිය', 1), ('හැකි', 1), ('මාතෘ', 1)]
  Target: 'ඊට' -> Neighbors (Top 3): [('සර්ව', 1), ('ලෝකයා', 1), ('ක්ෂාන්තිය', 1)]
  Target: 'හා' -> Neighbors (Top 3): [('වහන්සේ', 8), ('සමග', 6), ('සොරුන්', 4)]
  Target: 'කර' -> Neighbors (Top 3): [('භුවනෙකබාහු', 2), ('මනුසා', 2), ('සිත', 2)]
  Target: 'කිසි' -> Neighbors (Top 3): [('කීහ', 1), ('තව', 1), ('වර්', 1)]
  Target: 'එක' -> Neighbors (Top 3): [('බැලුම්', 1), ('බලා', 1), ('ප්රථම', 1)]
  Target: 'සමග' -> Neighbors (Top 3): [('වහන්සේ', 3), ('දසදහසක්', 3), ('සේක්', 3)]
  Target: 'මහත්' -> Neighbors (Top 3): [('පණ්ඩිතයෙනි', 2), ('නැවත', 2), ('උපන්', 2)]
  Target: 'සත්' -> Neighbors (Top 3): [('කුල', 2), ('ආයාසයක්', 2), ('පුරවන්නමුදු', 2)]
  Target: 'ඒ' -> Neighbors (Top 3): [('වහන්සේ', 24), ('සර්වඥයන්', 9), ('දොෂයෙක්', 8)]
  Target: 'කළ' -> Neighbors (Top 3): [('යනාදීන්', 3), ('ආරාධනා', 2), ('නොයෙක්', 2)]
  Target: 'ආ' -> Neighbors (Top 3): [('රජහුගේ', 2), ('නමැති', 2), ('ජම්බුද්වීපයෙහි', 1)]
  Target: 'එසේ' -> Neighbors (Top 3): [('ලදි', 3), ('ඉක්බිති', 2), ('නසී', 1)]
  Target: 'බලා' -> Neighbors (Top 3): [('ධර්ම', 3), ('දෝ', 2), ('වදාරා', 2)]
  Target: 'දක්වා' -> Neighbors (Top 3): [('කුල', 2), ('ජටිලයන්', 2), ('බ්රාහ්මණොත්තම', 1)]
  Target: 'බල' -> Neighbors (Top 3): [('සම්භාර', 1), ('ප්රධාන', 1), ('කියනුය', 1)]
  Target: 'යම්' -> Neighbors (Top 3): [('සියල්ල', 4), ('ආදී', 3), ('කෙනෙක්', 3)]
  Target: 'දී' -> Neighbors (Top 3): [('දෙසන', 8), ('ලද්දේද', 5), ('යන්නෙහි', 4)]
  Target: 'ආදි' -> Neighbors (Top 3): [('නොඉවසිය', 1), ('හැකි', 1), ('ඌෂෂ්ණයක්', 1)]
  Target: 'රැස්' -> Neighbors (Top 3): [('ලක්ෂයක්', 3), ('වහන්සේ', 3), ('දොළොස්', 2)]
  Target: 'දෙන' -> Neighbors (Top 3): [('කියනුයේ', 1), ('ඇවැත්නි', 1), ('සොක', 1)]
  Target: 'රජ' -> Neighbors (Top 3): [('බුදුන්', 5), ('විජය', 4), ('රජහු', 4)]
[15]:
  Target: 'වන' -> Neighbors (Top 3): [('නිති', 11), ('රත්න', 10), ('නොවී', 4)]
  Target: 'යන' -> Neighbors (Top 3): [('පදය', 28), ('සඳ', 11), ('පූර්ව', 9)]
  Target: 'එම' -> Neighbors (Top 3): [('තොප', 4), ('තුඩ', 4), ('සැප', 3)]
  Target: 'මා' -> Neighbors (Top 3): [('මිණි', 3), ('අධිපති', 1), ('මටම', 1)]
  Target: 'නැති' -> Neighbors (Top 3): [('අව්යාපජ්ජො', 3), ('විශෙෂයෙන්', 3), ('ව්යාපාද', 3)]
  Target: 'පමණ' -> Neighbors (Top 3): [('තොප', 4), ('සැප', 3), ('කුමට', 3)]
  Target: 'කියන' -> Neighbors (Top 3): [('ලදී', 5), ('භාවනා', 3), ('තමා', 3)]
  Target: 'එක්' -> Neighbors (Top 3): [('වැඩ', 2), ('මෛත්රී', 2), ('කැමැති', 1)]
  Target: 'කොට' -> Neighbors (Top 3): [('අන්ත', 6), ('නම්හුයි', 6), ('ප්රකාශ', 5)]
  Target: 'ඔහු' -> Neighbors (Top 3): [('වෙධිය', 1), ('පර්වතයට', 1), ('තමන්', 1)]
  Target: 'හට' -> Neighbors (Top 3): [('පූර්ව', 5), ('ස්වරය', 4), ('යුතුය', 3)]
  Target: 'සිට' -> Neighbors (Top 3): [('වැඳ', 4), ('ගත්තා', 2), ('බුදු', 2)]
  Target: 'මතු' -> Neighbors (Top 3): [('වැඩ', 3), ('යහලුව', 3), ('හස්න', 2)]
  Target: 'දැක' -> Neighbors (Top 3): [('සැදි', 4), ('බැඳී', 2), ('මිඳී', 2)]
  Target: 'ගිය' -> Neighbors (Top 3): [('තොරණ', 2), ('එළිකරතත්', 1), ('රන්', 1)]
  Target: 'ඇති' -> Neighbors (Top 3): [('අන්ත', 5), ('නම්හුයි', 5), ('රාජයන්ගේ', 4)]
  Target: 'දුක්' -> Neighbors (Top 3): [('සැප', 3), ('වේවයි', 2), ('තුමෝ', 2)]
  Target: 'ගුණ' -> Neighbors (Top 3): [('ගුණයයි', 7), ('නමැති', 6), ('තරසර', 5)]
  Target: 'ලද' -> Neighbors (Top 3): [('දක්වන', 6), ('තමා', 4), ('විභංග', 4)]
  Target: 'නිසි' -> Neighbors (Top 3): [('කාලෙපයක්', 1), ('වැනි', 1), ('වූ෴', 1)]
  Target: 'පුර' -> Neighbors (Top 3): [('වද්දන', 4), ('අපසර', 4), ('මිණි', 3)]
  Target: 'පද' -> Neighbors (Top 3): [('සඳ', 6), ('පරවිඳු', 4), ('අර්ථ', 3)]
  Target: 'කල' -> Neighbors (Top 3): [('පිපිපියුම්', 4), ('හිස', 4), ('තොප', 3)]
  Target: 'සතර' -> Neighbors (Top 3): [('තොප', 3), ('බ්රහ්ම', 2), ('අෂ්ටාදශ', 1)]
  Target: 'කී' -> Neighbors (Top 3): [('ථෙරො', 2), ('තෙරහු', 2), ('ලිය', 2)]
  Target: 'පළමු' -> Neighbors (Top 3): [('නොහැවිය', 2), ('යුතුයි', 2), ('දත', 2)]
  Target: 'ගත' -> Neighbors (Top 3): [('සැප', 3), ('නමස්කාර', 2), ('ඔප', 2)]
  Target: 'යනු' -> Neighbors (Top 3): [('පදය', 9), ('පදයි', 9), ('යනුද', 7)]
  Target: 'හෝ' -> Neighbors (Top 3): [('ප්රිය', 3), ('මෙත්', 2), ('ථෙරො', 2)]
  Target: 'එ' -> Neighbors (Top 3): [('ඔ', 3), ('මෙත්ත', 2), ('හ්රස්වයන්', 2)]
  Target: 'අප' -> Neighbors (Top 3): [('තොප', 4), ('වැනි', 3), ('ස්වකීය', 2)]
  Target: 'මේ' -> Neighbors (Top 3): [('මෙත්', 6), ('යුතුය', 5), ('මොවුන්', 5)]
  Target: 'අසා' -> Neighbors (Top 3): [('ස්ත්රී', 3), ('සිතින්', 3), ('කාවන්', 3)]
  Target: 'විසිනුදු' -> Neighbors (Top 3): [('ලෙව්හි', 1), ('පූජ්යව', 1), ('මහානුභාව', 1)]
  Target: 'නොව' -> Neighbors (Top 3): [('කරණය', 3), ('වෙතේයා', 2), ('කෙසේ', 1)]
  Target: 'නොයෙක්' -> Neighbors (Top 3): [('ගණන්', 4), ('දහස්', 2), ('සුවහස්', 2)]
  Target: 'නම්' -> Neighbors (Top 3): [('දක්වන', 7), ('සැහැලි', 6), ('රුවන්මල්', 5)]
  Target: 'ද' -> Neighbors (Top 3): [('ගරු', 9), ('කටයුතු', 8), ('දෙව්ලියෝ', 8)]
  Target: 'හැර' -> Neighbors (Top 3): [('තොප', 4), ('දිය', 2), ('මෙපුර', 2)]
  Target: 'යුතු' -> Neighbors (Top 3): [('තොමෝ', 3), ('දක්වමි', 2), ('තමහට', 2)]
  Target: 'මෙසේ' -> Neighbors (Top 3): [('ප්රිය', 3), ('වැඳ', 2), ('නොහැක්ක', 2)]
  Target: 'පැමිණි' -> Neighbors (Top 3): [('තොප', 4), ('ඔප', 3), ('වැඩි', 3)]
  Target: 'වූ' -> Neighbors (Top 3): [('නමැති', 42), ('ඇත්තා', 41), ('යුක්ත', 29)]
  Target: 'කාල' -> Neighbors (Top 3): [('තැන', 2), ('ශාසන', 1), ('දෙක', 1)]
  Target: 'විය' -> Neighbors (Top 3): [('නොහැක්ක', 16), ('බුදු', 7), ('රජ', 7)]
  Target: 'පෙර' -> Neighbors (Top 3): [('යනාදි', 2), ('සූත්රයෙන්', 2), ('ලදී', 1)]
  Target: 'මල්' -> Neighbors (Top 3): [('කලි', 2), ('ශබ්ද', 2), ('තොප', 1)]
  Target: 'වෙන' -> Neighbors (Top 3): [('සැප', 3), ('සබඳිනි', 2), ('කුමට', 2)]
  Target: 'දවස' -> Neighbors (Top 3): [('සිටිය', 1), ('සිටිනි', 1), ('අදහස', 1)]
  Target: 'වී' -> Neighbors (Top 3): [('නොවේද', 1), ('යත්', 1), ('ලෙ', 1)]
  Target: 'දත්' -> Neighbors (Top 3): [('කලාවන්', 3), ('පෙනුනු', 1), ('බිඹු', 1)]
  Target: 'මෙන්' -> Neighbors (Top 3): [('සපුමල්', 4), ('යුග්මය', 3), ('රණ්වණි', 3)]
  Target: 'දෙවියන්' -> Neighbors (Top 3): [('විඳ', 1), ('තමන්ගේ', 1), ('ආයු', 1)]
  Target: 'සියලු' -> Neighbors (Top 3): [('රත්න', 2), ('වර්ණ', 2), ('යුග්මය', 2)]
  Target: 'මහ' -> Neighbors (Top 3): [('තොප', 3), ('කළා', 3), ('නිවන්', 2)]
  Target: 'සත්ව' -> Neighbors (Top 3): [('තමා', 2), ('වැනි', 2), ('භයංකර', 1)]
  Target: 'වසන' -> Neighbors (Top 3): [('දොර', 1), ('කවුළු', 1), ('ආදියෙන්', 1)]
  Target: 'සිටි' -> Neighbors (Top 3): [('යළ', 4), ('යළි', 3), ('පිළි', 3)]
  Target: 'සිත' -> Neighbors (Top 3): [('වැඳ', 4), ('මෙත්තා', 2), ('වන්', 2)]
  Target: 'ඊට' -> Neighbors (Top 3): [('නිසාත්', 2), ('නොවන', 1), ('උපමාව', 1)]
  Target: 'හා' -> Neighbors (Top 3): [('උපදී', 7), ('සමාන', 6), ('කණ්ඨයෙන්', 6)]
  Target: 'කර' -> Neighbors (Top 3): [('පවර', 5), ('කොමල', 4), ('වද්දන', 3)]
  Target: 'කිසි' -> Neighbors (Top 3): [('කිරීමෙන්', 1), ('සිද්ධ', 1), ('කරන්නා', 1)]
  Target: 'එක' -> Neighbors (Top 3): [('නිවමින්', 3), ('සකල', 2), ('පැහැර', 2)]
  Target: 'සමග' -> Neighbors (Top 3): [('ලෙල', 3), ('දෙන', 3), ('ගිහිණි', 3)]
  Target: 'මහත්' -> Neighbors (Top 3): [('වැඳ', 2), ('මාර්ගය', 2), ('පලකළ', 2)]
  Target: 'සත්' -> Neighbors (Top 3): [('තොප', 3), ('සසර', 2), ('ලිය', 2)]
  Target: 'ඒ' -> Neighbors (Top 3): [('තැන', 5), ('ආරම්භ', 5), ('නියම්නෙනි', 4)]
  Target: 'කළ' -> Neighbors (Top 3): [('තොප', 2), ('සපුමල්', 2), ('අන්ය', 2)]
  Target: 'ආ' -> Neighbors (Top 3): [('හේ', 2), ('සෙනාව', 1), ('සමග', 1)]
  Target: 'එසේ' -> Neighbors (Top 3): [('වැඳ', 2), ('සපුමල්', 2), ('සියලු', 1)]
  Target: 'බලා' -> Neighbors (Top 3): [('වැද', 1), ('බුදුන්', 1), ('වැඳගෙන', 1)]
  Target: 'දක්වා' -> Neighbors (Top 3): [('නිසාත්', 2), ('අර්ථ', 2), ('ගුණෙන්', 2)]
  Target: 'බල' -> Neighbors (Top 3): [('වද්දන', 3), ('වැනි', 2), ('පල', 2)]
  Target: 'යම්' -> Neighbors (Top 3): [('නමස්කාර', 2), ('ප්රිය', 2), ('හි', 2)]
  Target: 'දී' -> Neighbors (Top 3): [('ලක්ෂණ', 2), ('තොප', 2), ('චක්ර', 1)]
  Target: 'ආදි' -> Neighbors (Top 3): [('යළ', 2), ('පූර්වයෙහි', 2), ('ශබ්දහා', 2)]
  Target: 'රැස්' -> Neighbors (Top 3): [('ලිය', 2), ('සුදු', 2), ('බුදු', 2)]
  Target: 'දෙන' -> Neighbors (Top 3): [('සිරි', 3), ('ඔප', 3), ('වැඩි', 3)]
  Target: 'රජ' -> Neighbors (Top 3): [('නොහැක්ක', 8), ('බුදු', 3), ('රත්න', 3)]
[16]:
  Target: 'වන' -> Neighbors (Top 3): [('උතුම්', 4), ('සිංහ', 3), ('වැඩ', 3)]
  Target: 'යන' -> Neighbors (Top 3): [('පවතින', 3), ('ලකුණු', 2), ('වෙන', 2)]
  Target: 'එම' -> Neighbors (Top 3): [('දිනෙක', 3), ('තුන', 2), ('නොච', 2)]
  Target: 'මා' -> Neighbors (Top 3): [('ආතුර', 1), ('සතහටද', 1), ('ඉටුකෘති', 1)]
  Target: 'නැති' -> Neighbors (Top 3): [('ලකුණු', 4), ('දුත', 2), ('අරිටුද', 2)]

In [64]:
final_filtered_results: Dict[str, Dict[str, T_Counter]] = {}

for century, cooccurrence_map in filtered_century_cooccurrence_results.items():
    
    # Filter the map to remove any target words found in the highly significant set
    doubly_filtered_map = {
        target_word: neighbors_counter
        for target_word, neighbors_counter in cooccurrence_map.items()
        if target_word not in highly_significant_word_set
    }
    
    # Only store the result if the map is not empty after filtering
    if doubly_filtered_map:
        final_filtered_results[century] = doubly_filtered_map

In [65]:
len(final_filtered_results[13].keys())

38

In [66]:
final_filtered_results[13]['සතර']

Counter({'ගණ': 5,
         'පර්වතය': 3,
         'භාගයෙහි': 3,
         'මනා': 3,
         'ඉෂ්ට': 3,
         'මෙසේයි': 3,
         'ඍතු': 3,
         'මණ්ඩලය': 2,
         'වැනි': 2,
         'භාගයෙන්': 2,
         'දෙභාගයෙක්': 2,
         'අක්': 2,
         'පතුල්': 2,
         'තුන්වන': 2,
         'ජංඝා': 2,
         'ප්රතිෂඨිත': 2,
         'ත්රිවිධ': 2,
         'යනාදි': 2,
         'සමාධි': 2,
         'උසස්': 2,
         'ස්ථානයකට': 2,
         'පැමිණේ': 2,
         'කිමවන': 2,
         'ලදී': 2,
         'අනිෂ්ට': 2,
         'දෙඅත්හි': 2,
         'ලුහු': 2,
         'දෙකින්': 2,
         'යන්නෙහි': 2,
         'පාරාජිකාවෝ': 2,
         'ච': 2,
         'හෘදය': 2,
         'ඉක්බිත්තෙන්': 2,
         'වා': 2,
         'ධාතූන්': 2,
         'සමුත්ථාන': 2,
         'රූපයො': 2,
         'වසයෙන්': 2,
         'සොළොස්': 2,
         'පැසුණු': 2,
         'හිමවත්': 1,
         'මෙරු': 1,
         'සුර්යය': 1,
         'චන්ද්ර': 1,
         'සපරිවාර': 1,
         'මහාද්වීපය': 1,
         'ස්පර්ෂත': 1,
         'සප්තරත්න': 1,
         'චක්රවර්තිය': 1,
         'දක්ෂිණා': 1,
         'වර්ණා': 1,
         'ශ්වෙතශංඛය': 1,
         'ස්වර්ණ': 1,
         'මතස්යයුගලය': 1,
         'චක්රායුධයසපත': 1,
         'සැසපීවාක්': 1,
         'බුදුනට': 1,
         'නොවෙයි': 1,
         'බුදුන්': 1,
         'පත්ලෙහි': 1,
         'හිදි': 1,
         'අගින්': 1,
         'වටා': 1,
         'තුබුවාක්': 1,
         'රක්ත': 1,
         'කම්බල': 1,
         'ගෙණ්ඩුකයක්': 1,
         'ශික්ෂාකල්ප': 1,
         'ව්යාකරණ': 1,
         'නිරුකතිච්ඡන්දො': 1,
         'විචිතිජ්යොතිෂ': 1,
         'ෂඩංගයෙන්': 1,
         'යුක්ත': 1,
         'වෙදයන්': 1,
         'ප්රධාන': 1,
         'අවෙද්ය': 1,
         'විද්යාස්ථාන': 1,
         'සම්බන්ධයෙන්': 1,
         'අග්රාම්ය': 1,
         'තත්තද්': 1,
         'කුමාරයන්ගේ': 1,
         'නැත්තම්හ': 1,
         'බා': 1,
         'සුව': 1,
         'විසුව': 1,
         'අපාය': 1,
         'හිස්': 1,
         'වුව': 1,
         'දෙව්': 1,
         'බඹ': 1,
         'ලෝ': 1,
         'පිරුණ': 1,
         'කම්මන්ත': 1,
         'මොහු': 1,
         'සම්මා': 1,
         'සංකප්ප': 1,
         'අවශිෂ්ට': 1,
         'ආර්ය': 1,
         'මාර්ග': 1,
         'ධර්මයො': 1,
         'එතෙන': 1,
         'අෂ්ටාංග': 1,
         'මාර්ගයෙන්': 1,
         'නිපාතය': 1,
         'සතිපට්ඨානා': 1,
         'බලා': 1,
         'යොදනු': 1,
         'මහ': 1,
         'සීවටන්': 1,
         'කෙනෙක්': 1,
         'ඇද්': 1,
         'සම්මප්පධානාදියෙ': 1,
         'දු': 1,
         'නය': 1,
         'විසින්ද': 1,
         'පරිත්ත': 1,
         'අප්පමාණාරම්මණ': 1,
         'සමාධිය': 1,
         'ධ්යානයට': 1,
         'අංගවන': 1,
         'චතුෂ්කනය': 1,
         'කීහු': 1,
         'භාගිය': 1,
         'ලකුණු': 1,
         'සරෙහි': 1,
         'තිබේ': 1,
         'එයින්': 1,
         'පළමුවෙනි': 1,
         'ගුරු': 1,
         'තුන්': 1,
         'බඳ': 1,
         'මීගණ': 1,
         'වනුයේ': 1,
         'ඉති': 1,
         'විශෙෂයෙන්': 1,
         'තැන්': 1,
         'පත්': 1,
         'මැදගුරු': 1,
         'හිරුගණ': 1,
         'නිරතුරු': 1,
         'ගිලන්': 1,
         'පීඩා': 1,
         'මාතිකා': 1,
         'සික්ඛා': 1,
         'ශික්ෂායි': 1,
         'කීයේ': 1,
         'මැනෝ': 1,
         'අනුක්ත': 1,
         'සමුච්චයාර්ථ': 1,
         'ශබ්දයෙන්': 1,
         'වක්ෂ්යමාන': 1,
         'උබ්හජානු': 1,
         'මණ්ඩලිකාදිප': 1,
         'සතරපදයකින්': 1,
         'කීහ': 1,
         'පදයෙන්': 1,
         'කීහයි': 1,
         'දත': 1,
         'නොපස්විකණ': 1,
         'සික': 1,
         'මහණ': 1,
         'වසන': 1,
         'රූපය': 1,
         'දකී': 1,
         'රූපයට': 1,
         'නිඃශ්රය': 1,
         'භූතානි': 1,
         'භූතයන්ද': 1,
         'භූත': 1,
         'නිස්සිතානි': 1,
         'චතුර්භූතයන්': 1,
         'පවත්නා': 1,
         'සෙසුපාදාය': 1,
         'සංඛෙපතො': 1,
         'විත්ථාරතො': 1,
         'සංක්ෂෙපයෙන්': 1,
         'විස්තරයෙන්': 1,
         'හො': 1,
         'චතස්සො': 1,
         'ධාතුයො': 1,
         'පරිගණ්හාති': 1,
         'පරිග්රහ': 1,
         'කෙරෙ෴': 1,
         'යොගිහට': 1,
         'යථා': 1,
         'ස්වභාව': 1,
         'ලක්ෂණ': 1,
         'පහළ': 1,
         'කර්ම': 1,
         'චර්මානන්තරගත': 1,
         'කෙශයෙහි': 1,
         'ධාතුහ': 1,
         'වර්ණ': 1,
         'ගන්ධය': 1,
         'රස': 1,
         'ඔජා': 1,
         'ජීවිතෙන්ද්රියය': 1,
         'කාය': 1,
         'සුසාළිස්': 1,
         'වෙත්෴': 1,
         'ස්වෙද': 1,
         'කඳුළු': 1,
         'කෙළය': 1,
         'මුකුණුය': 1,
         'චිත්තසමුත්ථානයන්': 1,
         'දෙදෙ': 1,
         'ඔජොෂ්ටමකයන්ගෙ': 1,
         'වෙති': 1,
         'අහරය': 1,
         'අහර': 1,
         'පූයා': 1,
         'මූත්ර': 1,
         'සමුත්ථානයන්': 1,
         'වසෙන': 1,
         'ඔජොෂ්ටමකයාගෙ': 1,
         'අට': 1})

In [67]:
final_filtered_results[16]['මල්']

Counter({'යක්': 2,
         'මනෝ': 1,
         'රෝගෙට': 1,
         'වේය': 1,
         'අවුසද': 1,
         'අකුරෙව්': 1,
         'සතර': 1,
         'දක්වා': 1,
         'මෙයින්': 1,
         'අනතුර': 1,
         'පලුගත්': 1,
         'පතර': 1,
         'තුරක්ෂ': 1,
         'දක්වනෙම්': 1,
         'ගෙනහැර': 1,
         'දුත': 1,
         'ලකුණුයන': 1,
         'පෙර': 1,
         'මග': 1,
         'ඇදුරාටද': 1,
         'පසු': 1,
         'දෙනක්හෝ': 1,
         'දි': 1,
         'කක්': 1,
         'සුදු': 1,
         'දමක්හෝ': 1,
         'ගජසිඳු': 1,
         'ගොනෙක්': 1,
         'පිරිකුඹු': 1,
         'බෙරක්හෝ': 1,
         'නිළ': 1,
         'නිසි': 1})

In [68]:
final_filtered_results[13]['මල්']

Counter({'නැමැති': 4,
         'අතුපතර': 1,
         'ත්රිවිධ': 1,
         'චර්යයා': 1,
         'පල්ලව': 1,
         'අභිඥා': 1,
         'බොධිසම්භාර': 1,
         'කප්රුක': 1,
         'සර්වඥතා': 1,
         'ඥාන': 1,
         'අමාඵල': 1,
         'ගන්වයි': 1,
         'බුදුවෙයි': 1})

In [69]:
final_filtered_results[18]['මල්']

Counter({'බඳු': 5,
         'වුවමනා': 4,
         'නිල්': 3,
         'තන්හි': 3,
         'පැහැය': 3,
         'රන්වන්': 3,
         'බුදුන්ගේ': 2,
         'ලක්ෂණයෙන්': 2,
         'දිය': 2,
         'බෙරලිය': 2,
         'කිණිහිරි': 2,
         'ජංඝාව': 1,
         'හාත්පසින්': 1,
         'පිරි': 1,
         'ගිය': 1,
         'හැගැබිසෙයින්': 1,
         'සම්': 1,
         'පූර්ණය': 1,
         'වටවූ': 1,
         'තැඹිලි': 1,
         'කැකුළු': 1,
         'සෙයින්': 1,
         'සම්පූර්ණ': 1,
         'ජංඝාවන්': 1,
         'එනිජංඝා': 1,
         'ස්වර': 1,
         'කරවීක': 1,
         'භාණි': 1,
         'සුදු': 1,
         'තන්හී': 1,
         'දහවත්තරු': 1})

In [70]:
final_filtered_results[19]['සතර']

Counter({'පාද': 8,
         'රූප': 4,
         'තැනින්': 3,
         'සතරවන': 3,
         'ස්ථානයකින්': 3,
         'උගුළුවාගෙන': 3,
         'සම': 3,
         'යුගලයෙහි': 3,
         'කව්': 3,
         'අයිති': 3,
         'ස්කන්ධ': 3,
         'නාම': 3,
         'දෙකට': 3,
         'විෂමපාදය': 2,
         'දෙයානුවන': 2,
         'සමපාදය': 2,
         'වර්ණයකින්': 2,
         'පරව': 2,
         'ජගණයක්': 2,
         'පාදය': 2,
         'දෙක': 2,
         'අනුවන': 2,
         'යනාදි': 2,
         'පාඨයෙන්': 2,
         'කීවොත්': 2,
         'විඤ්ඤාණයට': 2,
         'තිස්වන': 1,
         'තුන්වන': 1,
         'කොටගෙන': 1,
         'පථ්යාව': 1,
         'කත්ර': 1,
         'අසම': 1,
         'ආද්යන්තලඝු': 1,
         'ගුරුද්වය': 1,
         'භගණජගණද්වයකින්': 1,
         'සම්බන්ධ': 1,
         'වු': 1,
         'ගණ': 1,
         'අටකින්ද': 1,
         'අක්ෂර': 1,
         'දෙතිසකින්ද': 1,
         'මාත්රා': 1,
         'එකුන්': 1,
         'පණසකින්ද': 1,
         'ගුරු': 1,
         'වියරණට': 1,
         'පොත්': 1,
         'පත්': 1,
         'සදා': 1,
         'නෙක': 1,
         'විසුරුවාමෙම': 1,
         'මුළු': 1,
         'ලක': 1,
         'ආගම්': 1,
         'නසන්නට': 1,
         'තැත්කරතිනොවැසැ': 1,
         'සැඩ': 1,
         'විසැති': 1,
         'නාරද': 1,
         'පෙණය': 1,
         'සොඳ': 1,
         'ඩැහැගෙණ': 1,
         'කැබිලිතිද': 1,
         'ගැරඬි': 1,
         'උඩගුව': 1,
         'පෙණ': 1,
         'දත්': 1,
         'කිවිඳුන්': 1,
         'කිවිව්පද': 1,
         'බඳිත': 1,
         'පැහැදුන්': 1,
         'උපදෙසිනි': 1,
         'අවිදුන්': 1,
         'සඳන්': 1,
         'වරදක්': 1,
         'ඇතිවන': 1,
         'අඟ': 1,
         'නන්': 1,
         'දෙදෙන': 1,
         'ඉගෙණ': 1,
         'ගත්': 1,
         'හැටි': 1,
         'නොහොබි': 1,
         'දෙදෙනෙත්ව': 1,
         'තුට': 1,
         'සඳද': 1,
         'පඬිනට': 1,
         'සත්': 1,
         'මගෙහි': 1,
         'මනනද': 1,
         'නොවන': 1,
         'දනු': 1,
         'නැණින්පිරිසිඳ': 1,
         'දෙකේකී': 1,
         'පා': 1,
         'නිසකී': 1,
         'කවුඩාට': 1,
         'මිසකී': 1,
         'මුවාහට': 1,
         'මසකී': 1,
         'සතරක්': 1,
         'බොලඳ': 1,
         'දිගු': 1,
         'සක': 1,
         'මහත්': 1,
         'වරද': 1,
         'වෙයිම': 1,
         'යන්නෙන්': 1,
         'එකක': 1,
         'නොදත්': 1,
         'අඟන්නෝ': 1,
         'මෙලක': 1,
         'ගණි': 1,
         'සලෙල': 1,
         'දන': 1,
         'සිත්': 1,
         'බොරු': 1,
         'කවියෙහි': 1,
         'වුන': 1,
         'හටු': 1,
         'පදෙස්': 1,
         'සඳ': 1,
         'අමන': 1,
         'මග': 1,
         'තොරතුරු': 1,
         'කිසි': 1,
         'ලෙසින': 1,
         'රණ': 1,
         'හොඳද': 1,
         'අඟන': 1,
         'වනොද්යානයෙහිදී': 1,
         'ප්රසුතව': 1,
         'ක්රමයෙන්': 1,
         'වැඩී': 1,
         'රජ': 1,
         'සිරි': 1,
         'පැමිණ': 1,
         'උයන්': 1,
         'කෙළියට': 1,
         'නික්ම': 1,
         'පූර්ව': 1,
         'නිමිති': 1,
         'ගිහිගෙහි': 1,
         'කලකිරී': 1,
         'යනාදීන්': 1,
         'වර්ණනීය': 1,
         'අද්භූත': 1,
         'රාජ': 1,
         'තිබෙනවාය': 1,
         'වෙදනා': 1,
         'සඤ්ඤා': 1,
         'සංඛාර': 1,
         'ඇතුළත්': 1,
         'මිලින්ද': 1,
         'ප්රශ්නයේ': 1,
         'අයිතිය': 1,
         'මෙයින්': 1,
         'පමණක්': 1,
         'විඤ්ඤාණස්කන්ධය': 1,
         'නැතැයි': 1,
         'නාමරූප': 1,
         'නැතුව': 1,
         'පවතින්ට': 1,
         'නුපුළුවන්': 1,
         'සංයුන්': 1,
         'සඟියේ': 1,
         'රූපාදි': 1,
         'විඤ්ඤාණයාගේ': 1,
         'චුති': 1,
         'උත්පත්තියක්': 1,
         'පෙන්වන්ට': 1,
         'පුළුවනැයි': 1,
         'නුපුළුවනැයි': 1})

In [71]:
records = []
for century in centuries_to_compare:
    for target_word, neighbors_counter in final_filtered_results[century].items():
        for neighbor_word, count in neighbors_counter.items():
            records.append({
                'target_word': target_word,
                'collocate_word': neighbor_word,
                'cooccurrence_count': count
            })
    temp_df = pd.DataFrame(records)
    temp_df.to_csv(f'Collocates/collocates_{century}th_century.csv', index=False, encoding='utf-8-sig')

In [72]:
TARGET_WORD = 'සතර'
records: List[Dict[str, Any]] = []

In [73]:
common_keys = list(final_filtered_results[13].keys())

In [74]:
final_filtered_results[13].items()

dict_items([('සිට', Counter({'මාරවිජය': 1, 'සර්වඥපදප්රාප්ත': 1, 'වැ': 1, 'හුනස්නෙන්': 1, 'නැඟී': 1, 'පූර්වොත්තර': 1, 'දිශා': 1, 'භාගයෙහි': 1, 'වැඩ': 1, 'සප්තාහයක්': 1, 'අනිමිසලෝචන': 1, 'යුගලයෙන්': 1, 'පුදන': 1, 'ජය': 1, 'බොධිය': 1, 'තත': 1, 'ප්රභව': 1, 'දෙසන': 1, 'ලදි': 1, 'ගාථායෙහි': 1, 'සංක්ෂෙප': 1, 'වර්ණනා': 1, 'යන්නෙහි': 1, 'ශීලයෙහි': 1, 'ශීලය': 1, 'පුරන්නෙ': 1, 'සර්ව': 1, 'භාගයෙන්': 1, 'සංවරණය': 1, 'කරන්': 1, 'ව්යතික්රම': 1, 'නොකරන්නේය': 1, 'ආරාමාදි': 1, 'වස්තුව': 1, 'සොර': 1, 'සිතින්': 1, 'සටන්': 1, 'බැණ': 1, 'ගණී': 1, 'යමින්': 1, 'ගනී': 1, 'තමා': 1, 'නගා': 1, 'තුබුවා': 1, 'මම්': 1, 'නොගන්මි': 1, 'යනා': 1, 'දීන්': 1})), ('මතු', Counter({'වැසී': 4, 'පැවැති': 4, 'ගේ': 3, 'වතුරින්': 3, 'වන්නට': 3, 'නැමැති': 2, 'මෙයින්': 2, 'නොවෙයි': 2, 'සමාධි': 2, 'ධර්ම': 2, 'යනාදි': 2, 'පදාර්ථ': 2, 'ආයේ': 2, 'අවදියෙකි': 2, 'කලක්': 2, 'පැවැතී': 2, 'ගත්': 2, 'පියෙසෙක්හි': 2, 'සරියේ': 2, 'මිනිසා': 2, 'වැඩට': 2, 'සුජාත': 1, 'මවු': 1, 'පිය': 1, 'පක්ෂ': 1, 'ජාතිවාදයෙන්': 1, 'අකලිෂ්ට': 1, 'ඇතිවන': 1, 'දෙතිස්': 1, 'පුරුෂ': 1, 'ලක්ෂණයෙන්': 1, 'අශිත්යනු': 1, 'ව්යඤ්ජනයෙන්': 1, 'කෙතුමාලායෙන්': 1, 'බ්යාමප්රභායෙන්': 1, 'මනොහර': 1, 'බුදු': 1, 'බවට': 1, 'මූණලා': 1, 'මුණින්': 1, 'වැදහෙව': 1, 'තිලෝගුරු': 1, 'බුදුන්ගෙන්ද': 1, 'තෙමේ': 1, 'එන': 1, 'දවස': 1, 'සිල්': 1, 'පොළොව': 1, 'ප්රතිඥා': 1, 'මුල්': 1, 'සිහි': 1, 'අර්ථණාවට': 1, 'උපකාරක': 1, 'නානාවජ්ජනොපචාරයාගෙද': 1, 'සංග්රහය': 1, 'දත': 1, 'එකාවර්ජනොපචාරයාගෙ': 1, 'හඟවනේ': 1, 'උපචාර': 1, 'අනන්තර': 1, 'ප්රත්යයෙන්': 1, 'ප්රත්යය': 1, 'සෘද්ධිවිධ': 1, 'ඥානය': 1, 'කුදු': 1, 'වැළිත්': 1, 'අනිකුදු': 1, 'විශිෂ්ට': 1, 'ඇතැයි': 1, 'මත්තෙහි': 1, 'ප්රණීත': 1, 'ප්රණීතතර': 1, 'දේශනාව': 1, 'පිණිස': 1, 'සො': 1, 'එවං': 1, 'සමාහිතෙ': 1, 'පිණ්ඩාර්ථ': 1, 'නිර්ධාරණය': 1, 'සම්බන්ධාභිප්රාය': 1, 'විභාවනය': 1, 'යනාදී': 1, 'චොදනාය': 1, 'එයින්': 1, 'ශොධනායී': 1, 'ප්රඥා': 1, 'කථායෙහි': 1, 'විසර්ජනය': 1, 'පෘච්ඡා': 1, 'ව්යාකරණ': 1, 'සමර්ථතාව': 1, 'එළවනුවූ': 1, 'යනාදිස්තුතිය': 1, 'පූර්වාංග': 1, 'මකොට': 1, 'යථාභිප්රෙතවර්ණනාව': 1, 'කරනුපිණිස': 1, 'කීහු': 1, 'සන්ය': 1, 'ටීකා': 1, 'තුබූ': 1, 'ප්රසන්න': 1, 'වචනයෙන්': 1, 'සාභිප්රාය': 1, 'වර්ණනා': 1, 'කරනු': 1, 'අතිනි': 1, 'මහ': 1, 'බිමක්': 1, 'ගත්තා': 1, 'සේපර': 1, 'සතුරු': 1, 'උවදුරින්': 1, 'ලක්දිව': 1, 'ඉන්': 1, 'මිදෙන්නට': 1, 'ගෙනැ': 1, 'සියල්ල': 1, 'නැසී': 1, 'ඇත්තා': 1})), ('ගිය', Counter({'කප්': 2, 'අසංඛ්යයක්': 2, 'මුදුනෙහි': 1, 'තුබූ': 1, 'පය': 1, 'වප්': 1, 'මඟුලෙහි': 1, 'වැඩහුන්': 1, 'තැනය': 1, 'හැරැ': 1, 'දඹ': 1, 'සේය': 1, 'එකුන්': 1, 'තිස්': 1, 'හවුරුද්දක්': 1, 'හිඳු': 1, 'ඇඹේණියෝ': 1, 'නික්මුණු': 1, 'සමය': 1, 'සහිතව': 1, 'හැරුණු': 1, 'දොර': 1, 'රෑ': 1, 'ගමන': 1, 'පෙරළා': 1, 'බැලූ': 1, 'නුවර': 1, 'පිනූ': 1, 'ගඟය': 1, 'වැඩසිටි': 1, 'වැල්ල': 1, 'උපාසිකාවෝ': 1, 'වැඩ': 1, 'හෙවැ': 1, 'පිරිනිවන්': 1, 'පෑ': 1, 'සල්වනය': 1, 'ශරීරයෙන්': 1, 'විසිර': 1, 'ධාතු': 1, 'වැළඳු': 1, 'පාත්රය': 1, 'පියවර': 1, 'එබූ': 1, 'තැන': 1, 'යනාදියෙහි': 1, 'සමණ': 1, 'දෙනාත්': 1, 'හැරගෙන': 1, 'නිවන්පුර': 1, 'වදනට': 1, 'සොයන': 1, 'කුසල්': 1, 'මඟ': 1, 'සාරාසැකි': 1, 'කප්සුවහස්': 1, 'කලටමුත්': 1, 'අතුර': 1, 'මුළුලු': 1, 'නොවන': 1, 'නියාවට': 1, 'දෘෂ්ටාන්තයා': 1, 'ඉදිකරන්ට': 1, 'පටන්ගත්': 1, 'මං': 1, 'ගසෙක': 1, 'යනාදීන්': 1, 'ඔබගෙන්': 1, 'විවරණ': 1, 'ලදින්': 1, 'නැවත': 1, 'ඔබට': 1, 'ඉක්බිතිව': 1, 'කලට': 1, 'තුන්': 1, 'තවත්': 1, 'කල්ප': 1, 'ලක්ෂයක්': 1, 'තිබියදී': 1, 'පැරුම්': 1})), ('දුක්', Counter({'නිවන්': 4, 'සසර': 3, 'වැ': 2, 'සිටියේ': 2, 'නැමැති': 2, 'අතට': 1, 'පත්': 1, 'පියා': 1, 'සතුන්': 1, 'සඳහා': 1, 'විඳුනා': 1, 'ගෙන': 1, 'භව': 1, 'දුර්ගයට': 1, 'වැද': 1, 'පැරුම්': 1, 'පුරා': 1, 'තු': 1, 'පුර': 1, 'තෙමේ': 1, 'දුඃඛ': 1, 'කාරණය': 1, 'නොවෙයි': 1, 'යත්': 1, 'නොවේ': 1, 'මැයි': 1, 'සියලු': 1, 'පිරු': 1, 'නිධානය': 1, 'මරහට': 1, 'ගොදුරු': 1, 'වැනි': 1, 'වියතක්': 1, 'සුදුසු': 1, 'ලොවෙහි': 1, 'දෙයක්': 1, 'එයට': 1, 'ප්රති': 1, 'පක්ෂ': 1, 'සුව': 1, 'නැතිව': 1, 'කුසල්': 1, 'නැවු': 1, 'නට': 1, 'මුහුදු': 1, 'ගැලී': 1, 'ගන්නා': 1, 'මඳ': 1, 'දෙනකු': 1, 'නොව': 1, 'සූවිසි': 1, 'අසංඛ්ය': 1, 'යක්': 1, 'සත්වයන්': 1, 'ඇරලා': 1, 'තනිව': 1, 'ස්ත්රීන්': 1, 'පරිද්දෙන්': 1, 'ලබන': 1, 'රස': 1, 'සලකා': 1, 'ඇස': 1, 'පහරනා': 1, 'රුජාවෙන්': 1, 'නොසැලකු': 1, 'චක්ඛුපාල': 1, 'මහ': 1, 'තෙරුන්': 1, 'වහන්සේගේ': 1, 'වස්තුවෙහි': 1, 'මහවත්ව': 1, 'සිටිනා': 1})), ('නිසි', Counter({'උපදෙස්': 2, 'පෙදෙන්': 1, 'යුත්': 1, 'ගාථා': 1, 'මාත්රයක්': 1, 'අසා': 1, 'සව්': 1, 'කෙලෙස්': 1, 'නසා': 1, 'ගෙවා': 1, 'රහත්වන්ට': 1, 'පින්කම්': 1, 'ඇතත්': 1, 'සියල්ලවුන්': 1, 'කරුණාවෙන්': 1, 'සායෙහි': 1, 'බතක්': 1, 'බොහෝ': 1, 'පරලොව': 1, 'යන්නාහු': 1, 'මස්සක්': 1, 'විචාරත්': 1, 'නොගෙන': 1, 'ගියහ': 1, 'උන්': 1, 'හැම': 1, 'හැරගෙන': 1, 'යන්ට': 1, 'නොදැන': 1, 'ගෙන': 1, 'ගියත්': 1, 'දන්නා': 1, 'වස්තුව': 1})), ('පුර', Counter({'පැමිණ': 2, 'දුක්': 1, 'නිවන්': 1, 'ගෙන': 1, 'භව': 1, 'දුර්ගයට': 1, 'වැද': 1, 'පැරුම්': 1, 'පුරා': 1, 'තු': 1, 'දසදහස්': 1, 'ලෝදාහි': 1, 'දෙව්බඹුන්ගේ': 1, 'අයජ': 1, 'කිඹුල්වත්හි': 1, 'ඉපද': 1, 'වැඩිවිය': 1, 'රත්නයෙන්': 1, 'සමුගත': 1, 'ප්රභා': 1, 'සාකල්යයෙන්': 1, 'වර්ණ': 1, 'භෙද': 1, 'සම්බන්ධයට': 1, 'පමුණුවන': 1, 'මස්තකා': 1, 'කාශ': 1, 'දෙශයෙන්': 1, 'හෙබි': 1, 'සර්ව': 1, 'කාලීන': 1, 'සෞභාග්ය': 1, 'කණාට': 1, 'කැරැලි': 1, 'අක්හි': 1, 'පියුම්රා': 1, 'මිණින්ගේ': 1, 'ශොභායෙන්': 1, 'ඔවිදුනා': 1, 'ලද්දා': 1, 'චන්ද්ර': 1, 'තෙමේ': 1, 'ස්ත්රීන්ගේ': 1, 'මුඛයෙන්': 1, 'පරිභව': 1, 'ඇත්තේ': 1, 'රොෂයෙන්': 1, 'රත්': 1, 'බවට': 1, 'රාත්රියෙහිලා': 1, 'බමන්නා': 1, 'අංගනා': 1, 'ජනයා': 1, 'රොෂ': 1, 'හර්ෂ': 1, 'දෙක': 1, 'කළෝද': 1, 'වර්ණනා': 1, 'නිමි': 1, 'දශරථය': 1, 'භූබර්තෘයෙක්': 1, 'අයොධ්යා': 1})), ('පද', Counter({'නාම': 7, 'පදය': 7, 'එයින්': 7, 'කීහ': 7, 'ආඛ්යාත': 5, 'උපසර්ග': 5, 'ක්රියාවාචක': 4, 'පදයන්': 3, 'චතුර්විධ': 3, 'නිපාතපදයි': 3, 'සර්වාර්ථයන්': 3, 'නමන්නෙන්': 3, 'කරනු': 2, 'ලැබේ': 2, 'යස්ස': 2, 'නාමපදයි': 2, 'කවරයත්': 2, 'ක්රියා': 2, 'ද්යෝතක': 2, 'තුන්': 1, 'බොධීන්ගේ': 1, 'වංශයෙහි': 1, 'සහස්රරශ්මින්': 1, 'විභක්ත': 1, 'අතුරෙහි': 1, 'පරිකථානුකූල': 1, 'ගෙන': 1, 'වර්ණනා': 1, 'දක්වන': 1, 'පදයන්ගේ': 1, 'ආද්යන්ත': 1, 'මධ්යයෙහි': 1, 'පවතීද': 1, 'අර්ථයි': 1, 'සමාධිහුගෙ': 1, 'ලක්ඛණ': 1, 'රස': 1, 'ලක්ෂණය': 1, 'රසය': 1, 'ප්රත්යුපස්ථානය': 1, 'ස්ථාකය': 1, 'මොහු': 1, 'කවරහ': 1, 'සමාධිය': 1, 'කති': 1, 'ප්රකාර': 1})), ('සතර', Counter({'ගණ': 5, 'පර්වතය': 3, 'භාගයෙහි': 3, 'මනා': 3, 'ඉෂ්ට': 3, 'මෙසේයි': 3, 'ඍතු': 3, 'මණ්ඩලය': 2, 'වැනි': 2, 'භාගයෙන්': 2, 'දෙභාගයෙක්': 2, 'අක්': 2, 'පතුල්': 2, 'තුන්වන': 2, 'ජංඝා': 2, 'ප්රතිෂඨිත': 2, 'ත්රිවිධ': 2, 'යනාදි': 2, 'සමාධි': 2, 'උසස්': 2, 'ස්ථානයකට': 2, 'පැමිණේ': 2, 'කිමවන': 2, 'ලදී': 2, 'අනිෂ්ට': 2, 'දෙඅත්හි': 2, 'ලුහු': 2, 'දෙකින්': 2, 'යන්නෙහි': 2, 'පාරාජිකාවෝ': 2, 'ච': 2, 'හෘදය': 2, 'ඉක්බිත්තෙන්': 2, 'වා': 2, 'ධාතූන්': 2, 'සමුත්ථාන': 2, 'රූපයො': 2, 'වසයෙන්': 2, 'සොළොස්': 2, 'පැසුණු': 2, 'හිමවත්': 1, 'මෙරු': 1, 'සුර්යය': 1, 'චන්ද්ර': 1, 'සපරිවාර': 1, 'මහාද්වීපය': 1, 'ස්පර්ෂත': 1, 'සප්තරත්න': 1, 'චක්රවර්තිය': 1, 'දක්ෂිණා': 1, 'වර්ණා': 1, 'ශ්වෙතශංඛය': 1, 'ස්වර්ණ': 1, 'මතස්යයුගලය': 1, 'චක්රායුධයසපත': 1, 'සැසපීවාක්': 1, 'බුදුනට': 1, 'නොවෙයි': 1, 'බුදුන්': 1, 'පත්ලෙහි': 1, 'හිදි': 1, 'අගින්': 1, 'වටා': 1, 'තුබුවාක්': 1, 'රක්ත': 1, 'කම්බල': 1, 'ගෙණ්ඩුකයක්': 1, 'ශික්ෂාකල්ප': 1, 'ව්යාකරණ': 1, 'නිරුකතිච්ඡන්දො': 1, 'විචිතිජ්යොතිෂ': 1, 'ෂඩංගයෙන්': 1, 'යුක්ත': 1, 'වෙදයන්': 1, 'ප්රධාන': 1, 'අවෙද්ය': 1, 'විද්යාස්ථාන': 1, 'සම්බන්ධයෙන්': 1, 'අග්රාම්ය': 1, 'තත්තද්': 1, 'කුමාරයන්ගේ': 1, 'නැත්තම්හ': 1, 'බා': 1, 'සුව': 1, 'විසුව': 1, 'අපාය': 1, 'හිස්': 1, 'වුව': 1, 'දෙව්': 1, 'බඹ': 1, 'ලෝ': 1, 'පිරුණ': 1, 'කම්මන්ත': 1, 'මොහු': 1, 'සම්මා': 1, 'සංකප්ප': 1, 'අවශිෂ්ට': 1, 'ආර්ය': 1, 'මාර්ග': 1, 'ධර්මයො': 1, 'එතෙන': 1, 'අෂ්ටාංග': 1, 'මාර්ගයෙන්': 1, 'නිපාතය': 1, 'සතිපට්ඨානා': 1, 'බලා': 1, 'යොදනු': 1, 'මහ': 1, 'සීවටන්': 1, 'කෙනෙක්': 1, 'ඇද්': 1, 'සම්මප්පධානාදියෙ': 1, 'දු': 1, 'නය': 1, 'විසින්ද': 1, 'පරිත්ත': 1, 'අප්පමාණාරම්මණ': 1, 'සමාධිය': 1, 'ධ්යානයට': 1, 'අංගවන': 1, 'චතුෂ්කනය': 1, 'කීහු': 1, 'භාගිය': 1, 'ලකුණු': 1, 'සරෙහි': 1, 'තිබේ': 1, 'එයින්': 1, 'පළමුවෙනි': 1, 'ගුරු': 1, 'තුන්': 1, 'බඳ': 1, 'මීගණ': 1, 'වනුයේ': 1, 'ඉති': 1, 'විශෙෂයෙන්': 1, 'තැන්': 1, 'පත්': 1, 'මැදගුරු': 1, 'හිරුගණ': 1, 'නිරතුරු': 1, 'ගිලන්': 1, 'පීඩා': 1, 'මාතිකා': 1, 'සික්ඛා': 1, 'ශික්ෂායි': 1, 'කීයේ': 1, 'මැනෝ': 1, 'අනුක්ත': 1, 'සමුච්චයාර්ථ': 1, 'ශබ්දයෙන්': 1, 'වක්ෂ්යමාන': 1, 'උබ්හජානු': 1, 'මණ්ඩලිකාදිප': 1, 'සතරපදයකින්': 1, 'කීහ': 1, 'පදයෙන්': 1, 'කීහයි': 1, 'දත': 1, 'නොපස්විකණ': 1, 'සික': 1, 'මහණ': 1, 'වසන': 1, 'රූපය': 1, 'දකී': 1, 'රූපයට': 1, 'නිඃශ්රය': 1, 'භූතානි': 1, 'භූතයන්ද': 1, 'භූත': 1, 'නිස්සිතානි': 1, 'චතුර්භූතයන්': 1, 'පවත්නා': 1, 'සෙසුපාදාය': 1, 'සංඛෙපතො': 1, 'විත්ථාරතො': 1, 'සංක්ෂෙපයෙන්': 1, 'විස්තරයෙන්': 1, 'හො': 1, 'චතස්සො': 1, 'ධාතුයො': 1, 'පරිගණ්හාති': 1, 'පරිග්රහ': 1, 'කෙරෙ෴': 1, 'යොගිහට': 1, 'යථා': 1, 'ස්වභාව': 1, 'ලක්ෂණ': 1, 'පහළ': 1, 'කර්ම': 1, 'චර්මානන්තරගත': 1, 'කෙශයෙහි': 1, 'ධාතුහ': 1, 'වර්ණ': 1, 'ගන්ධය': 1, 'රස': 1, 'ඔජා': 1, 'ජීවිතෙන්ද්රියය': 1, 'කාය': 1, 'සුසාළිස්': 1, 'වෙත්෴': 1, 'ස්වෙද': 1, 'කඳුළු': 1, 'කෙළය': 1, 'මුකුණුය': 1, 'චිත්තසමුත්ථානයන්': 1, 'දෙදෙ': 1, 'ඔජොෂ්ටමකයන්ගෙ': 1, 'වෙති': 1, 'අහරය': 1, 'අහර': 1, 'පූයා': 1, 'මූත්ර': 1, 'සමුත්ථානයන්': 1, 'වසෙන': 1, 'ඔජොෂ්ටමකයාගෙ': 1, 'අට': 1})), ('පළමු', Counter({'ගාථාව': 5, 'පෘච්ඡා': 4, 'විසර්ජන': 3, 'බල': 2, 'විසර්ජනය': 2, 'පූර්වාංග': 2, 'මනුයි': 2, 'කියයුත්තෙහි': 2, 'කුමක්': 2, 'මාත්සර්යය': 1, 'මුඹ': 1, 'බෝ': 1, 'මැඩෙහි': 1, 'ගන්නා': 1, 'සර්වඥතාඥාන': 1, 'නැමැති': 1, 'කල්ප': 1, 'වෘක්ෂයෙහි': 1, 'බිජුවට': 1, 'හිඳු': 1, 'තෝතැන්න': 1, 'බඳු': 1, 'අමර': 1, 'පුරවර': 1, 'ස්පඨිත': 1, 'ලද්දාහට': 1, 'අසකර': 1, 'වඩනේ': 1, 'ආයුස්': 1, 'සංස්කාරය': 1, 'වර්ධනය': 1, 'කරන්නේයි': 1, 'ගුරු': 1, 'ලුහු': 1, 'යුවලෙක්': 1, 'වනේ': 1, 'සඳ': 1, 'ගණ': 1, 'යස': 1, 'රුසිරු': 1, 'වඩා': 1, 'තාව': 1, 'ආරභිස්සාම': 1, 'ප්රඥා': 1, 'භාවනා': 1, 'කථා': 1, 'වට': 1, 'අවසරය': 1, 'සම්ප්රාප්තව': 1, 'ඇතුදු': 1, 'ඉන්': 1, 'අභිඥා': 1, 'කථාව': 1, 'ආරම්භ': 1, 'කරන්නෙමු': 1, 'අභිප්රාය': 1, 'යි෴': 1, 'භගවතා': 1, 'පඤ්ච': 1, 'උක්කමනං': 1, 'උල්ලංඝනය': 1, 'කිරීම': 1, 'කසිණුක්කන්තිකං': 1, 'නාම': 1, 'කසිණොත්': 1, 'ක්රාන්තික': 1, 'නම෴': 1, 'නියෙන්ම': 1, 'කසිණුක්කන්තිකයෙහි': 1, 'ආපොකසිණාදි': 1, 'මූලික': 1, 'යොජනාව': 1, 'කටයුතු': 1, 'එසෙම': 1, 'යත්': 1, 'තදර්ථය': 1, 'මංගල': 1, 'පූර්වංගම': 1, 'කොටම': 1, 'දක්වනුවෝ': 1, 'කියනු': 1, 'ලබන': 1, 'ස්තුත්යාකාරයට': 1, 'කාරණො': 1, 'ඬාරණය': 1, 'කරනු': 1, 'පිණිස': 1, 'නික්ෂෙප': 1, 'ගාථාවට': 1, 'නිදාන': 1, 'වොදනා': 1, 'මුඛයෙන්': 1, 'යානිකයා': 1, 'සොපචාර': 1, 'ධ්යන්හි': 1, 'පිහිටා': 1, 'විදර්ශනායෙහි': 1, 'යෙදෙනුයෙ': 1, 'ශමථ': 1, 'යානික': 1, 'භවාග්ර': 1, 'ධර්මයන්': 1, 'කර්මිකයා': 1, 'දුෂ්පරි': 1, 'ග්රහ': 1})), ('ගත', Counter({'පාද': 2, 'මිහි': 2, 'අර්ථ': 2, 'ගතකුර': 2, 'යුතුයි': 2, 'සූත්රය': 2, 'දෙසන': 2, 'ප්රමාණ': 1, 'පර්වතයෙකුදු': 1, 'හුයාපී': 1, 'වෙයග': 1, 'බඩක්': 1, 'සෙයින්': 1, 'නැමී': 1, 'සමීපයට': 1, 'උප': 1, 'එයින්': 1, 'කීහ': 1, 'මෙසෙයින්': 1, 'සුප්රතිෂ්ඨිත': 1, 'තලද්වය': 1, 'උප්පාදයිස්සාමි': 1, 'තාත්': 1, 'පර්යාර්ථයි': 1, 'මත්තෙහිදු': 1, 'නයින්': 1, 'සියලු': 1, 'ත්රෛභූමික': 1, 'සංස්කාරයො': 1, 'ලොකොත්තරයන්': 1, 'සම්මර්ශන': 1, 'යොග්ය': 1, 'නොවන': 1, 'කාලයෙන්': 1, 'අර්ධයක්': 1, 'පවත්තේ': 1, 'ස්වභාවෙන්ම': 1, 'අල්': 1, 'අකුරයි': 1, 'කුරු': 1, 'ග්': 1, 'යනාදියයි': 1, 'හුදකලාව': 1, 'ව්යක්ත': 1, 'ශබ්දයක්': 1, 'මෙහිම': 1, 'නිමෙස්': 1, 'කමත්': 1, 'දැක්වූ': 1, 'කාල': 1, 'යෙන්ම': 1, 'මාගධ': 1, 'සංස්කෘත': 1, 'දෙක්හිද': 1, 'මාත්රා': 1, 'නියම': 1, 'තැන': 1, 'ලකුණෙන්': 1, 'නොව': 1, 'බදය': 1, 'නිදර්ශනයෙහි': 1, 'වැටේ': 1, 'එහෙයින්': 1, 'මෙසේම': 1, 'ලදැයි': 1, 'කුමක්': 1, 'පන': 1, 'විතර්කාදීන්': 1, 'සැපියුතු': 1, 'ධර්මයො': 1, 'ලක්ෂණ': 1, 'රසාදි': 1, 'පිරිසිඳ': 1, 'පරිග්රහකොට': 1, 'සියල්ල': 1, 'අරමුණට': 1, 'අභිමුඛව': 1, 'නැමෙන': 1, 'නම': 1, 'නට්ඨෙන': 1})), ('අසා', Counter({'බුදුන්': 9, 'නියාව': 4, 'මහ': 3, 'අපගේ': 3, 'බෝසත්හු': 3, 'නුවරට': 3, 'බුදු': 2, 'වැඩි': 2, 'කරා': 2, 'එළබ': 2, 'මියුරු': 2, 'බණ': 2, 'පැහැද': 2, 'අටුවා': 2, 'තුන්': 1, 'පියවරකින්': 1, 'තව්තිසා': 1, 'වැඩැ': 1, 'පණ්ඩුකම්බල': 1, 'සිලාසනයෙහි': 1, 'වැඩහිඳැ': 1, 'වදාරන්නා': 1, 'විජම්': 1, 'අමා': 1, 'නිවන්': 1, 'සෙව්ව': 1, 'මනා': 1, 'මුළු': 1, 'ලොවට': 1, 'මරණ': 1, 'පුතනුවෝ': 1, 'කෙළි': 1, 'උයන': 1, 'දුටු': 1, 'පූර්ව': 1, 'නිමිති': 1, 'නැඟි': 1, 'නික්මුණු': 1, 'සමය': 1, 'සහිතව': 1, 'හැරුණු': 1, 'දොර': 1, 'රෑ': 1, 'යට': 1, 'දීපංකර': 1, 'සමයෙහි': 1, 'සිවු': 1, 'පෙදෙන්': 1, 'යුත්': 1, 'ගාථා': 1, 'මාත්රයක්': 1, 'සව්': 1, 'කෙලෙස්': 1, 'නසා': 1, 'ගෙවා': 1, 'රහත්වන්ට': 1, 'නිසි': 1, 'පින්කම්': 1, 'ඇතත්': 1, 'සියල්ලවුන්': 1, 'හැම': 1, 'අතින්': 1, 'විචාරා': 1, 'කෙනෙකුන්': 1, 'වහන්සේ': 1, 'වඩනට': 1, 'ඉදිකරන': 1, 'මඟක්': 1, 'තමන්දැත්': 1, 'මං': 1, 'ඉදිකිරීමට': 1, 'සහාය': 1, 'වීමටත්': 1, 'වඩා': 1, 'කුසල්': 1, 'නැමැති': 1, 'බිජුවට': 1, 'වපුරන්ට': 1, 'එකල': 1, 'විජිතාවි': 1, 'සක්විතිව': 1, 'වැඩිනියාව': 1, 'දහම්සක': 1, 'පැවැති': 1, 'කලට': 1, 'සක්': 1, 'රුවනෙහි': 1, 'ආනුභාව': 1, 'දහසකම': 1, 'අනුවන්ට': 1, 'සුරුචි': 1, 'බ්රාහ්මණව': 1, 'ප්රධාන': 1, 'කෙළලක්ෂයක්': 1, 'සඟනට': 1, 'ආරාධනා': 1, 'අතුල': 1, 'දිව්ය': 1, 'නාගව': 1, 'ලොව': 1, 'උපන්': 1, 'නාග': 1, 'භවනයෙන්': 1, 'අවුත්': 1, 'කෙළ': 1, 'ලක්ෂයක්': 1, 'පාමොක්': 1, 'සඳහා': 1, 'ලංකාද්වීපයට': 1, 'වැඩ': 1, 'මහාවිහාරයෙහි': 1, 'සංඝපාල': 1, 'මහාස්ථවිරයන්': 1, 'හෙළු': 1, 'සියලු': 1, 'ස්ථවිරවා': 1, 'ඉගෙන': 1, 'සංඝයා': 1, 'රැස්': 1, 'ලියන්නට': 1})), ('විසිනුදු', Counter({'යනාදි': 2, 'භයින්': 1, 'සොරුන්': 1, 'කෙරෙන්': 1, 'දුරු': 1, 'වැ': 1, 'යන්නා': 1, 'සසර': 1, 'පමණින්': 1, 'ලුහු': 1, 'බැඳගෙණැ': 1, 'දුවන්නා': 1, 'ශරීර': 1, 'නැමැති': 1, 'මහසොරහට': 1, 'පදාර්ථය': 1, 'සම්බන්ධය': 1, 'අභිප්රායය': 1, 'චොදනාය': 1, 'ශොධනාය': 1, 'කිය': 1, 'යුතුයි': 1, 'ආචාර්යයන්': 1, 'එසෙයින්ම': 1, 'ලදී': 1, 'දෙසනාවට': 1, 'නිදානප්රයොජන': 1, 'නිර්වාරණය': 1, 'පිණ්ඩාර්ථ': 1})), ('නොව', Counter({'යුතුයි': 3, 'මාත්රා': 2, 'ලකුණෙන්': 2, 'නියම': 2, 'නට': 1, 'සසර': 1, 'නැමැති': 1, 'මුහුදු': 1, 'ගැලී': 1, 'දුක්': 1, 'ගන්නා': 1, 'මඳ': 1, 'දෙනකු': 1, 'සූවිසි': 1, 'අසංඛ්ය': 1, 'යක්': 1, 'සත්වයන්': 1, 'ඇරලා': 1, 'තනිව': 1, 'නිවන්': 1, 'දැක්ම': 1, 'වැන්නවුන්ට': 1, 'වඩා': 1, 'ඇප්': 1, 'කා': 1, 'ලය': 1, 'වැඩි': 1, 'නොවේ': 1, 'වැඩිවීම': 1, 'ශබ්දයෙන්ම': 1, 'මෙහිම': 1, 'නිමෙස්': 1, 'කමත්': 1, 'දැක්වූ': 1, 'කාල': 1, 'ගත': 1, 'මාගධ': 1, 'සංස්කෘත': 1, 'දෙක්හිද': 1, 'තැන': 1, 'කාලයෙන්ම': 1, 'තිබේ': 1, 'මෙසේයි': 1, 'සංස්කෘතෙහි': 1, 'ආ': 1, 'නොවෙයි': 1, 'දත': 1, 'කුමක්': 1, 'හෙයිනයත්': 1, 'ශාස්ත්රයෙහි': 1, 'වස්තුකීර්තනය': 1, 'ලොකයෙහි': 1, 'කෙවල': 1, 'ශාස්ත්ර': 1, 'සම්පත්ති': 1, 'විභාවන': 1, 'පවත්නා': 1, 'හෙයිනි': 1, 'එහෙයින්ම': 1, 'වක්ෂ්යමාණය': 1, 'යනාදි': 1})), ('නොයෙක්', Counter({'රජු': 2, 'වසේළඹීම්': 1, 'අවෙහංගි': 1, 'ගරු': 1, 'භාණ්ඩ': 1, 'පරිද්දෙන්': 1, 'සංකීර්ණයද': 1, 'ඇවැත්': 1, 'දෙසීම': 1, 'සැඳපිරිසිදු': 1, 'පවුරුණු': 1, 'දිම්': 1, 'පොහෝ': 1, 'පිය': 1, 'ගේ': 1, 'සිරුර': 1, 'දැවූ': 1, 'තැන': 1, 'සෑයක්': 1, 'බඳවා': 1, 'වෙහෙරේ': 1, 'පිරියම්': 1, 'කැරැවී': 1, 'පතිරජු': 1, 'කරවන': 1, 'ලද්දේ': 1})), ('පැමිණි', Counter({'උත්පත්ති': 1, 'දෙවියන්ට': 1, 'ඉදි': 1, 'කිරිබත': 1, 'විශුද්ධි': 1, 'දෙවිව': 1, 'පිළිගෙන': 1, 'තමන්': 1, 'වහන්සේට': 1, 'කොටසෙහි': 1, 'දෙවියන්': 1, 'දිවජස්': 1, 'බහාලූ': 1, 'සෙසු': 1, 'දවස්': 1, 'වළඳන': 1, 'භොජනය': 1})), ('කාල', Counter({'යුතුයි': 2, 'අවහාර': 2, 'කාලය': 2, 'නොව': 1, 'ශබ්දයෙන්ම': 1, 'මෙහිම': 1, 'නිමෙස්': 1, 'කමත්': 1, 'දැක්වූ': 1, 'යෙන්ම': 1, 'ගත': 1, 'මාගධ': 1, 'සංස්කෘත': 1, 'දෙක්හිද': 1, 'මාත්රා': 1, 'නියම': 1, 'තැන': 1, 'කෙලෙස්': 1, 'සතුරන්': 1, 'පරදවන': 1, 'වන්නො': 1, 'භණ්ඩ': 1, 'සොරාගත්': 1, 'වස්තුවය': 1, 'අග්නි': 1, 'භාණ්ඩයෙහි': 1, 'අගය': 1, 'දෙසෙහි': 1, 'දෙශය': 1, 'මොවුන්': 1, 'මන්ත්රාඛ්ය': 1, 'විද්යාව': 1, 'ගේ': 1, 'පරිජපනයද': 1, 'මොහු': 1, 'සදෙන': 1, 'වධ': 1, 'ප්රයෝග': 1, 'යොයි': 1, 'පූර්වාණ්හාදී': 1, 'යුක්ත': 1, 'මැරි': 1, 'සත්වය': 1, 'ආයුධ': 1, 'මරණ': 1})), ('පෙර', Counter({'කිසුණු': 1, 'ඉගුළු': 1, 'අහස': 1, 'මෙනෙහි': 1, 'නොකිරීමෙන්': 1, 'ආකාශානන්ත්යායතන': 1, 'ධ්යානයට': 1, 'සමවැද': 1, 'පැවැති': 1, 'විඥානයාගෙ': 1, 'අපගමනය': 1, 'අරමුණු': 1, 'ආකිඤ්චඤ්ඤායතනයට': 1, 'සමවදනෙ': 1, 'යි෴': 1, 'ඉමිනා': 1, 'නයෙන': 1})), ('මල්', Counter({'නැමැති': 4, 'අතුපතර': 1, 'ත්රිවිධ': 1, 'චර්යයා': 1, 'පල්ලව': 1, 'අභිඥා': 1, 'බොධිසම්භාර': 1, 'කප්රුක': 1, 'සර්වඥතා': 1, 'ඥාන': 1, 'අමාඵල': 1, 'ගන්වයි': 1, 'බුදුවෙයි': 1})), ('වෙන', Counter({'බඳු': 4, 'ශෘංගාර': 2, 'ශාලාවක්': 2, 'වැනි': 2, 'ශිල්පයට': 2, 'විද්යාශාලාවක්': 2, 'වු': 2, 'අධර්මයට': 2, 'වධ්ය': 2, 'භූමියක්': 2, 'ධර්මාධිකරණ': 2, 'ප්රවෘත්තීන්': 2, 'විනි': 2, 'වර්තිත': 2, 'භව': 2, 'ප්රභෙදයෙක්': 2, 'නිෂ්පන්න': 2, 'වෙද': 2, 'සියලු': 2, 'විභාගය': 2, 'නිර්ධාරණය': 2, 'කියනු': 2, 'ලබන්නේ': 2, 'වික්ෂෙප': 2, 'අර්ථයි': 2, 'ලදි': 2, 'සෘද්ධිය': 2, 'විකුණය': 2, 'දැයි': 2, 'මෙසෙ': 2, 'හො': 2, 'අර්ථය': 2, 'පූර්වාංගම': 2, 'නොවන': 2, 'බැවිනුදු': 2, 'නාගරිකයන්ට': 1, 'මාත්සර්යය': 1, 'එහෙයින්': 1, 'විජහන': 1, 'ක්රියාව': 1, 'සෘද්ධීන්': 1, 'අතුරෙහි': 1, 'විකුණ': 1, 'ඍද්ධිය': 1, 'ප්රධාන': 1, 'මෙය': 1, 'දතයුතු': 1, 'විකුර්පණය': 1, 'ගැණීම': 1, 'කාරණයෙන්': 1, 'දත': 1, 'යුතු෴': 1, 'ආකාශ': 1, 'වස්තු': 1, 'නිර්දෙශ': 1, 'කුමක්': 1, 'යත්': 1, 'සංවර්ණනාවක්': 1, 'ප්රකරණාන්තරයක්': 1, 'ස්තුති': 1})), ('දවස', Counter({'නැමැති': 3, 'නුමුසු': 2, 'මූණලා': 1, 'මුණින්': 1, 'වැදහෙව': 1, 'තිලෝගුරු': 1, 'බුදුන්ගෙන්ද': 1, 'තෙමේ': 1, 'මතු': 1, 'එන': 1, 'සිල්': 1, 'පොළොව': 1, 'ප්රතිඥා': 1, 'මුල්': 1, 'සිහි': 1, 'නුවණ': 1, 'කසළ': 1, 'බණ': 1, 'සේම': 1, 'පැන්': 1, 'කිරිබත්': 1, 'දන්': 1, 'කෙළවර': 1, 'කෙළ': 1, 'ලක්ෂයක්': 1, 'පාත්රා': 1, 'පුරවා': 1, 'ශර්කරා': 1, 'ගිතෙල්': 1, 'උක්සකුරු': 1, 'මීන': 1, 'ආදී': 1})), ('දත්', Counter({'දහම්': 2, 'සරණ': 2, 'මුළුල්ලෙහි': 1, 'සොයා': 1, 'වෙහෙසී': 1, 'අන්තයෙහි': 1, 'බෝමැඩ': 1, 'වජ්රාසනයෙහි': 1, 'වැඩහිඳැ': 1, 'සව්': 1, 'ගෙවා': 1, 'කෙණෙහි': 1, 'පසක්': 1, 'කළා': 1, 'යෙමි': 1})), ('දෙවියන්', Counter({'ඉදි': 1, 'කිරිබත': 1, 'විශුද්ධි': 1, 'දෙවිව': 1, 'පිළිගෙන': 1, 'තමන්': 1, 'වහන්සේට': 1, 'පැමිණි': 1, 'කොටසෙහි': 1, 'දිවජස්': 1, 'බහාලූ': 1, 'සෙසු': 1, 'දවස්': 1, 'වළඳන': 1, 'භොජනය': 1, 'සතියක්': 1})), ('සියලු', Counter({'මිහි': 4, 'තමන්': 4, 'සමාධි': 4, 'සම්පත්තීන්': 3, 'අකුසලින්': 3, 'දුරුව': 3, 'පිහිටා': 3, 'සිත්': 3, 'පවිත්ර': 3, 'ගෙන': 3, 'බැරියා': 3, 'නුවර': 3, 'රූප': 3, 'නිෂ්පන්න': 2, 'යත්': 2, 'වැ': 2, 'දු': 2, 'කැමැති': 2, 'විශුද්ධි': 2, 'සර්ව': 2, 'පැරුම්': 2, 'පිහිටියා': 2, 'දරුවන්': 2, 'තරමේ': 2, 'හික්ම': 2, 'වන්නා': 2, 'කුසලෙහි': 2, 'සතන්': 2, 'නැතිව': 2, 'ධනධාන්ය': 2, 'ඉගෙන': 2, 'බෝසත්හු': 2, 'සැව': 2, 'සිටිනා': 2, 'පහළ': 2, 'ලබන': 2, 'විසර්ජනය': 2, 'තෙමෙ': 2, 'ලෞකික': 2, 'වෙන': 2, 'උපචාර': 2, 'සප්රීතික': 2, 'මැද': 2, 'අවසනැ': 2, 'සඳ': 2, 'තොමෝ': 2, 'අටුවා': 2, 'යනාදි': 2, 'රූපයන්': 2, 'රූපය': 2, 'රුප්නා': 2, 'යොගි': 2, 'ලකුණෙන්': 2, 'එකක්': 2, 'අවයව': 1, 'මනොහර': 1, 'කුන්ද': 1, 'නූ': 1, 'චන්ද්රිකා': 1, 'කුමුදෙ': 1, 'න්දිවරාදී': 1, 'මධුර': 1, 'වස්තූන්ගේ': 1, 'ස්ථානොචිත': 1, 'වින්යාසයෙන්': 1, 'මනොඥ': 1, 'පරිණාමයෙන්': 1, 'රූපයක්': 1, 'වුව': 1, 'තෙමේ': 1, 'දුඃඛ': 1, 'කාරණය': 1, 'නොවෙයි': 1, 'නොවේ': 1, 'මැයි': 1, 'දුක්': 1, 'පිරු': 1, 'නිධානය': 1, 'සිටියේ': 1, 'මරහට': 1, 'ගොදුරු': 1, 'බඳු': 1, 'ප්රයෝජන': 1, 'ඇත්තෙ': 1, 'ස්වරූප': 1, 'නොදන්නා': 1, 'සුද්ධිකාමාපි': 1, 'සංක්ලෙශයන්': 1, 'කෙරෙනු': 1, 'සංසාරයෙනු': 1, 'විමුක්තිය': 1, 'අපි': 1, 'කියම්': 1, 'සකස්කොට': 1, 'කියන්නා': 1, 'මාගෙ': 1, 'මාර්ගය': 1, 'නිවන්': 1, 'සාධුජනයෙනි': 1, 'සකස්': 1, 'අසව්෴': 1, 'ඉමිස්සා': 1, 'දානි': 1, 'ගාථාය': 1, 'යනුයෙන්': 1, 'වචනයක්': 1, 'ඇද්ද': 1, 'අර්ථයි': 1, 'විසුද්ධි': 1, 'රාගාදි': 1, 'මලයෙන්': 1, 'වෙන්': 1, 'මල': 1, 'විරහිත': 1, 'හැමකල': 1, 'තාත්': 1, 'පර්යාර්ථයි': 1, 'මත්තෙහිදු': 1, 'නයින්': 1, 'අර්ථ': 1, 'ගත': 1, 'ත්රෛභූමික': 1, 'සංස්කාරයො': 1, 'ලොකොත්තරයන්': 1, 'සම්මර්ශන': 1, 'යොග්ය': 1, 'නොවන': 1, 'සබ්බේ': 1, 'සංඛාරා': 1, 'ලදින්': 1, 'සමතිස්': 1, 'පිරීමට': 1, 'නියත': 1, 'වීමෙන්': 1, 'අධි': 1, 'ගතයන්': 1, 'පුරවන්නා': 1, 'අධිගතයන්': 1, 'ආර්යය': 1, 'භූමියෙහි': 1, 'කුසල්හි': 1, 'තරම්': 1, 'දෙමවුපියන්': 1, 'සෝවාන්': 1, 'පුඟුලන්': 1, 'අපාය': 1, 'ගාමිනී': 1, 'අකුසල්හි': 1, 'හැසිරෙන්ට': 1, 'ලෙසින්ම': 1, 'කෘත': 1, 'පුණ්යතා': 1, 'ජාත්යන්ධයන්ට': 1, 'අන්ධයෂ්ටි': 1, 'ගමන්': 1, 'බමුණු': 1, 'කුමාරව': 1, 'ඉපද': 1, 'බොහෝ': 1, 'සමෘද්ධව': 1, 'උගතමනා': 1, 'ශිල්ප': 1, 'මවුපිය': 1, 'දෙදෙනාගේ': 1, 'අයාමෙන්': 1, 'උපයා': 1, 'රැස්කළ': 1, 'වස්තු': 1, 'රාශිය': 1, 'දෙඅසංඛ්ය': 1, 'කලක්ෂයක්': 1, 'තිබියදී': 1, 'මංගල': 1, 'තුසී': 1, 'පුරෙන්': 1, 'දඹදිව': 1, 'වලට': 1, 'උතුම්ව': 1, 'උත්තර': 1, 'යස': 1, 'පුරා': 1, 'නිමවා': 1, 'රෙවත': 1, 'මහ': 1, 'තුසීපුරෙන්': 1, 'සමෘද්ධ': 1, 'සුධඤ්ඤවතී': 1, 'සව්': 1, 'බරණින්': 1, 'සැරහුණු': 1, 'ප්රණිධිය': 1, 'අධිමොක්ෂය': 1, 'අභිනීහාරය': 1, 'ප්රඥාය': 1, 'මොවුන්ගෙ': 1, 'නානාත්වාදියෙන්': 1, 'නානාප්රකාර': 1, 'ප්රකාරය': 1, 'කරන්නට': 1, 'ආරම්භ': 1, 'භාවනා': 1, 'ලභ්යමාන': 1, 'විභාග': 1, 'කරනු': 1, 'ධ්යාන': 1, 'විභංගාදියෙහි': 1, 'ආගත': 1, 'ප්රභේදය': 1, 'විසදිය': 1, 'අභිමත': 1, 'එකාදශවිධ': 1, 'භව': 1, 'ප්රභෙදයෙක්': 1, 'වෙද': 1, 'විභාගය': 1, 'නිර්ධාරණය': 1, 'කියනු': 1, 'ලබන්නේ': 1, 'වික්ෂෙ

In [75]:
# for key in common_keys:   
#     for century, cooccurrence_map in final_filtered_results.items():
#         if TARGET_WORD in cooccurrence_map:
#             neighbors_counter = cooccurrence_map[key]
#             # print(neighbors_counter)
            
#             for collocate_word, count in neighbors_counter.items():
#                 records.append({
#                     'century': century,
#                     'collocate_word': collocate_word,
#                     # Temporary column to mark presence
#                     'count': count
#                 })
#     temp_df = pd.DataFrame(records)
#     # print(temp_df)
#     temp_df = temp_df.pivot_table(index='collocate_word', columns='century', values='count', aggfunc='first', fill_value=' ')
#     temp_df.to_csv(f'Collocates/{key}.csv', index=True, encoding='utf-8-sig')

In [76]:
for key in common_keys:   
    records = []  # ← RESET HERE, inside the loop
    for century, cooccurrence_map in final_filtered_results.items():
        if key in cooccurrence_map:          # ← also fix: check for `key`, not TARGET_WORD
            neighbors_counter = cooccurrence_map[key]
            
            for collocate_word, count in neighbors_counter.items():
                records.append({
                    'century': century,
                    'collocate_word': collocate_word,
                    'count': count
                })
    temp_df = pd.DataFrame(records)
    temp_df = temp_df.pivot_table(
        index='collocate_word',
        columns='century',
        values='count',
        aggfunc='sum',   # ← use 'sum' instead of 'first'
        fill_value=0     # ← use 0 instead of ' ' for cleaner numeric output
    )
    temp_df.to_csv(f'Collocates/{key}.csv', index=True, encoding='utf-8-sig')

## 'මහ' Analysis

In [77]:
maha_collocates_df = pd.read_csv('Collocates/මහ.csv')

In [78]:
maha_collocates_df.head()

  collocate_word  13  14  15  16  18  19  20
0          අක්ෂර   0   0   0   0   0   0   1
1           අකැප   2   0   0   0   0   0   0
2       අචින්ත්ය   0   1   0   0   0   0   0
3         අජාසත්   0   2   0   0   0   0   0
4  අඤ්ඤාකොණ්ඩඤ්ඤ   0   0   0   0   0   1   0

In [79]:
maha_collocates_df = maha_collocates_df.replace(r'^\s*$', np.nan, regex=True).fillna(0)

In [80]:
maha_collocates_df.isna().sum()

collocate_word    0
13                0
14                0
15                0
16                0
18                0
19                0
20                0
dtype: int64

In [81]:
cols_to_sum = ['13', '14', '15', '16', '18', '19', '20']
maha_collocates_df[cols_to_sum] = maha_collocates_df[cols_to_sum].apply(pd.to_numeric, errors='coerce')
maha_collocates_df['total_count'] = maha_collocates_df[cols_to_sum].sum(axis=1)

In [82]:
maha_collocates_df.sort_values(by='total_count', ascending=False, inplace=True)

In [83]:
maha_collocates_df.head()

    collocate_word  13  14  15  16  18  19  20  total_count
442         නැමැති  10   0   1   0   0   0   0           11
838         වහන්සේ   1   6   0   0   0   2   2           11
463          නිවන්   8   0   2   0   0   0   0           10
741             රජ   0   1   0   0   0   0   8            9
64             අසා   3   2   0   1   1   0   0            7

In [84]:
maha_collocates_df['century_span'] = (maha_collocates_df[cols_to_sum] > 0).sum(axis=1)

In [85]:
maha_collocates_df['longevity_score'] = maha_collocates_df['total_count'] * maha_collocates_df['century_span']

In [86]:
maha_collocates_df.sort_values(by='longevity_score', ascending=False, inplace=True)

In [87]:
maha_collocates_df.head()

,collocate_word,13,14,15,16,18,19,20,total_count,century_span,longevity_score
838,වහන්සේ,1,6,0,0,0,2,2,11,4,44
64,අසා,3,2,0,1,1,0,0,7,4,28
442,නැමැති,10,0,1,0,0,0,0,11,2,22
753,රහතන්,0,2,0,0,0,1,4,7,3,21
463,නිවන්,8,0,2,0,0,0,0,10,2,20

In [88]:
maha_collocates_df.to_csv('Collocates/maha_collocates_analysis.csv', index=False, encoding='utf-8-sig')

In [89]:
maha_collocates_df[maha_collocates_df['collocate_word'] == 'ප්රධාන']

,collocate_word,13,14,15,16,18,19,20,total_count,century_span,longevity_score
526,ප්රධාන,1,0,0,0,0,0,1,2,2,4

In [90]:
# maha_collocates_df['collocate_word']

In [91]:
maha_collocates = ['වහන්සේ', 'රහතන්', 'තෙරුන්', 'සඟ', 'වහන්සේගේ', 'ධර්ම', 'සංඝයා', 'බුදුන්', #esteemed, great, sacred
                   'රජ', 'ප්රධාන', 'රජුන්', 'ඉසුරු', 'ඇමැති', 'රජානනි', 'රාජගුරු', 'අජාසත්' ,'නරනිඳු', 'ධර්මාශෝක', 'පතිරජ', #powerful, royal, political
                   'ලක්ෂයක්', 'මහත්', 'සමූහයක්', 'මුහුද', 'කෛලාස' #big, large, massive
                   ]

In [92]:
maha_collocates_df[maha_collocates_df['collocate_word'].isin(maha_collocates)]

,collocate_word,13,14,15,16,18,19,20,total_count,century_span,longevity_score
838,වහන්සේ,1,6,0,0,0,2,2,11,4,44
753,රහතන්,0,2,0,0,0,1,4,7,3,21
741,රජ,0,1,0,0,0,0,8,9,2,18
775,ලක්ෂයක්,4,1,0,0,0,0,1,6,3,18
937,සඟ,0,2,1,0,0,0,2,5,3,15
337,තෙරුන්,1,3,0,0,0,1,0,5,3,15
412,ධර්ම,1,1,0,0,0,0,1,3,3,9
839,වහන්සේගේ,1,3,0,0,0,0,0,4,2,8
931,සංඝයා,0,0,2,0,1,0,0,3,2,6
627,බුදුන්,2,0,0,0,0,0,1,3,2,6
526,ප්රධාන,1,0,0,0,0,0,1,2,2,4
108,ඉසුරු,1,0,0,0,0,0,1,2,2,4
971,සමූහයක්,0,0,1,0,0,0,1,2,2,4
671,මහත්,0,1,1,0,0,0,0,2,2,4
748,රජුන්,0,0,0,0,0,0,4,4,1,4
3,අජාසත්,0,2,0,0,0,0,0,2,1,2
238,කෛලාස,0,0,2,0,0,0,0,2,1,2
757,රාජගුරු,0,0,0,0,0,0,2,2,1,2
747,රජානනි,0,0,0,0,0,0,2,2,1,2
491,පතිරජ,2,0,0,0,0,0,0,2,1,2
416,ධර්මාශෝක,0,0,0,0,0,0,2,2,1,2
707,මුහුද,2,0,0,0,0,0,0,2,1,2
91,ඇමැති,0,0,0,0,0,0,1,1,1,1
433,නරනිඳු,0,0,0,0,0,0,1,1,1,1

In [93]:
meanings_map = {
    **{w: "esteemed, great, sacred" for w in ['වහන්සේ', 'රහතන්', 'තෙරුන්', 'සඟ', 'වහන්සේගේ', 'ධර්ම', 'සංඝයා', 'බුදුන්']},
    **{w: "powerful, strong" for w in ['රජ', 'ප්රධාන', 'රජුන්', 'ඉසුරු', 'ඇමැති', 'රජානනි', 'රාජගුරු', 'අජාසත්' ,'නරනිඳු', 'ධර්මාශෝක', 'පතිරජ']},
    **{w: "big, large, massive" for w in ['ලක්ෂයක්', 'මහත්', 'සමූහයක්', 'මුහුද', 'කෛලාස']}
}

In [94]:
maha_collocates_df_filtered = maha_collocates_df[maha_collocates_df['collocate_word'].isin(maha_collocates)].copy()

In [95]:
col_pos = maha_collocates_df_filtered.columns.get_loc('collocate_word') + 1

In [96]:
meanings_column = maha_collocates_df_filtered['collocate_word'].map(meanings_map)

In [97]:
maha_collocates_df_filtered.insert(col_pos, 'Related Meaning(s)', meanings_column)

In [98]:
maha_collocates_df_filtered['collocate_word'] = pd.Categorical(maha_collocates_df_filtered['collocate_word'], categories=maha_collocates, ordered=True)
maha_collocates_df_filtered = maha_collocates_df_filtered.sort_values('collocate_word').reset_index(drop=True)

In [99]:
maha_collocates_df_filtered

,collocate_word,Related Meaning(s),13,14,15,16,18,19,20,total_count,century_span,longevity_score
0,වහන්සේ,"esteemed, great, sacred",1,6,0,0,0,2,2,11,4,44
1,රහතන්,"esteemed, great, sacred",0,2,0,0,0,1,4,7,3,21
2,තෙරුන්,"esteemed, great, sacred",1,3,0,0,0,1,0,5,3,15
3,සඟ,"esteemed, great, sacred",0,2,1,0,0,0,2,5,3,15
4,වහන්සේගේ,"esteemed, great, sacred",1,3,0,0,0,0,0,4,2,8
5,ධර්ම,"esteemed, great, sacred",1,1,0,0,0,0,1,3,3,9
6,සංඝයා,"esteemed, great, sacred",0,0,2,0,1,0,0,3,2,6
7,බුදුන්,"esteemed, great, sacred",2,0,0,0,0,0,1,3,2,6
8,රජ,"powerful, strong",0,1,0,0,0,0,8,9,2,18
9,ප්රධාන,"powerful, strong",1,0,0,0,0,0,1,2,2,4
10,රජුන්,"powerful, strong",0,0,0,0,0,0,4,4,1,4
11,ඉසුරු,"powerful, strong",1,0,0,0,0,0,1,2,2,4
12,ඇමැති,"powerful, strong",0,0,0,0,0,0,1,1,1,1
13,රජානනි,"powerful, strong",0,0,0,0,0,0,2,2,1,2
14,රාජගුරු,"powerful, strong",0,0,0,0,0,0,2,2,1,2
15,අජාසත්,"powerful, strong",0,2,0,0,0,0,0,2,1,2
16,නරනිඳු,"powerful, strong",0,0,0,0,0,0,1,1,1,1
17,ධර්මාශෝක,"powerful, strong",0,0,0,0,0,0,2,2,1,2
18,පතිරජ,"powerful, strong",2,0,0,0,0,0,0,2,1,2
19,ලක්ෂයක්,"big, large, massive",4,1,0,0,0,0,1,6,3,18
20,මහත්,"big, large, massive",0,1,1,0,0,0,0,2,2,4
21,සමූහයක්,"big, large, massive",0,0,1,0,0,0,1,2,2,4
22,මුහුද,"big, large, massive",2,0,0,0,0,0,0,2,1,2
23,කෛලාස,"big, large, massive",0,0,2,0,0,0,0,2,1,2

In [100]:
maha_collocates_df_filtered.drop(columns=['total_count', 'century_span', 'longevity_score'], inplace=True)

In [101]:
maha_collocates_df_filtered

   collocate_word       Related Meaning(s)  13  14  15  16  18  19  20
0          වහන්සේ  esteemed, great, sacred   1   6   0   0   0   2   2
1           රහතන්  esteemed, great, sacred   0   2   0   0   0   1   4
2          තෙරුන්  esteemed, great, sacred   1   3   0   0   0   1   0
3              සඟ  esteemed, great, sacred   0   2   1   0   0   0   2
4        වහන්සේගේ  esteemed, great, sacred   1   3   0   0   0   0   0
5            ධර්ම  esteemed, great, sacred   1   1   0   0   0   0   1
6           සංඝයා  esteemed, great, sacred   0   0   2   0   1   0   0
7          බුදුන්  esteemed, great, sacred   2   0   0   0   0   0   1
8              රජ         powerful, strong   0   1   0   0   0   0   8
9          ප්රධාන         powerful, strong   1   0   0   0   0   0   1
10          රජුන්         powerful, strong   0   0   0   0   0   0   4
11          ඉසුරු         powerful, strong   1   0   0   0   0   0   1
12          ඇමැති         powerful, strong   0   0   0   0   0   0   1
13         රජානනි         powerful, strong   0   0   0   0   0   0   2
14        රාජගුරු         powerful, strong   0   0   0   0   0   0   2
15         අජාසත්         powerful, strong   0   2   0   0   0   0   0
16         නරනිඳු         powerful, strong   0   0   0   0   0   0   1
17       ධර්මාශෝක         powerful, strong   0   0   0   0   0   0   2
18          පතිරජ         powerful, strong   2   0   0   0   0   0   0
19        ලක්ෂයක්      big, large, massive   4   1   0   0   0   0   1
20           මහත්      big, large, massive   0   1   1   0   0   0   0
21        සමූහයක්      big, large, massive   0   0   1   0   0   0   1
22          මුහුද      big, large, massive   2   0   0   0   0   0   0
23          කෛලාස      big, large, massive   0   0   2   0   0   0   0

In [102]:
maha_collocates_df_filtered.to_latex('Tex_Files/maha_collocates_table.tex', index=False, encoding='utf-8-sig')

## 'සතර' Analysis

In [103]:
sathara_collocates_df = pd.read_csv('Collocates/සතර.csv')

In [104]:
sathara_collocates_df.head()

  collocate_word  13  14  15  16  18  19  20
0          අංගවන   1   0   0   0   0   0   0
1            අක්   2   0   0   0   0   0   0
2          අක්ෂර   0   0   0   0   0   1   0
3        අකුරෙව්   0   0   0   1   0   0   0
4             අග   0   0   0   1   0   0   0

In [105]:
sathara_collocates_df = sathara_collocates_df.replace(r'^\s*$', np.nan, regex=True).fillna(0)

In [106]:
sathara_collocates_df.isna().sum()

collocate_word    0
13                0
14                0
15                0
16                0
18                0
19                0
20                0
dtype: int64

In [107]:
cols_to_sum = ['13', '14', '15', '16', '18', '19', '20']
sathara_collocates_df[cols_to_sum] = sathara_collocates_df[cols_to_sum].apply(pd.to_numeric, errors='coerce')
sathara_collocates_df['total_count'] = sathara_collocates_df[cols_to_sum].sum(axis=1)

In [108]:
sathara_collocates_df.sort_values(by='total_count', ascending=False, inplace=True)

In [109]:
sathara_collocates_df.head()

    collocate_word  13  14  15  16  18  19  20  total_count
330            පාද   0   0   0   0   0   8   1            9
465            රූප   0   0   0   0   3   4   0            7
134             ගණ   5   0   0   0   0   1   0            6
190         තුන්වන   2   0   0   0   2   1   0            5
502           වැනි   2   0   0   0   0   0   2            4

In [110]:
sathara_collocates_df['century_span'] = (sathara_collocates_df[cols_to_sum] > 0).sum(axis=1)

In [111]:
sathara_collocates_df['longevity_score'] = sathara_collocates_df['total_count'] * sathara_collocates_df['century_span']

In [112]:
sathara_collocates_df.sort_values(by='longevity_score', ascending=False, inplace=True)

In [113]:
sathara_collocates_df.reset_index(drop=True, inplace=True)

In [114]:
sathara_collocates_df.head(200)

,collocate_word,13,14,15,16,18,19,20,total_count,century_span,longevity_score
0,පාද,0,0,0,0,0,8,1,9,2,18
1,තුන්වන,2,0,0,0,2,1,0,5,3,15
2,රූප,0,0,0,0,3,4,0,7,2,14
3,ගණ,5,0,0,0,0,1,0,6,2,12
4,වැනි,2,0,0,0,0,0,2,4,2,8
5,රාජ,0,0,0,0,0,1,3,4,2,8
6,යනාදි,2,0,0,0,0,2,0,4,2,8
7,ෂට්,0,0,1,0,3,0,0,4,2,8
8,ලක්ෂණ,1,0,0,0,2,0,0,3,2,6
9,ජංඝා,2,0,0,0,1,0,0,3,2,6
10,සතරක්,0,0,0,2,0,1,0,3,2,6
11,බුද්ධ,0,0,1,0,0,0,1,2,2,4
12,පත්,1,0,0,0,0,1,0,2,2,4
13,ඉති,1,0,0,0,0,0,1,2,2,4
14,තුන්,1,0,0,0,0,0,1,2,2,4
15,පූර්ව,0,1,0,0,0,1,0,2,2,4
16,අපාය,1,0,1,0,0,0,0,2,2,4
17,වසන,1,0,0,0,0,0,1,2,2,4
18,ගුරු,1,0,0,0,0,1,0,2,2,4
19,මෙයින්,0,0,0,1,0,1,0,2,2,4
20,ඥාන,0,0,0,0,4,0,0,4,1,4
21,පංචෙන්ද්රිය,0,0,0,0,3,0,0,3,1,3
22,ව්යජන,0,0,0,0,3,0,0,3,1,3
23,ඉෂ්ට,3,0,0,0,0,0,0,3,1,3
24,සෘද්ධිපාද,0,0,0,0,3,0,0,3,1,3
25,බල,0,0,0,0,3,0,0,3,1,3
26,සම,0,0,0,0,0,3,0,3,1,3
27,වෛසාර,0,0,0,0,3,0,0,3,1,3
28,තැනින්,0,0,0,0,0,3,0,3,1,3
29,යුගලයෙහි,0,0,0,0,0,3,0,3,1,3
30,පංච,0,0,0,0,3,0,0,3,1,3
31,උගුළුවාගෙන,0,0,0,0,0,3,0,3,1,3
32,ඍතු,3,0,0,0,0,0,0,3,1,3
33,මෙසේයි,3,0,0,0,0,0,0,3,1,3
34,භාගයෙහි,3,0,0,0,0,0,0,3,1,3
35,මනා,3,0,0,0,0,0,0,3,1,3
36,සතරවන,0,0,0,0,0,3,0,3,1,3
37,අයිති,0,0,0,0,0,3,0,3,1,3
38,ස්ථානයකින්,0,0,0,0,0,3,0,3,1,3
39,විලාසයක්,0,0,0,0,3,0,0,3,1,3
40,තොප,0,0,3,0,0,0,0,3,1,3
41,සම්යප්රධාන,0,0,0,0,3,0,0,3,1,3
42,කව්,0,0,0,0,0,3,0,3,1,3
43,ගුරෙකු,0,0,0,0,0,0,3,3,1,3
44,නාම,0,0,0,0,0,3,0,3,1,3
45,අශීත්යානු,0,0,0,0,3,0,0,3,1,3
46,දෙකට,0,0,0,0,0,3,0,3,1,3
47,පර්වතය,3,0,0,0,0,0,0,3,1,3
48,අසාධාරණ,0,0,0,0,3,0,0,3,1,3
49,ස්කන්ධ,0,0,0,0,0,3,0,3,1,3
50,ඛ්යාමප්රභානුරඤ්ජිත,0,0,0,0,3,0,0,3,1,3
51,ස්ථානයකට,2,0,0,0,0,0,0,2,1,2
52,බලයි,0,0,0,0,2,0,0,2,1,2
53,පාදය,0,0,0,0,0,2,0,2,1,2
54,සොළොස්,2,0,0,0,0,0,0,2,1,2
55,පරව,0,0,0,0,0,2,0,2,1,2
56,පාරාජිකාවෝ,2,0,0,0,0,0,0,2,1,2
57,ඇඟිලි,0,0,0,0,2,0,0,2,1,2
58,පැසුණු,2,0,0,0,0,0,0,2,1,2
59,භාගයෙන්,2,0,0,0,0,0,0,2,1,2
60,අනුවන,0,0,0,0,0,2,0,2,1,2
61,පුතු,0,0,0,0,0,0,2,2,1,2
62,සමාධි,2,0,0,0,0,0,0,2,1,2
63,සමුත්ථාන,2,0,0,0,0,0,0,2,1,2
64,බ්රහ්ම,0,0,2,0,0,0,0,2,1,2
65,අක්,2,0,0,0,0,0,0,2,1,2
66,බුදුන්ගේ,0,0,0,0,2,0,0,2,1,2
67,ප්රතිෂඨිත,2,0,0,0,0,0,0,2,1,2
68,සිප්,0,0,0,0,0,0,2,2,1,2
69,ඉක්බිත්තෙන්,2,0,0,0,0,0,0,2,1,2
70,පැමිණේ,2,0,0,0,0,0,0,2,1,2
71,පතුල්,2,0,0,0,0,0,0,2,1,2
72,ඉන්මගෙ,0,0,0,0,0,0,2,2,1,2
73,හෘදය,2,0,0,0,0,0,0,2,1,2
74,පාඨයෙන්,0,0,0,0,0,2,0,2,1,2
75,අනිෂ්ට,2,0,0,0,0,0,0,2,1,2
76,රූපයො,2,0,0,0,0,0,0,2,1,2
77,ත්රිවිධ,2,0,0,0,0,0,0,2,1,2
78,සමඟ,0,0,0,0,0,0,2,2,1,2
79,උසස්,2,0,0,0,0,0,0,2,1,2
80,සමපාදය,0,0,0,0,0,2,0,2,1,2
81,සප්ත,0,0,0,0,2,0,0,2,1,2
82,නොහොබින,0,0,0,0,0,0,2,2,1,2
83,මැ,0,0,0,0,0,0,2,2,1,2
84,මණ්ඩලය,2,0,0,0,0,0,0,2,1,2
85,කිමවන,2,0,0,0,0,0,0,2,1,2
86,මහාපුරුෂ,0,0,0,0,2,0,0,2,1,2
87,කීවොත්,0,0,0,0,0,2,0,2,1,2
88,ධාතූන්,2,0,0,0,0,0,0,2,1,2
89,ලදී,2,0,0,0,0,0,0,2,1,2
90,ලුහු,2,0,0,0,0,0,0,2,1,2
91,වර්ණයකින්,0,0,0,0,0,2,0,2,1,2
92,දෙඅත්හි,2,0,0,0,0,0,0,2,1,2
93,විඤ්ඤාණයට,0,0,0,0,0,2,0,2,1,2
94,ච,2,0,0,0,0,0,0,2,1,2
95,දෙක,0,0,0,0,0,2,0,2,1,2
96,විරිත,0,0,0,0,0,0,2,2,1,2
97,දෙයානුවන,0,0,0,0,0,2,0,2,1,2
98,දෙභාගයෙක්,2,0,0,0,0,0,0,2,1,2
99,යන්නෙහි,2,0,0,0,0,0,0,2,1,2
100,වා,2,0,0,0,0,0,0,2,1,2
101,විෂමපාදය,0,0,0,0,0,2,0,2,1,2
102,ජගණයක්,0,0,0,0,0,2,0,2,1,2
103,වසයෙන්,2,0,0,0,0,0,0,2,1,2
104,දෙකින්,2,0,0,0,0,0,0,2,1,2
105,අෂ්ටාංග,1,0,0,0,0,0,0,1,1,1
106,උන්,0,0,1,0,0,0,0,1,1,1
107,උපෙක්ෂාය,0,0,1,0,0,0,0,1,1,1
108,උතුම්,0,0,1,0,0,0,0,1,1,1
109,උදෙසන,0,0,1,0,0,0,0,1,1,1
110,උයන්,0,0,0,0,0,1,0,1,1,1
111,උනොත්,0,0,0,0,0,0,1,1,1,1
112,උපදවනු,0,0,1,0,0,0,0,1,1,1
113,උපදෙසිනි,0,0,0,0,0,1,0,1,1,1
114,උබ්හජානු,1,0,0,0,0,0,0,1,1,1
115,උඩගුව,0,0,0,0,0,1,0,1,1,1
116,එකක,0,0,0,0,0,1,0,1,1,1
117,අවෙනික,0,0,1,0,0,0,0,1,1,1
118,අශ්ව,0,1,0,0,0,0,0,1,1,1
119,අකුරෙව්,0,0,0,1,0,0,0,1,1,1
120,අතර,0,0,1,0,0,0,0,1,1,1
121,අත,0,0,0,0,1,0,0,1,1,1
122,අටකින්ද,0,0,0,0,0,1,0,1,1,1
123,අට,1,0,0,0,0,0,0,1,1,1
124,අඟන්නෝ,0,0,0,0,0,1,0,1,1,1
125,අඟන,0,0,0,0,0,1,0,1,1,1
126,අතින්,0,0,1,0,0,0,0,1,1,1
127,අඟ,0,0,0,0,0,1,0,1,1,1
128,අගැ,0,0,0,0,0,0,1,1,1,1
129,අග්රාම්ය,1,0,0,0,0,0,0,1,1,1
130,අග්පතුල්,0,0,0,0,1,0,0,1,1,1
131,අග,0,0,0,1,0,0,0,1,1,1
132,එකුන්,0,0,0,0,0,1,0,1,1,1
133,අක්ෂර,0,0,0,0,0,1,0,1,1,1
134,අගින්,1,0,0,0,0,0,0,1,1,1
135,එකක්,0,0,0,1,0,0,0,1,1,1
136,ඉමෙසු,0,0,1,0,0,0,0,1,1,1
137,එතී,0,0,1,0,0,0,0,1,1,1
138,ඇසීමි,0,0,1,0,0,0,0,1,1,1
139,අනතුර,0,0,0,1,0,0,0,1,1,1
140,නොවන,0,0,0,0,0,1,0,1,1,1
141,නොමදන්න්නෙය,0,0,0,0,0,0,1,1,1,1
142,නොම,0,0,0,1,0,0,0,1,1,1
143,නොබිඳේ,0,0,0,0,0,0,1,1,1,1
144,නොපස්විකණ,1,0,0,0,0,0,0,1,1,1
145,නොදැන,0,0,0,0,0,0,1,1,1,1
146,නොදත්,0,0,0,0,0,1,0,1,1,1
147,නෙක,0,0,0,0,0,1,0,1,1,1
148,පථ්යාව,0,0,0,0,0,1,0,1,1,1
149,පුළුවනැයි,0,0,0,0,0,1,0,1,1,1
150,තත්තද්,1,0,0,0,0,0,0,1,1,1
151,ටැඹට,0,0,1,0,0,0,0,1,1,1
152,ඉගෙණ,0,0,0,0,0,1,0,1,1,1
153,ඇද්,1,0,0,0,0,0,0,1,1,1
154,එතෙන,1,0,0,0,0,0,0,1,1,1
155,ඇතුළත්,0,0,0,0,0,1,0,1,1,1
156,ඇතිවන,0,0,0,0,0,1,0,1,1,1
157,ඇඟිලිපසද,0,0,0,0,1,0,0,1,1,1
158,ආහාර,0,0,0,0,0,0,1,1,1,1
159,ආයත,0,0,0,0,1,0,0,1,1,1
160,ආද්යන්තලඝු,0,0,0,0,0,1,0,1,1,1
161,ආගම්,0,0,0,0,0,1,0,1,1,1
162,අහරය,1,0,0,0,0,0,0,1,1,1
163,අහර,1,0,0,0,0,0,0,1,1,1
164,අසම,0,0,0,0,0,1,0,1,1,1
165,ආර්ය,1,0,0,0,0,0,0,1,1,1
166,අෂ්ටාදශ,0,0,1,0,0,0,0,1,1,1
167,උගනීද,0,0,0,1,0,0,0,1,1,1
168,උත්පත්තියක්,0,0,0,0,0,1,0,1,1,1
169,අද්භූත,0,0,0,0,0,1,0,1,1,1
170,චක්රායුධයසපත,1,0,0,0,0,0,0,1,1,1
171,අනතුරු,0,0,1,0,0,0,0,1,1,1
172,චතුර්භූතයන්,1,0,0,0,0,0,0,1,1,1
173,ගෙනහැර,0,0,0,1,0,0,0,1,1,1
174,ගොති,0,0,0,0,0,0,1,1,1,1
175,චක්ර,0,0,0,0,1,0,0,1,1,1
176,ඥානය,0,0,1,0,0,0,0,1,1,1
177,ජීවිතෙන්ද්රියය,1,0,0,0,0,0,0,1,1,1
178,ඡතුවන,0,0,0,0,0,0,1,1,1,1
179,චුද්දශ,0,0,1,0,0,0,0,1,1,1
180,චුති,0,0,0,0,0,1,0,1,1,1
181,චිත්තසමුත්ථානයන්,1,0,0,0,0,0,0,1,1,1
182,චර්මානන්තරගත,1,0,0,0,0,0,0,1,1,1
183,චන්ද්ර,1,0,0,0,0,0,0,1,1,1
184,චතුසු,0,0,1,0,0,0,0,1,1,1
185,චතුස්සත්යය,0,0,0,0,0,0,1,1,1,1
186,චතුෂ්කනය,1,0,0,0,0,0,0,1,1,1
187,චතස්සො,1,0,0,0,0,0,0,1,1,1
188,අවෙද්ය,1,0,0,0,0,0,0,1,1,1
189,නොහොබි,0,0,0,0,0,1,0,1,1,1
190,චක්රවර්තිය,1,0,0,0,0,0,0,1,1,1
191,කෙශයෙහි,1,0,0,0,0,0,0,1,1,1
192,ඩැහැගෙණ,0,0,0,0,0,1,0,1,1,1
193,කෙරෙ෴,1,0,0,0,0,0,0,1,1,1
194,කුමාරයන්ගේ,1,0,0,0,0,0,0,1,1,1
195,කලී,0,0,0,0,0,0,1,1,1,1
196,කලැ,0,0,0,0,0,0,1,1,1,1
197,කලණ,0,0,1,0,0,0,0,1,1,1
198,කලකිරී,0,0,0,0,0,1,0,1,1,1
199,කරුණාය,0,0,1,0,0,0,0,1,1,1

In [115]:
sathara_collocates_df.to_csv('Collocates/sathara_collocates_analysis.csv', index=False, encoding='utf-8-sig')

In [116]:
sathara_collocates = ["දක්ෂ", "පඬින" #Intelligent
                   "උගනීද", "ඉගෙන", "සිප්", "ගුරෙකු", "ඉගෙණ", "සිප්සතරා", "ශික්ෂායි", "විද්යාස්ථාන", #Learn, Educate
                   "ගණ", "තුන්", "පංච", "අටකින්ද", "පණසකින්ද", "සතරක්", #Value, Math
                   "ඩැහැගෙණ", #Thief
                   "අපාය", #Hell
                   "ඥාන", "නුවණ", "ඥානය", "දත්", "දැනගන්ට", "නැණින්", #Wisdom, Knowledge
                #    "දිශා" #Direction
                   ]

In [117]:
sathara_collocates_df[sathara_collocates_df['collocate_word'].isin(sathara_collocates)]

,collocate_word,13,14,15,16,18,19,20,total_count,century_span,longevity_score
3,ගණ,5,0,0,0,0,1,0,6,2,12
10,සතරක්,0,0,0,2,0,1,0,3,2,6
14,තුන්,1,0,0,0,0,0,1,2,2,4
16,අපාය,1,0,1,0,0,0,0,2,2,4
20,ඥාන,0,0,0,0,4,0,0,4,1,4
30,පංච,0,0,0,0,3,0,0,3,1,3
43,ගුරෙකු,0,0,0,0,0,0,3,3,1,3
68,සිප්,0,0,0,0,0,0,2,2,1,2
122,අටකින්ද,0,0,0,0,0,1,0,1,1,1
152,ඉගෙණ,0,0,0,0,0,1,0,1,1,1
176,ඥානය,0,0,1,0,0,0,0,1,1,1
192,ඩැහැගෙණ,0,0,0,0,0,1,0,1,1,1
267,දත්,0,0,0,0,0,1,0,1,1,1
272,පණසකින්ද,0,0,0,0,0,1,0,1,1,1
288,දැනගන්ට,0,0,0,1,0,0,0,1,1,1
333,නුවණ,0,0,0,0,1,0,0,1,1,1
372,ශික්ෂායි,1,0,0,0,0,0,0,1,1,1
584,සිප්සතරා,0,0,0,0,0,0,1,1,1,1
624,විද්යාස්ථාන,1,0,0,0,0,0,0,1,1,1

In [118]:
meanings_map = {
    **{w: "Intelligent" for w in ["දක්ෂ", "පඬින"]},
    **{w: "Learn, Educate" for w in ["උගනීද", "ඉගෙන", "සිප්", "ගුරෙකු", "ඉගෙණ", "සිප්සතරා", "ශික්ෂායි", "විද්යාස්ථාන"]},
    **{w: "Value, Math" for w in ["ගණ", "තුන්", "පංච", "අටකින්ද", "පණසකින්ද", "සතරක්"]},
    **{w: "Thief" for w in ["ඩැහැගෙණ"]},
    **{w: "Hell" for w in ["අපාය"]},
    **{w: "Wisdom, Knowledge" for w in ["ඥාන", "නුවණ", "ඥානය", "දත්", "දැනගන්ට", "නැණින්"]}
}

In [119]:
sathara_collocates_df[sathara_collocates_df['collocate_word'].isin(["දක්ෂ", "පඬින"])].copy()

Empty DataFrame
Columns: [collocate_word, 13, 14, 15, 16, 18, 19, 20, total_count, century_span, longevity_score]
Index: []

In [120]:
sathara_collocates_df_filtered = sathara_collocates_df[sathara_collocates_df['collocate_word'].isin(sathara_collocates)].copy()

In [121]:
sathara_collocates_df_filtered

,collocate_word,13,14,15,16,18,19,20,total_count,century_span,longevity_score
3,ගණ,5,0,0,0,0,1,0,6,2,12
10,සතරක්,0,0,0,2,0,1,0,3,2,6
14,තුන්,1,0,0,0,0,0,1,2,2,4
16,අපාය,1,0,1,0,0,0,0,2,2,4
20,ඥාන,0,0,0,0,4,0,0,4,1,4
30,පංච,0,0,0,0,3,0,0,3,1,3
43,ගුරෙකු,0,0,0,0,0,0,3,3,1,3
68,සිප්,0,0,0,0,0,0,2,2,1,2
122,අටකින්ද,0,0,0,0,0,1,0,1,1,1
152,ඉගෙණ,0,0,0,0,0,1,0,1,1,1
176,ඥානය,0,0,1,0,0,0,0,1,1,1
192,ඩැහැගෙණ,0,0,0,0,0,1,0,1,1,1
267,දත්,0,0,0,0,0,1,0,1,1,1
272,පණසකින්ද,0,0,0,0,0,1,0,1,1,1
288,දැනගන්ට,0,0,0,1,0,0,0,1,1,1
333,නුවණ,0,0,0,0,1,0,0,1,1,1
372,ශික්ෂායි,1,0,0,0,0,0,0,1,1,1
584,සිප්සතරා,0,0,0,0,0,0,1,1,1,1
624,විද්යාස්ථාන,1,0,0,0,0,0,0,1,1,1

In [122]:
col_pos = sathara_collocates_df_filtered.columns.get_loc('collocate_word') + 1

In [123]:
meanings_column = sathara_collocates_df_filtered['collocate_word'].map(meanings_map)

In [124]:
sathara_collocates_df_filtered.insert(col_pos, 'Related Meaning(s)', meanings_column)

In [125]:
sathara_collocates_df_filtered['collocate_word'] = pd.Categorical(sathara_collocates_df_filtered['collocate_word'], categories=sathara_collocates, ordered=True)
sathara_collocates_df_filtered = sathara_collocates_df_filtered.sort_values('collocate_word').reset_index(drop=True)

In [126]:
sathara_collocates_df_filtered

,collocate_word,Related Meaning(s),13,14,15,16,18,19,20,total_count,century_span,longevity_score
0,සිප්,"Learn, Educate",0,0,0,0,0,0,2,2,1,2
1,ගුරෙකු,"Learn, Educate",0,0,0,0,0,0,3,3,1,3
2,ඉගෙණ,"Learn, Educate",0,0,0,0,0,1,0,1,1,1
3,සිප්සතරා,"Learn, Educate",0,0,0,0,0,0,1,1,1,1
4,ශික්ෂායි,"Learn, Educate",1,0,0,0,0,0,0,1,1,1
5,විද්යාස්ථාන,"Learn, Educate",1,0,0,0,0,0,0,1,1,1
6,ගණ,"Value, Math",5,0,0,0,0,1,0,6,2,12
7,තුන්,"Value, Math",1,0,0,0,0,0,1,2,2,4
8,පංච,"Value, Math",0,0,0,0,3,0,0,3,1,3
9,අටකින්ද,"Value, Math",0,0,0,0,0,1,0,1,1,1
10,පණසකින්ද,"Value, Math",0,0,0,0,0,1,0,1,1,1
11,සතරක්,"Value, Math",0,0,0,2,0,1,0,3,2,6
12,ඩැහැගෙණ,Thief,0,0,0,0,0,1,0,1,1,1
13,අපාය,Hell,1,0,1,0,0,0,0,2,2,4
14,ඥාන,"Wisdom, Knowledge",0,0,0,0,4,0,0,4,1,4
15,නුවණ,"Wisdom, Knowledge",0,0,0,0,1,0,0,1,1,1
16,ඥානය,"Wisdom, Knowledge",0,0,1,0,0,0,0,1,1,1
17,දත්,"Wisdom, Knowledge",0,0,0,0,0,1,0,1,1,1
18,දැනගන්ට,"Wisdom, Knowledge",0,0,0,1,0,0,0,1,1,1

In [127]:
sathara_collocates_df_filtered.drop(columns=['total_count', 'century_span', 'longevity_score'], inplace=True)

In [128]:
sathara_collocates_df_filtered

   collocate_word Related Meaning(s)  13  14  15  16  18  19  20
0            සිප්     Learn, Educate   0   0   0   0   0   0   2
1          ගුරෙකු     Learn, Educate   0   0   0   0   0   0   3
2            ඉගෙණ     Learn, Educate   0   0   0   0   0   1   0
3        සිප්සතරා     Learn, Educate   0   0   0   0   0   0   1
4        ශික්ෂායි     Learn, Educate   1   0   0   0   0   0   0
5     විද්යාස්ථාන     Learn, Educate   1   0   0   0   0   0   0
6              ගණ        Value, Math   5   0   0   0   0   1   0
7            තුන්        Value, Math   1   0   0   0   0   0   1
8             පංච        Value, Math   0   0   0   0   3   0   0
9         අටකින්ද        Value, Math   0   0   0   0   0   1   0
10       පණසකින්ද        Value, Math   0   0   0   0   0   1   0
11          සතරක්        Value, Math   0   0   0   2   0   1   0
12        ඩැහැගෙණ              Thief   0   0   0   0   0   1   0
13           අපාය               Hell   1   0   1   0   0   0   0
14            ඥාන  Wisdom, Knowledge   0   0   0   0   4   0   0
15           නුවණ  Wisdom, Knowledge   0   0   0   0   1   0   0
16           ඥානය  Wisdom, Knowledge   0   0   1   0   0   0   0
17            දත්  Wisdom, Knowledge   0   0   0   0   0   1   0
18        දැනගන්ට  Wisdom, Knowledge   0   0   0   1   0   0   0

In [129]:
sathara_collocates_df_filtered.to_latex('Tex_Files/sathara_collocates_table.tex', index=False, encoding='utf-8-sig')