In [1]:
import pandas as pd

In [2]:
pip install openpyxl

Requirement already satisfied: openpyxl in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/.venv/lib/python3.13/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/.venv/lib/python3.13/site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [3]:
df = pd.read_excel('Collocates/සතර_sub.xlsx')

In [4]:
df

   collocate_word  collocate_meaning   13   14   15   16   18   19   20
0          උගණිත්        Intelligent  NaN  NaN  NaN  NaN  NaN  2.0  NaN
1          උගතමනා                NaN  1.0  1.0  NaN  NaN  NaN  NaN  NaN
2            උගත්                NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0
3      උගතුන්යෙදූ                NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0
4          උගන්වන     Learn, Educate  NaN  NaN  NaN  NaN  NaN  1.0  NaN
5          උගනිව්                NaN  NaN  NaN  NaN  NaN  NaN  1.0  NaN
6           උගනීද                NaN  NaN  NaN  NaN  3.0  NaN  NaN  NaN
7        ඉගනීමෙන්                NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0
8        ඉගැන්වීම                NaN  NaN  NaN  NaN  NaN  NaN  1.0  NaN
9            ඉගෙණ                NaN  NaN  NaN  NaN  NaN  NaN  1.0  NaN
10           ඉගෙන                NaN  2.0  NaN  NaN  1.0  NaN  NaN  NaN
11           සිප්                NaN  NaN  NaN  NaN  NaN  NaN  1.0  1.0
12        සිප්සතර                NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0
13       සිප්සතරා                NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0
14            ගණන        Value, Math  NaN  NaN  NaN  NaN  NaN  NaN  1.0
15          ගණනක්                NaN  NaN  NaN  NaN  NaN  NaN  2.0  NaN
16       ගණනකින්ද                NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0
17           ගණන්                NaN  NaN  NaN  3.0  NaN  NaN  2.0  2.0
18         ගණන්නේ                NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0
19           ගණිත                NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0
20        ගණිතයක්                NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0
21        ගණිතයත්                NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0
22           ගණින                NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0
23            සොර              Thief  1.0  NaN  NaN  NaN  NaN  NaN  NaN
24        සොරාගත්                NaN  1.0  NaN  NaN  NaN  NaN  NaN  NaN
25         සොරුන්                NaN  1.0  1.0  NaN  NaN  NaN  NaN  NaN
26       සොරුන්හා                NaN  NaN  1.0  NaN  NaN  NaN  NaN  NaN
27           අපාය               Hell  1.0  NaN  1.0  NaN  NaN  NaN  NaN
28           ඥාණය  Wisdom, Knowledge  NaN  1.0  NaN  NaN  NaN  NaN  NaN
29            ඥාන                NaN  1.0  1.0  NaN  NaN  4.0  NaN  NaN
30           ඥානය                NaN  1.0  NaN  1.0  NaN  NaN  NaN  NaN
31         ඥානයක්                NaN  NaN  NaN  NaN  NaN  NaN  1.0  NaN
32          ඥානයට                NaN  NaN  NaN  NaN  NaN  NaN  1.0  NaN
33           ඥානා                NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0
34     ඥානාදියෙන්                NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0
35            ඤාණ                NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0
36        ඤාණයෙන්                NaN  NaN  NaN  NaN  NaN  NaN  NaN  1.0
37        ඤාණවන්ත                NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
38           දිශා          Direction  1.0  NaN  NaN  NaN  NaN  NaN  NaN

In [5]:
df = df.fillna('')

In [6]:
df

   collocate_word  collocate_meaning   13   14   15   16   18   19   20
0          උගණිත්        Intelligent                           2.0
1          උගතමනා                     1.0  1.0
2            උගත්                                                   1.0
3      උගතුන්යෙදූ                                                   1.0
4          උගන්වන     Learn, Educate                           1.0
5          උගනිව්                                              1.0
6           උගනීද                                    3.0
7        ඉගනීමෙන්                                                   1.0
8        ඉගැන්වීම                                              1.0
9            ඉගෙණ                                              1.0
10           ඉගෙන                     2.0            1.0
11           සිප්                                              1.0  1.0
12        සිප්සතර                                                   1.0
13       සිප්සතරා                                                   1.0
14            ගණන        Value, Math                                1.0
15          ගණනක්                                              2.0
16       ගණනකින්ද                                                   1.0
17           ගණන්                               3.0            2.0  2.0
18         ගණන්නේ                                                   1.0
19           ගණිත                                                   1.0
20        ගණිතයක්                                                   1.0
21        ගණිතයත්                                                   1.0
22           ගණින                                                   1.0
23            සොර              Thief  1.0
24        සොරාගත්                     1.0
25         සොරුන්                     1.0  1.0
26       සොරුන්හා                          1.0
27           අපාය               Hell  1.0       1.0
28           ඥාණය  Wisdom, Knowledge       1.0
29            ඥාන                     1.0  1.0            4.0
30           ඥානය                     1.0       1.0
31         ඥානයක්                                              1.0
32          ඥානයට                                              1.0
33           ඥානා                                                   1.0
34     ඥානාදියෙන්                                                   1.0
35            ඤාණ                                                   1.0
36        ඤාණයෙන්                                                   1.0
37        ඤාණවන්ත
38           දිශා          Direction  1.0

In [8]:
df.to_latex('Collocates/සතර_sub.tex', index=False, encoding='utf-8-sig')