In [1]:
pip install pandas numpy matplotlib seaborn scikit-learn jupyterlab tabulate

Requirement already satisfied: pandas in ./.venv/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: numpy in ./.venv/lib/python3.13/site-packages (2.4.0)
Requirement already satisfied: matplotlib in ./.venv/lib/python3.13/site-packages (3.10.8)
Requirement already satisfied: seaborn in ./.venv/lib/python3.13/site-packages (0.13.2)
Requirement already satisfied: scikit-learn in ./.venv/lib/python3.13/site-packages (1.8.0)
Requirement already satisfied: jupyterlab in ./.venv/lib/python3.13/site-packages (4.5.1)
Requirement already satisfied: tabulate in ./.venv/lib/python3.13/site-packages (0.9.0)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./.venv/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in ./.venv/lib/python3.13/site-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in ./.venv/lib/python3.13/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in ./.venv/lib/python3.13/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in ./.venv/lib/python3.13/site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in ./.venv/lib/python3.13/site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in ./.venv/lib/python3.13/site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in ./.venv/lib/python3.13/site-packages (from matplotlib) (12.1.0)
Requirement already satisfied: pyparsing>=3 in ./.venv/lib/python3.13/site-packages (from matplotlib) (3.3.1)
Requirement already satisfied: scipy>=1.10.0 in ./.venv/lib/python3.13/site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.3.0 in ./.venv/lib/python3.13/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in ./.venv/lib/python3.13/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: async-lru>=1.0.0 in ./.venv/lib/python3.13/site-packages (from jupyterlab) (2.0.5)
Requirement already satisfied: httpx<1,>=0.25.0 in ./.venv/lib/python3.13/site-packages (from jupyterlab) (0.28.1)
Requirement already satisfied: ipykernel!=6.30.0,>=6.5.0 in ./.venv/lib/python3.13/site-packages (from jupyterlab) (7.1.0)
Requirement already satisfied: jinja2>=3.0.3 in ./.venv/lib/python3.13/site-packages (from jupyterlab) (3.1.6)
Requirement already satisfied: jupyter-core in ./.venv/lib/python3.13/site-packages (from jupyterlab) (5.9.1)
Requirement already satisfied: jupyter-lsp>=2.0.0 in ./.venv/lib/python3.13/site-packages (from jupyterlab) (2.3.0)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in ./.venv/lib/python3.13/site-packages (from jupyterlab) (2.17.0)
Requirement already satisfied: jupyterlab-server<3,>=2.28.0 in ./.venv/lib/python3.13/site-packages (from jupyterlab) (2.28.0)
Requirement already satisfied: notebook-shim>=0.2 in ./.venv/lib/python3.13/site-packages (from jupyterlab) (0.2.4)
Requirement already satisfied: setuptools>=41.1.0 in ./.venv/lib/python3.13/site-packages (from jupyterlab) (80.9.0)
Requirement already satisfied: tornado>=6.2.0 in ./.venv/lib/python3.13/site-packages (from jupyterlab) (6.5.4)
Requirement already satisfied: traitlets in ./.venv/lib/python3.13/site-packages (from jupyterlab) (5.14.3)
Requirement already satisfied: anyio in ./.venv/lib/python3.13/site-packages (from httpx<1,>=0.25.0->jupyterlab) (4.12.0)
Requirement already satisfied: certifi in ./.venv/lib/python3.13/site-packages (from httpx<1,>=0.25.0->jupyterlab) (2026.1.4)
Requirement already satisfied: httpcore==1.* in ./.venv/lib/python3.13/site-packages (from httpx<1,>=0.25.0->jupyterlab) (1.0.9)
Requirement already satisfied: idna in ./.venv/lib/python3.13/site-packages (from httpx<1,>=0.25.0->jupyterlab) (3.11)
Requirement already satisfied: h11>=0.16 in ./.venv/lib/python3.13/site-packages (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab) (0.16.0)
Requirement already satisfied: argon2-cffi>=21.1 in ./.venv/lib/python3.13/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (25.1.0)
Requirement already satisfied: jupyter-client>=7.4.4 in ./.venv/lib/python3.13/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (8.7.0)
Requirement already satisfied: jupyter-events>=0.11.0 in ./.venv/lib/python3.13/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (0.12.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in ./.venv/lib/python3.13/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (0.5.3)
Requirement already satisfied: nbconvert>=6.4.4 in ./.venv/lib/python3.13/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (7.16.6)
Requirement already satisfied: nbformat>=5.3.0 in ./.venv/lib/python3.13/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (5.10.4)
Requirement already satisfied: prometheus-client>=0.9 in ./.venv/lib/python3.13/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (0.23.1)
Requirement already satisfied: pyzmq>=24 in ./.venv/lib/python3.13/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (27.1.0)
Requirement already satisfied: send2trash>=1.8.2 in ./.venv/lib/python3.13/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (2.0.0)
Requirement already satisfied: terminado>=0.8.3 in ./.venv/lib/python3.13/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (0.18.1)
Requirement already satisfied: websocket-client>=1.7 in ./.venv/lib/python3.13/site-packages (from jupyter-server<3,>=2.4.0->jupyterlab) (1.9.0)
Requirement already satisfied: babel>=2.10 in ./.venv/lib/python3.13/site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab) (2.17.0)
Requirement already satisfied: json5>=0.9.0 in ./.venv/lib/python3.13/site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab) (0.13.0)
Requirement already satisfied: jsonschema>=4.18.0 in ./.venv/lib/python3.13/site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab) (4.25.1)
Requirement already satisfied: requests>=2.31 in ./.venv/lib/python3.13/site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab) (2.32.5)
Requirement already satisfied: argon2-cffi-bindings in ./.venv/lib/python3.13/site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab) (25.1.0)
Requirement already satisfied: appnope>=0.1.2 in ./.venv/lib/python3.13/site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab) (0.1.4)
Requirement already satisfied: comm>=0.1.1 in ./.venv/lib/python3.13/site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in ./.venv/lib/python3.13/site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab) (1.8.19)
Requirement already satisfied: ipython>=7.23.1 in ./.venv/lib/python3.13/site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab) (9.9.0)
Requirement already satisfied: matplotlib-inline>=0.1 in ./.venv/lib/python3.13/site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab) (0.2.1)
Requirement already satisfied: nest-asyncio>=1.4 in ./.venv/lib/python3.13/site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab) (1.6.0)
Requirement already satisfied: psutil>=5.7 in ./.venv/lib/python3.13/site-packages (from ipykernel!=6.30.0,>=6.5.0->jupyterlab) (7.2.1)
Requirement already satisfied: decorator>=4.3.2 in ./.venv/lib/python3.13/site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in ./.venv/lib/python3.13/site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab) (1.1.1)
Requirement already satisfied: jedi>=0.18.1 in ./.venv/lib/python3.13/site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab) (0.19.2)
Requirement already satisfied: pexpect>4.3 in ./.venv/lib/python3.13/site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in ./.venv/lib/python3.13/site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab) (3.0.52)
Requirement already satisfied: pygments>=2.11.0 in ./.venv/lib/python3.13/site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab) (2.19.2)
Requirement already satisfied: stack_data>=0.6.0 in ./.venv/lib/python3.13/site-packages (from ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab) (0.6.3)
Requirement already satisfied: wcwidth in ./.venv/lib/python3.13/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab) (0.2.14)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in ./.venv/lib/python3.13/site-packages (from jedi>=0.18.1->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab) (0.8.5)
Requirement already satisfied: MarkupSafe>=2.0 in ./.venv/lib/python3.13/site-packages (from jinja2>=3.0.3->jupyterlab) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in ./.venv/lib/python3.13/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in ./.venv/lib/python3.13/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in ./.venv/lib/python3.13/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in ./.venv/lib/python3.13/site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab) (0.30.0)
Requirement already satisfied: platformdirs>=2.5 in ./.venv/lib/python3.13/site-packages (from jupyter-core->jupyterlab) (4.5.1)
Requirement already satisfied: python-json-logger>=2.0.4 in ./.venv/lib/python3.13/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab) (4.0.0)
Requirement already satisfied: pyyaml>=5.3 in ./.venv/lib/python3.13/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab) (6.0.3)
Requirement already satisfied: rfc3339-validator in ./.venv/lib/python3.13/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in ./.venv/lib/python3.13/site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab) (0.1.1)
Requirement already satisfied: fqdn in ./.venv/lib/python3.13/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab) (1.5.1)
Requirement already satisfied: isoduration in ./.venv/lib/python3.13/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in ./.venv/lib/python3.13/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab) (3.0.0)
Requirement already satisfied: rfc3987-syntax>=1.1.0 in ./.venv/lib/python3.13/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab) (1.1.0)
Requirement already satisfied: uri-template in ./.venv/lib/python3.13/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in ./.venv/lib/python3.13/site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab) (25.10.0)
Requirement already satisfied: beautifulsoup4 in ./.venv/lib/python3.13/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (4.14.3)
Requirement already satisfied: bleach!=5.0.0 in ./.venv/lib/python3.13/site-packages (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (6.3.0)
Requirement already satisfied: defusedxml in ./.venv/lib/python3.13/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in ./.venv/lib/python3.13/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in ./.venv/lib/python3.13/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (3.2.0)
Requirement already satisfied: nbclient>=0.5.0 in ./.venv/lib/python3.13/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (0.10.4)
Requirement already satisfied: pandocfilters>=1.4.1 in ./.venv/lib/python3.13/site-packages (from nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (1.5.1)
Requirement already satisfied: webencodings in ./.venv/lib/python3.13/site-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in ./.venv/lib/python3.13/site-packages (from bleach[css]!=5.0.0->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (1.4.0)
Requirement already satisfied: fastjsonschema>=2.15 in ./.venv/lib/python3.13/site-packages (from nbformat>=5.3.0->jupyter-server<3,>=2.4.0->jupyterlab) (2.21.2)
Requirement already satisfied: ptyprocess>=0.5 in ./.venv/lib/python3.13/site-packages (from pexpect>4.3->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab) (0.7.0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in ./.venv/lib/python3.13/site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->jupyterlab) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.venv/lib/python3.13/site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->jupyterlab) (2.6.2)
Requirement already satisfied: lark>=1.2.2 in ./.venv/lib/python3.13/site-packages (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab) (1.3.1)
Requirement already satisfied: executing>=1.2.0 in ./.venv/lib/python3.13/site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in ./.venv/lib/python3.13/site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab) (3.0.1)
Requirement already satisfied: pure-eval in ./.venv/lib/python3.13/site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel!=6.30.0,>=6.5.0->jupyterlab) (0.2.3)
Requirement already satisfied: cffi>=1.0.1 in ./.venv/lib/python3.13/site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab) (2.0.0)
Requirement already satisfied: pycparser in ./.venv/lib/python3.13/site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab) (2.23)
Requirement already satisfied: soupsieve>=1.6.1 in ./.venv/lib/python3.13/site-packages (from beautifulsoup4->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (2.8.1)
Requirement already satisfied: typing-extensions>=4.0.0 in ./.venv/lib/python3.13/site-packages (from beautifulsoup4->nbconvert>=6.4.4->jupyter-server<3,>=2.4.0->jupyterlab) (4.15.0)
Requirement already satisfied: arrow>=0.15.0 in ./.venv/lib/python3.13/site-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab) (1.4.0)

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
import os
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
def get_written_dates_and_any_text_file_locations_to_dataframe(root_folder):
    print(f"--- Starting Scan for metadata.json and any associated non-JSON text files ---")
    print(f"Scanning root folder: {os.path.abspath(root_folder)}\n")

    if not os.path.exists(root_folder):
        print(f"Error: The root folder '{root_folder}' does not exist at '{os.path.abspath(root_folder)}'.")
        return pd.DataFrame()

    data_for_df = []
    
    for dirpath, dirnames, filenames in os.walk(root_folder):
        metadata_filepath_in_dir = None
        text_file_path_in_dir = None
        
        non_json_files = []

        # First, identify the metadata.json and any non-JSON files in the current directory
        for filename in filenames:
            if filename.lower() == "metadata.json":
                metadata_filepath_in_dir = os.path.join(dirpath, filename)
            elif filename.lower().endswith(".txt"): # Consider anything that's not JSON as a potential text file
                non_json_files.append(os.path.join(dirpath, filename))

        # Check conditions for a valid pair
        if metadata_filepath_in_dir:
            if len(non_json_files) == 1:
                # Exactly one non-JSON file found, assume it's the text file
                text_file_path_in_dir = non_json_files[0]
                
                print(f"Processing directory: {os.path.abspath(dirpath)}")
                print(f"  Found metadata.json: {metadata_filepath_in_dir}")
                print(f"  Found associated text file: {text_file_path_in_dir}")

                extracted_written_date = None
                genre = None
                title_en = None
                try:
                    with open(metadata_filepath_in_dir, 'r', encoding='utf-8') as f:
                        metadata = json.load(f)
                        if 'title' in metadata:
                            title = metadata['title']
                            print(f"  Extracted 'title': '{title}'")
                        else:
                            print(f"  Warning: 'title' key NOT found in {metadata_filepath_in_dir}. Setting to None for this entry.")
                        
                        if 'title_en' in metadata:
                            title_en = metadata['title_en']
                            print(f"  Extracted 'title_en': '{title_en}'")
                        else:
                            print(f"  Warning: 'title_en' key NOT found in {metadata_filepath_in_dir}. Setting to None for this entry.")
                        
                        if 'author' in metadata:
                            author = metadata['author']
                            print(f"  Extracted 'author': '{author}'")
                        else:
                            print(f"  Warning: 'author' key NOT found in {metadata_filepath_in_dir}. Setting to None for this entry.")

                        if 'author_en' in metadata:
                            author_en = metadata['author_en']
                            print(f"  Extracted 'author_en': '{author_en}'")
                        else:
                            author_en = 'Unknown'
                            print(f"  Warning: 'author_en' key NOT found in {metadata_filepath_in_dir}. Setting to None for this entry.")
                        
                        if 'author_en' in metadata:
                            author_en = metadata['author_en']
                            print(f"  Extracted 'author_en': '{author_en}'")
                        else:
                            author_en = 'Unknown'
                            print(f"  Warning: 'author_en' key NOT found in {metadata_filepath_in_dir}. Setting to None for this entry.")

                        if 'issued_date' in metadata:
                            extracted_issued_date = metadata['issued_date']
                            print(f"  Extracted 'written_date': '{extracted_issued_date}'")
                        else:
                            print(f"  Warning: 'issued_date' key NOT found in {metadata_filepath_in_dir}. Setting to None for this entry.")

                        if 'written_date' in metadata:
                            extracted_written_date = metadata['written_date']
                            print(f"  Extracted 'written_date': '{extracted_written_date}'")
                        else:
                            print(f"  Warning: 'written_date' key NOT found in {metadata_filepath_in_dir}. Setting to None for this entry.")
    

                        if 'genre' in metadata:
                            genre = metadata['genre']
                            print(f"  Extracted 'genre': '{genre}'")
                        else:
                            print(f"  Warning: 'genre' key NOT found in {metadata_filepath_in_dir}. Setting to None for this entry.")

                        if 'ocr_confidence' in metadata:
                            ocr_confidence = metadata['ocr_confidence']
                            print(f"  Extracted 'ocr_confidence': '{ocr_confidence}'")
                        else:
                            print(f"  Warning: 'ocr_confidence' key NOT found in {metadata_filepath_in_dir}. Setting to None for this entry.")

                except json.JSONDecodeError as e:
                    print(f"  Error: Could not parse JSON from {metadata_filepath_in_dir}: {e}. Setting 'written_date' to None.")
                except Exception as e:
                    print(f"  An unexpected error occurred reading {metadata_filepath_in_dir}: {e}. Setting 'written_date' to None.")
                
                # Add this pair to our DataFrame data
                data_for_df.append({
                    'title': title,
                    'title_en': title_en,
                    'author': author,
                    'author_en': author_en,
                    'issued_date': extracted_issued_date,
                    'written_date': extracted_written_date,
                    'genre': genre,
                    'text_file_location': os.path.abspath(text_file_path_in_dir),
                    'ocr_confidence': ocr_confidence
                })
                
            elif len(non_json_files) == 0:
                print(f"  Note: Found metadata.json in {os.path.abspath(dirpath)} but NO non-JSON text file found. Skipping this directory.")
            else: # len(non_json_files) > 1
                print(f"  Warning: Found metadata.json in {os.path.abspath(dirpath)} but MULTIPLE non-JSON files ({non_json_files}). Cannot determine which is the text file. Skipping this directory.")
        # No else for when metadata.json is not found at all, to keep output cleaner

    print(f"\n--- Scan Complete ---")
    print(f"Total valid pairs (metadata.json + single non-JSON text file): {len(data_for_df)}")
    
    df = pd.DataFrame(data_for_df)

    if df.empty:
        print("No valid pairs of metadata.json and single non-JSON text file found to create a DataFrame.")
    else:
        print("\n--- Resulting DataFrame Head ---")
        print(df.head())
        print(f"\nDataFrame has {len(df)} rows and {len(df.columns)} columns.")
    
    return df

In [4]:
root_directory_to_scan = "data/OCR_Final"

list_of_file_locations = get_written_dates_and_any_text_file_locations_to_dataframe(root_directory_to_scan)

--- Starting Scan for metadata.json and any associated non-JSON text files ---
Scanning root folder: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final

Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/ධර්ම ප්‍රදීපිකාව හෙවත් මහාබෝධිවංශ පරිකථාව
  Found metadata.json: data/OCR_Final/ධර්ම ප්‍රදීපිකාව හෙවත් මහාබෝධිවංශ පරිකථාව/metadata.json
  Found associated text file: data/OCR_Final/ධර්ම ප්‍රදීපිකාව හෙවත් මහාබෝධිවංශ පරිකථාව/ධර්ම ප්‍රදීපිකාව හෙවත් මහාබෝධිවංශ පරිකථාව.txt
  Extracted 'title': 'ධර්ම ප්‍රදීපිකාව හෙවත් මහාබෝධිවංශ පරිකථාව'
  Extracted 'title_en': 'Dharma Pradheepikawa hewath Mahabodhiwansha Parikathawa'
  Extracted 'author': 'Unknown'
  Warning: 'author_en' key NOT found in data/OCR_Final/ධර්ම ප්‍රදීපිකාව හෙවත් මහාබෝධිවංශ පරිකථාව/metadata.json. Setting to None for this entry.
  Warning: 'author_en' key NOT found in data/OCR_Final/ධර්ම ප්‍රදීපිකාව හෙවත් මහාබෝධිවංශ පරිකථාව/metadata.json. Setting to None for this entry.
  Extracted 'written_date': '1906'
  Extracted 'written_date': '1187 - 1225'
  Extracted 'genre': 'Non-Fiction; Religious'
  Extracted 'ocr_confidence': '0.9682'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/දුක්ඛ සත්‍ය වර්ණනා
  Found metadata.json: data/OCR_Final/දුක්ඛ සත්‍ය වර්ණනා/metadata.json
  Found associated text file: data/OCR_Final/දුක්ඛ සත්‍ය වර්ණනා/දුක්ඛ සත්‍ය වර්ණනා.txt
  Extracted 'title': 'දුක්ඛ සත්‍ය වර්ණනා'
  Extracted 'title_en': 'Dhukka Sathya Warnanaa'
  Extracted 'author': 'එම්.යූ කවීශ්වර හිමි'
  Extracted 'author_en': 'M.U Kaweeshwara Himi'
  Extracted 'author_en': 'M.U Kaweeshwara Himi'
  Extracted 'written_date': '1925'
  Extracted 'written_date': ''
  Extracted 'genre': 'Non-Fiction; Religious'
  Extracted 'ocr_confidence': '0.9887'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/ටිබැට් රටේ බුදුදහම
  Found metadata.json: data/OCR_Final/ටිබැට් රටේ බුදුදහම/metadata.json
  Found associated text file: data/OCR_Final/ටිබැට් රටේ බුදුදහම/ටිබැට් රටේ බුදුදහම.txt
  Extracted 'title': 'ටිබැට් රටේ බුදුදහම'
  Extracted 'title_en': 'Tibet Rate Budhudhahama'
  Extracted 'author': 'හෙන්රි එස් ඕල්කට්'
  Extracted 'author_en': 'Hendry S Olkat'
  Extracted 'author_en': 'Hendry S Olkat'
  Extracted 'written_date': '1897'
  Extracted 'written_date': '1832 - 1907'
  Extracted 'genre': 'Non-Fiction; Religious'
  Extracted 'ocr_confidence': '0.9973'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/නිදහසේ මන්ත්‍රය
  Found metadata.json: data/OCR_Final/නිදහසේ මන්ත්‍රය/metadata.json
  Found associated text file: data/OCR_Final/නිදහසේ මන්ත්‍රය/නිදහසේ මන්ත්‍රය.txt
  Extracted 'title': 'නිදහසේ මන්ත්‍රය'
  Extracted 'title_en': 'Nidhahase Manthraya'
  Extracted 'author': 'ඇස් මහින්ද හිමි'
  Extracted 'author_en': 'S. Mahinda Himi'
  Extracted 'author_en': 'S. Mahinda Himi'
  Extracted 'written_date': '1938'
  Extracted 'written_date': '1901 - 1938'
  Extracted 'genre': 'Non-Fiction; Poetry'
  Extracted 'ocr_confidence': '0.8997'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/පැරණි ගම
  Found metadata.json: data/OCR_Final/පැරණි ගම/metadata.json
  Found associated text file: data/OCR_Final/පැරණි ගම/පැරණි ගම.txt
  Extracted 'title': 'පැරණි ගම'
  Extracted 'title_en': 'Parani Gama'
  Extracted 'author': 'ගල්පාත ඛේමානන්ද හිමි'
  Extracted 'author_en': 'Galpatha Kemanandha Himi'
  Extracted 'author_en': 'Galpatha Kemanandha Himi'
  Extracted 'written_date': '1944'
  Extracted 'written_date': '1944'
  Extracted 'genre': 'Non-Fiction; History'
  Extracted 'ocr_confidence': '0.9846'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/පන්සිය පනස් ජාතක පොත
  Found metadata.json: data/OCR_Final/පන්සිය පනස් ජාතක පොත/metadata.json
  Found associated text file: data/OCR_Final/පන්සිය පනස් ජාතක පොත/පන්සිය පනස් ජාතක පොත.txt
  Extracted 'title': 'පන්සිය පනස් ජාතක පොත'
  Extracted 'title_en': 'Pansiya Panas Jathaka Potha'
  Extracted 'author': 'Unknown'
  Warning: 'author_en' key NOT found in data/OCR_Final/පන්සිය පනස් ජාතක පොත/metadata.json. Setting to None for this entry.
  Warning: 'author_en' key NOT found in data/OCR_Final/පන්සිය පනස් ජාතක පොත/metadata.json. Setting to None for this entry.
  Extracted 'written_date': '1881'
  Extracted 'written_date': '1303 - 1333'
  Extracted 'genre': 'Fiction; Religious'
  Extracted 'ocr_confidence': '0.9987'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/හිතෝපදේශ සන්නය
  Found metadata.json: data/OCR_Final/හිතෝපදේශ සන්නය/metadata.json
  Found associated text file: data/OCR_Final/හිතෝපදේශ සන්නය/හිතෝපදේශ සන්නය.txt
  Extracted 'title': 'හිතෝපදේශ සන්නය'
  Extracted 'title_en': 'Hithopadhesha Sannaya'
  Extracted 'author': 'වැලිගම ශ්‍රී සුමංගල හිමි'
  Extracted 'author_en': 'Waligama Sri Sumangala Himi'
  Extracted 'author_en': 'Waligama Sri Sumangala Himi'
  Extracted 'written_date': '1884'
  Extracted 'written_date': '1825 - 1905'
  Extracted 'genre': 'Non-Fiction'
  Extracted 'ocr_confidence': '0.9871'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/කඩවර දීම සහ තුන්සමයන් පෙළපාලිය
  Found metadata.json: data/OCR_Final/කඩවර දීම සහ තුන්සමයන් පෙළපාලිය/metadata.json
  Found associated text file: data/OCR_Final/කඩවර දීම සහ තුන්සමයන් පෙළපාලිය/කඩවර දීම සහ තුන්සමයන් පෙළපාලිය.txt
  Extracted 'title': 'කඩවර දීම සහ තුන්සමයන් පෙළපාලිය'
  Extracted 'title_en': 'Kadawara Dheema saha Thunsamayan Pelapaaliya'
  Extracted 'author': 'ජී.ජී. ලුවිස් අප්පුහාමි'
  Extracted 'author_en': 'G. G. Lewis Appuhaami'
  Extracted 'author_en': 'G. G. Lewis Appuhaami'
  Extracted 'written_date': '1950'
  Extracted 'written_date': ''
  Extracted 'genre': 'Fiction; Poetry'
  Extracted 'ocr_confidence': '0.9629'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/අධිමාසභේදය
  Found metadata.json: data/OCR_Final/අධිමාසභේදය/metadata.json
  Found associated text file: data/OCR_Final/අධිමාසභේදය/අධිමාසභේදය.txt
  Extracted 'title': 'අධිමාසභේදය'
  Extracted 'title_en': 'Adhimasabhedhaya'
  Extracted 'author': 'අඹගහපිටියේ බුද්ධසිරිතිස්ස හිමි'
  Extracted 'author_en': 'Abhagahapitiye Bhudhdhasirithissa Himi'
  Extracted 'author_en': 'Abhagahapitiye Bhudhdhasirithissa Himi'
  Extracted 'written_date': '1895'
  Extracted 'written_date': ''
  Extracted 'genre': 'Non-Fiction; Religious'
  Extracted 'ocr_confidence': '0.9753'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/අධිමාස සංග්‍රහව
  Found metadata.json: data/OCR_Final/අධිමාස සංග්‍රහව/metadata.json
  Found associated text file: data/OCR_Final/අධිමාස සංග්‍රහව/අධිමාස සංග්‍රහව.txt
  Extracted 'title': 'අධිමාස සංග්‍රහව'
  Extracted 'title_en': 'Adhimasa Sangrahawa'
  Extracted 'author': 'මාදම්පේ ධම්මතිලක හිමි'
  Extracted 'author_en': 'Madhampe Dhammathilaka Himi'
  Extracted 'author_en': 'Madhampe Dhammathilaka Himi'
  Extracted 'written_date': '1903'
  Extracted 'written_date': '1850 - 1903'
  Extracted 'genre': 'Non-Fiction; Religious'
  Extracted 'ocr_confidence': '0.9692'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/සත්‍යාර්ථදීපනිය
  Found metadata.json: data/OCR_Final/සත්‍යාර්ථදීපනිය/metadata.json
  Found associated text file: data/OCR_Final/සත්‍යාර්ථදීපනිය/සත්‍යාර්ථදීපනිය.txt
  Extracted 'title': 'සත්‍යාර්ථදීපනිය'
  Extracted 'title_en': 'Sathyaarthadheepanaya'
  Extracted 'author': 'වාගීශ්වර මාලාලංකාර ස්ථවිර'
  Extracted 'author_en': 'Waasheeshwara Maalaalankaara Sthawira'
  Extracted 'author_en': 'Waasheeshwara Maalaalankaara Sthawira'
  Extracted 'written_date': '1912'
  Extracted 'written_date': ''
  Extracted 'genre': 'Non-Fiction; Religious'
  Extracted 'ocr_confidence': '0.9961'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/දහම් සරණ.txt
  Found metadata.json: data/OCR_Final/දහම් සරණ.txt/metadata.json
  Found associated text file: data/OCR_Final/දහම් සරණ.txt/දහම් සරණ.txt
  Extracted 'title': 'දහම් සරණ'
  Extracted 'title_en': 'Dhaham Sarana'
  Extracted 'author': 'Unknown'
  Warning: 'author_en' key NOT found in data/OCR_Final/දහම් සරණ.txt/metadata.json. Setting to None for this entry.
  Warning: 'author_en' key NOT found in data/OCR_Final/දහම් සරණ.txt/metadata.json. Setting to None for this entry.
  Extracted 'written_date': '1931'
  Extracted 'written_date': '1220 - 1293'
  Extracted 'genre': 'Fiction; Religious'
  Extracted 'ocr_confidence': '0.9891'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/සඟබත් බෙදුම හෙවත් තුන්වන සඟබත බෙදුම පිළිබඳ විභාගය
  Found metadata.json: data/OCR_Final/සඟබත් බෙදුම හෙවත් තුන්වන සඟබත බෙදුම පිළිබඳ විභාගය/metadata.json
  Found associated text file: data/OCR_Final/සඟබත් බෙදුම හෙවත් තුන්වන සඟබත බෙදුම පිළිබඳ විභාගය/සඟබත් බෙදුම හෙවත් තුන්වන සඟබත බෙදුම පිළිබඳ විභාගය.txt
  Extracted 'title': 'සඟබත් බෙදුම හෙවත් තුන්වන සඟබත බෙදුම පිළිබඳ විභාගය'
  Extracted 'title_en': 'Sangabath Bedhuma hewath Thunwana Sangabatha Bedhuma Pilibandha Wibhaagaya'
  Extracted 'author': 'පානදුර ඤානවිමලතිස්ස හිමි'
  Extracted 'author_en': 'Panadura Nyaanawimalathissa Himi'
  Extracted 'author_en': 'Panadura Nyaanawimalathissa Himi'
  Extracted 'written_date': '1896'
  Extracted 'written_date': ''
  Extracted 'genre': 'Non-Fiction; Religious'
  Extracted 'ocr_confidence': '0.9811'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/මධුර මනෝහර කථාවස්තූන් සඋදාහරණ කොට සන්න කරණ ලද පරාභව සූත්‍රය
  Found metadata.json: data/OCR_Final/මධුර මනෝහර කථාවස්තූන් සඋදාහරණ කොට සන්න කරණ ලද පරාභව සූත්‍රය/metadata.json
  Found associated text file: data/OCR_Final/මධුර මනෝහර කථාවස්තූන් සඋදාහරණ කොට සන්න කරණ ලද පරාභව සූත්‍රය/මධුර මනෝහර කථාවස්තූන් සඋදාහරණ කොට සන්න කරණ ලද පරාභව සූත්‍රය.txt
  Extracted 'title': 'මධුර මනෝහර කථාවස්තූන් සඋදාහරණ කොට සන්න කරණ ලද පරාභව සූත්‍රය'
  Extracted 'title_en': 'Madhura Manohara Kathawasthuun Saudhaaharana Kota Sanna Karana Ladha Paraabhawa Suthraya'
  Extracted 'author': 'කලුතර සාරානන්ද හිමි'
  Extracted 'author_en': 'Kaluthara Saaraanandha Himi'
  Extracted 'author_en': 'Kaluthara Saaraanandha Himi'
  Extracted 'written_date': '1891'
  Extracted 'written_date': ''
  Extracted 'genre': 'Non-Fiction; Religious'
  Extracted 'ocr_confidence': '0.9961'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/සූත්‍රසංග්‍රහව
  Found metadata.json: data/OCR_Final/සූත්‍රසංග්‍රහව/metadata.json
  Found associated text file: data/OCR_Final/සූත්‍රසංග්‍රහව/සූත්‍රසංග්‍රහව.txt
  Extracted 'title': 'සූත්‍රසංග්‍රහව'
  Extracted 'title_en': 'Suthrasangrahawa'
  Extracted 'author': 'වස්කඩුවේ මේදභිතිස්ස හිමි'
  Extracted 'author_en': 'Waskaduwe Medhabithissa Thero'
  Extracted 'author_en': 'Waskaduwe Medhabithissa Thero'
  Extracted 'written_date': '1935'
  Extracted 'written_date': ''
  Extracted 'genre': 'Non-Fiction; Religious'
  Extracted 'ocr_confidence': '0.9807'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/දුර්වාදී හෘදය විදාරණය
  Found metadata.json: data/OCR_Final/දුර්වාදී හෘදය විදාරණය/metadata.json
  Found associated text file: data/OCR_Final/දුර්වාදී හෘදය විදාරණය/දුර්වාදී හෘදය විදාරණය.txt
  Extracted 'title': 'දුර්වාදී හෘදය විදාරණය'
  Extracted 'title_en': 'Dhurwadhi Hardhaya Widharanaya'
  Extracted 'author': 'ශ්‍රී ධනුද්ධරාචාර්ය'
  Extracted 'author_en': 'Sri Dhanudhdharacharya'
  Extracted 'author_en': 'Sri Dhanudhdharacharya'
  Extracted 'written_date': '1899'
  Extracted 'written_date': '1854 - 1899'
  Extracted 'genre': 'Non-Fiction; Religious'
  Extracted 'ocr_confidence': '0.9919'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/ශ්‍රද්‍රනීර්ණයදර්පණය
  Found metadata.json: data/OCR_Final/ශ්‍රද්‍රනීර්ණයදර්පණය/metadata.json
  Found associated text file: data/OCR_Final/ශ්‍රද්‍රනීර්ණයදර්පණය/ශ්‍රද්‍රනීර්ණයදර්පණය.txt
  Extracted 'title': 'ශුද්‍රනීර්ණයදර්පණය'
  Extracted 'title_en': 'Shudhraneernayadharpanaya'
  Extracted 'author': 'ශ්‍රී කවිරාජසිංහ'
  Extracted 'author_en': 'Sri Kawiraajasinha'
  Extracted 'author_en': 'Sri Kawiraajasinha'
  Extracted 'written_date': '1895'
  Extracted 'written_date': ''
  Extracted 'genre': 'Non-Fiction; Religious'
  Extracted 'ocr_confidence': '0.9975'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/විමතිඡේදකය
  Found metadata.json: data/OCR_Final/විමතිඡේදකය/metadata.json
  Found associated text file: data/OCR_Final/විමතිඡේදකය/විමතිඡේදකය.txt
  Extracted 'title': 'විමතිඡේදකය'
  Extracted 'title_en': 'Wimathichedhakaya'
  Extracted 'author': 'මාදම්පේ සිරිධම්මතිලක හිමි'
  Extracted 'author_en': 'Madhampe Siridhammathilaka Himi'
  Extracted 'author_en': 'Madhampe Siridhammathilaka Himi'
  Extracted 'written_date': '1911'
  Extracted 'written_date': ''
  Extracted 'genre': 'Non-Fiction; Religious'
  Extracted 'ocr_confidence': '0.9933'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/විස්තරාර්ථ ග්‍රන්ථිපද විවර්ණය සහිත සිංහල විමානවස්තූප්‍රකරණය
  Found metadata.json: data/OCR_Final/විස්තරාර්ථ ග්‍රන්ථිපද විවර්ණය සහිත සිංහල විමානවස්තූප්‍රකරණය/metadata.json
  Found associated text file: data/OCR_Final/විස්තරාර්ථ ග්‍රන්ථිපද විවර්ණය සහිත සිංහල විමානවස්තූප්‍රකරණය/විස්තරාර්ථ ග්‍රන්ථිපද විවර්ණය සහිත සිංහල විමානවස්තූප්‍රකරණය.txt
  Extracted 'title': 'විස්තරාර්ථ ග්‍රන්ථිපද විවර්ණය සහිත සිංහල විමානවස්තූප්‍රකරණය'
  Extracted 'title_en': 'Wistharaartha Granthipadha Wiwarnaya sahitha Sinhala Wimaanawasthuuprakarana'
  Extracted 'author': 'ඩී.බී.කේ. ගුණතිලක රාජකරුණා දිසානායක'
  Extracted 'author_en': 'D.B.K. Gunathilaka Raajakarunaa Dissanayake'
  Extracted 'author_en': 'D.B.K. Gunathilaka Raajakarunaa Dissanayake'
  Extracted 'written_date': '1925'
  Extracted 'written_date': '1469 - 1815'
  Extracted 'genre': 'Non-Fiction; Religious'
  Extracted 'ocr_confidence': '0.9882'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/ද්‍රව්‍ය ගුණදර්පණ සන්නය
  Found metadata.json: data/OCR_Final/ද්‍රව්‍ය ගුණදර්පණ සන්නය/metadata.json
  Found associated text file: data/OCR_Final/ද්‍රව්‍ය ගුණදර්පණ සන්නය/ද්‍රව්‍ය ගුණදර්පණ සන්නය.txt
  Extracted 'title': 'ද්‍රව්‍ය ගුණදර්පණ සන්නය'
  Extracted 'title_en': 'Dhrawya Gunadharpana Sannaya'
  Extracted 'author': 'Unknown'
  Extracted 'author_en': 'Unknown'
  Extracted 'author_en': 'Unknown'
  Extracted 'written_date': '1907'
  Extracted 'written_date': ''
  Extracted 'genre': 'Non-Fiction'
  Extracted 'ocr_confidence': '0.9935'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/මහාකප්පිත නරේන්ද්‍ර චරිතය
  Found metadata.json: data/OCR_Final/මහාකප්පිත නරේන්ද්‍ර චරිතය/metadata.json
  Found associated text file: data/OCR_Final/මහාකප්පිත නරේන්ද්‍ර චරිතය/මහාකප්පිත නරේන්ද්‍ර චරිතය.txt
  Extracted 'title': 'මහාකප්පිත නරේන්ද්‍ර චරිතය'
  Extracted 'title_en': 'Mahaakappitha Narendhra Charithaya'
  Extracted 'author': 'Unknown'
  Extracted 'author_en': 'Unknown'
  Extracted 'author_en': 'Unknown'
  Extracted 'written_date': '1924'
  Extracted 'written_date': ''
  Extracted 'genre': 'Fiction; Poetry'
  Extracted 'ocr_confidence': '0.906'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/අවවාද පරිච්ජේදය
  Found metadata.json: data/OCR_Final/අවවාද පරිච්ජේදය/metadata.json
  Found associated text file: data/OCR_Final/අවවාද පරිච්ජේදය/අවවාද පරිච්ජේදය.txt
  Extracted 'title': 'අවවාද පරිච්ජේදය'
  Extracted 'title_en': 'Awawaadha Parichchedhaya'
  Extracted 'author': 'Unknown'
  Extracted 'author_en': 'Unknown'
  Extracted 'author_en': 'Unknown'
  Extracted 'written_date': '1926'
  Extracted 'written_date': ''
  Extracted 'genre': 'Non-Fiction; Religious'
  Extracted 'ocr_confidence': '0.9983'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/සිගාලෝවාද සූත්‍රය - සන්න සහිතයි
  Found metadata.json: data/OCR_Final/සිගාලෝවාද සූත්‍රය - සන්න සහිතයි/metadata.json
  Found associated text file: data/OCR_Final/සිගාලෝවාද සූත්‍රය - සන්න සහිතයි/සිගාලෝවාද සූත්‍රය - සන්න සහිතයි.txt
  Extracted 'title': 'සිගාලෝවාද සූත්‍රය - සන්න සහිතයි'
  Extracted 'title_en': 'Sigaalowaadha Suthraya - Sanna Sahithai'
  Extracted 'author': 'Unknown'
  Extracted 'author_en': 'Unknown'
  Extracted 'author_en': 'Unknown'
  Extracted 'written_date': '1874'
  Extracted 'written_date': ''
  Extracted 'genre': 'Non-Fiction; Religious'
  Extracted 'ocr_confidence': '0.9988'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/කැලණි හෑල්ල
  Found metadata.json: data/OCR_Final/කැලණි හෑල්ල/metadata.json
  Found associated text file: data/OCR_Final/කැලණි හෑල්ල/කැලණි හෑල්ල.txt
  Extracted 'title': 'කැලණි හෑල්ල'
  Extracted 'title_en': 'Kalani Haalla'
  Extracted 'author': 'Unknown'
  Extracted 'author_en': 'Unknown'
  Extracted 'author_en': 'Unknown'
  Extracted 'written_date': '1933'
  Extracted 'written_date': ''
  Extracted 'genre': 'Fiction; Poetry'
  Extracted 'ocr_confidence': '0.9659'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/දශ පොරොන්දම සහ අංගවිනිස්චය
  Found metadata.json: data/OCR_Final/දශ පොරොන්දම සහ අංගවිනිස්චය/metadata.json
  Found associated text file: data/OCR_Final/දශ පොරොන්දම සහ අංගවිනිස්චය/දශ පොරොන්දම සහ අංගවිනිස්චය.txt
  Extracted 'title': 'දශ පොරොන්දම සහ අංගවිනිස්චය'
  Extracted 'title_en': 'Dhasha Porondhama saha Angawinischaya'
  Extracted 'author': 'Unknown'
  Extracted 'author_en': 'Unknown'
  Extracted 'author_en': 'Unknown'
  Extracted 'written_date': '1915'
  Extracted 'written_date': ''
  Extracted 'genre': 'Fiction; Poetry'
  Extracted 'ocr_confidence': '0.9573'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/රුවන්මල් නිඝන්ටුව හෙවත් නාමරතන මාලාව
  Found metadata.json: data/OCR_Final/රුවන්මල් නිඝන්ටුව හෙවත් නාමරතන මාලාව/metadata.json
  Found associated text file: data/OCR_Final/රුවන්මල් නිඝන්ටුව හෙවත් නාමරතන මාලාව/රුවන්මල් නිඝන්ටුව හෙවත් නාමරතන මාලාව.txt
  Extracted 'title': 'රුවන්මල් නිඝන්ටුව හෙවත් නාමරතන මාලාව'
  Extracted 'title_en': 'Ruwanmal Nigantuwa hewath Naamarathana Maalawa'
  Extracted 'author': 'හයවෙනි ශ්‍රී පරාක්‍රමබාහු රජතුමා; ඩී.පී. ද අල්විස් විජයසේකර'
  Extracted 'author_en': 'Hayaweni Sri Parakramabahu Rajathumaa; D.P. de Alwis Wijesekara'
  Extracted 'author_en': 'Hayaweni Sri Parakramabahu Rajathumaa; D.P. de Alwis Wijesekara'
  Extracted 'written_date': '1914'
  Extracted 'written_date': '1412 - 1467'
  Extracted 'genre': 'Non-Fiction; Language'
  Extracted 'ocr_confidence': '0.9662'
Processing directory: /Users/nevidujayatilleke/Documents/MSC - Research/OCR of Corpus/SiDiaC-v.2.0/data/OCR_Final/වෛද්‍ය චින්තාමනි භෛෂද්‍ය සංග්‍රහව
  Found metadata.json: data/OCR_Final/වෛද්‍ය චින්තාමනි භෛෂද්‍ය සංග්‍රහව/metadata.json
  Found associated text file: data/OCR_Final/වෛද්‍ය චින්තාමනි භෛෂද්‍ය සංග්‍රහව/වෛද්‍ය චින්තාමනි භෛෂද්‍ය සංග්‍රහව.txt
  Extracted 'title': 'වෛද්‍ය චින්තාමනි භෛෂද්‍ය සංග්‍රහව'
  Extracted 'title_en': 'Waidya Chinthamani Baishadhya Sangrahawa'
  Extracted 'author': 'Unknown'

In [5]:
list_of_file_locations.head()

,title,title_en,author,author_en,issued_date,written_date,genre,text_file_location,ocr_confidence
0,ධර්ම ප්‍රදීපිකාව හෙවත් මහාබෝධිවංශ පරිකථාව,Dharma Pradheepikawa hewath Mahabodhiwansha Pa...,Unknown,Unknown,1906,1187 - 1225,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9682
1,දුක්ඛ සත්‍ය වර්ණනා,Dhukka Sathya Warnanaa,එම්.යූ කවීශ්වර හිමි,M.U Kaweeshwara Himi,1925,,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9887
2,ටිබැට් රටේ බුදුදහම,Tibet Rate Budhudhahama,හෙන්රි එස් ඕල්කට්,Hendry S Olkat,1897,1832 - 1907,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9973
3,නිදහසේ මන්ත්‍රය,Nidhahase Manthraya,ඇස් මහින්ද හිමි,S. Mahinda Himi,1938,1901 - 1938,Non-Fiction; Poetry,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.8997
4,පැරණි ගම,Parani Gama,ගල්පාත ඛේමානන්ද හිමි,Galpatha Kemanandha Himi,1944,1944,Non-Fiction; History,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9846

In [6]:
list_of_file_locations['issued_date'] = pd.to_datetime(
    list_of_file_locations['issued_date']
)

In [7]:
list_of_file_locations['issued_date'].head()

0   1906-01-01
1   1925-01-01
2   1897-01-01
3   1938-01-01
4   1944-01-01
Name: issued_date, dtype: datetime64[ns]

In [8]:
year_only = list_of_file_locations['issued_date'].dt.year.astype('Int64')

In [9]:
list_of_file_locations['issued_date'] = list_of_file_locations['issued_date'].dt.year.astype('Int64')

In [10]:
list_of_file_locations['issued_date'].head()

0    1906
1    1925
2    1897
3    1938
4    1944
Name: issued_date, dtype: Int64

In [11]:
list_of_file_locations['issued_date'].describe()

count          185.0
mean     1910.135135
std        24.812517
min           1800.0
25%           1894.0
50%           1908.0
75%           1930.0
max           1955.0
Name: issued_date, dtype: Float64

In [12]:
list_of_file_locations[['primaryGenre', 'secondaryGenre']] = list_of_file_locations['genre'].str.split('; ', expand=True)

In [13]:
list_of_file_locations.head()

,title,title_en,author,author_en,issued_date,written_date,genre,text_file_location,ocr_confidence,primaryGenre,secondaryGenre
0,ධර්ම ප්‍රදීපිකාව හෙවත් මහාබෝධිවංශ පරිකථාව,Dharma Pradheepikawa hewath Mahabodhiwansha Pa...,Unknown,Unknown,1906,1187 - 1225,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9682,Non-Fiction,Religious
1,දුක්ඛ සත්‍ය වර්ණනා,Dhukka Sathya Warnanaa,එම්.යූ කවීශ්වර හිමි,M.U Kaweeshwara Himi,1925,,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9887,Non-Fiction,Religious
2,ටිබැට් රටේ බුදුදහම,Tibet Rate Budhudhahama,හෙන්රි එස් ඕල්කට්,Hendry S Olkat,1897,1832 - 1907,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9973,Non-Fiction,Religious
3,නිදහසේ මන්ත්‍රය,Nidhahase Manthraya,ඇස් මහින්ද හිමි,S. Mahinda Himi,1938,1901 - 1938,Non-Fiction; Poetry,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.8997,Non-Fiction,Poetry
4,පැරණි ගම,Parani Gama,ගල්පාත ඛේමානන්ද හිමි,Galpatha Kemanandha Himi,1944,1944,Non-Fiction; History,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9846,Non-Fiction,History

In [14]:
len(list_of_file_locations)

185

In [15]:
list_of_file_locations['primaryGenre'].value_counts()

primaryGenre
Non-Fiction    135
Fiction         50
Name: count, dtype: int64

In [16]:
list_of_file_locations['secondaryGenre'].value_counts()

secondaryGenre
Religious    86
Poetry       54
History      18
Language     17
Medical       5
Name: count, dtype: int64

In [17]:
list_of_file_locations['secondaryGenre'].fillna('NA', inplace=True)

/var/folders/p0/y_n4880x7cjbhx11tzvvqpzh0000gn/T/ipykernel_39836/1341505363.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  list_of_file_locations['secondaryGenre'].fillna('NA', inplace=True)

In [18]:
list_of_file_locations['secondaryGenre'].value_counts()

secondaryGenre
Religious    86
Poetry       54
History      18
Language     17
NA            5
Medical       5
Name: count, dtype: int64

In [19]:
confusion_matrix_1 = pd.crosstab(list_of_file_locations['primaryGenre'], list_of_file_locations['secondaryGenre'], margins=True, margins_name='Total')
confusion_matrix_1 = confusion_matrix_1.rename_axis(None, axis=0).rename_axis(None, axis=1)
cols = [c for c in confusion_matrix_1.columns if c not in ['NA', 'Total']]
confusion_matrix_1 = confusion_matrix_1[cols + ['NA', 'Total']]

In [20]:
confusion_matrix_1

             History  Language  Medical  Poetry  Religious  NA  Total
Fiction            2         0        0      41          5   2     50
Non-Fiction       16        17        5      13         81   3    135
Total             18        17        5      54         86   5    185

In [21]:
confusion_matrix_1.to_latex('Tex_Files/Confusion_Matrix.tex')

In [22]:
list_of_file_locations['written_date'].replace(['', None], np.nan, inplace=True)

/var/folders/p0/y_n4880x7cjbhx11tzvvqpzh0000gn/T/ipykernel_39836/1470307445.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  list_of_file_locations['written_date'].replace(['', None], np.nan, inplace=True)

In [23]:
list_of_file_locations_filtered = list_of_file_locations.copy()

In [24]:
list_of_file_locations_filtered.dropna(subset=['written_date'], inplace=True)

In [25]:
list_of_file_locations_filtered.reset_index(drop=True, inplace=True)

In [26]:
list_of_file_locations_filtered['primaryGenre'].value_counts()

primaryGenre
Non-Fiction    43
Fiction        16
Name: count, dtype: int64

In [27]:
list_of_file_locations_filtered['secondaryGenre'].value_counts()

secondaryGenre
Religious    26
Poetry       15
Language     10
History       5
Medical       2
NA            1
Name: count, dtype: int64

In [28]:
list_of_file_locations_filtered['title'][list_of_file_locations_filtered['secondaryGenre'] == 'Poetry']

2                        නිදහසේ මන්ත්‍රය
12                        ජුබිලි වර්ණනාව
15                            හංස සංදේශය
18         කාව්‍ය වජ්‍රායුධය - පළමු කොටස
20                             ලංකා මාතා
22          සිතියම් සහිත මහියංගන වර්ණනාව
26             සිතියම් සහිත සියබස් මල්දම
28                           කාව්‍යශේඛරය
36                          යොග රත්නාකරය
42                               කුදුසික
48                           පරවි සංදේශය
54                             මගේ මල්ලි
55    සන්න සහිත කව්සිළුමිණ හෙවත් කුසදාවත
56                         ලියනෝරා නාඩගම
58                         නිකම් හැකියාව
Name: title, dtype: object

In [29]:
list(list_of_file_locations_filtered['title'][list_of_file_locations_filtered['secondaryGenre'] == 'Poetry'])

['නිදහසේ මන්ත්\u200dරය',
 'ජුබිලි වර්ණනාව',
 'හංස සංදේශය',
 'කාව්\u200dය වජ්\u200dරායුධය - පළමු කොටස',
 'ලංකා මාතා',
 'සිතියම් සහිත මහියංගන වර්ණනාව',
 'සිතියම් සහිත සියබස් මල්දම',
 'කාව්\u200dයශේඛරය',
 'යොග රත්නාකරය',
 'කුදුසික',
 'පරවි සංදේශය',
 'මගේ මල්ලි',
 'සන්න සහිත කව්සිළුමිණ හෙවත් කුසදාවත',
 'ලියනෝරා නාඩගම',
 'නිකම් හැකියාව']

In [30]:
list_of_file_locations_filtered

,title,title_en,author,author_en,issued_date,written_date,genre,text_file_location,ocr_confidence,primaryGenre,secondaryGenre
0,ධර්ම ප්‍රදීපිකාව හෙවත් මහාබෝධිවංශ පරිකථාව,Dharma Pradheepikawa hewath Mahabodhiwansha Pa...,Unknown,Unknown,1906,1187 - 1225,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9682,Non-Fiction,Religious
1,ටිබැට් රටේ බුදුදහම,Tibet Rate Budhudhahama,හෙන්රි එස් ඕල්කට්,Hendry S Olkat,1897,1832 - 1907,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9973,Non-Fiction,Religious
2,නිදහසේ මන්ත්‍රය,Nidhahase Manthraya,ඇස් මහින්ද හිමි,S. Mahinda Himi,1938,1901 - 1938,Non-Fiction; Poetry,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.8997,Non-Fiction,Poetry
3,පැරණි ගම,Parani Gama,ගල්පාත ඛේමානන්ද හිමි,Galpatha Kemanandha Himi,1944,1944,Non-Fiction; History,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9846,Non-Fiction,History
4,පන්සිය පනස් ජාතක පොත,Pansiya Panas Jathaka Potha,Unknown,Unknown,1881,1303 - 1333,Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9987,Fiction,Religious
5,හිතෝපදේශ සන්නය,Hithopadhesha Sannaya,වැලිගම ශ්‍රී සුමංගල හිමි,Waligama Sri Sumangala Himi,1884,1825 - 1905,Non-Fiction,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9871,Non-Fiction,NA
6,අධිමාස සංග්‍රහව,Adhimasa Sangrahawa,මාදම්පේ ධම්මතිලක හිමි,Madhampe Dhammathilaka Himi,1903,1850 - 1903,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9692,Non-Fiction,Religious
7,දහම් සරණ,Dhaham Sarana,Unknown,Unknown,1931,1220 - 1293,Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9891,Fiction,Religious
8,දුර්වාදී හෘදය විදාරණය,Dhurwadhi Hardhaya Widharanaya,ශ්‍රී ධනුද්ධරාචාර්ය,Sri Dhanudhdharacharya,1899,1854 - 1899,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9919,Non-Fiction,Religious
9,විස්තරාර්ථ ග්‍රන්ථිපද විවර්ණය සහිත සිංහල විමාන...,Wistharaartha Granthipadha Wiwarnaya sahitha S...,ඩී.බී.කේ. ගුණතිලක රාජකරුණා දිසානායක,D.B.K. Gunathilaka Raajakarunaa Dissanayake,1925,1469 - 1815,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9882,Non-Fiction,Religious
10,රුවන්මල් නිඝන්ටුව හෙවත් නාමරතන මාලාව,Ruwanmal Nigantuwa hewath Naamarathana Maalawa,හයවෙනි ශ්‍රී පරාක්‍රමබාහු රජතුමා; ඩී.පී. ද අල්...,Hayaweni Sri Parakramabahu Rajathumaa; D.P. de...,1914,1412 - 1467,Non-Fiction; Language,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9662,Non-Fiction,Language
11,වෛද්‍ය චින්තාමනි භෛෂද්‍ය සංග්‍රහව,Waidya Chinthamani Baishadhya Sangrahawa,Unknown,Unknown,1909,1706 - 1739,Non-Fiction; Medical,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9965,Non-Fiction,Medical
12,ජුබිලි වර්ණනාව,Jubili Warnanawa,ජෝන් ද සිල්වා,John de Silva,1887,1857 - 1922,Fiction; Poetry,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9957,Fiction,Poetry
13,සිතියම් සහිත සද්ධර්මාලංකාරය,Sithiyam sahitha Sadhdharmalankaraya,Unknown,Unknown,1954,1398 - 1410,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9810,Non-Fiction,Religious
14,විශුද්ධිමාර්ගය බ්‍රහ්මවිහාර නිර්දේශාත්මක තෘතීය...,Wishudhdhi Maargaya Brahmawihaara Nirdheshaath...,බුද්ධඝෝෂ හිමි; පරාක්‍රමභාහු රජතුමා,Budhdhagosha Himi; Parakramabahu Rajathuma,1888,1412 - 1467,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9910,Non-Fiction,Religious
15,හංස සංදේශය,Hansa Sandheshaya,සී.ඊ. ගොඩකුඹුරේ,C.E. Godakumbure,1953,1457 - 1465,Fiction; Poetry,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.8553,Fiction,Poetry
16,ධම්පියා අටුවා ගැටපදය,Dhampiya Atuwa Gatapadaya,ඩී.බි. ජයතිලක,D.B. Jayathilaka,1932,1868 - 1932,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9241,Non-Fiction,Religious
17,සන්න සහිත සැළලිහිණි සංදේශය,Sanna sahitha Salalihini Sandheshaya,Unknown,Unknown,1859,1450,Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9909,Fiction,Religious
18,කාව්‍ය වජ්‍රායුධය - පළමු කොටස,Kavya Wajrayudhaya - Palamu Kotasa,එංගල්තිනා කුමාරි,Engalthina Kumari,1889,1825 - 1893,Fiction; Poetry,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9254,Fiction,Poetry
19,විශුද්ධි මාර්ගය - ප්‍රථම භාගය - 1949,Wishudhdhi Maargaya - Prathama Baagaya -1949,Unknown,Unknown,1949,1266 - 1270,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9539,Non-Fiction,Religious
20,ලංකා මාතා,Lanka Maathaa,ඇස් මහින්ද හිමි,S. Mahinda Himi,1935,1901 - 1951,Fiction; Poetry,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.8567,Fiction,Poetry
21,සද්ධර්ම රත්නාවලිය - ප්‍රථම භාගය,Sadhdharma Rathnawaliya - Prathama Bagaya,ධර්මසේන හිමි,Dharmasena Himi,1930,1220 - 1293,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9962,Non-Fiction,Religious
22,සිතියම් සහිත මහියංගන වර්ණනාව,Sithiyam sahitha Mahiyangana Warnanawa,Unknown,Unknown,1898,1878,Fiction; Poetry,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9989,Fiction,Poetry
23,විශුද්ධි මාර්ගය - ද්විතීය භාගය,Wishudhdhi Margaya - Dhwitheeya Baagaya,Unknown,Unknown,1851,1266 - 1270,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9944,Non-Fiction,Religious
24,දළදා පූජාවලිය,Dhaladha Pujawaliya,Unknown,Unknown,1893,1325 - 1333,Non-Fiction; History,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9978,Non-Fiction,History
25,නිකාය සංග්‍රහය හෙවත් ශාසනාවතාරය,Nikaya Sangrahaya hewath Shasanawatharaya,Unknown,Unknown,1922,1390,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9754,Non-Fiction,Religious
26,සිතියම් සහිත සියබස් මල්දම,Sithiyam sahitha Siyabas Maldhama,කිරම ධම්මානන්ද හිමි,Kirama Dhammanandha Himi,1894,1820,Fiction; Poetry,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9256,Fiction,Poetry
27,විබත් මල්දම,Wibath Maldhama,කිරම ධම්මාරාම හිමි,Kirama Dhammarama Himi,1906,1821,Non-Fiction; Language,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9986,Non-Fiction,Language
28,කාව්‍යශේඛරය,Kavyashekaraya,තොටගමුවේ රාහුල හිමි,Thotagamuwe Rahula Himi,1872,1408 - 1491,Fiction; Poetry,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9813,Fiction,Poetry
29,සංස්කෘත ශබ්ධමාලාව හෙවත් සංස්කෘත නාම වරනැගිල්ල,Sanskrutha Shabdhamalawa hewath Sanskrutha Nam...,රත්මලානේ ධර්මාලෝක හිමි,Rathmalane Dharmaloka Himi,1876,1828 - 1887,Non-Fiction; Language,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9671,Non-Fiction,Language
30,සිදත් සඟරාව - 1892,Sidath Sangaraawa - 1892,ජේ. පී. අමරසිංහ,J P Amarasinghe,1892,1270 - 1293,Non-Fiction; Language,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9883,Non-Fiction,Language
31,සිංහල ව්‍යාකරණය එනම් සිදත් සඟරාව,Sinhala Wyakaranaya enam Sidath Sangarawa,හික්කඩුවේ ශ්‍රි සුමංගල හිමි,Hikkaduwe Sri Sumangala Himi,1884,1827 - 1911,Non-Fiction; Language,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9886,Non-Fiction,Language
32,අ‍‍ශෝක ශිලාලිපි සහ ප්‍රතිමාකරණ විනිශ්චය,Ashoka Shilalipi saha Prathimakarana Winishchaya,ඩී. ඊ. වික්‍රමසූරිය,D. E. Wickramasuriya,1919,1916,Non-Fiction; History,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9989,Non-Fiction,History
33,අධිමාස විනිශ්චය,Adhimasa Winishchaya,වැලිකන්දේ ශ්‍රී සුමංගල හිමි,Walikande Sri Sumangala Himi,1904,1850 - 1904,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9971,Non-Fiction,Religious
34,මුවදෙව් දා විවරණය,Muwadew da Wiwaranaya,මුනිදාස කුමාරතුංග,Munidhasa Kumarathunga,1949,1887 - 1944,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.8710,Non-Fiction,Religious
35,මහා සන්‍ය සහිත විශුද්ධි මාර්ගය - තෘතීය භාගය,Maha Sanya sahitha Wishudhdhi Maargaya - Thrut...,Unknown,Unknown,1954,1266 - 1270,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9683,Non-Fiction,Religious
36,යොග රත්නාකරය,Yoga Rathnaakaraya,Unknown,Unknown,1930,1501 - 1600,Non-Fiction; Poetry,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9460,Non-Fiction,Poetry
37,සාරාර්ථ සංග්‍රහව: ප්‍රථම භාගය,Sarartha Sangrahawa: Prathama Bhagaya,ශ්‍රීමද් බුද්ධදාස රජතුමා,Srimadh Budhdhadhasa Rajathuma,1904,398 - 426,Non-Fiction; Medical,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9997,Non-Fiction,Medical
38,සිතියම් සහිත සිංහල මහාවංශය,Sithiyam sahitha Sinhala Mahawanshaya,ඩි.එච්.එස් අභයරත්න,D. H. S. Abayarathna,1922,1874,Non-Fiction; History,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9549,Non-Fiction,History
39,අනාගතවංශය: මෙතේ බුදු සිරිත,Anagathawanshaya: Methe Budu Siritha,වටද්දර මේධානන්ද හිමි; සිරි පරාකුමබාහු විල්ගම්ම...,Watadhdhara Medhanandha Himi; Siri Parakumabah...,1934,1325 - 1333,Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9992,Fiction,Religious
40,සන්න සහිත අභිසම්බෝධි අලංකාරය,Sanna sahitha Abhisambodhi Alankaraya,වැලිවිට සරණංකර සංඝරාජ හිමි,Waliwita Saranankara Sangaraja Himi,1897,1698 - 1778,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9989,Non-Fiction,Religious
41,ඔකඳපොල සන්නය හෙවත් බාලාවතාර ලියන සන්න,Okandapala Sannaya hewath Balawathara Liyana S...,දොන් අන්ද්‍රිස් සිල්වා,Don Andhris Silva,1888,1760 - 1778,Non-Fiction; Language,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9884,Non-Fiction,Language
42,කුදුසික,Kudusika,Unknown,Unknown,1894,1270 - 1293,Non-Fiction; Poetry,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9988,Non-Fiction,Poetry
43,මොග්ගල්ලාන පංචිකා ප්‍රදීපය,Moggallana Panchika Pradeepaya,Unknown,Unknown,1896,1070 - 1232,Non-Fiction; Language,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9918,Non-Fiction,Language
44,කුසජාතක විවරණය (ප්‍රථම භාගය),Kusajathaka Wiwaranaya (Prathama Bagaya),මුනිදාස කුමාරතුංග,Munidhasa Kumarathunga,1932,1887 - 1932,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9701,Non-Fiction,Religious
45,ජානකීහරණ,Jaanakeeharana,ශ්‍රී කුමාරදාස,Sri Kumaaradhaasa,1891,1201 - 1300,Non-Fiction; History,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9976,Non-Fiction,History
46,විශුද්ධි මාර්ගය - ප්‍රථම භාගය - 1897,Wishudhdhi Margaya - Prathama Baagay - 1897,බුද්ධඝෝෂ හිමි,Budhdhagosha Himi,1897,1266 - 1270,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9947,Non-Fiction,Religious
47,ව්‍යාකරණ විවරණය හෙවත් සිංහල භාෂාවේ ව්‍යාකරණය,Wyakarana Wiwarana hewath Sinhala Bashawe Wyak...,මුනිදාස කුමාරතුංග,Munidhasa Kumarathunga,1937,1887 - 1937,Non-Fiction; Language,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9029,Non-Fiction,Language
48,පරවි සංදේශය,Parawi Sandheshaya,Unknown,Unknown,1873,1430 - 1440,Fiction; Poetry,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9902,Fiction,Poetry
49,සිංහල උපාසක ජනාලංකාරය,Sinhala Upaasaka Janaalankaaraya,Unknown,Unknown,1914,1701 - 1800,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9910,Non-Fiction,Religious
50,ගඩලාදෙණි සන්නයයි ප්‍රසිද්ධ වූ බාලාවතාරේ පුරාණ ...,Gadaladeni Sannayai Prasidhdha wu Balawathare ...,හික්කඩුවේ ශ්‍රි සුමංගල හිමි,Hikkaduwe Sri Sumangala Himi,1877,1341 - 1408,Non-Fiction; Language,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9970,Non-Fiction,Language
51,කතලුවේරාමඤ්ඤවාදය,Kathaluweeramanyawaadhaya,Unknown,Unknown,1899,1899,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9936,Non-Fiction,Religious
52,සිදත් සඟරාව - 1954,Sidath Sangaraawa - 1954,පතිරජ පිරුවන් හිමි; රැ. තෙන්නකෝන්,Pathiraja Piruwan Himi; Ra. Thennakon,1892,1270 - 1293,Non-Fiction; Language,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9883,Non-Fiction,Language
53,මහා සන්‍ය සහිත විශුද්ධි මාර්ගය - චතුර්ථ භාගය,Maha Sanya sahitha Wishudhdhi Maargaya - Chath...,Unknown,Unknown,1955,1266 - 1270,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9745,Non-Fiction,Religious
54,මගේ මල්ලි,Mage Malli,ජී .එච් පෙරේරා,G. H Perera,1938,1886 - 1938,Fiction; Poetry,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.8659,Fiction,Poetry
55,සන්න සහිත කව්සිළුමිණ හෙවත් කුසදාවත,Sanna sahitha Kawsilumina hewath Kusadhaawatha,කලිකාල සඞගීත සාහිත්‍ය සර්වඥ පණ්ඩිත පරාක්‍රමබාහ...,Kalikaala Sangeetha Sahithya Panditha Parakram...,1926,1101 - 1200,Fiction; Poetry,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9424,Fiction,Poetry
56,ලියනෝරා නාඩගම,Liyanora Nadagama,Unknown,Unknown,1936,1852 - 1927,Fiction; Poetry,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9935,Fiction,Poetry
57,පානදුරා වාදය,Paanadhuraa waadhaya,පී.ඒ. පීරිස්; පී.ජේ. දියෙස්,P.A. Peris; P.J. Dhiyes,1903,1873,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9945,Non-Fiction,Religious
58,නිකම් හැකියාව,Nikam Hakiyawa,මුනිදාස කුමාරතුංග,Munidhasa Kumarathunga,1941,1887 - 1941,Fiction; Poetry,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.8932,Fiction,Poetry

In [31]:
list_of_file_locations_filtered = list_of_file_locations_filtered.sort_values(by='title_en')
list_of_file_locations_filtered.reset_index(drop=True, inplace=True)

In [32]:
list_of_file_locations_filtered

,title,title_en,author,author_en,issued_date,written_date,genre,text_file_location,ocr_confidence,primaryGenre,secondaryGenre
0,අධිමාස සංග්‍රහව,Adhimasa Sangrahawa,මාදම්පේ ධම්මතිලක හිමි,Madhampe Dhammathilaka Himi,1903,1850 - 1903,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9692,Non-Fiction,Religious
1,අධිමාස විනිශ්චය,Adhimasa Winishchaya,වැලිකන්දේ ශ්‍රී සුමංගල හිමි,Walikande Sri Sumangala Himi,1904,1850 - 1904,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9971,Non-Fiction,Religious
2,අනාගතවංශය: මෙතේ බුදු සිරිත,Anagathawanshaya: Methe Budu Siritha,වටද්දර මේධානන්ද හිමි; සිරි පරාකුමබාහු විල්ගම්ම...,Watadhdhara Medhanandha Himi; Siri Parakumabah...,1934,1325 - 1333,Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9992,Fiction,Religious
3,අ‍‍ශෝක ශිලාලිපි සහ ප්‍රතිමාකරණ විනිශ්චය,Ashoka Shilalipi saha Prathimakarana Winishchaya,ඩී. ඊ. වික්‍රමසූරිය,D. E. Wickramasuriya,1919,1916,Non-Fiction; History,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9989,Non-Fiction,History
4,දහම් සරණ,Dhaham Sarana,Unknown,Unknown,1931,1220 - 1293,Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9891,Fiction,Religious
5,දළදා පූජාවලිය,Dhaladha Pujawaliya,Unknown,Unknown,1893,1325 - 1333,Non-Fiction; History,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9978,Non-Fiction,History
6,ධම්පියා අටුවා ගැටපදය,Dhampiya Atuwa Gatapadaya,ඩී.බි. ජයතිලක,D.B. Jayathilaka,1932,1868 - 1932,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9241,Non-Fiction,Religious
7,ධර්ම ප්‍රදීපිකාව හෙවත් මහාබෝධිවංශ පරිකථාව,Dharma Pradheepikawa hewath Mahabodhiwansha Pa...,Unknown,Unknown,1906,1187 - 1225,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9682,Non-Fiction,Religious
8,දුර්වාදී හෘදය විදාරණය,Dhurwadhi Hardhaya Widharanaya,ශ්‍රී ධනුද්ධරාචාර්ය,Sri Dhanudhdharacharya,1899,1854 - 1899,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9919,Non-Fiction,Religious
9,ගඩලාදෙණි සන්නයයි ප්‍රසිද්ධ වූ බාලාවතාරේ පුරාණ ...,Gadaladeni Sannayai Prasidhdha wu Balawathare ...,හික්කඩුවේ ශ්‍රි සුමංගල හිමි,Hikkaduwe Sri Sumangala Himi,1877,1341 - 1408,Non-Fiction; Language,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9970,Non-Fiction,Language
10,හංස සංදේශය,Hansa Sandheshaya,සී.ඊ. ගොඩකුඹුරේ,C.E. Godakumbure,1953,1457 - 1465,Fiction; Poetry,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.8553,Fiction,Poetry
11,හිතෝපදේශ සන්නය,Hithopadhesha Sannaya,වැලිගම ශ්‍රී සුමංගල හිමි,Waligama Sri Sumangala Himi,1884,1825 - 1905,Non-Fiction,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9871,Non-Fiction,NA
12,ජානකීහරණ,Jaanakeeharana,ශ්‍රී කුමාරදාස,Sri Kumaaradhaasa,1891,1201 - 1300,Non-Fiction; History,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9976,Non-Fiction,History
13,ජුබිලි වර්ණනාව,Jubili Warnanawa,ජෝන් ද සිල්වා,John de Silva,1887,1857 - 1922,Fiction; Poetry,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9957,Fiction,Poetry
14,කතලුවේරාමඤ්ඤවාදය,Kathaluweeramanyawaadhaya,Unknown,Unknown,1899,1899,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9936,Non-Fiction,Religious
15,කාව්‍ය වජ්‍රායුධය - පළමු කොටස,Kavya Wajrayudhaya - Palamu Kotasa,එංගල්තිනා කුමාරි,Engalthina Kumari,1889,1825 - 1893,Fiction; Poetry,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9254,Fiction,Poetry
16,කාව්‍යශේඛරය,Kavyashekaraya,තොටගමුවේ රාහුල හිමි,Thotagamuwe Rahula Himi,1872,1408 - 1491,Fiction; Poetry,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9813,Fiction,Poetry
17,කුදුසික,Kudusika,Unknown,Unknown,1894,1270 - 1293,Non-Fiction; Poetry,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9988,Non-Fiction,Poetry
18,කුසජාතක විවරණය (ප්‍රථම භාගය),Kusajathaka Wiwaranaya (Prathama Bagaya),මුනිදාස කුමාරතුංග,Munidhasa Kumarathunga,1932,1887 - 1932,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9701,Non-Fiction,Religious
19,ලංකා මාතා,Lanka Maathaa,ඇස් මහින්ද හිමි,S. Mahinda Himi,1935,1901 - 1951,Fiction; Poetry,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.8567,Fiction,Poetry
20,ලියනෝරා නාඩගම,Liyanora Nadagama,Unknown,Unknown,1936,1852 - 1927,Fiction; Poetry,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9935,Fiction,Poetry
21,මගේ මල්ලි,Mage Malli,ජී .එච් පෙරේරා,G. H Perera,1938,1886 - 1938,Fiction; Poetry,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.8659,Fiction,Poetry
22,මහා සන්‍ය සහිත විශුද්ධි මාර්ගය - චතුර්ථ භාගය,Maha Sanya sahitha Wishudhdhi Maargaya - Chath...,Unknown,Unknown,1955,1266 - 1270,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9745,Non-Fiction,Religious
23,මහා සන්‍ය සහිත විශුද්ධි මාර්ගය - තෘතීය භාගය,Maha Sanya sahitha Wishudhdhi Maargaya - Thrut...,Unknown,Unknown,1954,1266 - 1270,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9683,Non-Fiction,Religious
24,මොග්ගල්ලාන පංචිකා ප්‍රදීපය,Moggallana Panchika Pradeepaya,Unknown,Unknown,1896,1070 - 1232,Non-Fiction; Language,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9918,Non-Fiction,Language
25,මුවදෙව් දා විවරණය,Muwadew da Wiwaranaya,මුනිදාස කුමාරතුංග,Munidhasa Kumarathunga,1949,1887 - 1944,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.8710,Non-Fiction,Religious
26,නිදහසේ මන්ත්‍රය,Nidhahase Manthraya,ඇස් මහින්ද හිමි,S. Mahinda Himi,1938,1901 - 1938,Non-Fiction; Poetry,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.8997,Non-Fiction,Poetry
27,නිකම් හැකියාව,Nikam Hakiyawa,මුනිදාස කුමාරතුංග,Munidhasa Kumarathunga,1941,1887 - 1941,Fiction; Poetry,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.8932,Fiction,Poetry
28,නිකාය සංග්‍රහය හෙවත් ශාසනාවතාරය,Nikaya Sangrahaya hewath Shasanawatharaya,Unknown,Unknown,1922,1390,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9754,Non-Fiction,Religious
29,ඔකඳපොල සන්නය හෙවත් බාලාවතාර ලියන සන්න,Okandapala Sannaya hewath Balawathara Liyana S...,දොන් අන්ද්‍රිස් සිල්වා,Don Andhris Silva,1888,1760 - 1778,Non-Fiction; Language,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9884,Non-Fiction,Language
30,පානදුරා වාදය,Paanadhuraa waadhaya,පී.ඒ. පීරිස්; පී.ජේ. දියෙස්,P.A. Peris; P.J. Dhiyes,1903,1873,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9945,Non-Fiction,Religious
31,පන්සිය පනස් ජාතක පොත,Pansiya Panas Jathaka Potha,Unknown,Unknown,1881,1303 - 1333,Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9987,Fiction,Religious
32,පැරණි ගම,Parani Gama,ගල්පාත ඛේමානන්ද හිමි,Galpatha Kemanandha Himi,1944,1944,Non-Fiction; History,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9846,Non-Fiction,History
33,පරවි සංදේශය,Parawi Sandheshaya,Unknown,Unknown,1873,1430 - 1440,Fiction; Poetry,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9902,Fiction,Poetry
34,රුවන්මල් නිඝන්ටුව හෙවත් නාමරතන මාලාව,Ruwanmal Nigantuwa hewath Naamarathana Maalawa,හයවෙනි ශ්‍රී පරාක්‍රමබාහු රජතුමා; ඩී.පී. ද අල්...,Hayaweni Sri Parakramabahu Rajathumaa; D.P. de...,1914,1412 - 1467,Non-Fiction; Language,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9662,Non-Fiction,Language
35,සද්ධර්ම රත්නාවලිය - ප්‍රථම භාගය,Sadhdharma Rathnawaliya - Prathama Bagaya,ධර්මසේන හිමි,Dharmasena Himi,1930,1220 - 1293,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9962,Non-Fiction,Religious
36,සන්න සහිත අභිසම්බෝධි අලංකාරය,Sanna sahitha Abhisambodhi Alankaraya,වැලිවිට සරණංකර සංඝරාජ හිමි,Waliwita Saranankara Sangaraja Himi,1897,1698 - 1778,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9989,Non-Fiction,Religious
37,සන්න සහිත කව්සිළුමිණ හෙවත් කුසදාවත,Sanna sahitha Kawsilumina hewath Kusadhaawatha,කලිකාල සඞගීත සාහිත්‍ය සර්වඥ පණ්ඩිත පරාක්‍රමබාහ...,Kalikaala Sangeetha Sahithya Panditha Parakram...,1926,1101 - 1200,Fiction; Poetry,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9424,Fiction,Poetry
38,සන්න සහිත සැළලිහිණි සංදේශය,Sanna sahitha Salalihini Sandheshaya,Unknown,Unknown,1859,1450,Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9909,Fiction,Religious
39,සංස්කෘත ශබ්ධමාලාව හෙවත් සංස්කෘත නාම වරනැගිල්ල,Sanskrutha Shabdhamalawa hewath Sanskrutha Nam...,රත්මලානේ ධර්මාලෝක හිමි,Rathmalane Dharmaloka Himi,1876,1828 - 1887,Non-Fiction; Language,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9671,Non-Fiction,Language
40,සාරාර්ථ සංග්‍රහව: ප්‍රථම භාගය,Sarartha Sangrahawa: Prathama Bhagaya,ශ්‍රීමද් බුද්ධදාස රජතුමා,Srimadh Budhdhadhasa Rajathuma,1904,398 - 426,Non-Fiction; Medical,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9997,Non-Fiction,Medical
41,සිදත් සඟරාව - 1892,Sidath Sangaraawa - 1892,ජේ. පී. අමරසිංහ,J P Amarasinghe,1892,1270 - 1293,Non-Fiction; Language,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9883,Non-Fiction,Language
42,සිදත් සඟරාව - 1954,Sidath Sangaraawa - 1954,පතිරජ පිරුවන් හිමි; රැ. තෙන්නකෝන්,Pathiraja Piruwan Himi; Ra. Thennakon,1892,1270 - 1293,Non-Fiction; Language,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9883,Non-Fiction,Language
43,සිංහල උපාසක ජනාලංකාරය,Sinhala Upaasaka Janaalankaaraya,Unknown,Unknown,1914,1701 - 1800,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9910,Non-Fiction,Religious
44,සිංහල ව්‍යාකරණය එනම් සිදත් සඟරාව,Sinhala Wyakaranaya enam Sidath Sangarawa,හික්කඩුවේ ශ්‍රි සුමංගල හිමි,Hikkaduwe Sri Sumangala Himi,1884,1827 - 1911,Non-Fiction; Language,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9886,Non-Fiction,Language
45,සිතියම් සහිත මහියංගන වර්ණනාව,Sithiyam sahitha Mahiyangana Warnanawa,Unknown,Unknown,1898,1878,Fiction; Poetry,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9989,Fiction,Poetry
46,සිතියම් සහිත සද්ධර්මාලංකාරය,Sithiyam sahitha Sadhdharmalankaraya,Unknown,Unknown,1954,1398 - 1410,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9810,Non-Fiction,Religious
47,සිතියම් සහිත සිංහල මහාවංශය,Sithiyam sahitha Sinhala Mahawanshaya,ඩි.එච්.එස් අභයරත්න,D. H. S. Abayarathna,1922,1874,Non-Fiction; History,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9549,Non-Fiction,History
48,සිතියම් සහිත සියබස් මල්දම,Sithiyam sahitha Siyabas Maldhama,කිරම ධම්මානන්ද හිමි,Kirama Dhammanandha Himi,1894,1820,Fiction; Poetry,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9256,Fiction,Poetry
49,ටිබැට් රටේ බුදුදහම,Tibet Rate Budhudhahama,හෙන්රි එස් ඕල්කට්,Hendry S Olkat,1897,1832 - 1907,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9973,Non-Fiction,Religious
50,වෛද්‍ය චින්තාමනි භෛෂද්‍ය සංග්‍රහව,Waidya Chinthamani Baishadhya Sangrahawa,Unknown,Unknown,1909,1706 - 1739,Non-Fiction; Medical,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9965,Non-Fiction,Medical
51,විබත් මල්දම,Wibath Maldhama,කිරම ධම්මාරාම හිමි,Kirama Dhammarama Himi,1906,1821,Non-Fiction; Language,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9986,Non-Fiction,Language
52,විශුද්ධි මාර්ගය - ප්‍රථම භාගය - 1949,Wishudhdhi Maargaya - Prathama Baagaya -1949,Unknown,Unknown,1949,1266 - 1270,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9539,Non-Fiction,Religious
53,විශුද්ධිමාර්ගය බ්‍රහ්මවිහාර නිර්දේශාත්මක තෘතීය...,Wishudhdhi Maargaya Brahmawihaara Nirdheshaath...,බුද්ධඝෝෂ හිමි; පරාක්‍රමභාහු රජතුමා,Budhdhagosha Himi; Parakramabahu Rajathuma,1888,1412 - 1467,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9910,Non-Fiction,Religious
54,විශුද්ධි මාර්ගය - ද්විතීය භාගය,Wishudhdhi Margaya - Dhwitheeya Baagaya,Unknown,Unknown,1851,1266 - 1270,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9944,Non-Fiction,Religious
55,විශුද්ධි මාර්ගය - ප්‍රථම භාගය - 1897,Wishudhdhi Margaya - Prathama Baagay - 1897,බුද්ධඝෝෂ හිමි,Budhdhagosha Himi,1897,1266 - 1270,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9947,Non-Fiction,Religious
56,විස්තරාර්ථ ග්‍රන්ථිපද විවර්ණය සහිත සිංහල විමාන...,Wistharaartha Granthipadha Wiwarnaya sahitha S...,ඩී.බී.කේ. ගුණතිලක රාජකරුණා දිසානායක,D.B.K. Gunathilaka Raajakarunaa Dissanayake,1925,1469 - 1815,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9882,Non-Fiction,Religious
57,ව්‍යාකරණ විවරණය හෙවත් සිංහල භාෂාවේ ව්‍යාකරණය,Wyakarana Wiwarana hewath Sinhala Bashawe Wyak...,මුනිදාස කුමාරතුංග,Munidhasa Kumarathunga,1937,1887 - 1937,Non-Fiction; Language,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9029,Non-Fiction,Language
58,යොග රත්නාකරය,Yoga Rathnaakaraya,Unknown,Unknown,1930,1501 - 1600,Non-Fiction; Poetry,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9460,Non-Fiction,Poetry

In [33]:
list_of_file_locations_filtered[['title_en', 'issued_date', 'author_en', 'written_date', 'primaryGenre', 'secondaryGenre', 'ocr_confidence']].to_latex('Tex_Files/Metadata_Analysis_Table.tex', index=False)

In [34]:
for index, row in list_of_file_locations_filtered.iterrows():
    date_str = str(row['written_date']) # Ensure it's treated as a string
    
    start_year = np.nan
    end_year = np.nan

    if ' - ' in date_str:
        # It's a range
        try:
            start_year_str, end_year_str = date_str.split(' - ')
            start_year = int(start_year_str.strip())
            end_year = int(end_year_str.strip())
        except ValueError:
            print(f"Warning: Could not parse range '{date_str}' at index {index}. Setting to NaN.")
    else:
        # It's a single year or potentially unparseable
        try:
            single_year = int(date_str.strip())
            start_year = single_year
            end_year = single_year # Duplicate for single date
        except ValueError:
            print(f"Warning: Could not parse single year/date '{date_str}' at index {index}. Setting to NaN.")
            
    # Assign the parsed (or NaN) values back to the DataFrame
    list_of_file_locations_filtered.at[index, 'start_date'] = start_year
    list_of_file_locations_filtered.at[index, 'end_date'] = end_year

In [35]:
list_of_file_locations_filtered.head()

,title,title_en,author,author_en,issued_date,written_date,genre,text_file_location,ocr_confidence,primaryGenre,secondaryGenre,start_date,end_date
0,අධිමාස සංග්‍රහව,Adhimasa Sangrahawa,මාදම්පේ ධම්මතිලක හිමි,Madhampe Dhammathilaka Himi,1903,1850 - 1903,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9692,Non-Fiction,Religious,1850.0,1903.0
1,අධිමාස විනිශ්චය,Adhimasa Winishchaya,වැලිකන්දේ ශ්‍රී සුමංගල හිමි,Walikande Sri Sumangala Himi,1904,1850 - 1904,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9971,Non-Fiction,Religious,1850.0,1904.0
2,අනාගතවංශය: මෙතේ බුදු සිරිත,Anagathawanshaya: Methe Budu Siritha,වටද්දර මේධානන්ද හිමි; සිරි පරාකුමබාහු විල්ගම්ම...,Watadhdhara Medhanandha Himi; Siri Parakumabah...,1934,1325 - 1333,Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9992,Fiction,Religious,1325.0,1333.0
3,අ‍‍ශෝක ශිලාලිපි සහ ප්‍රතිමාකරණ විනිශ්චය,Ashoka Shilalipi saha Prathimakarana Winishchaya,ඩී. ඊ. වික්‍රමසූරිය,D. E. Wickramasuriya,1919,1916,Non-Fiction; History,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9989,Non-Fiction,History,1916.0,1916.0
4,දහම් සරණ,Dhaham Sarana,Unknown,Unknown,1931,1220 - 1293,Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9891,Fiction,Religious,1220.0,1293.0

In [36]:
def get_century(year):
    """Calculates the century for a given year."""
    if pd.isna(year):
        return np.nan
    return (int(year) - 1) // 100 + 1

In [37]:
list_of_file_locations_filtered[((list_of_file_locations_filtered['end_date'] >= 1500) & (list_of_file_locations_filtered['end_date'] <= 1600))]

,title,title_en,author,author_en,issued_date,written_date,genre,text_file_location,ocr_confidence,primaryGenre,secondaryGenre,start_date,end_date
58,යොග රත්නාකරය,Yoga Rathnaakaraya,Unknown,Unknown,1930,1501 - 1600,Non-Fiction; Poetry,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.946,Non-Fiction,Poetry,1501.0,1600.0

In [38]:
list_of_file_locations_filtered['end_century'] = list_of_file_locations_filtered['end_date'].apply(get_century)

In [39]:
list_of_file_locations_filtered[((list_of_file_locations_filtered['end_date'] >= 1500) & (list_of_file_locations_filtered['end_date'] <= 1600))]

,title,title_en,author,author_en,issued_date,written_date,genre,text_file_location,ocr_confidence,primaryGenre,secondaryGenre,start_date,end_date,end_century
58,යොග රත්නාකරය,Yoga Rathnaakaraya,Unknown,Unknown,1930,1501 - 1600,Non-Fiction; Poetry,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.946,Non-Fiction,Poetry,1501.0,1600.0,16

In [40]:
list_of_file_locations_filtered[list_of_file_locations_filtered['end_century'] == 14]

,title,title_en,author,author_en,issued_date,written_date,genre,text_file_location,ocr_confidence,primaryGenre,secondaryGenre,start_date,end_date,end_century
2,අනාගතවංශය: මෙතේ බුදු සිරිත,Anagathawanshaya: Methe Budu Siritha,වටද්දර මේධානන්ද හිමි; සිරි පරාකුමබාහු විල්ගම්ම...,Watadhdhara Medhanandha Himi; Siri Parakumabah...,1934,1325 - 1333,Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9992,Fiction,Religious,1325.0,1333.0,14
5,දළදා පූජාවලිය,Dhaladha Pujawaliya,Unknown,Unknown,1893,1325 - 1333,Non-Fiction; History,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9978,Non-Fiction,History,1325.0,1333.0,14
28,නිකාය සංග්‍රහය හෙවත් ශාසනාවතාරය,Nikaya Sangrahaya hewath Shasanawatharaya,Unknown,Unknown,1922,1390,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9754,Non-Fiction,Religious,1390.0,1390.0,14
31,පන්සිය පනස් ජාතක පොත,Pansiya Panas Jathaka Potha,Unknown,Unknown,1881,1303 - 1333,Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9987,Fiction,Religious,1303.0,1333.0,14

In [41]:
confusion_matrix_2 = pd.crosstab(list_of_file_locations_filtered['primaryGenre'], list_of_file_locations_filtered['secondaryGenre'], margins=True, margins_name='Total')
confusion_matrix_2 = confusion_matrix_2.rename_axis(None, axis=0).rename_axis(None, axis=1)
cols = [c for c in confusion_matrix_2.columns if c not in ['NA', 'Total']]
confusion_matrix_2 = confusion_matrix_2[cols + ['NA', 'Total']]

In [42]:
confusion_matrix_2

             History  Language  Medical  Poetry  Religious  NA  Total
Fiction            0         0        0      12          4   0     16
Non-Fiction        5        10        2       3         22   1     43
Total              5        10        2      15         26   1     59

In [43]:
confusion_matrix_2.to_latex('Tex_Files/Confusion_Matrix_Filtered.tex')

In [44]:
list_of_file_locations_filtered.columns

Index(['title', 'title_en', 'author', 'author_en', 'issued_date',
       'written_date', 'genre', 'text_file_location', 'ocr_confidence',
       'primaryGenre', 'secondaryGenre', 'start_date', 'end_date',
       'end_century'],
      dtype='object')

In [45]:
list_of_file_locations_filtered['century_label'] = list_of_file_locations_filtered['end_century'].astype(str) + 'th'

In [46]:
primary = pd.crosstab(list_of_file_locations_filtered['end_century'], list_of_file_locations_filtered['primaryGenre'])
primary.columns = pd.MultiIndex.from_product([['Primary Category'], primary.columns])

secondary = pd.crosstab(list_of_file_locations_filtered['end_century'], list_of_file_locations_filtered['secondaryGenre'])
secondary.columns = pd.MultiIndex.from_product([['Secondary Category'], secondary.columns])

final_df = pd.concat([primary, secondary], axis=1)

final_df['Total'] = final_df.sum(axis=1)

final_df.loc['Total'] = final_df.sum()

In [47]:
final_df

            Primary Category             Secondary Category                   \
                     Fiction Non-Fiction            History Language Medical
end_century
5                          0           1                  0        0       1
12                         1           0                  0        0       0
13                         1          12                  1        3       0
14                         2           2                  1        0       0
15                         4           4                  0        2       0
16                         0           1                  0        0       0
18                         0           4                  0        1       1
19                         3           7                  1        2       0
20                         5          12                  2        2       0
Total                     16          43                  5       10       2

                                Total
            NA Poetry Religious
end_century
5            0      0         0     2
12           0      1         0     2
13           0      1         8    26
14           0      0         3     8
15           0      3         3    16
16           0      1         0     2
18           0      0         2     8
19           0      3         4    20
20           1      6         6    34
Total        1     15        26   118

In [48]:
final_df = final_df.drop(('Secondary Category', 'NA'), axis=1)

In [49]:
final_df

            Primary Category             Secondary Category                   \
                     Fiction Non-Fiction            History Language Medical
end_century
5                          0           1                  0        0       1
12                         1           0                  0        0       0
13                         1          12                  1        3       0
14                         2           2                  1        0       0
15                         4           4                  0        2       0
16                         0           1                  0        0       0
18                         0           4                  0        1       1
19                         3           7                  1        2       0
20                         5          12                  2        2       0
Total                     16          43                  5       10       2

                             Total
            Poetry Religious
end_century
5                0         0     2
12               1         0     2
13               1         8    26
14               0         3     8
15               3         3    16
16               1         0     2
18               0         2     8
19               3         4    20
20               6         6    34
Total           15        26   118

In [50]:
final_df.to_latex('Genre_Distribution_by_Century.tex')

In [51]:
bins = np.arange(1800, 1961, 20)
labels = [f"{bins[i]} - {bins[i+1]}" for i in range(len(bins)-1)]

In [52]:
list_of_file_locations['issued_date_range'] = pd.cut(
    list_of_file_locations['issued_date'], 
    bins=bins, 
    labels=labels, 
    right=False  # This makes the range [1800, 1820), meaning 1820 falls in the next bin
)

In [55]:
books_without_written_dates = list_of_file_locations[list_of_file_locations['written_date'].isna()]

In [56]:
books_without_written_dates.reset_index(drop=True, inplace=True)

In [58]:
books_without_written_dates.to_csv('Books_Without_Written_Dates.csv', index=False)

In [59]:
books_with_written_dates = list_of_file_locations[~list_of_file_locations['written_date'].isna()]
books_with_written_dates.reset_index(drop=True, inplace=True)

In [61]:
books_with_written_dates.to_csv('Books_With_Written_Dates.csv', index=False)

In [54]:
primary = pd.crosstab(list_of_file_locations['issued_date_range'], list_of_file_locations['primaryGenre'])
primary.columns = pd.MultiIndex.from_product([['Primary Category'], primary.columns])

secondary = pd.crosstab(list_of_file_locations['issued_date_range'], list_of_file_locations['secondaryGenre'])
secondary.columns = pd.MultiIndex.from_product([['Secondary Category'], secondary.columns])

final_df_issued = pd.concat([primary, secondary], axis=1)

final_df_issued['Total'] = final_df_issued.sum(axis=1)

final_df_issued.loc['Total'] = final_df_issued.sum()

In [55]:
final_df_issued

                  Primary Category             Secondary Category           \
                           Fiction Non-Fiction            History Language
issued_date_range
1800 - 1820                      1           0                  0        0
1820 - 1840                      0           1                  0        1
1840 - 1860                      2           1                  0        0
1860 - 1880                      2           6                  1        2
1880 - 1900                     12          51                  3        7
1900 - 1920                     13          27                  3        2
1920 - 1940                     15          35                  6        4
1940 - 1960                      5          14                  5        1
Total                           50         135                 18       17

                                              Total
                  Medical NA Poetry Religious
issued_date_range
1800 - 1820             0  0      1         0     2
1820 - 1840             0  0      0         0     2
1840 - 1860             0  0      1         2     6
1860 - 1880             0  0      2         3    16
1880 - 1900             1  1     17        34   126
1900 - 1920             3  3     11        18    80
1920 - 1940             1  1     17        21   100
1940 - 1960             0  0      5         8    38
Total                   5  5     54        86   370

In [56]:
final_df_issued = final_df_issued.drop(('Secondary Category', 'NA'), axis=1)

In [57]:
final_df_issued.to_latex('Genre_Distribution_by_Issued_Date_Range.tex')

In [58]:
list_of_file_locations[list_of_file_locations['secondaryGenre'] == 'NA'][['title_en', 'issued_date_range']]

                         title_en issued_date_range
6           Hithopadhesha Sannaya       1880 - 1900
19   Dhrawya Gunadharpana Sannaya       1900 - 1920
45              Asabandhi Sabandi       1900 - 1920
127              Ajuudha Neethiya       1920 - 1940
141                     Maadhanaa       1900 - 1920

In [59]:
list_of_file_locations = list_of_file_locations.sort_values(by='title_en')
list_of_file_locations.reset_index(drop=True, inplace=True)

In [60]:
list_of_file_locations.head()

,title,title_en,author,author_en,issued_date,written_date,genre,text_file_location,ocr_confidence,primaryGenre,secondaryGenre,issued_date_range
0,අධිමාස සංග්‍රහව,Adhimasa Sangrahawa,මාදම්පේ ධම්මතිලක හිමි,Madhampe Dhammathilaka Himi,1903,1850 - 1903,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9692,Non-Fiction,Religious,1900 - 1920
1,අධිමාස විනිශ්චය,Adhimasa Winishchaya,වැලිකන්දේ ශ්‍රී සුමංගල හිමි,Walikande Sri Sumangala Himi,1904,1850 - 1904,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9971,Non-Fiction,Religious,1900 - 1920
2,අධිමාසභේදය,Adhimasabhedhaya,අඹගහපිටියේ බුද්ධසිරිතිස්ස හිමි,Abhagahapitiye Bhudhdhasirithissa Himi,1895,NaN,Non-Fiction; Religious,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9753,Non-Fiction,Religious,1880 - 1900
3,අහමඩ් - අරාබි කථන්දරය,Ahmad - Arabi Kathandaraya,ඩී. එච්. ස්ටෙෆන් අබේරත්න,D. H. Stephen Abayarathna,1895,NaN,Non-Fiction; History,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9948,Non-Fiction,History,1880 - 1900
4,ඵෙතිහාසික පාඨ,Aithihaasika Paata,ඩබ්ලිව්. තෝමස් ෆර්නෑණ්ඩෝ,W. Thomas Fernando,1925,NaN,Non-Fiction; History,/Users/nevidujayatilleke/Documents/MSC - Resea...,0.9804,Non-Fiction,History,1920 - 1940

In [61]:
list_of_file_locations_md = list_of_file_locations[['title', 'title_en', 'author', 'author_en', 'primaryGenre', 'secondaryGenre', 'issued_date', 'written_date', 'ocr_confidence']].to_markdown(index=False)

In [62]:
with open("Tex_Files/Metadata_Analysis_Full_Table.md", "w") as f:
    f.write("# SiDiaC-v.2.0 Metadata Information\n\n")
    f.write(list_of_file_locations_md)

In [63]:
len(list_of_file_locations[list_of_file_locations['author_en'] == 'Unknown'])

69

In [64]:
split_authors = list_of_file_locations['author_en'].str.split(';', expand=True)
split_authors = split_authors.fillna('')

In [65]:
authors_list = split_authors.stack().tolist()

In [66]:
authors_list = [author for author in authors_list if author != '']

In [67]:
clean_authors = [a.strip() for a in authors_list if a.strip()]

In [68]:
df_authors = pd.DataFrame(clean_authors, columns=["author_en"])

In [69]:
df_authors

                                             author_en
0                          Madhampe Dhammathilaka Himi
1                         Walikande Sri Sumangala Himi
2               Abhagahapitiye Bhudhdhasirithissa Himi
3                            D. H. Stephen Abayarathna
4                                   W. Thomas Fernando
5                                              Unknown
6                                              Unknown
7                         Watadhdhara Medhanandha Himi
8          Siri Parakumabahu Wilgammula Sangaraja Himi
9                                              Unknown
10                                 Hansini Pramudhitha
11                                D. E. Wickramasuriya
12                                             Unknown
13                                             Unknown
14                                             Unknown
15                                             Unknown
16                                       Winston Prera
17                                             Unknown
18                                             Unknown
19                                             Unknown
20                                     M. Dharmarathna
21                                             Unknown
22                     Malalagama Sri Wijayanaaga Himi
23                                             Unknown
24                                        K. S. Perera
25                                             Unknown
26                                    D.B. Jayathilaka
27                                             Unknown
28                                             Unknown
29                                             Unknown
30                                             Unknown
31                                             Unknown
32                                             Unknown
33                                M.U Kaweeshwara Himi
34                                   M.S Gauthamadhasa
35                              Sri Dhanudhdharacharya
36                         Ilukwaththe Medhankara Himi
37                         Udugampala Swarnajothi Himi
38                                          D.C. Prera
39             Panynyahi Sirisadhdharma Kavidhaja Himi
40                        Hikkaduwe Sri Sumangala Himi
41                                         G. H Perera
42                                D. E. Hettiaarachchi
43                                 H.D.S. Wijayarathna
44                                    C.E. Godakumbure
45                         Waligama Sri Sumangala Himi
46                                             Unknown
47   Waraahamihiraachaarya Puth Pruthuyashas Pandiw...
48                                       A. Dasanayake
49                                             Unknown
50                                   Sri Kumaaradhaasa
51                                             Unknown
52                                             Unknown
53                                       John de Silva
54                               G. G. Lewis Appuhaami
55                                             Unknown
56                                             Unknown
57                        Dhodanduuwe Piyarathana Himi
58                         Waligama Sri Sumangala Himi
59                                             Unknown
60                                   Engalthina Kumari
61                                             Unknown
62                             Thotagamuwe Rahula Himi
63                                             Unknown
64                                             Unknown
65                           K. Don Hendrick Appuhaami
66                              Munidhasa Kumarathunga
67                                     S. Mahinda Himi
68                                             Unknown
69                                   Bodhi Widhyaartha
70                              M.L.D. James Appuhaami
71                         Kaluthara Saaraanandha Himi
72                                         G. H Perera
73                                       B. J Fernando
74                                    L.S Gunawardhana
75                                             Unknown
76                                             Unknown
77                                             Unknown
78                                             Unknown
79                               Gunapaala Weerasekara
80                                             Unknown
81                         Raigama Sri Indrajothi Himi
82                           Nalagama Nyaanaaloka Himi
83                                             Unknown
84                                       Sri Wopadhewa
85              Seenawaththe Gunaalankaara Thissa Himi
86                                             Unknown
87                              Munidhasa Kumarathunga
88                       Dhodandhuuwe Saranapothi Himi
89                                             Unknown
90                                     S. Mahinda Himi
91                              Munidhasa Kumarathunga
92                                             Unknown
93                                   Don Andhris Silva
94                                          P.A. Peris
95                                         P.J. Dhiyes
96                                             Unknown
97                        Madabaawita Nyaanawaasa Himi
98                                             Unknown
99                                             Unknown
100                             Don Salman Gunathilake
101                                   D. S. Jayasekara
102                           Galpatha Kemanandha Himi
103                                            Unknown
104                       Dhodanduuwe Piyarathana Himi
105                                            Unknown
106                                            Unknown
107                                    D. D Ranasinghe
108                 Don Basthiyan de Silva Jayasooriya
109                      Thotagamuwe Sugunathissa Himi
110                                            Unknown
111                                     Binthanne Himi
112                              Charles Karunathilaka
113                             Wladmeir Iliyich Lenin
114                                Philip Gunawardhana
115                                    Albert de Silva
116                                               K. S
117              Hayaweni Sri Parakramabahu Rajathumaa
118                           D.P. de Alwis Wijesekara
119             Kiralawalle Muhandhiramgei Sinynyaappu
120                                              K.R.P
121        Raajaguru Sri Chandraabhidhaana Pandithayoo
122                                    Dharmasena Himi
123                     Ambalangoda Dhammakuusala Himi
124                                Balangoda Guruthuma
125                   Panadura Nyaanawimalathissa Himi
126                                            Unknown
127                Waliwita Saranankara Sangaraja Himi
128                                            Unknown
129                 Udugampola Suwannajothyasabha Himi
130                             Sadhdharmakeerthi Himi
131     Walithora Aariyawaasadhaja Nyaanathilakathissa
132  Kalikaala Sangeetha Sahithya Panditha Parakram...
133                         Madugalle Sidhdhartha Himi
134                                            Unknown
135                           Pannananda Induruwa Himi
136                                            Unknown
137                                            Unknown
138                                            Unknown
139                         Rathmalane Dharmaloka Himi
140                       Rathmalana Saranathissa Himi
141                     Srimadh Budhdhadhasa Rajathuma
142                                            Unknown
143              Waasheeshwara Maalaalankaara Sthawira
144                                  Waageeshwara Himi
145  Walithota Nyaanaanandha Sirisadhdhammajothipaa...
146                   Walithota Budhdhasirithissa Himi
147                                            Unknown
148                           Boruggamuwe Rewatha Himi
149                                      Charlis Dhies
150                                            Unknown
151                                 Sri Kawiraajasinha
152                                    J P Amarasinghe
153                             Pathiraja Piruwan Himi
154                                      Ra. Thennakon
155                                            Unknown
156                      Maadhowita Nyaanaanandha Himi
157                                            Unknown
158                                            Unknown
159                       Hikkaduwe Sri Sumangala Himi
160                               D. H. S. Abayarathna
161                                            Unknown
162                                            Unknown
163                               D. H. S. Abayarathna
164                           Kirama Dhammanandha Himi
165  Jethawana Mahaa Wihaaradheeshwara Dhimbulaagal...
166                                            Unknown
167                                 David Karunarathna
168                                            Unknown
169                                      John de Silva
170                                    Pilippu Sinynyo
171                            Kodhaagoda Upasena Himi
172                                      Mahasena Himi
173                      Waskaduwe Medhabithissa Thero
174                            M. H. Arnolis Kularatne
175         Haapitigama Wajiragosha Thapasayan Wahanse
176                                     Hendry S Olkat
177                                            Unknown
178  Batuwanthudaawe Sri Dhewarakshitha Rajakeeya P...
179                                        G. M. Salah
180                                        G. M. Salah
181                                  Ubeeris Wijeweera
182                                            Unknown
183                                      T. A. D Alpin
184                                            Unknown
185                             Kirama Dhammarama Himi
186                    Madhampe Siridhammathilaka Himi
187     Thalalle Sri Dheeranandha Dharmarakshitha Himi
188                          Halthota Jinaanandha Himi
189                                          S.W Silva
190                                 R.H Wickramasinghe
191                                            Unknown
192                                  Budhdhagosha Himi
193                            Parakramabahu Rajathuma
194                                            Unknown
195                                  Budhdhagosha Himi
196        D.B.K. Gunathilaka Raajakarunaa Dissanayake
197                           Subhawickrama Munidhaasa
198                             Munidhasa Kumarathunga
199                                            Unknown
200                                            Unknown

In [70]:
df_authors_counts = df_authors.value_counts().to_frame(name='count').reset_index().sort_values(by='count', ascending=False)

In [71]:
df_authors_counts

                                             author_en  count
0                                              Unknown     69
1                               Munidhasa Kumarathunga      4
2                                 D. H. S. Abayarathna      2
3                                    Budhdhagosha Himi      2
4                                          G. H Perera      2
5                                      S. Mahinda Himi      2
6                         Dhodanduuwe Piyarathana Himi      2
7                         Hikkaduwe Sri Sumangala Himi      2
8                                        John de Silva      2
9                          Waligama Sri Sumangala Himi      2
10                                         G. M. Salah      2
86                                      Binthanne Himi      1
82                               Charles Karunathilaka      1
83                                    C.E. Godakumbure      1
84                            Boruggamuwe Rewatha Himi      1
85                                   Bodhi Widhyaartha      1
91                                     Albert de Silva      1
87   Batuwanthudaawe Sri Dhewarakshitha Rajakeeya P...      1
88                                 Balangoda Guruthuma      1
89                                       B. J Fernando      1
90                      Ambalangoda Dhammakuusala Himi      1
80                                     D. D Ranasinghe      1
81                                       Charlis Dhies      1
74         D.B.K. Gunathilaka Raajakarunaa Dissanayake      1
79                                D. E. Hettiaarachchi      1
78                                D. E. Wickramasuriya      1
77                           D. H. Stephen Abayarathna      1
76                                    D. S. Jayasekara      1
75                                    D.B. Jayathilaka      1
93                                   Engalthina Kumari      1
73                                          D.C. Prera      1
72                            D.P. de Alwis Wijesekara      1
71                                  David Karunarathna      1
70                                     Dharmasena Himi      1
69                       Dhodandhuuwe Saranapothi Himi      1
68                                   Don Andhris Silva      1
92                              Don Salman Gunathilake      1
98                                     M. Dharmarathna      1
94                               G. G. Lewis Appuhaami      1
108                           Galpatha Kemanandha Himi      1
119                              Gunapaala Weerasekara      1
118                                H.D.S. Wijayarathna      1
117         Haapitigama Wajiragosha Thapasayan Wahanse      1
116                          Halthota Jinaanandha Himi      1
115                                Hansini Pramudhitha      1
114              Hayaweni Sri Parakramabahu Rajathumaa      1
113                                     Hendry S Olkat      1
112                        Ilukwaththe Medhankara Himi      1
111                                    J P Amarasinghe      1
110  Jethawana Mahaa Wihaaradheeshwara Dhimbulaagal...      1
109                          K. Don Hendrick Appuhaami      1
107                                               K. S      1
95                                        K. S. Perera      1
106                                              K.R.P      1
105  Kalikaala Sangeetha Sahithya Panditha Parakram...      1
104                        Kaluthara Saaraanandha Himi      1
103             Kiralawalle Muhandhiramgei Sinynyaappu      1
102                           Kirama Dhammanandha Himi      1
101                             Kirama Dhammarama Himi      1
100                            Kodhaagoda Upasena Himi      1
99                                    L.S Gunawardhana      1
66                                   M.S Gauthamadhasa      1
97              Abhagahapitiye Bhudhdhasirithissa Himi      1
96                              M.L.D. James Appuhaami      1
67                  Don Basthiyan de Silva Jayasooriya      1
60                                   Sri Kumaaradhaasa      1
65                                M.U Kaweeshwara Himi      1
23                                  R.H Wickramasinghe      1
34                                       A. Dasanayake      1
33                    Panadura Nyaanawimalathissa Himi      1
32                            Pannananda Induruwa Himi      1
31             Panynyahi Sirisadhdharma Kavidhaja Himi      1
30                           Nalagama Nyaanaaloka Himi      1
29                              Sadhdharmakeerthi Himi      1
28                             Parakramabahu Rajathuma      1
27                              Pathiraja Piruwan Himi      1
26                                 Philip Gunawardhana      1
25                     Malalagama Sri Wijayanaaga Himi      1
24                                     Pilippu Sinynyo      1
22                                       Ra. Thennakon      1
36              Seenawaththe Gunaalankaara Thissa Himi      1
21                                       Mahasena Himi      1
20         Raajaguru Sri Chandraabhidhaana Pandithayoo      1
19                          Madugalle Sidhdhartha Himi      1
18                         Raigama Sri Indrajothi Himi      1
17                        Rathmalana Saranathissa Himi      1
16                          Rathmalane Dharmaloka Himi      1
15                     Madhampe Siridhammathilaka Himi      1
14                                           S.W Silva      1
13                         Madhampe Dhammathilaka Himi      1
12                                          P.A. Peris      1
11                                         P.J. Dhiyes      1
35         Siri Parakumabahu Wilgammula Sangaraja Himi      1
37                       Maadhowita Nyaanaanandha Himi      1
64                             M. H. Arnolis Kularatne      1
51                         Udugampala Swarnajothi Himi      1
63                        Madabaawita Nyaanawaasa Himi      1
62                              Sri Dhanudhdharacharya      1
61                                  Sri Kawiraajasinha      1
59                                       Sri Wopadhewa      1
58                      Srimadh Budhdhadhasa Rajathuma      1
57                            Subhawickrama Munidhaasa      1
56                                       T. A. D Alpin      1
55      Thalalle Sri Dheeranandha Dharmarakshitha Himi      1
54                             Thotagamuwe Rahula Himi      1
53                       Thotagamuwe Sugunathissa Himi      1
52                                   Ubeeris Wijeweera      1
50                  Udugampola Suwannajothyasabha Himi      1
38                                       Winston Prera      1
49                                  W. Thomas Fernando      1
48                                   Waageeshwara Himi      1
47               Waasheeshwara Maalaalankaara Sthawira      1
46                        Walikande Sri Sumangala Himi      1
45      Walithora Aariyawaasadhaja Nyaanathilakathissa      1
44                    Walithota Budhdhasirithissa Himi      1
43   Walithota Nyaanaanandha Sirisadhdhammajothipaa...      1
42                 Waliwita Saranankara Sangaraja Himi      1
41   Waraahamihiraachaarya Puth Pruthuyashas Pandiw...      1
40                       Waskaduwe Medhabithissa Thero      1
39                        Watadhdhara Medhanandha Himi      1
120                             Wladmeir Iliyich Lenin      1

In [72]:
df_authors_counts.sort_values(by = "author_en")

                                             author_en  count
34                                       A. Dasanayake      1
97              Abhagahapitiye Bhudhdhasirithissa Himi      1
91                                     Albert de Silva      1
90                      Ambalangoda Dhammakuusala Himi      1
89                                       B. J Fernando      1
88                                 Balangoda Guruthuma      1
87   Batuwanthudaawe Sri Dhewarakshitha Rajakeeya P...      1
86                                      Binthanne Himi      1
85                                   Bodhi Widhyaartha      1
84                            Boruggamuwe Rewatha Himi      1
3                                    Budhdhagosha Himi      2
83                                    C.E. Godakumbure      1
82                               Charles Karunathilaka      1
81                                       Charlis Dhies      1
80                                     D. D Ranasinghe      1
79                                D. E. Hettiaarachchi      1
78                                D. E. Wickramasuriya      1
2                                 D. H. S. Abayarathna      2
77                           D. H. Stephen Abayarathna      1
76                                    D. S. Jayasekara      1
75                                    D.B. Jayathilaka      1
74         D.B.K. Gunathilaka Raajakarunaa Dissanayake      1
73                                          D.C. Prera      1
72                            D.P. de Alwis Wijesekara      1
71                                  David Karunarathna      1
70                                     Dharmasena Himi      1
69                       Dhodandhuuwe Saranapothi Himi      1
6                         Dhodanduuwe Piyarathana Himi      2
68                                   Don Andhris Silva      1
67                  Don Basthiyan de Silva Jayasooriya      1
92                              Don Salman Gunathilake      1
93                                   Engalthina Kumari      1
94                               G. G. Lewis Appuhaami      1
4                                          G. H Perera      2
10                                         G. M. Salah      2
108                           Galpatha Kemanandha Himi      1
119                              Gunapaala Weerasekara      1
118                                H.D.S. Wijayarathna      1
117         Haapitigama Wajiragosha Thapasayan Wahanse      1
116                          Halthota Jinaanandha Himi      1
115                                Hansini Pramudhitha      1
114              Hayaweni Sri Parakramabahu Rajathumaa      1
113                                     Hendry S Olkat      1
7                         Hikkaduwe Sri Sumangala Himi      2
112                        Ilukwaththe Medhankara Himi      1
111                                    J P Amarasinghe      1
110  Jethawana Mahaa Wihaaradheeshwara Dhimbulaagal...      1
8                                        John de Silva      2
109                          K. Don Hendrick Appuhaami      1
107                                               K. S      1
95                                        K. S. Perera      1
106                                              K.R.P      1
105  Kalikaala Sangeetha Sahithya Panditha Parakram...      1
104                        Kaluthara Saaraanandha Himi      1
103             Kiralawalle Muhandhiramgei Sinynyaappu      1
102                           Kirama Dhammanandha Himi      1
101                             Kirama Dhammarama Himi      1
100                            Kodhaagoda Upasena Himi      1
99                                    L.S Gunawardhana      1
98                                     M. Dharmarathna      1
64                             M. H. Arnolis Kularatne      1
96                              M.L.D. James Appuhaami      1
66                                   M.S Gauthamadhasa      1
65                                M.U Kaweeshwara Himi      1
37                       Maadhowita Nyaanaanandha Himi      1
63                        Madabaawita Nyaanawaasa Himi      1
13                         Madhampe Dhammathilaka Himi      1
15                     Madhampe Siridhammathilaka Himi      1
19                          Madugalle Sidhdhartha Himi      1
21                                       Mahasena Himi      1
25                     Malalagama Sri Wijayanaaga Himi      1
1                               Munidhasa Kumarathunga      4
30                           Nalagama Nyaanaaloka Himi      1
12                                          P.A. Peris      1
11                                         P.J. Dhiyes      1
33                    Panadura Nyaanawimalathissa Himi      1
32                            Pannananda Induruwa Himi      1
31             Panynyahi Sirisadhdharma Kavidhaja Himi      1
28                             Parakramabahu Rajathuma      1
27                              Pathiraja Piruwan Himi      1
26                                 Philip Gunawardhana      1
24                                     Pilippu Sinynyo      1
23                                  R.H Wickramasinghe      1
22                                       Ra. Thennakon      1
20         Raajaguru Sri Chandraabhidhaana Pandithayoo      1
18                         Raigama Sri Indrajothi Himi      1
17                        Rathmalana Saranathissa Himi      1
16                          Rathmalane Dharmaloka Himi      1
5                                      S. Mahinda Himi      2
14                                           S.W Silva      1
29                              Sadhdharmakeerthi Himi      1
36              Seenawaththe Gunaalankaara Thissa Himi      1
35         Siri Parakumabahu Wilgammula Sangaraja Himi      1
62                              Sri Dhanudhdharacharya      1
61                                  Sri Kawiraajasinha      1
60                                   Sri Kumaaradhaasa      1
59                                       Sri Wopadhewa      1
58                      Srimadh Budhdhadhasa Rajathuma      1
57                            Subhawickrama Munidhaasa      1
56                                       T. A. D Alpin      1
55      Thalalle Sri Dheeranandha Dharmarakshitha Himi      1
54                             Thotagamuwe Rahula Himi      1
53                       Thotagamuwe Sugunathissa Himi      1
52                                   Ubeeris Wijeweera      1
51                         Udugampala Swarnajothi Himi      1
50                  Udugampola Suwannajothyasabha Himi      1
0                                              Unknown     69
49                                  W. Thomas Fernando      1
48                                   Waageeshwara Himi      1
47               Waasheeshwara Maalaalankaara Sthawira      1
9                          Waligama Sri Sumangala Himi      2
46                        Walikande Sri Sumangala Himi      1
45      Walithora Aariyawaasadhaja Nyaanathilakathissa      1
44                    Walithota Budhdhasirithissa Himi      1
43   Walithota Nyaanaanandha Sirisadhdhammajothipaa...      1
42                 Waliwita Saranankara Sangaraja Himi      1
41   Waraahamihiraachaarya Puth Pruthuyashas Pandiw...      1
40                       Waskaduwe Medhabithissa Thero      1
39                        Watadhdhara Medhanandha Himi      1
38                                       Winston Prera      1
120                             Wladmeir Iliyich Lenin      1

In [73]:
list_of_file_locations[list_of_file_locations['author_en'] == 'D. H. S. Abhayarathna'][['title_en', 'issued_date_range']]

Empty DataFrame
Columns: [title_en, issued_date_range]
Index: []

In [74]:
len(df_authors_counts)

121

In [75]:
len(df_authors_counts[df_authors_counts["count"] == 1])

110

In [76]:
len(df_authors_counts[df_authors_counts["count"] == 2])

9

## Author Analysis on filtered dataset

In [77]:
split_authors = list_of_file_locations_filtered['author_en'].str.split(';', expand=True)
split_authors = split_authors.fillna('')

In [78]:
authors_list = split_authors.stack().tolist()

In [79]:
authors_list = [author for author in authors_list if author != '']

In [80]:
clean_authors = [a.strip() for a in authors_list if a.strip()]

In [81]:
df_authors = pd.DataFrame(clean_authors, columns=["author_en"])

In [82]:
df_authors

                                            author_en
0                         Madhampe Dhammathilaka Himi
1                        Walikande Sri Sumangala Himi
2                        Watadhdhara Medhanandha Himi
3         Siri Parakumabahu Wilgammula Sangaraja Himi
4                                D. E. Wickramasuriya
5                                             Unknown
6                                             Unknown
7                                    D.B. Jayathilaka
8                                             Unknown
9                              Sri Dhanudhdharacharya
10                       Hikkaduwe Sri Sumangala Himi
11                                   C.E. Godakumbure
12                        Waligama Sri Sumangala Himi
13                                  Sri Kumaaradhaasa
14                                      John de Silva
15                                            Unknown
16                                  Engalthina Kumari
17                            Thotagamuwe Rahula Himi
18                                            Unknown
19                             Munidhasa Kumarathunga
20                                    S. Mahinda Himi
21                                            Unknown
22                                        G. H Perera
23                                            Unknown
24                                            Unknown
25                                            Unknown
26                             Munidhasa Kumarathunga
27                                    S. Mahinda Himi
28                             Munidhasa Kumarathunga
29                                            Unknown
30                                  Don Andhris Silva
31                                         P.A. Peris
32                                        P.J. Dhiyes
33                                            Unknown
34                           Galpatha Kemanandha Himi
35                                            Unknown
36              Hayaweni Sri Parakramabahu Rajathumaa
37                           D.P. de Alwis Wijesekara
38                                    Dharmasena Himi
39                Waliwita Saranankara Sangaraja Himi
40  Kalikaala Sangeetha Sahithya Panditha Parakram...
41                         Madugalle Sidhdhartha Himi
42                                            Unknown
43                         Rathmalane Dharmaloka Himi
44                     Srimadh Budhdhadhasa Rajathuma
45                                    J P Amarasinghe
46                             Pathiraja Piruwan Himi
47                                      Ra. Thennakon
48                                            Unknown
49                       Hikkaduwe Sri Sumangala Himi
50                                            Unknown
51                                            Unknown
52                               D. H. S. Abayarathna
53                           Kirama Dhammanandha Himi
54                                     Hendry S Olkat
55                                            Unknown
56                             Kirama Dhammarama Himi
57                                            Unknown
58                                  Budhdhagosha Himi
59                            Parakramabahu Rajathuma
60                                            Unknown
61                                  Budhdhagosha Himi
62        D.B.K. Gunathilaka Raajakarunaa Dissanayake
63                             Munidhasa Kumarathunga
64                                            Unknown

In [83]:
df_authors_counts = df_authors.value_counts().to_frame(name='count').reset_index().sort_values(by='count', ascending=False)

In [84]:
df_authors_counts

                                            author_en  count
0                                             Unknown     20
1                              Munidhasa Kumarathunga      4
2                        Hikkaduwe Sri Sumangala Himi      2
3                                     S. Mahinda Himi      2
4                                   Budhdhagosha Himi      2
30                                        G. H Perera      1
24                               D. H. S. Abayarathna      1
25                                   D.B. Jayathilaka      1
26        D.B.K. Gunathilaka Raajakarunaa Dissanayake      1
27                           D.P. de Alwis Wijesekara      1
28                                    Dharmasena Himi      1
29                                  Don Andhris Silva      1
32                           Galpatha Kemanandha Himi      1
31                             Kirama Dhammarama Himi      1
22                                  Engalthina Kumari      1
33              Hayaweni Sri Parakramabahu Rajathumaa      1
34                                     Hendry S Olkat      1
35                                    J P Amarasinghe      1
36                                      John de Silva      1
37  Kalikaala Sangeetha Sahithya Panditha Parakram...      1
38                           Kirama Dhammanandha Himi      1
23                               D. E. Wickramasuriya      1
20                        Madhampe Dhammathilaka Himi      1
21                                   C.E. Godakumbure      1
11                       Walikande Sri Sumangala Himi      1
5                         Waligama Sri Sumangala Himi      1
6                             Thotagamuwe Rahula Himi      1
7                      Srimadh Budhdhadhasa Rajathuma      1
8                                   Sri Kumaaradhaasa      1
9                              Sri Dhanudhdharacharya      1
10                         Madugalle Sidhdhartha Himi      1
12                         Rathmalane Dharmaloka Himi      1
19        Siri Parakumabahu Wilgammula Sangaraja Himi      1
13                                      Ra. Thennakon      1
14                Waliwita Saranankara Sangaraja Himi      1
15                             Pathiraja Piruwan Himi      1
16                            Parakramabahu Rajathuma      1
17                                        P.J. Dhiyes      1
18                                         P.A. Peris      1
39                       Watadhdhara Medhanandha Himi      1

In [85]:
len(df_authors_counts)

40

In [86]:
df_authors_counts[df_authors_counts["count"] > 1]

                      author_en  count
0                       Unknown     20
1        Munidhasa Kumarathunga      4
2  Hikkaduwe Sri Sumangala Himi      2
3               S. Mahinda Himi      2
4             Budhdhagosha Himi      2

In [87]:
len(df_authors_counts[df_authors_counts["count"] == 1])

35